### ISSUE TITLE
Timeout when Facebook takes request but does not respond

### ISSUE THREAD

**Issue by NenadP** [restfb/restfb#1001]
When using FacebookClient **publish** method, what happens if Facebook accepts the request but holds connection alive, not replying? Is there any timeout strategy implemented in restFb? And if yes how?

I suspect I had this situation and I would like to get more control of how long shall I wait for Facebook response.

Thanks

**Comment by nbartels** [comment]
The DefaultWebRequestor waits 180000ms (3mins) for a response. You can write your own class and extend the `DefaultWebRequestor`. You can then add your own timeouts by overriding the `customizeConnection(HttpURLConnection)`.

**Comment by NenadP** [comment]
Hi Norbert,

Thanks for clarifying. I was able to test this now  by mocking Fiddler response with high Latency. After 3 mins there was

> java.net.SocketTimeoutException: Read timed out

thrown.
