### ISSUE TITLE
Received Facebook error response of type OAuthException:  Requires session when calling from a desktop app 

### ISSUE THREAD

**Issue by JasminGuberinic** [restfb/restfb#1002]
I am getting the error message ;

Received Facebook error response of type OAuthException: (#15) Requires session when calling from a desktop app (code 15, subcode null) 'null - null'

I am not making calls from desktop app. This error is thrown when I tray to get feeds.

JsonObject dataJson = client.fetchObject("feed", JsonObject.class, Parameter.with(IDS, csvf),
						Parameter.with(FIELDS, LISTFIELDS));

where csvf is list of pages ids which I require before feeds with the same client with no problem.

**Comment by nbartels** [comment]
What kind of access token do you use?

**Comment by JasminGuberinic** [comment]
I am using application access token.

**Comment by nbartels** [comment]
I don't think it is possible to fetch some page feeds with an application access token. The error above seems to be the way Facebook tries to tell you something like that. 

Please try a user access token. And maybe the app needs the "public page content access" feature, too.

**Comment by JasminGuberinic** [comment]
It was working and I manged to fetch page feeds, then it suddenly stop working and started throwing this exception. I already have public page content access.

**Comment by nbartels** [comment]
Okay, if it changed all of a sudden, I suggest to open up a bug report at [Facebook](https://developers.facebook.com/support/bugs/).

**Comment by JasminGuberinic** [comment]
This is the answer that I  got from Facebook.

Thank you for reaching out to us. I'm sorry to hear you're encountering this issue.

Unfortunately, we do not provide support to third party plugins like the one you have listed. Please go to the plugin's support page for help on your issue.

**Comment by nbartels** [comment]
Yes, they always try to dodge if an error occurs.

Please check the Graph API Explorer if you can reproduce the problem there, too.

**Comment by JasminGuberinic** [comment]
Just to follow thru.

The problem was that (Native or desktop app) option was on. That created the exception.
Everything works fine now.

Thanks .

**Comment by nbartels** [comment]
Many thanks for the heads up.
