### ISSUE TITLE
com.restfb.types.Message field "shares" not List<Message.Share>

### ISSUE THREAD

**Issue by TUANNT39** [restfb/restfb#1007]
Hi,
com.restfb.types.Message
```
@Facebook
private List<Message.Share> shares = new ArrayList();
```
I test:
https://developers.facebook.com/docs/graph-api/reference/v3.3/conversation/messages
```
"shares": { 
    "data": [ 
        { 
            "id": "ee.mid.$cAAeCrIItCiRxmrsDvFraXW7JOsgK", 
            "link": "https://www.facebook.com/2208209609292946/posts/2303068989807007/", 
            "name": "18-06-2019-test2-🧐🧐" 
        } 
    ] 
}
```

**Comment by nbartels** [comment]
Can you explain your problem? We have a unit test that checks this and the conversion of the JSON to a `Message` is working. You need to call `getShares()` to fetch the shares.

**Comment by TUANNT39** [comment]
sorry, my mistake
