### ISSUE TITLE
Rate Limiting version 3.3

### ISSUE THREAD

**Issue by santinomazzocchi** [restfb/restfb#1008]
Hi,
I'm upgrading our application to the newest 3.3 graph api version and I have problems with page limit returned by DebugHeaderInfo class.

I noticed the old header "x-page-usage" expired, the new header to use is "x-business-use-case-usage". I don't see any reference to "x-business-use-case-usage" in restfb library. 

What I'm doing wrong?
Do you have to upgrade restfb to apply to these changes?

Thank you
Santino

**Comment by nbartels** [comment]
This looks like a new rate limit field:
https://developers.facebook.com/docs/graph-api/overview/rate-limiting/#ads-insights-level-rate-limiting

We have to add this first, before you can use it. Maybe there is a workaround, but I need some deeper insights...
