### ISSUE TITLE
Send a file as BinaryAttachment to User

### ISSUE THREAD

**Issue by omer92** [restfb/restfb#1022]
I am trying to send an attachment to User but it always is telling me

` (#100) Message cannot be empty, must provide valid attachment or text (code 100, subcode 2018034) 'null - null'`

This is the code I am trying to make it work:

```
IdMessageRecipient recipient = new IdMessageRecipient("recipientId");

FacebookClient pageClient = new DefaultFacebookClient("PageAccessToken", Version.VERSION_3_3);

pageClient.publish("me/messages", JsonObject.class,
                BinaryAttachment.with("fileName", "byte[]", "fileType"),
                Parameter.with("message", "TestImage"), Parameter.with("recipient", recipient));
```

Before method **_publish_** I have checked the attributes and there is not null anywhere but somehow it is still telling me to provide valid attachment. If I want to send a messageText like "Hello World" it is sent to User successfully.

Any insight would be helpful, because I have read on some closed issue that at the moment it is not possible. 

Thank you in advance

**Comment by nbartels** [comment]
Have a look at the documentation. You try to use the messenger API and this is a bit special and different from the normal API used for writing Posts with images.

https://restfb.com/documentation/#messenger-imagemessage

Let me know if you need further information

**Comment by omer92** [comment]
Thank you for provided link but I already have working solution for sending the URLs as an attachment.
Reading your documentation I thought it is possible to send attachment as byte[ ] with messengerAPI but I was wrong apparently. 

So you are telling me that only way sending to User messenger is with URLs or with reusable attachment ID ?

**Comment by nbartels** [comment]
You can upload an image as "reusable media attachment" and use the id afterwards. We don't have any RestFB specific documentation so far, but maybe the description in the Facebook reference may lead you to the right direction:
https://developers.facebook.com/docs/messenger-platform/reference/attachment-upload-api

**Comment by omer92** [comment]
Ok, I will do it that way then. Thank you for your time
