### ISSUE TITLE
Populating next/previous page urls that don't point to any data

### ISSUE THREAD

**Issue by rnortekled** [restfb/restfb#1041]
https://github.com/restfb/restfb/blob/a522c0cfdc5f42781d5e727a8eb05ef1cd1c206a/src/main/java/com/restfb/DefaultFacebookClient.java#L290-L299

Hello,

We've been using an older version of RestFB and currently integrating with a newer version. One thing we've noticed when testing with the new version is that page urls that were previously empty (the previous token on the first page of data and the next token on the last page of data) are now being populated with urls that point to empty data. What was the intention with the code change above? 

This isn't necessarily an issue, but I'm curious about the reasoning here- not sure if there is a better channel for questions like this.

Thanks,
Rob

**Comment by nbartels** [comment]
Please check https://github.com/restfb/restfb/issues/909
