### ISSUE TITLE
Does the restfb platform not allow you to post scheduled photos?

### ISSUE THREAD

**Issue by RowanBurns01** [restfb/restfb#1052]
Hi there,

I have reached an interesting issue when I try schedule a post with a photo to me/photos using the restfb api. It says the "scheduled_publish_time" is an invalid Date, yet I know the Date is fine because I can use it to schedule a normal post with text to me/feed. I am also able to post a photo without scheduling and that works fine.

This leads me to think that scheduling photos with restfb is not possible?

Any help would be appreciated, I'm trying to make a bot :)

Cheers,
Rowan Burns

Picture shows the difference in methods, makeTextPost() works but makePost() doesn't.
![Capture](https://user-images.githubusercontent.com/54560359/72690049-5cf09980-3b6c-11ea-8e38-e36caa7a0953.PNG)

**Comment by nbartels** [comment]
I just checked the Facebook reference and it should be possible.

Can you please try to use `DateUtils.toLongFormatFromDate​(d.getDate())` as parameter for the `scheduled_publish_time`?

**Comment by RowanBurns01** [comment]
Hi nbartels,

Thank you for the response!

Unfortunately that didn't fix the problem.

Here is the error received:
![Capture](https://user-images.githubusercontent.com/54560359/72720476-2f3c3c80-3bce-11ea-8a91-09e12f24ff08.JPG)

If I providing any other information could help let me know - I have the repo available on my github too.

Kind regards, 
Rowan

**Comment by RowanBurns01** [comment]
Also in regards to the Facebook reference you are using to check - is that just the restFB documentation or something else? 

Thanks

**Comment by nbartels** [comment]
It's the official Facebook documentation: 
https://developers.facebook.com/docs/graph-api/reference/photo/#Creating

**Comment by nbartels** [comment]
Okay, so I wrote the test, did some experiments and found the solution. 
It looks a bit strange and we have to provide some help for the use case in our docs and in RestFB itself, but it works:

```
Date dt = createTomorrowAsDate();
client.publish("<page id>/photos", GraphResponse.class,
      BinaryAttachment.with("test.png", imageAsBytes, "image/png"),  // just a binary
         Parameter.with("message", "Test Image"), // the message added to the image
         Parameter.with("published", "false"), 
         Parameter.with("scheduled_publish_time", dt.getTime() / 1000)); 
```

The `scheduled_publish_time` needs to be a unix timestamp in seconds. You can get it from a Date object, but it's in milliseconds and so you have to "remove" the milliseconds. Dividing by 1000 is sufficient here :) Otherwise the date is too far in the future ...

If this is also working for you, please drop a note.

**Comment by RowanBurns01** [comment]
That has solved the problem! Thank you very much this has been a most positive first experience with github.
