### ISSUE TITLE
RestFB Published Posts not visible to public

### ISSUE THREAD

**Issue by RowanBurns01** [restfb/restfb#1053]
Hi there,

I have a follow up issue which I haven't been able to see the solution to.

My posts that were scheduled to go up earlier today and have been posted. Unfortunately only I can see the posts and people who have liked the page cannot see them. These posts were scheduled through the restfb api to both feed and photos.

I tested a normal post manually as a status and that showed up fine. My settings all seem to be on public and so I'm unsure what the problem is.

Any help would be appreciated.

Kind regards,
Rowan Burns

**Comment by nbartels** [comment]
Hi Rowan,

your Facebook app is set to live and you finished the Facebook review process successfully?

During development, only you can see posted stuff.

**Comment by RowanBurns01** [comment]
That was my problem thank you.
