### ISSUE TITLE
Support configuration of Marketing API version

### ISSUE THREAD

**Issue by tpschar** [restfb/restfb#1054]
Since Facebook manages the deprecation of the Marketing API versions separately from the Graph API, it would be nice to be able to set both versions independently into the FacebookClient and have it use the appropriate version for API calls, depending on whether the calls are from the Marketing API or the regular Graph API.

**Comment by nbartels** [comment]
What about using two instances of the FacebookClient with different versions? 

Otherwise we have to find a trigger point to switch between the two versions.

**Comment by tpschar** [comment]
Yes, that's true.  I thought it would be very convenient not to have to remember which API calls were marketing and which were not and switch clients during my flow, which consists of a mixture of the two APIs.  But I understand if the design of the FacebookClient is such that it would not be easy to implement such a switch internally.
