### ISSUE TITLE
Connection hasNext() method returns false even if there is a next page available.

### ISSUE THREAD

**Issue by ciprian197** [restfb/restfb#1059]
Version 3.2.0.

When paginating data using limit=1 the before and after cursors have the same value, but in this case this doesn't mean that there is no next page available.

**Comment by nbartels** [comment]
Can you please provide the json? It would be much easier to write a unit test and fix the problem afterwards.

**Comment by ciprian197** [comment]
Endpoint: me/friends?limit=1

{
  "data": [
    {
      "name": "John Doe",
      "id": "randomId"
    }
  ],
  "paging": {
    "cursors": {
      "before": "QVFIUlNEN1BWay1jWVVfN05JSUt2Ri1FVEJ5dXBYa2dBTVNlb2N6UDlxbDlSNXMxLUJIekVtVEd3TmhGQ2tKOXhRU3lfTTZAxNnAxMHJfME4xWlMyRHZAtekZAR",
      "after": "QVFIUlNEN1BWay1jWVVfN05JSUt2Ri1FVEJ5dXBYa2dBTVNlb2N6UDlxbDlSNXMxLUJIekVtVEd3TmhGQ2tKOXhRU3lfTTZAxNnAxMHJfME4xWlMyRHZAtekZAR"
    },
    "next": "https://graph.facebook.com/v4.0/1332043400283557/friends?access_token=EAAG9BkJsduIBAJTdqdUJ4BYw9thbjDwGE30NbhMFHBBvxNAcOZAyRrzWwDohPfqEo8Iz55jt6zxfx4OJYu3wRZBxZADbg4t5e4GUJJ4eFiZCoZAPLhoHJQDP9RMnnq14y0nXFJz0ddwlh0udNzuhOMuUP7WWywOZCsr4rZBG7psD6HksNUNDdgjftZBc5T4A7LOeR0KCDZA7nbAZDZD&pretty=0&limit=1&after=QVFIUlNEN1BWay1jWVVfN05JSUt2Ri1FVEJ5dXBYa2dBTVNlb2N6UDlxbDlSNXMxLUJIekVtVEd3TmhGQ2tKOXhRU3lfTTZAxNnAxMHJfME4xWlMyRHZAtekZAR"
  },
  "summary": {
    "total_count": randomNumber
  }
}
