### ISSUE TITLE
What's the correct way to obtain a page access token with restfb?

### ISSUE THREAD

**Issue by davioooh** [restfb/restfb#1061]
From my application I need to post images in a photo album of a Facebook Page.

Following resfb docs I'm implementing the OAuth flow. In particular I created the login url this way:

```
FacebookClient client = new DefaultFacebookClient(Version.VERSION_2_12);
String loginDialogUrlString = client.getLoginDialogUrl(APP_ID, REDIRECT_URL, scopeBuilder);
```
but now I can't understand I to create the Page Access Token.

I've tried using this:

```
AccessToken accessToken = client.obtainUserAccessToken(APP_ID, APP_SECRET, REDIRECT_URL, verificationCode); // verification code from the the previous login
```

but when I try to post contents on my page using this (USER) access token I get this error:

```
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#210) A page access token is required to request this resource. (code 210, subcode null) 'null - null'
```

So, what's the correct way to obtain a PAGE access token?

**Comment by nbartels** [comment]
You are almost there 😉

With the user access token you can fetch the page access token. The tokens are returned if you call the `me/accounts` endpoint with your user access token.

Create a `FacebookClient` with your access token and do:

```java
Connection<Account> connection = client.fetchConnection("/me/accounts", Account.class);
```

You have to iterate over the connection to get all accounts. You can find the information how to iterate here in our documentation: https://restfb.com/documentation/#fetching-connections

**Comment by davioooh** [comment]
Thank you @nbartels . I missed this point! 😊
