### ISSUE TITLE
MediaAttachment in Send API should work without URL or ResuseId

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#1062]
According to the Facebook docs it is possible to send an attachment without providing an URL or a ReuseId. The binary data is directly send to the me/messages endpoint.

We have to support this, too.
https://developers.facebook.com/docs/messenger-platform/send-messages#file

**Comment by nbartels** [comment]
Here is some workaround and the information for the documentation:

First we need a simple new `MessageAttachment` object. In the version we will publish to our repository the payload will be more sophisticated, this is just the shortest version that works.

```java
import com.restfb.Facebook;
import com.restfb.types.send.MediaAttachment.Type;
import com.restfb.types.send.MessageAttachment;

public class UploadMessageAttachment extends MessageAttachment {

  @Facebook
  private Object payload = new Object(); 
  // payload is important, without publishing will not work

  private static final long serialVersionUID = 1L;

  public UploadMessageAttachment(Type type) {
    setType(type.toString().toLowerCase());
  }

}
```
Now we have the code in the application. We need a recipient, an attachment and the we can publish the answer. This will look like:

```java
IdMessageRecipient recipient = new IdMessageRecipient("receiving user id");
BinaryAttachment attachment = BinaryAttachment.with("filename", getIs());

// we have to tell FB what kind of attachment we are going to publish, in this example it is an image
// you can use file, video and audio, too
UploadMessageAttachment messageAttachment = new UploadMessageAttachment(Type.IMAGE);

// the message can only contain text OR an attachment
Message message = new Message(messageAttachment);

//Now, we publish this stuff
SendResponse resp = client.publish("me/messages", SendResponse.class, attachment,
        Parameter.with("recipient", recipient),
        Parameter.with("message", responseMessage));

// in the resp object you find some useful information
```

**Comment by torbenw** [comment]
There is no way to send more than 1 attachment or to include a text, right? So we will have publish each attachment and the text individually.

**Comment by nbartels** [comment]
Yes, this is how the Facebook API works... 
https://developers.facebook.com/docs/messenger-platform/reference/send-api/#message
