### ISSUE TITLE
Is it possible to use the Attachment Upload API with RestFB?

### ISSUE THREAD

**Issue by torbenw** [restfb/restfb#1063]
I'm trying to switch from the old Conversations API to the newer Send API. With the old API it was possible to send attachments as BinaryAttachments without uploading them first. With the Send API this doesn't seem to be possible.

Are there any classes for the requests and responses of the [Attachment Upload API](https://developers.facebook.com/docs/messenger-platform/reference/attachment-upload-api) in RestFB? I don't see any. The [example](https://restfb.com/documentation/#messenger-imagemessage) for using the Send API only shows how it can be done using a link.

Is there a way RestFB can help me with this or do I have to write my own classes for the requests and responses?

**Comment by nbartels** [comment]
Please check issue #1062

**Comment by torbenw** [comment]
Thank you for the quick response! Sorry, I didn't see that issue.

That's exactly what I'm trying right now, but I'm not sure if it's possible to somehow do a form-data request with the RestFB client or if I would have to use another client for that.

Do you know when your example code would be ready?

**Comment by nbartels** [comment]
I added an example to #1062 and I try to push the necessary code to restfb this weekend, maybe this evening. The publishing code can be found in the other issue, too.

Would be great if you simply track 1062 then, I can close this duplicate here ;)

Thanks for the feedback.
