### ISSUE TITLE
NullPointerExeption while fetching comments

### ISSUE THREAD

**Issue by saipraveenH** [restfb/restfb#1068]
`Connection<Comment> parentComment = fb.fetchConnection(parentCommentId, Comment.class,
				Parameter.with("fields", "comments"));`
connection is calling 
`JsonArray jsonData = jsonObject.get("data").asArray();`
but there is no field "data" inside jsonObject. It has only one field "comments"

**Comment by nbartels** [comment]
Please try:

```java
Connection<Comment> parentComment = fb.fetchConnection(parentCommentId + "/comments", Comment.class);
```

**Comment by saipraveenH** [comment]
hi nbartels,

Thanks for your reply. Im now able to get comments of a comment. However how to add a comment reply and  publish. (Code example would be helpful) @nbartels

**Comment by nbartels** [comment]
If your comment has the flag set by Facebook, you can write a comment to that comment (reply), otherwise you have to write a comment to the parentCommentId.

```java
Connection<Comment> parentComment 
    = fb.fetchConnection(parentCommentId + "/comments", Comment.class, Parameter.with("fields","id,can_comment");
```

Publishing a comment looks like this:

```java
GraphResponse response = fb.publish(commentId + "/comments", GraphResponse.class, Parameter.with("message", "Just a test message"));
```

**Comment by saipraveenH** [comment]
@nbartels  Thanks for the help again.

I tried what you have mentioned 

`Connection<Comment> parentComment = fb.fetchConnection(parentCommentId + "/comments", Comment.class,
				Parameter.with("fields", "id,can_comment"));
		Comment comment = parentComment.getData().stream().findFirst().get();
		Comment newComemnt = new Comment();
		newComemnt.setMessage(message);
		Comments commentReplies = comment.getComments();
		commentReplies.addData(comment);
		//update parentComment
		`
can you please tell me what i need to do at updateParentComment

**Comment by nbartels** [comment]
Sorry, I don't get it. What are you trying to do and what ist `updateParentComment`?

**Comment by saipraveenH** [comment]
sorry @nbartels ,i am successful in posting a comment reply.

Thank you for yor quick response and time.
