### ISSUE TITLE
Cant determine the type of a Post

### ISSUE THREAD

**Issue by chachoe** [restfb/restfb#1077]
Hi restfb comunity!
I´m havaing a problem when i want to determine de type of my posts. For example, if the post is a video, a photo, a link, or just text.
Once a time I used the field "type" and it used to work fine.
But now its not working and [in the fb documentation they say the field still exists](https://developers.facebook.com/docs/graph-api/reference/post/)

Here is how I try to get de post:

```
String fields = "id,message,type,created_time,shares,comments.summary(true)"; 
		fields += ",reactions.limit(0).summary(1)" // reactions overview
				+ ",reactions.type(LIKE).limit(0).summary(1).as(reactions_like)" // like
				+ ",reactions.type(LOVE).limit(0).summary(1).as(reactions_love)" // love
				+ ",reactions.type(WOW).limit(0).summary(1).as(reactions_wow)" // wow
				+ ",reactions.type(HAHA).limit(0).summary(1).as(reactions_haha)" // haha
				+ ",reactions.type(SAD).limit(0).summary(1).as(reactions_sad)" // sad
				+ ",reactions.type(ANGRY).limit(0).summary(1).as(reactions_angry)" // angry
				+ ",reactions.type(THANKFUL).limit(0).summary(1).as(reactions_thankful)" // thankful
				+ ",reactions.type(CARE).limit(0).summary(1).as(reactions_care)"; // thankful
		
		Connection<PostWithDetailedReactions> myFeed = fbClient.get(fanpage_id).fetchConnection("me/feed",
				PostWithDetailedReactions.class, Parameter.with("since", fecha_desde),
				Parameter.with("until", fecha_hasta), Parameter.with("fields", fields));

```

And this is the error:
 **com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#12) type field is deprecated for versions v3.3 and higher (code 12, subcode null) 'null - null'**

When I delete the field "type", its work fine:

`String fields = "id,message,created_time,shares,comments.summary(true)"; `

Do you know how I can get the type field?

Thanks!

**Comment by nbartels** [comment]
hi @chachoe 

your're right the `type` field is deprecated. The new way - as defined by Facebook - is the following:

* the default type is `status`. 
* if the post has an `attachments` field, the type of the post is `attachments{media_type}`

https://developers.facebook.com/docs/graph-api/changelog/version3.3#pages

I hope this helps ...

**Comment by chachoe** [comment]
Thanks a lot! 

It works fine calling with `attachments{media_type}`
