### ISSUE TITLE
Acquire test user access tokens for integration tests

### ISSUE THREAD

**Issue by zzvara** [restfb/restfb#1084]
Automated testing of integrations may require ad-hoc test users and access tokens created by parallel processes. Is there any support for test user generation and access token retrieval, and if not, do you plan to add these features?

**Comment by nbartels** [comment]
Yes, test users are supported. We have a special `TestUser` type for this and you can use RestFB to implement the calls described here: https://developers.facebook.com/docs/graph-api/reference/app/accounts/test-users#publish

If you need further information or example codes, please let me know.

**Comment by zzvara** [comment]
@nbartels thank you for your kind response. Could you provide or point me to a schematic code snippet to start with? Do you have tests regarding this feature in `restfb`?

**Comment by nbartels** [comment]
I'll push an integration test later on (today), so you can start with that.

**Comment by nbartels** [comment]
Please check the commit, you should find the information to create and delete test users there.

**Comment by zzvara** [comment]
@nbartels looks nice, I'm going to try it out ASAP!

**Comment by zzvara** [comment]
I'm getting an exception:

```
Received Facebook error response of type OAuthException: Invalid OAuth access token. (code 190, subcode null) 'null - null'
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: Invalid OAuth access token. (code 190, subcode null) 'null - null'
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerator.java:174)
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookExceptionGenerator.java:61)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:794)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:721)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:331)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:350)
```

This is how the client is created:

`val client = new DefaultFacebookClient(secret, Version.LATEST)`

And how publish is used:

```
    val accessToken = zuckerberg.client
      .publish(
        identifier + "/accounts/test-users",
        classOf[TestUser],
        Parameter.`with`("installed", true)
      ).getAccessToken
```

It seems to be working with calls like:


```
      val extendedAccessToken = client.obtainExtendedAccessToken(identifier, secret, accessToken)
      extendedAccessToken.getAccessToken
```

**Comment by nbartels** [comment]
You need the app access token for this call: https://developers.facebook.com/docs/facebook-login/access-tokens/#apptokens

**Comment by zzvara** [comment]
I can see it now, it works! Isn't this a bit confusing to use different keys for different use-cases with the same `DefaultFacebookClient` constructor waiting for an `accessToken`?

**Comment by nbartels** [comment]
You may have several FacebookClient instances 😉 

You could simply add the app access token facebook client in a base test class and create the testuser client in the `Before` method - as an example.

Facebook uses several access tokens and so we developer have to handle that ...

**Comment by zzvara** [comment]
> Facebook uses several access tokens and so we developer have to handle that ...

I see, thanks!
