### ISSUE TITLE
DefaultFacebookExceptionGenerator.skipResponseStatusExceptionParsing is too sloppy

### ISSUE THREAD

**Issue by DerKeil** [restfb/restfb#1088]
Hey,
the criterion used in `DefaultFacebookExceptionGenerator.skipResponseStatusExceptionParsing()` is too sloppy, as there is an example of a successful API-request that will be converted into a `FacebookGraphException`, instead of the correct reply being returned.

Example:
The request
https://graph.facebook.com/v3.1/debug_token?input_token=abcd&access_token=efgh
can give the correct reply
```
{
   "data": {
      "type": "PAGE",
      "error": {
         "code": 190,
         "message": "Page does not exist or cannot be loaded"
      },
      "expires_at": 0,
      "is_valid": false,
      "issued_at": 1597649209,
      "profile_id": "123...",
      "scopes": [
         
      ]
   }
}
```
which is then not returned as a `DebugTokenInfo`, but converted into a `FacebookGraphException`.

**Comment by nbartels** [comment]
Okay, let me check this ...
