### ISSUE TITLE
Page Access Tokens

### ISSUE THREAD

**Issue by develm** [restfb/restfb#1092]
Hi,
I am looking to implement Page access and long lived page access tokens token for this library. Do you have any pointers or have you planned this feature?

Page access token documentation:
https://developers.facebook.com/docs/facebook-login/access-tokens#pagetokens

Long lived page access token:
https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing/#get-a-long-lived-page-access-token

These tokens are permanent and don't expire until the application access is revoked.

**Comment by nbartels** [comment]
Okay, here is the code for the page access tokens:

```java
DefaultFacebookClient client = new DefaultFacebookClient("<user access token>", Version.LATEST);
    Connection<Account> connection = client.fetchConnection("/me/accounts", Account.class);
    for (List<Account> accountList : connection) {
      for (Account account : accountList) {
        System.out.println("Page Access Token for page " + account.getName() + " : " + account.getAccessToken());
      }
    }
```

The long lived access tokens can be fetched with this call:

```java
FacebookClient.AccessToken at  = client.obtainExtendedAccessToken("appId","appSecret","access token");
```

Hope this helps ...
