### ISSUE TITLE
Check CATALOG_MANAGEMENT permission, please

### ISSUE THREAD

**Issue by w00dg1n** [restfb/restfb#1093]
Hi restfb team!

Do you have plan to change string representation of CATALOG_MANAGEMENT permission from 'business_management' to 'catalog_management'?

**Comment by nbartels** [comment]
yes, this will be fixed with the next release and I try to prepare this in the next days ...

**Comment by w00dg1n** [comment]
Thanks a lot for quick answer!

**Comment by nbartels** [comment]
@w00dg1n 3.10.0 is released, so you can use the permission right now 😅
