### ISSUE TITLE
Exception on parsing Error message

### ISSUE THREAD

**Issue by manikshitij** [restfb/restfb#1095]
messagge: "Can not instantiate value of type [simple type, class com.restfb.json.JsonObject] from String value ('{"error":{"message":"An unknown error occurred","type":"OAuthException","code":1,"error_subcode":1446036,"is_transient":false,"error_user_title":"Duplicate Mark Spam Request","error_user_msg":"Comment is already marked as spam. Duplicate request to mark comment as spam.","fbtrace_id":"AXNSTEPpjX5zEG-g80nQydI"}}'); no single-String constructor/factory method↵ at [Source: N/A; line: -1, column: -1]"

We get the above exception upon receiving error response from facebook(also above).

**Comment by nbartels** [comment]
Can you please send the complete stack trace?

**Comment by manikshitij** [comment]
Hi @nbartels I am sorry but we do not store exception logs for this piece of implementation.

**Comment by nbartels** [comment]
okay @manikshitij , then I have to try to reproduce the problem somehow with the given information ... makes it a bit harder, but I think it is possible.

**Comment by manikshitij** [comment]
@nbartels I have noticed similar issues in our logging for other Exceptions too. These exception are generally those which facebook does not mention in their documentation and are ad-hoc.

**Comment by nbartels** [comment]
it looks like the exception you send us, comes from "Jackson" and not from RestFB. We don't use Jackson for any mapping. 
Check this link: https://stackoverflow.com/questions/10839297/jsonmappingexception-can-not-instantiate-value-of-type-simple-type-a-b-c-comp
