### ISSUE TITLE
Logout of facebook

### ISSUE THREAD

**Issue by kbk1303** [restfb/restfb#1104]
hi,

I can find a lot of good tutorials on how to log in to Facebook, and do all sorts of stuff with the API, which is absolutely fine, but I need to be able to log out of Facebook, immediately after a user logged in. I can't really find a good example of how to do that. I guess it is a question of invalidating the access token.

I have tried to retrieve the "getLogoutUrl("next") and open that, but I still get the "success" from Facebook login site, and the security warning, instead of the login site. Another annoying issue is that facebook now has started to issue a top-label saying something like: "Your browser is not supported ...." I'm using webEngine with javafx. If you know how to get rid of that - that would be great.

**Comment by kbk1303** [comment]
> hi,
> 
> I can find a lot of good tutorials on how to log in to Facebook, and do all sorts of stuff with the API, which is absolutely fine, but I need to be able to log out of Facebook, immediately after a user logged in. I can't really find a good example of how to do that. I guess it is a question of invalidating the access token.
> 
> I have tried to retrieve the "getLogoutUrl("next") and open that, but I still get the "success" from Facebook login site, and the security warning, instead of the login site. Another annoying issue is that facebook now has started to issue a top-label saying something like: "Your browser is not supported ...." I'm using webEngine with javafx. If you know how to get rid of that - that would be great.

Btw. I'm using version 3.4.0

**Comment by nbartels** [comment]
I hope you use instead of the parameter "next" a real url you like to redirect to.

BTW, maybe this helps on the "unsupported browser" message: https://stackoverflow.com/questions/48046586/javafx-webview-recaptcha-wont-work-unsupported-browser

**Comment by kbk1303** [comment]
Hi,
Well, it doesn't really matter whether I use a real redirect URL or a localhost (or null). The result is the same. But I think this has to do with session cookies, rather than logging out of Facebook. I will fiddle around with that today.

**Comment by nbartels** [comment]
okay, I see. We just provide this URL for convenience.
I didn't find any official way to use the API to logout. So it's a bit more tricky here. Maybe your session cookie approach will work.

Great to hear, that you solved the "not supported browser" problem...
