### ISSUE TITLE
Facebook send text instead of postback button payload in persistent menu

### ISSUE THREAD

**Issue by AlonKapi** [restfb/restfb#1106]
Hello,
I'm using restfb version 3.12.0 and I'm trying to add a postback button to persistent menu like this:
```

FacebookClient client = new DefaultFacebookClient(PAGE_ACCESS_TOKEN, APP_SECRET, Version.LATEST);
PersistentMenu defaultMenu = new PersistentMenu();
defaultMenu.addCallToAction(new PostbackButton("Restart Conversation", "RESTART"));
JsonObject response = client.publish("me/messenger_profile",
			        JsonObject.class,
			        Parameter.with("persistent_menu", Arrays.asList(defaultMenu)));
```

and I get a success repsonse from Facebook, but when I actually click on the button in the menu I get text response from Facebook with the text "Restart Conversation", instead of postback response with payload "RESTART".

Any idea why this happens?

**Comment by nbartels** [comment]
Hm, interesting. Do you see the correct text on the button in your menu?

According to our unit tests and the Facebook description the JSON should be correct. 
But maybe it is this bug here on Facebook: https://developers.facebook.com/support/bugs/739951780213405/

**Comment by AlonKapi** [comment]
Yes I see the correct text, seems like it is indeed a bug in Facebook.
