### ISSUE TITLE
Extending CategorizedFacebookType "from"

### ISSUE THREAD

**Issue by santinomazzocchi** [restfb/restfb#1134]
Hi,
I need to get the subfield "global_brand_page_name" in field "from" of various classes: Photo, Album, Comments, Post.
Via api it's possible to ask him using this parameter:  "fields=from{id,name,global_brand_page_name}".

In restfb I don't get it because "from" is mapped in CategorizedFacebookType class, containing only the field "category".

How can I extend this class to include this extra field?

**Comment by nbartels** [comment]
Hm, this is a bit tricky.

I would try to extend Photo and so on and add a second `from` field of the type Page. 

```java
MyPhoto extends Photo {

   @Facebook("from")
   private Page pageFrom;

  // add getter
}
```

**Comment by santinomazzocchi** [comment]
Hi,
thank you, I hoped in an alternative way (more integrated) but I'll use this.

**Comment by santinomazzocchi** [comment]
Hi,
thank you!

Santino

**Comment by nbartels** [comment]
We try to get a more generic way to replace the used `from` type to the one the developer likes to use (Page/User), but no good idea so far 😞

**Comment by santinomazzocchi** [comment]
It's possible in some way to expose the new field with a different alias?

Like @JsonAlias("temperature") in this Jackson example https://www.baeldung.com/json-multiple-fields-single-java-field?

**Comment by nbartels** [comment]
Ah, interesting idea. The only Problem I see is, that we have to merge the `User` and the `Page` object fields in one and maybe work with the alias. A solution I was thinking about was adding to fields that are mapped to the Facebook from field and one returns the Page and one the User. The question is, if a developer will understand this and can really determine which version he/she needs.

**Comment by santinomazzocchi** [comment]
I’m in trouble with comments: extending the class does’t work because I iterate them with Comments.getData(), which return the super class..

**Comment by nbartels** [comment]
Okay, I see. I try to provide a solution ...

**Comment by nbartels** [comment]
Please give the 3.15.0 a try. We have a new "From" type that contains the User and the Page object. It's about to the developer to decide what is the best object for the use case.

The "From" type extends the `CategorizedFacebookType` for compatibility reasons ...

**Comment by santinomazzocchi** [comment]
Great, it works like a charm!

Thank you Norbert for the great job you're doing with restfb!
