### ISSUE TITLE
Get user data from a comment

### ISSUE THREAD

**Issue by pintotomase** [restfb/restfb#1136]
Hello, thank you for this library, so far it has been of great use to me!

I'm having the following problem while fetching comments from facebook. First I get get the parent id (for example, an id of a Post object) and do:

`        Connection<Comment> allComments = client.fetchConnection(parentId+"/comments", Comment.class, Parameter.with("fields", "parent,id,from,message"), Parameter.with("limit",2));`

(I have also tried from{name,id})
        
Problem is, I can iterate throught each comment from allComents but in some cases, getFrom() is null

```
        for(List<Comment> postComments : comments) {
            for (Comment c : postComments){
                ....
                c.getFrom() // <--- this returns null
            }
        }
```
The cases in which it's null is when the author is not the page administrator itself. Am I doing something wrong? When I use graph API directly I can get the From information of any author besides it's the administrator or not

I appreciate your help

**Comment by nbartels** [comment]
I think it's a problem with the Standard and Advanced Access level of the application. It is similar to the development and live mode. So I think the data is filled after your application is reviewed. If I find more information I'll post it here. But this may take some time...

**Comment by pintotomase** [comment]
> I think it's a problem with the Standard and Advanced Access level of the application. It is similar to the development and live mode. So I think the data is filled after your application is reviewed. If I find more information I'll post it here. But this may take some time...

Thank you! I didn't get my app reviewed yet because I was juts making some tests and it required contracts and other stuff I currently don't have, but I am reassured if once reviewed it should work fine. Let me know if I can help with something!

**Comment by nbartels** [comment]
Okay, If the graph api explorer provides the information you should check the returned JSON by changing the loglevel of RestFB. Maybe the information is not there. If it is there and the Comment is not filled correctly you found a bug ;)
