### ISSUE TITLE
Programatically delete old, stuck test-users from integration tests

### ISSUE THREAD

**Issue by zzvara** [restfb/restfb#1147]
Relates to the issue https://github.com/restfb/restfb/issues/1084.

I found no endpoint on the current Graph API that would support a `get-all` operation on all `TestUser` types. Some integration tests leave users in the account, therefore eventually reaching the limit of 2000. On the web UI of Facebook, there is no way to "mass-delete" these `TestUsers`. [1]

Is there any way to get all the `TestUser`s? I'm thinking if maybe there is an undocumented way or I'm missing something.

Thanks!

[1] https://developers.facebook.com/docs/graph-api/reference/v10.0/test-user

**Comment by nbartels** [comment]
I don't see a way to get all test users either. Maybe you should save the test user ID in your test case and remove the test user on teardown.

Or maybe someone on [stackoverflow](https://stackoverflow.com/questions/tagged/facebook-graph-api) knows a way to get all test users.
