### ISSUE TITLE
Publishing to FB Pages not possible anymore?

### ISSUE THREAD

**Issue by joergrech** [restfb/restfb#1150]
Hi, since this month I can't post to my pages anymore. Facebook returns the following error:

`Received Facebook error response of type OAuthException: (#200) This endpoint is deprecated since the required permission publish_actions is deprecated`

Is posting to Pages now completely deprecated or is there another way to post an Image with a message to them?

**Comment by nbartels** [comment]
Can you please check your access token in the access token debugger? The assigned permissions are interesting here. What endpoint do you use?

**Comment by joergrech** [comment]
Sorry but it seems that it was my fault - I did not explicitly selected "Page" and the Graph API Explorer generated a "User" Token. The error message from FB did not help.

By the way, is there an easy way to use the refresh token to update the access token programmatically? I only need the Facebook access for my own Page - not from other users.

**Comment by nbartels** [comment]
Maybe you can check for the "long-lived" access tokens. But you have write a small application to get the user access token before you can convert it to a long-lived one.
https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing

In our https://github.com/restfb/restfb-examples repository, you can find an javafx example how to get a user access token.
