### ISSUE TITLE
Add media_product_type and video_title fields to IgMedia

### ISSUE THREAD

**Issue by StephenFlavin** [restfb/restfb#1152]
these two fields were added to the Instagram graph api in v10.0 to support the addition of IGTV posts https://developers.facebook.com/docs/instagram-api/reference/ig-media
It looks like `media_product_type` could be an enum of AD, FEED, IGTV, or STORY although might be simpler for the maintainability for this to be a string.

**Comment by StephenFlavin** [comment]
@nbartels thanks for the quick work however, it looks like your comment is referencing the wrong field https://github.com/restfb/restfb/commit/430a5c032e7af5854dd211b14b7fd0abf54c2674#diff-388bdad70396ba2df5c808b55ec506e214841beb84bf4d87c34c67b200aaf934R75

**Comment by nbartels** [comment]
Thanks, now it should be fine :)
