### ISSUE TITLE
Instagram messaging

### ISSUE THREAD

**Issue by PavelHumeniuk** [restfb/restfb#1159]
Please, add support for Instagram messaging
https://developers.facebook.com/docs/messenger-platform/instagram

**Comment by PavelHumeniuk** [comment]
it looks like it is already supported by the existing graph API, but maybe I didn`t find all cases.

**Comment by nbartels** [comment]
Hm, I check this. Instagram messaging sounds interesting ...

**Comment by gurkein** [comment]
NamedFacebookType referenced by Conversation class is not enough to handle "username" and "user_id" fields. Most of the other parts are already supported.

**Comment by nbartels** [comment]
@gurkein can you please provide some example json?

**Comment by gurkein** [comment]
From https://developers.facebook.com/docs/messenger-platform/instagram/features/conversation:

Sample `Conversation` response JSON:
```
{
  "id": "<THREAD_ID>"
  "participants": {
      'data': [
          {
              "username": "<IG_USER_NAME>" // user name of the user 
              "id":  "<IGSID>" // ig scoped id of the user  
              "user_id": "<IGID>",     
          },
          {
              "username": "<IG_USER_NAME>",// username of the business
              "id":  "<IGID>", // business id      
              "user_id": "<IGID>",
          },
      ]
  }
}
```
Look at the participants array fields `username` and `user_id`. Those are mapped to `NamedFacebookType` which only includes `id` and `name`. 

You can implement `ExtendedReferenceType` which extends `NamedFacebookType` including those fields. Then you should update `NamedFacebookType` fields in both `Conversation` and `Message`.

Also two new fields have been added to `Message` class for Instagram. You can find `story` and `reactions` fields details from the above link.

Here's an example for those new fields:
```
{
  ...,
  "reactions" : {
      "data": [
          {
              "reaction": "love",
              "users" : [
                  {
                      "username": "<IG_USERNAME>",
                      "id": "<IGSID|IGID>", //if sent to business then IGID else IGSID
                      "user_id": "<IGID>"
                   }
              ]
          }
      ]
  },
  "story" : {
     "reply_to": { // Story Reply Feature
       "link": "<CDN_URL>",
       "id": "<STORY_ID>"
     },
     "mention": { // Story Mention Feature
        "link": "<CDN_URL>",
        "id": "<STORY_ID>"
     }
  },
  ...
}
```

**Comment by gurkein** [comment]
For querying user profiles may developers also need a class to map the returned data that has `name` and `profile_pic` fields: https://developers.facebook.com/docs/messenger-platform/instagram/features/user-profile

For Facebook profiles `UserProfile` is used. But it does not have `name` field.

**Comment by gurkein** [comment]
Additional info: For querying user profiles for Facebook counterpart, a class with a `name` field is also needed:
https://developers.facebook.com/docs/messenger-platform/identity/user-profile

`UserProfile` does not have all the fields. Not critical but minor problem. Maybe a generic class for messenger user profiles can be implemented.

**Comment by nbartels** [comment]
Many thanks for the input, I try to resolve the current problems, so the next version will provide support for the instagram messaging feature.
