### ISSUE TITLE
private replies to a public post/comment for FB Version11

### ISSUE THREAD

**Issue by sheenaagrawal-khoros** [restfb/restfb#1165]
Hi, I am trying to post a private reply to a public post/comment using Facebook's version 11 API.
My request to publish looks as follows:

```
final List<Parameter> parameters = Lists.newArrayList();
var recipient = new CommentIdMessageRecipient(commentId);
parameters.add(Parameter.with("recipient", recipient));
Message toSend = new Message(responseText);
parameters.add(Parameter.with("message", toSend));
var sendResponse = facebookClient.publish("me/messages",
                                      SendResponse.class,
                                      Iterables.toArray(parameters, Parameter.class));
```
                                      
I get this error:
      
      `com.restfb.exception.FacebookOAuthException:` Received Facebook error response of type OAuthException: (#100) Invalid comment_id parameter (code 100, subcode 2018292) 'null - null'`
      
Could you help me with what I am missing.
      
The documentation that I have followed:

https://restfb.com/documentation/#messenger-overview
https://restfb.com/documentation/
https://developers.facebook.com/docs/messenger-platform/discovery/private-replies/

**Comment by nbartels** [comment]
I suggest you activate debugging logging for `com.restfb.HTTP` and check the transferred data. The code looks okay, but maybe the "test_commentid" is not correct.

**Comment by sheenaagrawal-khoros** [comment]
Hi @nbartels 
I debugged and saw that a valid value is getting passed to as commentId.
Its of the format: 100234567891011_100234567891011

Please let me know in case I am missing anything?

Also, the error message from Facebook:

A. contains `'null - null'` at the end. Does it mean anything?
B.  specifies a sub code that I did not find anywhere in the documentation: https://developers.facebook.com/docs/messenger-platform/reference/send-api/error-codes
