### ISSUE TITLE
Examples not updated

### ISSUE THREAD

**Issue by AndrewMarines** [restfb/restfb#1166]
Seems like all this project is deprecated.

```
FacebookClient client = new DefaultFacebookClient(access_token, Version.LATEST);
		
User user = facebookClient.fetchObject("me", User.class);
		
System.out.println("User name: " + user.getName());
```
This, for example, is not working anymore.

Could you please update your examples?

**Comment by AndrewMarines** [comment]
What do you mean with 

> correct user access token

?
It's been a long time since i worked with FB dev and i usually used [this](link) to access the token

**Comment by nbartels** [comment]
The Graph API Explorer is good enough to get a valid access token. 
So, can you explain, what is not working. Do you get some error message, or something?

**Comment by AndrewMarines** [comment]
[This ](https://pastebin.com/yVFL4GHy)is the code.
The exceptions are: 
```
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	User cannot be resolved to a type
	facebookClient cannot be resolved
	User cannot be resolved to a type

```

**Comment by revetkn** [comment]
It looks like you are trying to run the code even though it did not compile correctly.  If you are using an IDE, maybe it is not set up correctly to use the RestFB JAR?

Have you tried the examples at https://github.com/restfb/restfb-examples?

**Comment by revetkn** [comment]
Also, you will need more imports than just `import com.restfb.*;` before your code will compile.

**Comment by nbartels** [comment]
As @revetkn suggested: Please check your classpath, it sounds like the RestFB jar cannot be found.

**Comment by r1bnc** [comment]
This is unrelated but I just don't want to open an issue.
Can this project be used to programatically unsend sent messages of a user on Messenger using the user's account?

**Comment by nbartels** [comment]
I don't think so, because nowadays most of the actions you can trigger via the API are on behalf of the page. 

Feel free to open an issue if you have questions or send us a message via the contact form or the fb messenger ;)

**Comment by r1bnc** [comment]
Thank you for the information.
