### ISSUE TITLE
Graph API 12: deprecated fields in page object

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#1172]
This fields are deprecated:

* GET /{page-id}/admin_notes
* GET /{page-id}/businessprojects
* GET /{page-id}/connected_instagram_account
* GET /{page-id}/connected_page_backed_instagram_account
* GET /{page-id}/insights_exports
* GET /{page-id}/instagram_business_account

**Comment by gurkein** [comment]
@nbartels are you sure about the deprecation?

Related parts from the changelog:

The Graph API **default behavior** is **to throw an error when an app requests a field or edge that returns an associated node or nodes, but lacks the appropriate permissions required by the associated nodes**. Fields and edges on the endpoints listed below did not follow this protocol and instead were omitted from API responses when the calling app lacked appropriate permissions. Starting with version 12.0, these fields and edges will now conform to the default behavior. This change will apply to all versions on December 13, 2021.

Hence this is not a deprecation, but a behavior change only.
