### ISSUE TITLE
Missing shop product type

### ISSUE THREAD

**Issue by TheFuseGamer** [restfb/restfb#1182]
Hello, when I share a product from Facebook shop I get the following webhook payload

`
{
  "object": "page",
  "entry": [
    {
      "id": "page id",
      "time": 1636729432317,
      "messaging": [
        {
          "sender": {
            "id": "send id"
          },
          "recipient": {
            "id": "page id"
          },
          "timestamp": 1636729431949,
          "message": {
            "mid": "m_id",
            "text": "text sent along with the product",
            "attachments": [
              {
                "type": "template",
                "payload": {
                  "product": {
                    "elements": [
                      {
                        "id": "12345678910",
                        "retailer_id": "123456",
                        "image_url": "https://scontent.xx.fbcdn.net/v/...",
                        "title": "product name",
                        "subtitle": "product price as a string"
                      }
                    ]
                  }
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
`

I can't seem to find a way to handle this.

**Comment by nbartels** [comment]
It looks like a messenger object ... interesting. I'll check this.
