### ISSUE TITLE
Whatsapp Conversation Analytics Objects

### ISSUE THREAD

**Issue by akashtyagi08** [restfb/restfb#1194]
https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account/conversation_analytics/

Can we expect a object class build around the response for conversation_analytics endpoint ?

Like we already have for WABA Analytics, https://github.com/restfb/restfb/blob/master/src/main/lombok/com/restfb/types/whatsapp/WABAAnalytics.java

**Comment by nbartels** [comment]
Yes, I check the structure and provide a suitable object in the next days ...
