### ISSUE TITLE
Support for `onBehalfOfBusinessInfo` field in `WhatsAppBusinessAccount`

### ISSUE THREAD

**Issue by maganth-seetharaman** [restfb/restfb#1195]
The [onBehalfOfBusinessInfo](https://github.com/restfb/restfb/blob/master/src/main/lombok/com/restfb/types/whatsapp/WhatsAppBusinessAccount.java#L88-L92) field is commented stating the field "is not defined in Graph API reference"

The field is now defined in [WhatsAppBusinessAccount](https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account) Graph API reference. 
Would like to know if it is possible to support this field.

**Comment by nbartels** [comment]
The problem here is, that the `WABAOnBehalfOfComputedInfo` is not defined in the Facebook API reference. So I have no idea how it looks like. I could use a JsonObject, but I'm not sure if this is usable. If you have a link to a description or you can send me the metadata I can add it in one of the next releases.

**Comment by maganth-seetharaman** [comment]
This is the response for the field we are receiving currently
```json
"on_behalf_of_business_info": {
     "name": "STRING",
     "id": "STRING",
     "status": "STRING",
     "type": "STRING"
}
```

**Comment by maganth-seetharaman** [comment]
When is the expected/estimated release of [2022.3.0](https://github.com/restfb/restfb/milestone/123)?

**Comment by nbartels** [comment]
Hopefully until tomorrow (CET) 😎

**Comment by maganth-seetharaman** [comment]
Wow that was fast thanks

**Comment by nbartels** [comment]
@maganth-seetharaman you can check the 2022.3.1 now, it is fixed there 😎

**Comment by maganth-seetharaman** [comment]
Thank you so much for the quick fix ❤️
