### ISSUE TITLE
Unsubscribe app to a Webhook for a Facebook Page

### ISSUE THREAD

**Issue by Sofasmile** [restfb/restfb#1209]
Before we could use the following approach to unsubscribe:
```
FacebookClient facebookClient = new DefaultFacebookClient(pageAccessToken, Version.VERSION_13_0);
facebookClient.deleteObject("me/subscribed_apps", Parameter.with("object", "page"));
```
But now we should use this request to unsubscribe:
```
https://graph.facebook.com/v13.0/{page_id}/subscribed_apps?access_token={access_token}
```
where:
- {page_id} - is the id of connected page
- {access_token} - is the app access token. Or you can just pass your app ID and app secret as the access_token parameter `&access_token={your-app_id}|{your-app_secret}`

<img width="787" alt="image" src="https://user-images.githubusercontent.com/36365171/167811971-95ce1847-cd39-4713-89a6-5967ca25b767.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/36365171/167812544-4bf5f035-62b9-4362-8cda-d97ae6313c86.png">

**Comment by nbartels** [comment]
According to this docs, it is still possible to use the method you are using: https://developers.facebook.com/docs/graph-api/reference/v13.0/page/subscribed_apps

If you like to work with the app access token, simply create a new `FacebookClient` object.

```java
String appAccessToken = "<your app id>|<your app secret>"; // don't forget the pipe sign between
FacebookClient fbClientApp = new DefaultFacebookClient(appAccessToken, Version.VERSION_13_0);
fbClientApp.deleteObject("<pageid>/subscribed_apps");
```
