### ISSUE TITLE
Webhook event messaging_seen

### ISSUE THREAD

**Issue by Nick97-git** [restfb/restfb#1210]
Hi! Can't subscribe to Instagram webhook event messaging_seen. Have such an error:
`Received Facebook error response of type OAuthException: (#100) Param subscribed_fields[2] must be one of {feed, mention, name, picture, category, description, conversations, branded_camera, feature_access_list, inbox_labels, standby, message_mention, messages, message_reactions, messaging_account_linking, messaging_checkout_updates, messaging_customer_information, message_echoes, message_deliveries, messaging_game_plays, messaging_optins, messaging_optouts, messaging_payments, messaging_postbacks, messaging_pre_checkouts, message_reads, messaging_referrals, messaging_handovers, messaging_policy_enforcement, messaging_page_feedback, messaging_appointments, messaging_direct_sends, messaging_fblogin_account_linking, user_action, messaging_feedback, founded, company_overview, mission, products, general_info, leadgen, leadgen_fat, location, hours, parking, public_transit, page_about_story, mcom_invoice_change, invoice_access_invoice_change, invoice_access_onboarding_status_active, local_delivery, phone, email, website, ratings, attire, payment_options, culinary_team, general_manager, price_range, awards, hometown, current_location, bio, affiliation, birthday, personal_info, personal_interests, members, checkins, page_upcoming_change, page_change_proposal, merchant_review, product_review, videos, live_videos, video_text_question_responses, registration, publisher_subscriptions}. (code 100, subcode null) 'null - null'
`

Maybe there's an option for how to deal with this?

**Comment by nbartels** [comment]
I think the field you try to use is the wrong one, and you should use instead of `messaging_seen` the `message_reads`. https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-reads

**Comment by nbartels** [comment]
yes, strange thing. In the list, you shared above as part of the error, there is no messaging_seen either

**Comment by Nick97-git** [comment]
https://stackoverflow.com/questions/58370116/instagram-webhook-subscription-fails
here is suggested to use another version, because Instagram webhook events weren't supported by the new version of subscribed_apps, but this issue was several years ago + this solution didn't help me

**Comment by Nick97-git** [comment]
To fix this problem I catch an error and process it in case of subscribed_fields contains messaging_seen, because even if you get such an error, webhook events are set successfully))

**Comment by nbartels** [comment]
According to the Facebook webhook docs, you do everything right: https://developers.facebook.com/docs/graph-api/webhooks/reference/instagram/v13.0

Can you please show your code with the endpoint?

**Comment by Nick97-git** [comment]
`FacebookClient client = new DefaultFacebookClient(account.getAccessToken(), VERSION);
GraphResponse result = client.publish("me/subscribed_apps",
        GraphResponse.class,
        Parameter.with("subscribed_fields", "messages,messaging_seen,message_reactions,messaging_postbacks"));
 return result.isSuccess();`

**Comment by nbartels** [comment]
![image](https://user-images.githubusercontent.com/1113969/168901824-f4fd9855-c367-4735-a467-c0f4f2a68328.png)

Maybe that's the reason?

**Comment by Nick97-git** [comment]
Maybe, but there are companies that somehow do this without using the app dashboard + I did this too using the approach described above. It'll be enough for now. Thanks for your time, hope this limitation will be removed soon)

**Comment by nbartels** [comment]
You're welcome
