### ISSUE TITLE
Using of RestFB with Instagram

### ISSUE THREAD

**Issue by Nick97-git** [restfb/restfb#1211]
Hi, again) Have a question about your documentation, more specific about this part:
![Screenshot 2022-05-18 at 15 13 44](https://user-images.githubusercontent.com/60258373/169036340-e241fa89-1020-49f7-b969-f9f3a51449b0.png)
When it'll be possible to use your lib for Instagram not only by your partners?

**Comment by Nick97-git** [comment]
Maybe I didn't understand the first time correctly, I thought, that I can't do anything related to publishing on Instagram, even sending messages.

**Comment by nbartels** [comment]
I see, our documentation is misleading here, I'll fix this ...

**Comment by Nick97-git** [comment]
Thanks again)
