### ISSUE TITLE
How to use filtering to get leads

### ISSUE THREAD

**Issue by HelloWordU** [restfb/restfb#1212]
Hello there ,when i use restfb to get leads ,i try the flowing code  

facebookClient.fetchObject(futureFacebookFormId, JsonObject.class, Parameter.with("fields", "leads{id,created_time,ad_id,ad_name,adset_id,adset_name,campaign_id,campaign_name,form_id,is_organic,field_data}"),
                                Parameter.with("filtering", "[{\"field\":\"created_time\",\"operator\":\"GREATER_THAN\",\"value\":" + searchTimeSeconds + "}]")

then i find  there  filtering  Parameter not working ,can any body help me

**Comment by nbartels** [comment]
I suggest, you enable the RestFB HTTP log and check the requests there, if the url looks fine: https://restfb.com/documentation/#logging

**Comment by HelloWordU** [comment]
> I suggest, you enable the RestFB HTTP log and check the requests there, if the url looks fine: https://restfb.com/documentation/#logging

Thanks for reply  

i open the trace and get the flowing info :


17:18:31.754 logback [main] DEBUG com.restfb.HTTP - Making a GET request to https://graph.facebook.com/v12.0/1076420079436311?fields=leads%7Bid%2Ccreated_time%2Cad_id%2Cad_name%2Cadset_id%2Cadset_name%2Ccampaign_id%2Ccampaign_name%2Cform_id%2Cis_organic%2Cfield_data%7D&filtering=%5B%7B%22field%22%3A%22created_time%22%2C%22operator%22%3A%22GREATER_THAN%22%2C%22value%22%3A1652920710%7D%5D&access_token=XXXXXXXXXXXX&format=json
17:18:31.754 logback [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=dev_group_oversea] Discovered coordinator 10.2.2.87:9092 (id: 2147483647 rack: null)
17:18:32.283 logback [main] DEBUG com.restfb.HTTP - Facebook used the API v12.0 to answer your request
17:18:32.284 logback [main] DEBUG com.restfb.HTTP - Facebook responded with HTTP status code 200 and response body: {"leads":{"data":[{"id":"564598075096592","created_time":"2022-05-12T13:03:12+0000","form_id":"1076420079436311","is_organic":true,"field_data":[{"name":"insa","values":["uwuywyet"]},{"name":"full_name","values":["\u4e0d\u540c\u8868\u5355\u4e2d\u7684111"]},{"name":"email","values":["452544t54\u0040qq.com"]},{"name":"phone_number","values":["+8618745050987"]},{"name":"work_email","values":["452544t54\u0040qq.com"]}]}],"paging":{"cursors":{"before":"QVFIUmdqdUJiRzMwNTVBOFJnb0lsVVFfNU93M3RUMlhQMERjNmswa3B0Tk9EWHZA2MEYzZA0JJd0VZAeHNEUWpaREtZAZAzgxQ3JncTdqVW9sbkI1SWVyN2VpUS1n","after":"QVFIUmdqdUJiRzMwNTVBOFJnb0lsVVFfNU93M3RUMlhQMERjNmswa3B0Tk9EWHZA2MEYzZA0JJd0VZAeHNEUWpaREtZAZAzgxQ3JncTdqVW9sbkI1SWVyN2VpUS1n"}}},"id":"1076420079436311"}



request params  filtering=%5B%7B%22field%22%3A%22created_time%22%2C%22operator%22%3A%22GREATER_THAN%22%2C%22value%22%3A1652920710%7D%5D   use urlencode is  [{"field":"created_time","operator":"GREATER_THAN","value":1652920710}]
i find this param from  [here](https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving)  but  i still get the worng answer ,the logging info shows the result i get a  2022-05-12T13:03:12+0000 data ,acturely  i want  created_time > 1652920710 （means： 2022-05-19 08:38:30）

**Comment by HelloWordU** [comment]
sorry  it's my fault, 

 curl -X GET \
  -d 'filtering=[
       {
         "field": "time_created",
         "operator": "GREATER_THAN",
         "value": 1652348056
       }
     ]' \
  -d 'access_token=<ACCESS_TOKEN>' \
  https://graph.facebook.com/v13.0/{adgroup-id}/leads

that's another api ,i make misstakes .
