### ISSUE TITLE
DefaultJsonMapper Should Support Enumerated Types

### ISSUE THREAD

**Issue by MusikPolice** [restfb/restfb#122]
While attempting to add support for Facebook Payment objects, I created a custom class to deserialize the object into and annotated its fields with RestFb's @Facebook annotation. This works in the general case, but DefaultJsonMapper throws a com.restfb.exception.FacebookJsonMappingException when it attempts to deserialize into an enum type.

The Facebook Payment object contains many fields that will always contain one of a finite number of string values, such as actions.type, actions.status, actions.currency, etc, and it would be nice if the object that I am deserializing this response into could represent these strings as an enum type as well.

See the "Responding to Updates" section of https://developers.facebook.com/docs/payments/realtimeupdates/ for an example of the object that I'm attempting to deserialize.

**Comment by nbartels** [comment]
The `DefaultJsonMapper` can handle enums now, enums not added. This should be done in different issues.

**Comment by nbartels** [comment]
Breaking Change label removed because the current implementation does not change the API.
