### ISSUE TITLE
Can I send WhatsApp Business Platform  Cloud API message using restfb

### ISSUE THREAD

**Issue by astrit-hakobyan** [restfb/restfb#1225]
I see WABP integration is in upcoming todo. Currently can I send simple whatsapp Media Messages using restfb?

```shell
curl -X  POST \
 'https://graph.facebook.com/v13.0/FROM_PHONE_NUMBER_ID/messages' \
 -H 'Authorization: Bearer ACCESS_TOKEN' \
 -d '{
  "messaging_product": "whatsapp",
  "recipient_type": "individual",
  "to": "PHONE_NUMBER",
  "type": "image",
  "image": {
    "id" : "MEDIA_OBJECT_ID"
  }
}'
```

**Comment by nbartels** [comment]
As I see, the problem is the data. The publish methods we have so far, can only post form data. But we have no way so far to post a "simple" json. I think this should be one of the next steps before supporting all the objects.

The access token in the header is not a problem and the `DefaultFacebookClient` has already the `setHeaderAuthorization` method in place.

**Comment by nbartels** [comment]
As short update. I will use this issue to add a way to post a JSON as "body" to an endpoint as alternative to send the data in a form.

This should solve the basic problem, and you can start (as soon as the release is published) using RestFB to send WhatsApp messages.

The concept is ready so far, and I already started the implementation, but the unit tests are missing atm. Hopefully everything's ready after the weekend and this great feature will be available next week.

Thanks for the input/question 😀

**Comment by nbartels** [comment]
With the next release it will be possible using a code similar to this snippet:

```java
DefaultFacebookClient fbClient = new DefaultFacebookClient("<access token>", Version.VERSION_13_0);
fbClient.setHeaderAuthorization(true);
JsonObject message = new JsonObject();
// fill message JSON here - as long as we have no WABP objects in place 
Body body = Body.withData(message);
JsonObject result = fbClient.publish("FROM_PHONE_NUMBER_ID/messages", JsonObject.class, body);
```

**Comment by nbartels** [comment]
I have to correct the code.
After writing an integration test, this is the code that sends an WA message.

```java
DefaultFacebookClient fbClient = new DefaultFacebookClient(waAccessToken, Version.VERSION_13_0);
fbClient.setHeaderAuthorization(true);
    
JsonObject textJso = new JsonObject();
textJso.add("preview_url", false);
textJso.add("body", "this is a short test message");

Parameter[] params = new Parameter[] { //
        Parameter.with("messaging_product", "whatsapp"), //
        Parameter.with("recipient_type", "individual"), //
        Parameter.with("type", "text"), //
        Parameter.with("to", "<recipient number>"), //
        Parameter.with("text", textJso)};

// Send the data and get the result as JsonObject
JsonObject jso = fbClient.publish(sendWaId + "/messages", JsonObject.class, params);
System.out.println(jso.toString());
```

**Comment by nbartels** [comment]
With the latest fix on this issue, it is possible to post a json object direct as body.
So you have the choice to use parameters or the body.

Using body looks like:

```java
DefaultFacebookClient fbClient = new DefaultFacebookClient(waAccessToken, Version.VERSION_13_0);
fbClient.setHeaderAuthorization(true);

JsonObject sJso = new JsonObject();
sJso.add("messaging_product", "whatsapp");
sJso.add("recipient_type", "individual");
sJso.add("type", "text");
sJso.add("to", "<recipient number>");

JsonObject textJso = new JsonObject();
textJso.add("preview_url", false);
textJso.add("body", "this is a short test message");
sJso.add("text", textJso);

// post json as body
JsonObject jso = fbClient.publish(sendWaId + "/messages", JsonObject.class, Body.withData(sJso));
System.out.println(jso.toString());
```

**Comment by astrit-hakobyan** [comment]
Thank you for fast response
