### ISSUE TITLE
Request phone number and share contact 

### ISSUE THREAD

**Issue by liliia-ponomarenko** [restfb/restfb#1228]
Hi! 

I tried to find components to send a request to shared contact with the bot (the user receives a keyboard button with an informative message, and can send a phone number by clicking on it). Such functionality is available in Viber and Telegram libraries. Is it possible to receive user contact information from Instagram and/or Facebook?

Regards, L.Ponomarenko

**Comment by nbartels** [comment]
With the Facebook messenger this is possible as you can see in the facebook send api reference;:https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies

**Comment by liliia-ponomarenko** [comment]
Thanks a lot, I will try it ;)

**Comment by liliia-ponomarenko** [comment]
Hello! 

I tried to implement a contact request from Facebook users as you suggested and it works correctly. 
Thank you very much! 

Next step I tried to implement the same for Instagram but it doesn't work as expected. At first, I tried to implement it in the same way as Facebook, but I received an exception in response. 
Also, I tried to implement it as follows: 

` QuickReply quickReply = new QuickReply(
      QuickReply.QuickReplyType.USER_PHONE_NUMBER.getContentType(), "title", "payload");
    message.addQuickReply(quickReply);`

it works without exception, but the user receives a request with the text "Phone number" (screens below). 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/96740815/176988272-d6ac1d91-bec1-4074-b969-7534aabb4ed1.png">
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/96740815/176988287-21ef23e0-f596-4db3-ac2d-0b7bf5a67386.png">

Could you please tell me if it is possible to request the phone numbers of Instagram users? 
How can I implement this if possible?

**Comment by nbartels** [comment]
According to the Facebook docs (https://developers.facebook.com/docs/messenger-platform/instagram/features/quick-replies) this is not possible for Instagram.

![image](https://user-images.githubusercontent.com/1113969/176997764-6f7e4df2-a1c2-4ff2-a513-5a1fe677c060.png)

**Comment by liliia-ponomarenko** [comment]
Ok. Thanks a lot for your help!
