### ISSUE TITLE
Reels API feature

### ISSUE THREAD

**Issue by gurkein** [restfb/restfb#1229]
https://developers.facebook.com/blog/post/2022/06/27/introducing-reels-apis-to-instagram-platform/

Summary:
- Available for all versions of the Graph API
- July 6: expected to complete rollout to 100% of users
- Reels publishing enabled: `media_type=REELS`, 'share_to_feed=boolean` \
  https://developers.facebook.com/docs/instagram-api/reference/ig-user/media
- Media fields related to reels: `media_product_type=REELS, is_shared_to_feed=boolean` \
https://developers.facebook.com/docs/instagram-api/reference/ig-media

**Comment by nbartels** [comment]
Many thanks for the input. Publishing is no problem because there, `Parameter.with` is used. But the `IgMedia` type needs the additional `is_shared_to_feed` field. `media_product_type` is a String, so already prepared to handle Reels.
