### ISSUE TITLE
WABP: interactive messages are not implemented according to documentation

### ISSUE THREAD

**Issue by ztomic** [restfb/restfb#1268]
Hi,

according to [documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#header-object), text header only has string value:

![image](https://user-images.githubusercontent.com/1428972/216313081-44997f39-2f9c-4433-8a0d-c2a18b20dc94.png)

Implementation is wrapping string value to "body" so invalid json is produced:

```json
"header": {
	"text": {
	   "body": "This is header text"
	},
	"type": "text"
}
```

Correct should be:
```json
"header": {
	"text": "This is header text",
	"type": "text"
}
```

Example exception:
```log
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#100) Param interactive['header']['text'] must be a string. (code 100, subcode null) 'null - null'
        at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerator.java:181)
```

**Comment by ztomic** [comment]
Buttons are also invalid.

Valid json part according to documentation:
```json
"action": {
      "buttons": [
        {
          "type": "reply",
          "reply": {
            "id": "UNIQUE_BUTTON_ID_1",
            "title": "BUTTON_TITLE_1"
          }
        },
        {
          "type": "reply",
          "reply": {
            "id": "UNIQUE_BUTTON_ID_2",
            "title": "BUTTON_TITLE_2"
          }
        }
      ]
    }
```

Invalid json part produced from library:
```json
"action": {
			"buttons": [
				{
					"title": "Button 1 title",
					"id": "button-1",
					"type": "reply"
				},
				{
					"title": "Button 2 title",
					"id": "button-2",
					"type": "reply"
				},
				{
					"title": "Button 3 title",
					"id": "button-3",
					"type": "reply"
				}
			]
		}
```

**Comment by nbartels** [comment]
Hi @ztomic, thanks for checking in. Can you please write the code and which RestFB types you are using atm. I checked the objects, and it looks like they are ok, but only if the right ones are used. I think we should add a section how the WhatsApp business platform is used to our documentation 😄 

So, please show me the part of your code and the imports of the objects ...

**Comment by nbartels** [comment]
Many thanks for the example code.
