### ISSUE TITLE
IgMedia getCaption() method return "story"

### ISSUE THREAD

**Issue by Blogmeter** [restfb/restfb#1277]
IgMedia getCaption() method return the string "story" even if the caption in empty. In older versions (e.g. 2.24.1) it returns null. I'm using 3.17.0 version.

**Comment by nbartels** [comment]
Can you please check the JSON you get from the request. I don't see atm how the string "story" can be placed in the caption other than it is part of the JSON.

**Comment by Blogmeter** [comment]
"data": [
    {
      "id": "18054507568386506",
      "caption": "story",
      "media_type": "IMAGE",
      "media_url": "https://scontent.cdninstagram.com/v/t51.12442-15/332391201_727460548791068_2549688391727560596_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=8ae9d6&_nc_ohc=DkEZoiSVmVsAX-tLRXL&_nc_ht=scontent.cdninstagram.com&edm=AB9oSrcEAAAA&oh=00_AfCuM-l7iyaLcjICiS6WsXZS8QrePIsI8OeQrouU84y1Xw&oe=63FD91D2",
      "owner": {
        "id": "17841407234617954"
      },
      "permalink": "https://instagram.com/stories/adriana.blogmeter/3044477074780820854",
      "timestamp": "2023-02-23T10:59:30+0000",
      "insights": {
        "data": [
          {
            "name": "impressions",
            "period": "lifetime",
            "values": [
              {
                "value": -1
              }
            ],
            "title": "Impression",
            "description": "Numero di volte in cui l'elemento multimediale è stato visto",
            "id": "[18054507568386506](https://developers.facebook.com/tools/explorer/177603122289216/?method=GET&path=17841407234617954%2Fstories%3Ffields%3Did%2Ccaption%2Cmedia_type%2Cmedia_url%2Cowner%2Cpermalink%2Cthumbnail_url%2Ctimestamp%2Cinsights.metric(impressions%2Creach%2Cexits%2Creplies%2Ctaps_back%2Ctaps_forward)&version=v10.0#)/insights/impressions/lifetime"
          },
          {
            "name": "reach",
            "period": "lifetime",
            "values": [
              {
                "value": -1
              }
            ],
            "title": "Copertura",
            "description": "Numero totale di account unici che hanno visto questo elemento multimediale",
            "id": "18054507568386506/insights/reach/lifetime"
          },
          {
            "name": "exits",
            "period": "lifetime",
            "values": [
              {
                "value": -1
              }
            ],
            "title": "Uscite",
            "description": "Numero di volte in cui una persona è uscita dal carosello",
            "id": "18054507568386506/insights/exits/lifetime"
          },
          {
            "name": "replies",
            "period": "lifetime",
            "values": [
              {
                "value": 0
              }
            ],
            "title": "Risposte",
            "description": "Numero totale di risposte al carosello",
            "id": "18054507568386506/insights/replies/lifetime"
          },
          {
            "name": "taps_back",
            "period": "lifetime",
            "values": [
              {
                "value": -1
              }
            ],
            "title": "Tocchi per tornare indietro",
            "description": "Numero totale di tocchi per vedere la foto o il video precedente di questa storia",
            "id": "18054507568386506/insights/taps_back/lifetime"
          },
          {
            "name": "taps_forward",
            "period": "lifetime",
            "values": [
              {
                "value": -1
              }
            ],
            "title": "Tocchi per andare avanti",
            "description": "Numero totale di tocchi per vedere la foto o il video successivi di questa storia",
            "id": "18054507568386506/insights/taps_forward/lifetime"
          }
        ]
      }
    }
  ],
  "paging": {
    "cursors": {
      "before": "QVFIUmNrVE9oaDdzdXBqaVUwODhab0pvOE1nbXBxRHdCNUpuNkJscFFoVl9oclZAQalBTNVM0Ymt1c3Ezei1XbHAyLVRDa3M0eUhILTlydVZAVXy1MNjA1TGdR",
      "after": "QVFIUmNrVE9oaDdzdXBqaVUwODhab0pvOE1nbXBxRHdCNUpuNkJscFFoVl9oclZAQalBTNVM0Ymt1c3Ezei1XbHAyLVRDa3M0eUhILTlydVZAVXy1MNjA1TGdR"
    }
  }
}
Response received in 311 ms

the String "story" in caption comes from Facebook graph API, is not a problem of the library. Excuse me for have opened this issue.
