### ISSUE TITLE
BUG: When consulting a post by ID

### ISSUE THREAD

**Issue by vicdaran** [restfb/restfb#1289]
There is a bug in line **157 of the Connection** class, when a message is consulted by id.

The response **JSON** does not contain the "data" element, so it throws a **NullPointerException** exception

The JSON received is directly the message data

Example:
`client.fetchConnection("100063462043113_686474443477951", com.restfb.types.Post.class);`

Possible solution:

```
JsonArray jsonData = new JsonArray();
if(jsonObject.get("data")==null){
        jsonData.add(jsonObject);
}else{
       jsonData = jsonObject.get("data").asArray();
}
```

Thanks

**Comment by nbartels** [comment]
Fetching single objects should use the `fetchObject` method. The `fetchConnection` is for some kind of list of types. We can add some error handling here to give the developer some hint. But in general, if you misuse a method the result may be not as expected 😀

**Comment by vicdaran** [comment]
Oh thanks!

I forgot about the fetchObject, you're right.

Likewise, it would not hurt to control that exception. :-)

Thank you
