### ISSUE TITLE
WABP: Webhooks - CategoryType missing enum constants

### ISSUE THREAD

**Issue by ztomic** [restfb/restfb#1304]
[CategoryType](https://github.com/restfb/restfb/blob/master/src/main/lombok/com/restfb/types/whatsapp/platform/status/CategoryType.java) is missing `authentication, marketing, utility, service` so webhook requests for message status update are failing now.

https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/components (I have not compared all classes, only this one so maybe there are other changes needed also)

![image](https://github.com/restfb/restfb/assets/1428972/e6019111-2c0f-4d18-bccb-987347eac43e)

**Comment by nbartels** [comment]
Would be great if you can post one or more JSONs you receice on your webhook. That makes it much easier to test the modification 😄

**Comment by ztomic** [comment]
I have one in a fork, as I needed to fix it asap. Here is JUnit test

```java
@Test
	public void testPayload() {
		String payload = "{\"object\":\"whatsapp_business_account\",\"entry\":[{\"id\":\"9999999999\",\"changes\":[{\"value\":{\"messaging_product\":\"whatsapp\",\"metadata\":{\"display_phone_number\":\"1111111\",\"phone_number_id\":\"222222222\"},\"statuses\":[{\"id\":\"wamid.bla\",\"status\":\"delivered\",\"timestamp\":\"1685965154\",\"recipient_id\":\"999999999\",\"conversation\":{\"id\":\"698ed3cebasdas23asd44baa7c5387fd9013\",\"origin\":{\"type\":\"marketing\"}},\"pricing\":{\"billable\":true,\"pricing_model\":\"CBP\",\"category\":\"marketing\"}}]},\"field\":\"messages\"}]}]}";
		
		JsonMapper mapper = new DefaultJsonMapper();
		WebhookObject whObject = mapper.toJavaObject(payload, WebhookObject.class);
	}
```

Here I'm just testing if it is parsed without exceptions.

**Comment by nbartels** [comment]
Okay great. I'll add the test afterwards. But for now the code change in 2023.7.0 should fix your problem 😃

**Comment by ztomic** [comment]
It will fix, same thing I have done in a fork and it is working OK with that. Thanks.
