### ISSUE TITLE
Missing app_secret proof.

### ISSUE THREAD

**Issue by walschap** [restfb/restfb#1311]
Hi

When sending a whatsapp message using the body style method we are getting an error from facebook that the appsecret_proof is missing.

When sending the message using the parameters. Listing the 'to','text','messaging_product" ,we are succesfull.

Is the appsecret_proof omitted in this case?

**Comment by nbartels** [comment]
@walschap do you have any docs, where the appsecret_proof should be added in this type of request. Is this still a query parameter? Can you check this, please?

**Comment by walschap** [comment]
hey @nbartels sorry for the late reply. 

I don't find any specifice app_secret handling regarding whatsapp.
The cloud-api docs https://developers.facebook.com/docs/whatsapp/cloud-api/overview are linked to the graph-api docs
https://developers.facebook.com/docs/graph-api/guides/secure-requests where they mention adding it as a parameter. 
My assumption would be that it stays a query parameter.

**Comment by walschap** [comment]
This works.

`curl --location 'https://graph.facebook.com/v17.0/114382691577535/messages?appsecret_proof=159c40800e032142457c42eeab333deea246f9d4fd15e0b155abaa59c26b78c4' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxxx' \
--data '{
  "to": "32487367060",
  "type": "text",
  "text": {"body":"test"},
  "messaging_product": "whatsapp"
}'`


gives

`{
    "messaging_product": "whatsapp",
    "contacts": [
        {
            "input": "32487367060",
            "wa_id": "32487367060"
        }
    ],
    "messages": [
        {
            "id": "wamid.HBgLMzI0ODczNjcwNjAVAgARGBI0NDcwNTFDNEI0NzUwRTM1RkQA"
        }
    ]
}`

**Comment by nbartels** [comment]
Thanks for the hint, I'll check this in the RestFB code. Maybe the appsecret proof is handled with the Body ... let's see

**Comment by nbartels** [comment]
@walschap can you please show the code you use to define the DefaultFacebookClient and the objects you use in the publish method.

I tried this locally with a FakeWebRequestor and the result looks very similar to what you try with curl.

**Comment by walschap** [comment]
Hey norbert,

Instantiation:
`    DefaultFacebookClient defaultFacebookClient =
        new DefaultFacebookClient(
            accessToken,
            secret,
            new DefaultWebRequestor(),
            new DefaultJsonMapper(),
            WHATSAPP_API_VERSION);`
            
           Here we use it:
           
           `    
           DefaultFacebookClient client = facebookClientFactory.getFacebookClient(accessToken.getValue());
    try {
      client.setHeaderAuthorization(true);
      return client
          .publish(
              mediumChannelId.value() + "/messages",
              SuccessfulResponse.class,
              Body.withData(message))
          .getMessages()
          .stream()
          .map(SuccessfulResponse.MessageResponse::getId)
          .collect(Collectors.toList());
    } catch (FacebookGraphException e) {
      LOGGER.debug("Could not publish to whatsapp {}", message);
      throw e;
    }`

**Comment by nbartels** [comment]
Okay @walschap , many thanks for the code. I wrote an integration test and found the problem. I fixed it locally and have to check if the change will break other stuff 😄 

As soon as this is done, I'll release the new version. Thanks for your patience.
