### ISSUE TITLE
Make error_data a property on the exception for easy access. 

### ISSUE THREAD

**Issue by walschap** [restfb/restfb#1341]
Hi

When we receive an error doing whatsapp messaging there is an error_data object present 
https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes/

this is present in the rawErrorJson. Do we need to parse this to get to the details? Or is it possible that they are added as a field on the exception? or in the exception message.

**Comment by nbartels** [comment]
Hi @walschap, 
can you provide me an example JSON?
The issue is about an error object coming in via webhook, right?

**Comment by lennehendrickx** [comment]
Hi @nbartels ,

The issue occurs when sending a message using the send messages api.
https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages/

The `rawErrorJson` of the `com.restfb.exception.FacebookOAuthException` looks like this:

```
{"error":{"message":"(#131009) Parameter value is not valid","type":"OAuthException","code":131009,"error_data":{"messaging_product":"whatsapp","details":"Duplicate button id"},"fbtrace_id":"A7YysJRhDLLwyNk-RXuVBTM"}}
```

Thanks

**Comment by nbartels** [comment]
We added two methods and you can use `getErrorData` on the `FacebookOAuthException` to get an `Optional<JsonObject>`. For convenience reasons, there is the `getErrorData(String field)` and if you know the field you like to check, you can simply fetch it using the second method. For example the `details`.
