### ISSUE TITLE
Facebook Stories API

### ISSUE THREAD

**Issue by saunders-d** [restfb/restfb#1355]
Facebook just recently released image and video stories.

https://developers.facebook.com/docs/page-stories-api

**Comment by nbartels** [comment]
With the release of version 2023.13.0, we now have all the tools necessary to seamlessly publish your stories. The primary distinction between a reel and a story lies in their endpoints: reels utilize the `video_reels` endpoint, while stories employ the `video_stories` endpoint. The uploading process remains consistent, and you can find detailed instructions on how to do so in our documentation: https://restfb.com/documentation/#publishing-reel

I think we can provide a short description in our docs, how to upload stories.
However, many thanks for the hint and the feedback!

**Comment by saunders-d** [comment]
Awesome thank you! Didn't see it at first!
