### ISSUE TITLE
post.getPicture() return null

### ISSUE THREAD

**Issue by waelantar** [restfb/restfb#1388]
Hello everyone,

I've been using RestFB version 2024.2.0 for the past two weeks. I'm attempting to display pictures of the posts I've shared using my page, but I keep encountering a NullPointerException. I consulted the documentation and found that the type is a string. I attempted to print it in the console, but to no avail. Then, I tried using Thymeleaf, but encountered the same issue. Despite this, I was successful in displaying pictures using the Spring Social library.
**Java code:**
 ```
 FacebookClient facebookClient = new DefaultFacebookClient(MY_ACCESS_TOKEN, Version.VERSION_9_0);

        Connection<Post> myfeed = facebookClient.fetchConnection("me/feed", Post.class);

        List<Post> posts = new ArrayList<>();

        for (List<Post> myFeedPage : myfeed) {

            for (Post post : myFeedPage) {

                if (post.getMessage() != null) {

                    posts.add(post);

                    System.out.println(post.getPicture());
                }
            }
```
**Thymeleaf code:**
```
<body>
<h1>My Facebook Feed</h1>
<div th:each="post : ${posts}" class="post">
    <!-- Display post picture if available -->
    <img  th:src="${post.fullPicture}" alt="Post Image"/>
    <img  th:src="${post.picture}" alt="Post Image"/>
    <img  th:src="${post.icon}" alt="Post Image"/>
```

**Comment by nbartels** [comment]
please try:
```
Connection<Post> myfeed = 
     facebookClient.fetchConnection("me/feed", Post.class, Parameter.withFields("picture"));
```

And add additional fields, if you need more.

**Comment by waelantar** [comment]
Thank you very much I tried it and it works just fine
