### ISSUE TITLE
Persistent Data Inaccessibility in FacebookPage, Insights, Posts, and Comments.

### ISSUE THREAD

**Issue by waelantar** [restfb/restfb#1393]
I am trying to create a Facebook management tool for my Facebook page using RestFB, but when I use 

```java
Page page = facebookClient25.fetchObject("page-name", Page.class);
````
despite using all possible permission I only get the page name and its ID, no more info like this:
````about=null                   accessToken=null                   adminNotes=[]                   affiliation=null 
appId=null                   artistsWeLike=null                 assetScore=null                 attire=null 
awards=null                  bandInterests=null                 bandMembers=null                bestPage=null 
bio=null                     birthday=null                      bookingAgent=null               built=null 
business=null                canCheckin=null                    canPost=null                    category=null 
categoryList=[]              checkins=null                      companyOverview=null            connectedInstagramAccount=null 
contactAddress=null          countryPageLikes=null              cover=null                      culinaryTeam=null 
currentLocation=null         description=null                   descriptionHtml=null            directedBy=null 
displaySubtext=null         displayedMessageResponseTime=null  emails=[]                       engagement=null 
fanCount=null                featuredVideo=null                 features=null                   followersCount=null 
foodStyles=[]                founded=null                       generalInfo=null                generalManager=null 
genre=null                   globalBrandPageName=null           globalBrandParentPage=null      globalBrandRootId=null 
groups=null                  hasAddedApp=null                   hasTransitionedToNewPageExperience=null   hasWhatsappBusinessNumber=null 
hasWhatsappNumber=null       hometown=null                      hours=null                     id=*********** 
impressum=null               influences=null                    insights=null                  instagramAccounts=[] 
instagramBusinessAccount=null instantArticlesReviewStatus=null   isAlwaysOpen=null              isChain=null 
isCommunityPage=null         isEligibleForBrandedContent=null  isMessengerBotGetStartedEnabled=null  isMessengerPlatformBot=null 
isOwned=null                isPermanentlyClosed=null           isPublished=null               isUnclaimed=null 
isWebhooksSubscribed=null   labels=[]                          lastUsedTime=null             leadgenTosAcceptanceTime=null 
leadgenTosAccepted=null     leadgenTosAcceptingUser=null       likes=null                    likesCount=null 
link=null                    location=null                      members=null                  merchantId=null 
merchantReviewStatus=null   messengerAdsDefaultIcebreakers=[]  metadata=null                 mission=null 
mpg=null                    name=xxxx                     nameWithLocationDescriptor=null  network=null 
newLikeCount=null           offerEligible=null                 overallStarRating=null        ownerBusiness=null 
pageToken=null              parentPage=null                    parking=null                   paymentOptions=null 
personalInfo=null           personalInterests=null             pharmaSafetyInfo=null         phone=null 
picture=null                placeType=null                     plotOutline=null              pressContact=null 
priceRange=null             privacyInfoUrl=null                producedBy=null                products=null 
promotionEligible=null     promotionIneligibleReason=null     publicTransit=null             ratingCount=null 
recipient=null              recordLabel=null                   releaseDate=null               restaurantServices=null 
restaurantSpecialties=null  schedule=null                      screenNames=[]                screenplayBy=null 
season=null                 singleLineAddress=null             starring=null                  startInfo=null 
storeCode=null              storeLocationDescriptor=null      storeNumber=null               studio=null 
talkingAboutCount=null      temporaryStatus=null               type=null                      unreadMessageCount=null 
unreadNotifCount=null       unseenMessageCount=null            userAccessExpireTime=null     username=null 
verificationStatus=null    voipInfo=null                      website=null                   wereHereCount=null 
whatsappNumber=null         writtenBy=null

````
I'm presently attempting to execute the RestFB examples from the repository you shared. I'm hoping for assistance with this endeavor. Additionally, I've successfully verified my Facebook app, but there's one remaining step, which involves utilizing RestFB to access the advanced APIs
![Capture](https://github.com/restfb/restfb/assets/70063334/45692410-16e5-4b9f-8f79-a1a10af8ed25)
I've been stuck in this situation for months now, unable to access complete information, including insights, posts, and comments data. I'm feeling quite stuck. If anyone has a solution to this problem, I would greatly appreciate any help.

**Comment by nbartels** [comment]
You have to add the fields you like to fetch to you request: 

```
Page page = facebookClient25.fetchObject("page-name", Page.class, Parameter.withFields("cover,fan_count,picture,website"));
```

Facebook changed this in Graph API 2.4 and you can find the information in our docs, too.
https://restfb.com/documentation/#fetching

**Comment by waelantar** [comment]
I sincerely appreciate your prompt response and assistance; it has resolved my issue effectively. I apologize for any inconvenience caused by not thoroughly reviewing the documentation beforehand. If you don't mind, I have a couple of additional inquiries:

Have you had the opportunity to verify your account, as depicted in the image provided?
Is it possible to increase the number of allowable requests per hour?
Additionally, I would like to inquire about obtaining the names and profiles of individuals who have commented on my posts and replied to comments. Currently, I'm unable to retrieve this information even through the API directly. I understand if this is a sensitive matter, and I apologize for any inconvenience my inquiries may cause, particularly in the issues section. However, these questions are crucial for my requirements.

Thank you for your understanding.

**Comment by nbartels** [comment]
Okay, it seems that you would like to have your application reviewed. In general it is hard to provide support from RestFB side. You need to implement a fairly working application and then let Facebook review it. The best way is for Facebook to access the web application and try the features themselves. A screencast is the harder way. I have had a few applications reviewed this way, but it was no fun.

Regarding the profiles of people who have commented on your posts. Maybe you can show me your requests, then it is much easier to help.

**Comment by waelantar** [comment]
```
      Post post = facebookClient.fetchObject("136720779840416_502997274971059", Post.class);
        out.println(post.getComments());//136720779840416_502997274971059
      Connection<Comment> allComments = facebookClient.fetchConnection("136720779840416_502997274971059"+"/comments", Comment.class);
      for(List<Comment> postcomments : allComments){
          for (Comment comment : postcomments){
              out.println(comment.getMessage());
              out.println(comment.getFrom().getName());
          }
       }
```
I want to get a name like this but it only give me the name if it was commented by a page or my own account or my own page
also when I use getId i only get a scopedId i can't use to get the page url or an id to send messages

**Comment by nbartels** [comment]
Then you should add the `Parameter.withFields("from")` in your fetchConnection call as you did with the Page.

**Comment by nbartels** [comment]
That's because your app is not reviewed.

**Comment by waelantar** [comment]
Okay I understand thanks a lot for the help
