### ISSUE TITLE
How do i publish a video to a facebook page's story

### ISSUE THREAD

**Issue by vincitegx** [restfb/restfb#1411]
I try to publish a video to a facebook page's story, but i get the error "There is a problem uploading your video, Please try again with another file".
Please review code
```java
public void postVideo(String contentUrl) throws MalformedURLException, FileNotFoundException, FacebookOAuthException {
        Users loggedInUser = userService.getCurrentUser();
        Socials social = socialsService.getSocialByPlatform(SocialPlatform.FACEBOOK);
        UserSocials userSocial= userSocialsService.findUserSocial(loggedInUser, social).orElseThrow(()-> new UserException("User social not found"));
        FacebookClient defaultFacebookClient = new DefaultFacebookClient(userSocial.getAccessToken(), Version.LATEST);
        File videoFile = new File("uploads/" + contentUrl);
        if (!videoFile.exists()) {
            throw new FileNotFoundException("Video file not found at specified path.");
        }
        FileInputStream fileInputStream = new FileInputStream(videoFile);
        FBVideoStoryStartResponse fbVideoStoryStartResponse1 = defaultFacebookClient.publish(userSocial.getSocialUserId() + "/video_stories", FBVideoStoryStartResponse.class,
                Parameter.with("upload_phase", "start"));
        String videoUploadID = fbVideoStoryStartResponse1.getVideoId();
        System.out.println(videoUploadID);
        GraphResponse graphResponse = defaultFacebookClient.publish(videoUploadID, GraphResponse.class, BinaryAttachment.with(videoFile.getName(), fileInputStream));
        GraphResponse graphResponse1 = defaultFacebookClient.publish(userSocial.getSocialUserId() + "/video_stories", GraphResponse.class,
                Parameter.with("video_id", videoUploadID),
                Parameter.with("upload_phase", "finish"),
                Parameter.with("video_state", "PUBLISHED"),
                Parameter.with("description", "A short description text"),
                Parameter.with("message", "Your message here"),
                Parameter.with("title", "Title of testing video"),
                Parameter.with("description", "Description of testing video"));
            try {
                fileInputStream.close();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
    }
```

**Comment by nbartels** [comment]
First, you have to many parameters in your `video_stories` publish call. Only `video_id` and upload_phase is used here according to the Facebook reference. So remove the other stuff. BTW the "description" parameter is a duplicate anyway. 
then you should check which of these 3 calls is not working. I think the first one should wor, because it simply create a container and returns the video id, but the second or the 3rd can lead to a problem. With this code structure you cannot determine it. 

Additionally you should try different video files and maybe check the possibility to give Facebook the video url instead of uploading the binary data. 

And you can check the `ResumableUploadStartResponse` class instead of your custom `FBVideoStoryStartResponse`. If you don't have some custom fields in there, it should be the same.

**Comment by vincitegx** [comment]
Hi @nbartels thanks for the response, after much trial and error, i was able to implement this code below and it showed it was successful, only that i could not see the feed or story on my page, tried with so many videos, and all returned 200 OK but didnt see any story nor reel, i followed the example in the documentation. here is the code: 
public void postVideo(String contentUrl) throws MalformedURLException, FileNotFoundException, FacebookOAuthException {
        Users loggedInUser = userService.getCurrentUser();
        Socials social = socialsService.getSocialByPlatform(SocialPlatform.FACEBOOK);
        UserSocials userSocial= userSocialsService.findUserSocial(loggedInUser, social).orElseThrow(()-> new UserException("User social not found"));
        try (FileInputStream fileInputStream = new FileInputStream("uploads/" + contentUrl)) {
            FacebookClient defaultFacebookClient = new DefaultFacebookClient(userSocial.getAccessToken(), Version.LATEST);
            File videoFile = new File("uploads/" + contentUrl);
            if (!videoFile.exists()) {
                throw new FileNotFoundException("Video file not found at specified path.");
            }
            ReelsUploadStartResponse startResponse = defaultFacebookClient.publish(userSocial.getSocialUserId() + "/video_reels",
                    ReelsUploadStartResponse.class,
                    Parameter.with("upload_phase", "start"));
            String videoUploadID = startResponse.getVideoId();
            byte[] videoBytes = Files.readAllBytes(videoFile.toPath());
            FacebookReelAttachment reelAttachment = FacebookReelAttachment.withByteContent(videoBytes);
            GraphResponse response = defaultFacebookClient.publish(videoUploadID, GraphResponse.class, reelAttachment);
            GraphResponse publishResponse = defaultFacebookClient.publish(userSocial.getSocialUserId() + "/video_stories", GraphResponse.class,
                    Parameter.with("video_id", videoUploadID),
                    Parameter.with("upload_phase", "finish"),
                    Parameter.with("video_state", "PUBLISHED"),
                    Parameter.with("description", "A short description text"));
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

**Comment by nbartels** [comment]
Okay, so here is an example code that publishes a Story to a Facebook Page:

```java
byte[] videoAsBytes = fetchBytesOfVideoYouLikeToPublish();
String pageAccessToken = "<some page access token>";
String pageId = "<the page id>";

// define client
FacebookClient fbClient = new DefaultFacebookClient(pageAccessToken, Version.LATEST);

// create video upload container and save the video id
ResumableUploadStartResponse videoResponse = fbClient.publish(pageId + "/video_stories",
      ResumableUploadStartResponse.class, Parameter.with("upload_phase", "start"));
String videoId = videoResponse.getVideoId();

// upload the video to the container. you need the Reel Attachment, because of the special upload mechanism
GraphResponse uploadResponse =
        fbClient.publish(videoId, GraphResponse.class, FacebookReelAttachment.withByteContent(videoAsBytes));

// close the container and publish the video as story
GraphResponse publishResponse = fbClient.publish(getTestSettings().getPageId() + "/video_stories",
      GraphResponse.class, Parameter.with("video_id", videoId), Parameter.with("upload_phase", "finish"));

System.out.println("Post ID: " + publishResponse.getPostId());
```

**Comment by vincitegx** [comment]
@nbartels thanks for the response, but i still cant understand why i dont see the reel or story on my page, it actually shows me the video upload id and the post id, even with this code : 
`
public void postVideo(String contentUrl) throws MalformedURLException, FileNotFoundException, FacebookOAuthException {
        Users loggedInUser = userService.getCurrentUser();
        Socials social = socialsService.getSocialByPlatform(SocialPlatform.FACEBOOK);
        UserSocials userSocial = userSocialsService.findUserSocial(loggedInUser, social).orElseThrow(() -> new UserException("User social not found"));
        try (FileInputStream fileInputStream = new FileInputStream("uploads/" + contentUrl)) {
            FacebookClient defaultFacebookClient = new DefaultFacebookClient(userSocial.getAccessToken(), Version.LATEST);
            File videoFile = new File("uploads/" + contentUrl);
            if (!videoFile.exists()) {
                throw new FileNotFoundException("Video file not found at specified path.");
            }
            ResumableUploadStartResponse startResponse = defaultFacebookClient.publish(userSocial.getSocialUserId() + "/video_reels",
                    ResumableUploadStartResponse.class, Parameter.with("upload_phase", "start"));
            if (startResponse != null) {
                System.out.println("success1");
                String videoUploadID = startResponse.getVideoId();
                System.out.println("video id: " + videoUploadID);
                byte[] videoBytes = Files.readAllBytes(videoFile.toPath());
                FacebookReelAttachment reelAttachment = FacebookReelAttachment.withByteContent(videoBytes);
                GraphResponse response = defaultFacebookClient.publish(videoUploadID, GraphResponse.class, reelAttachment);
                if (response.isSuccess()) {
                    System.out.println("success2");
                    GraphResponse publishResponse = defaultFacebookClient.publish(userSocial.getSocialUserId() + "/video_reels", GraphResponse.class,
                            Parameter.with("video_id", videoUploadID),
                            Parameter.with("upload_phase", "finish"));
                    if (publishResponse != null) {
                        System.out.println("success3");
                        System.out.println(publishResponse.getPostId());
                    }
                }
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
`
I have also looked into my settings to see if there's anything blocking it but none

**Comment by nbartels** [comment]
Please check the `userSocial.getSocialUsedId()` and `userSocial.getAccessToken()`. These should be page id and page access token. Everything else looks great to me.

**Comment by nbartels** [comment]
Additionally, you can check the permissions of the page access token with the access token debugger, maybe something is missing there?

**Comment by vincitegx** [comment]
Thanks for the response @nbartels, so i tried calling the APIs directly, and i noticed after creating and uploading the reel, when i try to get the upload session status, i am flagged for copyright, i dont see any sense in it, i just did a quick video on my device and uploaded it, why should it have an issue with copyright, this is the response from calling the api: {
    "status": {
        "video_status": "upload_complete",
        "uploading_phase": {
            "status": "complete",
            "bytes_transferred": 2823663
        },
        "processing_phase": {
            "status": "not_started"
        },
        "publishing_phase": {
            "status": "not_started"
        },
        "copyright_check_status": {
            "status": "error"
        }
    },
    "id": "414900168065199"
}
I have tried this with many videos but still the same, maybe thats why i was unable to see it displayed using restfb, any ideas or suggestions
