### ISSUE TITLE
Documentation Error in MessengerPlatform: Incorrect Method for Adding Bubbles in Generic Template

### ISSUE THREAD

**Issue by waelantar** [restfb/restfb#1416]
I've identified an error in the documentation under the section "MessengerPlatform/use the generic template." The current code snippet shows:

```java
payload.add(firstBubble);
payload.add(secondBubble);
```

However, it should be:

```java
payload.addBubble(firstBubble);
```

**Comment by nbartels** [comment]
thanks @waelantar, I fixed this in the docs.
