### ISSUE TITLE
Duplicate Key Created When WebhookObject with MessagingAttachment is converted to json using DefaultJsonMapper().

### ISSUE THREAD

**Issue by parth0201-in** [restfb/restfb#1485]
This is a Json of Facebook Chat Message -- 
`{
  "object": "page",
  "entry": [
    {
      "id": "1093809957474043",
      "time": 1556666374239,
      "messaging": [
        {
          "sender": {
            "id": "2224767397618937"
          },
          "recipient": {
            "id": "1093809957474043"
          },
          "timestamp": 1556666373817,
          "message": {
            "mid": "baotbDNz04ehTODkTaN4IfMmr-D8cRLTER2ucXRc1ZZ0pga7Plfb3DOEG7TW1iojnd1E6nUAVuhpDDjrCL44LA",
            "seq": 41,
            "attachments": [
              {
                "type": "image",
                "payload": {
                  "url": "https://scontent.xx.fbcdn.net/v/t1.15752-9/59022753_360942548099158_2867301913198592000_n.jpg?_nc_cat=111&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&oh=52c2a8c5f3db3f59eccf0936c4f14acd&oe=5D2D69EA"
                }
              }
            ]
          }
        }
      ]
    }
  ]
}`
When Converting this to a WebhookObject using DefaultJsonMapper(),

`JsonMapper mapper = new DefaultJsonMapper();
WebhookObject webhookObject = mapper.toJavaObject(payload, WebhookObject.class);`

I get a WebhookObject in Which MessagingAttachment has 2 properties -- String fallbackPayload and MessagingPayload payload.
Both Are annotated with @Facebook Annotation.

When Converting to a JsonString using DefaultJSonMapper() --
`mapper.toJson(webhookObject, true)` 

It creates properties annotated with @Facebook to a JSONObject. There MessagingAttachment's instances fallbackPayload and payload are also added to the JSONObject, but the fieldName/Key assigned to both is "payload". So when JsonString is converted to a JSONObject, it throws a DuplicateKeyException.
This is What the WebhookObject converted to jsonString using DefaultJsonMapper look like -- 
`{"object":"page","entry":[{"id":"1093809957474043","time":1556666374239,"messaging":[{"sender":{"id":"2224767397618937"},"recipient":{"id":"1093809957474043"},"timestamp":1556666373817,"message":{"mid":"baotbDNz04ehTODkTaN4IfMmr-D8cRLTER2ucXRc1ZZ0pga7Plfb3DOEG7TW1iojnd1E6nUAVuhpDDjrCL44LA","is_echo":false,"attachments":[{"type":"image","
payload
":"{\"url\":\"https://scontent.xx.fbcdn.net/v/t1.15752-9/59022753_360942548099158_2867301913198592000_n.jpg?_nc_cat=111&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&oh=52c2a8c5f3db3f59eccf0936c4f14acd&oe=5D2D69EA\"}","
payload
":{"url":"https://scontent.xx.fbcdn.net/v/t1.15752-9/59022753_360942548099158_2867301913198592000_n.jpg?_nc_cat=111&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&oh=52c2a8c5f3db3f59eccf0936c4f14acd&oe=5D2D69EA"}}]}}]}]}`

It has 2 payload Keys for both fallbackPayload and payload.
Some SS Taken from Debugging Why this was happening -- 
![image](https://github.com/user-attachments/assets/aa8797fc-511a-48bd-a5d1-218d8acfc30c)
![image](https://github.com/user-attachments/assets/dea9e3e9-8ced-488e-a8bb-38a0954813c1)

**Comment by nbartels** [comment]
It's an interesting use case for the WebhookObject and the JsonMapper, but you're right. It should build a valid object. I'll try to find a solution in one of the next releases ...
