### ISSUE TITLE
Graph API 2.2: Follow "max. 50 ids per request" rule for requests utilising the "?ids=" syntax

### ISSUE THREAD

**Issue by jahudi** [restfb/restfb#157]
If using the "?ids=" syntax you are now limited to only use 50 ids per request as described here: https://developers.facebook.com/docs/apps/upgrading#v21tov22

**Comment by nbartels** [comment]
After reading this issue again, I think it's not part of restfb, because we expect the developer to know what she's doing. The comment's attachment field (for example) is only filled if correctly requested. And I think Facebook throws a useful exception in the too-many-ids-case.
