### ISSUE TITLE
Page Rating story has a different comment/likes summary

### ISSUE THREAD

**Issue by ronaldheft** [restfb/restfb#186]
Page Rating's with the field open_graph_story appear to not use the standard summary format for comments and likes. Instead of using `total_count` or the `summary` object, the JSON returned from the graph API (2.2) is as follows:

```
{
      "created_time": "", 
      "has_rating": true, 
      "has_review": true, 
      "rating": 5, 
      "review_text": "", 
      "reviewer": {
        "id": "", 
        "name": ""
      }, 
      "open_graph_story": {
        "id": "", 
        "from": {
          "id": "", 
          "name": ""
        }, 
        "start_time": "", 
        "publish_time": "", 
        "application": {
          "name": "Places", 
          "namespace": "app_places", 
          "id": "302324425790"
        }, 
        "data": {
          "rating": {
            "value": 5, 
            "scale": 5
          }, 
          "review_text": "", 
          "generic_place": {
            "id": "", 
            "url": "", 
            "type": "place", 
            "title": ""
          }
        }, 
        "type": "places.rates", 
        "likes": {
          "count": 2, 
          "can_like": true, 
          "user_likes": true
        }, 
        "comments": {
          "count": 2, 
          "can_comment": true, 
          "comment_order": "chronological"
        }
      }
    }
```

Notice the straight `count` field along with additional fields like `can_like` and `can_comment`. I'm thinking a third count type needs to be supported on the comments and likes objects.

**Comment by nbartels** [comment]
the `open_graph_story` is a special kind of field and we should provide a generic base class for open graph stories and a special class for this `places.rates` type. So we should be able to access the likes and comments information as requested.

**Comment by nbartels** [comment]
Between the graph api version 1.0 and 2.0, they did a major change on the page rating objects. So we have to fix this and add the mentioned fields, too.
