### ISSUE TITLE
Create collections with needed size

### ISSUE THREAD

**Issue by profes** [restfb/restfb#189]
Since response sizes from Facebook might vary, it's quite important to create collections with initial size that big enough to avoid collection resize. It might improve performance.

**Comment by slumx** [comment]
I think there are many other places to look before turning towards ArrayList inial size for performance gain :-) We are talking nano seconds saved. See 
http://codinginthetrenches.com/2014/09/10/java-arraylist-resize-costs/

**Comment by profes** [comment]
True, but on the project I'm working on small things matter.
The blog post you mentioned did not use proper (micro) benchmarking tools like JMH, so I'd rather avoid making any decisions based on it.

**Comment by slumx** [comment]
Fair enough, an acurate benchmark would still be interesting though

**Comment by nbartels** [comment]
To improve restfb, we are planning to create an benchmark repository. So we don't disturb and pollute the main repository. This is part of some code re-organisation and I think everyone will benefit from that.

**Comment by nbartels** [comment]
The benchmark repository is available and a first benchmark (regarding the ```SimpleDateFormatter```) can be found there. @profes you may fork the dev branch and add your benchmark. I think it will be very interesting to compare the time.

**Comment by profes** [comment]
@nbartels I added an initial benchmark https://github.com/restfb/restfb-benchmark/pull/1
Where do you want me to put results of benchmarks of 1.8.0 vs https://github.com/restfb/restfb/pull/190 and https://github.com/restfb/restfb/pull/188 ?

**Comment by nbartels** [comment]
just put it in here. I think here we discuss the change and so we need them as foundation for further actions. BTW restfb-benchmark has a *dev* branch :smile: I will merge your benchmark changes into the benchmark dev...

**Comment by nbartels** [comment]
@profes what about the benchmark? Do you have some values?

**Comment by profes** [comment]
Sorry for not getting back to you. I remember that the change had minor effect on performance. However it affected GC, since it was creating less objects. It is noticeable when you make hundred thousands of requests.

**Comment by nbartels** [comment]
I added some of the changes that should help. The unit test change is not necessary, because they are only run once; so I dropped that one. In my opinion it's okay to have these changes because they don't do anything bad. Even if the speed up is very small.
