### ISSUE TITLE
Add cursors support for the Connection class

### ISSUE THREAD

**Issue by oferfort** [restfb/restfb#191]
This is something that can be useful if you want to know what would would be your next page, once you've reached the last one.
I've extended Connection, but have to override also the client so it will return my class. Would be much easier if it was supported 

```java
...
private String before;
private String after;
...
if (jsonObject.has("paging") && jsonObject.getJsonObject("paging").has("cursors")) 
{
    	JsonObject jsonCursors = jsonObject.getJsonObject("paging").getJsonObject("cursors");
    	before = jsonCursors.has("before") ? jsonCursors.getString("before") : null;
    	after = jsonCursors.has("after") ? jsonCursors.getString("after") : null;
}
...
public String getBefore() {
	return before;
}
public String getAfter() {
	return after;
}
```

thanks!

**Comment by nbartels** [comment]
I don't really understand what's the benefit from this cursors. If I look at the paging documentation the cursors are already included in the ```previous``` and ```next``` URLs. (https://developers.facebook.com/docs/graph-api/using-graph-api/v2.2#paging)

**Comment by oferfort** [comment]
When you reach the last page, you don't have the next element, only
previous. If you want to make the next call, you use it with the after
element, and if there is new data, it will appear. This can be useful for
paging through comments

**Comment by nbartels** [comment]
ah, I see. Do you save the last ```after``` cursor value, or do you have some high traffic page that get's new comments while iterating? Just personal interest :smile:

**Comment by oferfort** [comment]
Useful for Hugh traffic posts. From the documentation, it's recommended not
to save them, as they might expire...
