### ISSUE TITLE
Facebook logout url

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [restfb/restfb#196]
Is there a restfb equivalent for facebook logout url?

Examples:
https://developers.facebook.com/docs/reference/javascript/FB.logout
https://developers.facebook.com/docs/unity/reference/current/FB.Logout
https://developers.facebook.com/docs/reference/php/facebook-getLogoutUrl

**Comment by nbartels** [comment]
thanx for the input!

**Comment by FagnerMartinsBrack** [comment]
O.O

That was fast man thanks! Any idea when this is going to be available on maven central?

**Comment by nbartels** [comment]
As soon as I solve issue #191. I think we release 1.9.0 at the end of march.
