### ISSUE TITLE
Send a private message from a user account to another user inbox with Rest FB

### ISSUE THREAD

**Issue by ilpintu** [restfb/restfb#199]
Is there anyway to send a private message from my account into another user inbox using Rest FB?

The thing is, at first, I'm receiving messages to my inbox from different users( not all are my friends), and I'm taking these messages & saving them into a database, along with every sender id.

Then, I want to send a specific link to each correspondent user in a private message.

Is it possible using Rest FB ?

**Comment by nbartels** [comment]
It depends. If you fetch the messages from the inbox you should have with the user id a thread id and I think you should be able to comment on these ids. (https://developers.facebook.com/docs/graph-api/reference/v2.2/thread)

If you only a the user id saved, you should have a look at the xmpp protocol. Perhaps this is a away to go, but xmpp is obviously not part of restfb. (https://developers.facebook.com/docs/chat)
