### ISSUE TITLE
Graph API 2.3

### ISSUE THREAD

**Issue by scraly** [restfb/restfb#200]
Hi Mark,

During the F8, Mark Zuckerberg announced a new version of the Graph API, version 2.3 and some new featurs about that :

https://developers.facebook.com/docs/apps/changelog#v2_3

Is it possible to improve restfb in order to take account theses changes plea?

I see severals changes, like this:

* Add new version in Version class:
  VERSION_2_3("v2.3");

* Add new field in Facebook Page class:

New Page Fields -GET|POST /v2.3/{page-id} now supports fetching and updating these fields: emails, food_styles, public_transit, general_manager, attire, culinary_team, restaurant_services, restaurant_specialties, and start_info.

* Add new fields in Facebook Page Settings class:

* New Page Settings - GET|POST /v2.3/{page-id}/settings now supports four new settings: REVIEW_POSTS_BY_OTHER, COUNTRY_RESTRICTIONS, AGE_RESTRICTIONS, and PROFANITY_FILTER.

Thanks!

**Comment by nbartels** [comment]
Thanks for the information. I add the Graph API 2.3 support as the first Issue for the next release. Perhaps we have to split the main issue.

**Comment by scraly** [comment]
Thx norbert,
yes I thinks it should be more relevant to split the enhancement in order to not forget something.

**Comment by nbartels** [comment]
okay, we have 13 new issues now, and I hope we have everything needed for 2.3.

**Comment by nbartels** [comment]
I close this now. A lot of issues exists and they should cover the changes ...
