### ISSUE TITLE
Graph API 2.3: read_friendlists permission is renamed to read_custom_friendlists

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#212]
> ```read_custom_friendlists``` - Is the new name for ```read_friendlists``` Login permission. This is to clarify that the permission grants access to a person's custom friendlists, not the full list of that person's friends.

**Comment by phpdeveloper1** [comment]
I need to upgrade my graph api version from 2.2 to 2.8 . Please tell me how to replace it and where? I really do not find any solution yet...

**Comment by nbartels** [comment]
You only need to change the provided version in your `DefaultFacebookClient` instance.  The changes between the versions can be found in the Facebook Changelog.
