### ISSUE TITLE
me/picture endpoint returns empty picture object

### ISSUE THREAD

**Issue by eyal1984r** [restfb/restfb#217]
When invoking the me/picture (endpoint to retrieve the profile picture of the current user) the resulted Picture object contains empty fields.
When using Graph API Explorer i get (with the same request) the URL of the picture.
When i debug the request sent by RestFB, i see that facebook does respond with the URL but it is not returned eventually.
Is that a bug? filtered out intentionally? Graph API Explorer supports it so i guess that this is a bug.

**Comment by nbartels** [comment]
The ```me/picture```endpoint returns an encapsulated ```Picture```. As you can see in the Graph API Explorer the real picture is wrapped in a data json. 

So you cannot transfer the ```me/picture``` data into an ```Picture```. While using the ```User```-type we added an workaround, but this is only usable if you fetch the picture like:

```
/me?fields=picture
```

You can try this, too. 

But I'll try to move the workaround to the Picture type.

**Comment by nbartels** [comment]
I had a short look at the Facebook API and obviously the user picture is an array of pictures (or it could be). So you can try the ```FacebookClient.fetchConnection``` method.

**Comment by nbartels** [comment]
Is this still a problem? Otherwise I close this soon.
