### ISSUE TITLE
Real Time Update subscription

### ISSUE THREAD

**Issue by FrancoisThareau** [restfb/restfb#220]
I want to use the Real Time Updates for an application, but i don't found the subscription process in RestFB ? 

http://stackoverflow.com/questions/21967946/facebook-real-time-update-in-java-example

(https://developers.facebook.com/docs/graph-api/reference/v2.2/app/subscriptions)

**Comment by nbartels** [comment]
It's not implemented (yet). But I think with the deprecation of fql we have to provide the realtime subscriptions.

**Comment by scraly** [comment]
Fql and rtu are not the same thing, but for sûre it should be good to
implement rtu :).
Le 10 avr. 2015 18:42, "Norbert Bartels" <notifications@github.com> a écrit
:

**Comment by nbartels** [comment]
Yes, your right. But for example if you need to get the newest comments this is not a trivial task. With graph api you need to fetch almost all posts and afterwards you have to fetch the comments and filter them.

With FQL you can fetch these information really easy and if you don't have FQL at hand you need the realtime updates.

So I think RTU is some kind of replacement for FQL - for some use cases.

**Comment by scraly** [comment]
With rtu we just have to subscribe to and then we receive a JSON from
facebook for each new comments, posts for exemple.
I use it in couple with graph API when i receive an update, i have some ids
and i call graph API in order to retrieve all comment information that i
want for example.
 Le 10 avr. 2015 20:29, "Norbert Bartels" <notifications@github.com> a
écrit :

**Comment by nbartels** [comment]
Can you please tell what exactly do you expect RestFB should support?

A new type to read the information from ```/{app-id}/subscriptions``` is no problem. Do you need some convenience methods for publishing and deleting subscriptions? Afaik should this be possible right now.

I think a documentation section should be added to the website to show, how this can be done.

**Comment by FrancoisThareau** [comment]
We use RestFb for subscriptions but i expect to find a class Restfb.Subscriptions to call the get/post/delete functions, and not maually call a makeRrequest

**Comment by nbartels** [comment]
Okay...

**Comment by FrancoisThareau** [comment]
We made the same makeRequest to subscribe_apps get/post/delete

a generic entrypoint can be a good idea for theses facebook specific action like this :
abstract {
abstract String  generateUrl();
post
get
delete
}

**Comment by nbartels** [comment]
I see, so a high level api is what you request :smile: 

Perhaps in that special case this make sense, but in general high level apis are to specific to maintain all the possibilities.
