### ISSUE TITLE
User.getPicture() always returns null?

### ISSUE THREAD

**Issue by munwaikong** [restfb/restfb#224]
Looking at User.java, line 246:

```java
@Facebook("picture")
private JsonObject rawPicture;

  /**
   * The user's picture, if provided
   * 
   * @return the user's picture as picture object
   * @since 1.6.16
   */
@Getter
@Setter
private Picture picture;
```

Would getPicture() in this case always return null?

**Comment by nbartels** [comment]
If you look at line 916 in the User.java, you find a "postprocessing" method. The ```rawPicture``` is analyzed there and a Picture object should be put into the ```picture``` field.

Perhaps you can provide me your json, so I can write a unit test and check where's the problem.

**Comment by nbartels** [comment]
I just checked this with the graph api explorer and I think I know the problem.

If I call ```/me``` there's no picture field in the returned JSON. I have to explicitly tell Facebook, to return this field. So I call ```/me?fields=picture``` and the returned JSON contains the picture field. And the structure is just the same as in our unit tests. :smile: 

Hope this helps ...

**Comment by munwaikong** [comment]
Perfect - that was the issue.

Perhaps adding in the comments of the fields to remind users that they'll need to request the field manually.

Thanks!
