### ISSUE TITLE
Unable to get facebook username from the user object

### ISSUE THREAD

**Issue by ashrithg** [restfb/restfb#230]
Hello team,

From the past one week, we are not able to get the facebook username from the user object. 

User user = facebookClient.fetchObject("me", User.class);

Please check this.

Regards
Ashrith G

**Comment by malulmj2** [comment]
See below from https://developers.facebook.com/docs/apps/changelog

Endpoints no longer available in v2.0

    /me/locations has been removed. Please use /me/tagged_places instead.
    /me/checkins has been removed, along with the user_checkins permission.
    /me/questions has been removed, along with the user_questions permission. This also includes /{page-id}/questions, /{group-id}/questions, /{question-id} and /{question-option-id}.
    /me/subscribers and /me/subscribedto have been removed.
    /me/username is no longer available.
    /me/notes is no longer available, along with the user_notes permission.
    /{page-id}/notes is no longer available.
    /{page-id}/questions is no longer available.
    Public Post search is no longer available. (/search?type=post&q=foobar)
    News Feed search is no longer available (/me/home?q=foobar)
    Start Now is no longer available in v2.0.

**Comment by nbartels** [comment]
thx for the information. I'll set this field to deprecated and check the others
https://developers.facebook.com/docs/graph-api/reference/v1.0/user

**Comment by ashrithg** [comment]
Thanks a lot for the quick reply.
It will be awesome if restfb can come up with api to fetch the profile
picture url.

Right now I am using FQL

FacebookClient facebookClient = new DefaultFacebookClient(accessToken);
User user = facebookClient.fetchObject("me", User.class,
Parameter.with("metadata", 1));
String query = "SELECT url FROM profile_pic WHERE id="+user.getId();
List<FqlURL> users = facebookClient.executeFqlQuery(query, FqlURL.class);
if(users != null)
{
    FqlURL fqlURL = users.get(0);
    return fqlURL .getUrl();
}

Regards
Ashrith G

**Comment by nbartels** [comment]
That's already possible. You have to request the user with the fields you need. the `picture` field is normally not filled, but facebook do this on request. For example:

```java
User user = facebookClient.fetchObject("me", User.class,
Parameter.with("fields", "picture,first_name,last_name,gender,name"));
```

Now, you can access the profile picture with simply calling:
```java
user.getPicture()
``` 

and the url is here:
```java
user.getPicture().getUrl()
```

**Comment by ashrithg** [comment]
Thanks a lot.

Regards
Ashrith G
