### ISSUE TITLE
Question: set accessToken in runtime

### ISSUE THREAD

**Issue by moleksyuk** [restfb/restfb#233]
Hi team,

I have web application with NodeJS (frond-end) and RESTful web services (back-end).
UI does login and then just sends userId and accessToken to server which gets user information from facebook to store it in DB.

In a rest service I want to inject `FacebookClient`:

```
private final FacebookClient facebookClient;

    @Autowired
    public UserRestService(Facebook facebookClient) {
        this.facebookClient = facebookClient;
    }
```

which is configured as:

```
@Bean
public FacebookClient getFacebookClient() {
        return new DefaultFacebookClient(null, APP_SECRET, Version.VERSION_2_3);
}
```

And in one of rest service use it with income access token:

```
@POST
@Path("create")
public User create(@JsonBodyParam("socialId") String socialId, @JsonBodyParam("accessToken") String accessToken) {
   // facebookClient.setAccessToken(accessToken);

   User user = facebookClient.fetchObject("me", User.class);
....
```

As I understand accessToken is unique per each user.
I can't create a `DefaultFacebookClient` inside a rest method because I won't be able to write a test for it:

```
@POST
@Path("create")
public User create(@JsonBodyParam("socialId") String socialId, @JsonBodyParam("accessToken") String accessToken) {

 FacebookClient facebookClient = new DefaultFacebookClient(accessToken, APP_SECRET, Version.VERSION_2_3);

   User user = facebookClient.fetchObject("me", User.class);
....
```

Should I create my custom implementation of FacebookClient or I miss something?

**Comment by nbartels** [comment]
No, you're right. Normally a `FacebookClient` is generated per user. Your use case is a bit different so you can simply write you custom `FacebookClient`. The `accessToken` field is protected so you can access it in your client.

**Comment by moleksyuk** [comment]
@nbartels Thanks for confirmation.

**Comment by slumx** [comment]
if your spring controller is a singleton (default) this will not work because multiple users will use the same FacebookClient and thereby potentially take over another users access token. 

maybe you can just write a FacebookClient factory and then inject that into the service. The factory method could then take the access token as a parameter and create a new instance of FacebookClient. For your test you can then just replace the factory with another implementation
