### ISSUE TITLE
Post.get<Type>Count() and Post.<Type>.getCount() returns 0

### ISSUE THREAD

**Issue by PsiLupan** [restfb/restfb#234]
Example code:
```
Connection<Post> feed = client.fetchConnection(pageId + "/feed", Post.class, Parameter.with("limit", 50));
for (Post p : feed.getData()) {
   p.getLikesCount();
}
```

I know the data is actually being returned, because I can use:
```
if(post.getLikes() != null){
   post.getLikes().getData().size();
}
```
and it will return the actual likes count.

**Comment by nbartels** [comment]
`getLikesCount()` and `getLikes().getData().size()` is not the same. Facebook returns only some (25 or 50?) likes and with `size()` you can only get that size. If you have less than that it is correct, but if you have - let's say - 1345 likes the `size()` method is wrong.

You need to fetch the feed with the `fields` parameter and add at least `likes.summary(true)`. If you are only interested in the count and not in the users itself try `likes.limit(0).summary(true)`.

**Comment by PsiLupan** [comment]
Ahh, I wasn't aware of that likes limit, thanks for the heads up.

I'm trying to get likes, shares, and comments count, in addition to the original post's message, so I was getting incredibly frustrated.
