### ISSUE TITLE
DebugTokenInfo should add a few more fields

### ISSUE THREAD

**Issue by fern** [restfb/restfb#235]
https://developers.facebook.com/docs/graph-api/reference/v2.3/debug_token

To be more useful: error, scopes, metadata

**Comment by nbartels** [comment]
`scopes`is already added to dev, I'll add error soon. Can you provide a example DebugTokenInfo with metadata?

**Comment by fern** [comment]
Nice! :)

To be honest, I haven't seen "metadata" in my app yet; but it was mentioned in the docs I linked above, so thought it might be of use for someone.  So I suppose you'll have to treat is as a Map<String,String>? Or a generic JsonObject?

http://stackoverflow.com/search?q=debug_token+metadata&s=48d481c8-b470-4f61-9dac-76a2074b142e

 "metadata": {
            "sso": "iphone-safari"
 }

**Comment by nbartels** [comment]
Okay, so I add a generic JsonObject for `metadata`. Everyone can access the field and the internal structure. In the Graph Api Reference some metadata are described, but not the object in complete. So this is the best way to make it accessible without knowing how it looks like :smile:
