### ISSUE TITLE
obtainUserAccessToken will not validate code in fb_signed_request because redirect_uri needs to be ""

### ISSUE THREAD

**Issue by frett** [restfb/restfb#236]
My application uses the Facebook JS SDK to authenticate the user's session, then passes the `fb_signed_request` to my backend code to validate the session and issue several additional API requests.

In order to validate the session I parse & validate the signed_request, and to prevent replay attacks I validate the `code`[1] found in the signed_request directly with facebook.

In order to validate this `code` the `redirect_uri` needs to be "" [2], but the current implementation of `obtainUserAccessToken()` throws the following exception:
```
java.lang.IllegalArgumentException: The 'redirectUri' parameter cannot be an empty string.
at com.restfb.BaseFacebookClient.verifyParameterPresence(BaseFacebookClient.java:342)
at com.restfb.DefaultFacebookClient.obtainUserAccessToken(DefaultFacebookClient.java:708)
```

[1] https://developers.facebook.com/docs/reference/login/signed-request
[2] https://github.com/UWFlow/rmc/blob/master/shared/facebook.py#L38

**Comment by nbartels** [comment]
To get this right. You can call `obtainUserAccessToken` without a `redirect_uri`, in that case the redirect uri needs to be an empty String. At least the PHP implementation works that way. 

So I should provide another method for convenience and remove the null/empty check.
