### ISSUE TITLE
Event field "place" Does Not Exist. Location and Venue Deprecated in Graph API v2.3.

### ISSUE THREAD

**Issue by Blarff** [restfb/restfb#237]
When getting the event using something like: 

specificEvent = facebookClient.fetchObject(963563046988382, Event.class);

has the fields of "Venue" and "Location" equal to NULL. This is because these two fields are deprecated in the Facebook Graph API v2.3. The replacement should be place. But there is not way to access place via Restfb. 

Maybe there is another way to get the event location via Restfb?

**Comment by nbartels** [comment]
The `place` is already present in the development branch, I'll add some comments to venue and location, so the user knows which field should be used.
