### ISSUE TITLE
suddenly I can‘t read birthday

### ISSUE THREAD

**Issue by luyangliu616** [restfb/restfb#241]
![image](https://cloud.githubusercontent.com/assets/8186724/7912969/7f9ab1e2-089e-11e5-8b11-6842a7b037ea.png)

![image](https://cloud.githubusercontent.com/assets/8186724/7912983/928cf846-089e-11e5-9690-7d3fa1e0f420.png)

I use "client.fetchObject("me", User.class,Parameter)"   and both have user_birthday scope

**Comment by nbartels** [comment]
Have you checked your access token's permission in the debugger?

**Comment by luyangliu616** [comment]
Thanks Why I use scope=email,user_birthday and get token but no 'user_birthday' permission

**Comment by nbartels** [comment]
Perhaps you should let facebook review your app. The user_birthday permission need to be approved.

https://developers.facebook.com/docs/facebook-login/review/faqs

**Comment by luyangliu616** [comment]
![image](https://cloud.githubusercontent.com/assets/8186724/7931576/4bbb4bba-0944-11e5-9480-d5daf40a5785.png)
I have it but token haven't.   it‘samazing .thanks

**Comment by luyangliu616** [comment]
![image](https://cloud.githubusercontent.com/assets/8186724/7951559/73a6d62a-09db-11e5-8e71-1c73fd93285c.png)

I find it

**Comment by nbartels** [comment]
okay great, so you "only" need the permission to be approved and eveything's fine :smile:

**Comment by luyangliu616** [comment]
yeah  to be approved again
