### ISSUE TITLE
Publishing video with text

### ISSUE THREAD

**Issue by stanislav80** [restfb/restfb#244]
I try to publish video with some text description to my facebook page, The video is published, but the text is not published at all. When I publish text only or image with text the text is published well.

I am using a valid page access token for publishing and I am publishing it by this command.
<addr>
fc.publish(pageId + "/videos", FacebookType.class,
                        BinaryAttachment.with(attachment.getId() + attachment.getName(), inputStream),
                        Parameter.with("message", message));
</addr>
Any ideas what's wrong?

**Comment by nbartels** [comment]
Can you please try to use `description` instead of `message`?

**Comment by stanislav80** [comment]
It worked. Thank you very much. 
But please update your guide.

**Comment by nbartels** [comment]
Yes, we have to update the documentation a lot ... :smile:
