### ISSUE TITLE
Inefficiency in DefaultFacebookClient

### ISSUE THREAD

**Issue by lawrence-dol** [restfb/restfb#247]
The method for posting a list of binary attachments is:

    public <T> T publish(String connection, Class<T> objectType, List<BinaryAttachment> binaryAttachments,
        Parameter... parameters) {
      verifyParameterPresence("connection", connection);
    
      List<BinaryAttachment> attachments = new ArrayList<BinaryAttachment>();
      if (binaryAttachments != null) {
        attachments = binaryAttachments;
      }

which creates a new list, only to immediately replace it in 99% of uses.

It should do:

      List<BinaryAttachment> attachments = binaryAttachments!=null ? binaryAttachments : new ArrayList<BinaryAttachment>();

**Comment by nbartels** [comment]
The `binaryAttachments` can simply be forwarded to the underlying `makeRequest`. The method accepts `null`, too. So the complete part can be removed. And I think thats a nicer solution :smile:
