### ISSUE TITLE
Post is_hidden property is in wrong place in hiearchy

### ISSUE THREAD

**Issue by 2bitoperations** [restfb/restfb#248]
Currently in 1.10.0, the is_hidden and is_published fields on Post are actually inside the Post.Properties static class. As far as I can tell from the payloads coming back from Facebook, this is incorrect - they should be member fields on Post.

Consider the output from https://developers.facebook.com/tools/explorer/145634995501895/?session_id=867560713316798

There is a properties array on the post, but none of the entires contain is_hidden - that's a top-level field on the post.

**Comment by nbartels** [comment]
merged your pull request and added a unit test, THX!
