### ISSUE TITLE
RestFB get events in Java

### ISSUE THREAD

**Issue by lukaszog** [restfb/restfb#251]
Using FQL, by means of which finds events that contain a given word. FQL works only in API version <2.1.   By which I use the Graph API Explorer to display events. Eg.

    search?q=york&type=event

Example of FQL

    SELECT Eid, name, location, start_time, description, pic_small, creator, event venue FROM WHERE start_time> "Sun Jun 21 0:00:35 GMT 2015" AND (CONTAINS ("york")

I would like to make a search events by using RestFB not using FQL, but do not know how. The documentation is scarce.

**Comment by nbartels** [comment]
Your special case is not in the documentation, but you can transfer the knowledge you find in the documentation and solve your problem: http://restfb.com/#searching

```java
Connection<Event> eventList =
  facebookClient.fetchConnection("search", Event.class,
    Parameter.with("q", "york"), Parameter.with("type", "event"));
```

Now, you can iterate over the `eventList`. 
Here you can find how this can be done: http://restfb.com/#fetching-connections

**Comment by nbartels** [comment]
Question can be found on stackoverflow, too:

http://stackoverflow.com/questions/30960417/restfb-get-events-in-java
