### ISSUE TITLE
Strange behaviour getting place field for Events

### ISSUE THREAD

**Issue by lostpebble** [restfb/restfb#252]
I'm trying to get the place field for events pulled using their IDs like so:

```
Event event = facebookClient.fetchObject(eventid, Event.class, Parameter.with("fields", "id,name,place,owner,description,timezone,ticket_uri,cover,start_time,end_time,updated_time,is_date_only"));
```

I've updated to the latest version and I see you've added support for Places now, but I'm getting some strange results. For most events I'm getting the Place object but for some of them, it comes back null.

This ID works: 1074127502604196
But this one does not: 300473363410132

When I use the Graph API Explorer (or a regular HTTP request in the browser using the same Access Token I'm using with RestFB) on the same events, including the same fields, the place object returns no problem.

I've also tried getting the Event with just the place field, but still no luck.

**Comment by nbartels** [comment]
I fetched the JSONs from the Graph API Explorer and write some unittests to check your problem. Perhaps this will show some insights. Otherwise I'll have to write integration tests, too :smile: 

At first glance the JSONs are almost the same, so I have no easy explanation why you get different results ...

**Comment by nbartels** [comment]
I wrote unit and integration tests, but cannot reproduce your issue. Do have some other ids, that are not working?

**Comment by lostpebble** [comment]
Thanks for taking the time to run some tests :)

I've found another that is not working (they are quite far and few between): 396536827213314

Again, using the place field in the graph API explorer works just fine but somehow for just these few it doesn't translate into the Java object in RestFB.

It's strange because as far as I can see the JSON returned is structured exactly the same in both.

**Comment by nbartels** [comment]
Okay, that's really strange. Because the JSON are the same and RestFB can map the JSON correctly. I Think there is some special problem. Perhaps you can give me some information about your setup. Do you use RestFB in a Multithreading environment?

**Comment by lostpebble** [comment]
So you were not able to produce the same issue using RestFB and the bad ids?

Hmm.. Yea then this might be something more obscure (yayyy). I'm using Google App Engine, but haven't made use of multi-threading as far as I know.

I see for Place you've used the Page object. Perhaps it's something to do with the page itself, privacy settings or something, though they look exactly the same and work fine in the API Explorer. Something to look out for though is sometimes the place is not a page, it's just a string in the name field representing an address.

**Comment by nbartels** [comment]
Okay Google App Engine. Perhaps I should build a app engine test environment :smile: 

I map the place to the page object because they are almost the same. If a field is not present, it will be empty in the generated object. That should not be a problem, because the important information are still there. Otherwise we have to implement a lot more types. Facebook returns on some special cases objects that are not completely filled with data. 

You did this right in requesting the event with the fields set correctly.

If the `place` may be a simple string, I can add a fallback, so you can work with that. But I got correct places with your ids. So it's a bit hard to test :smile:

**Comment by nbartels** [comment]
Can you activate the restfb logging and check the json returned. Perhaps it's a difference between what your app receives and what you get via the Graph API Explorer. Again, this is just an idea ...

**Comment by nbartels** [comment]
Do you have any new information? Or is the problem solved?

**Comment by lostpebble** [comment]
I activated logging for all levels on App Engine and looked at what was returned and I can confirm that the actual JSON being returned from RestFB is not including the `place` field at all. Whereas the Graph API Explorer returns it no problem. So we can rule out the type classes configuration.

This is the latest event I've found giving me that problem: ID: 865270563558881

I just copied the link from the log console into my browser and again, the JSON returns the same without the `place` field. But I replaced my app access token to the one generated by the Graph API Explorer and suddenly `place` returns no problem! So that seems to be the problem... No idea why my app access token works with just about all events except a select few though. It's just the regular default generated access token when you create a Facebook App.

I guess this means it's not an issue with RestFB at all, so I think this is resolved. Thanks. :)

**Comment by nbartels** [comment]
Okay, that explains why I cannot reproduce the issue. 

Please open a bug at Facebook. As you said, there is something wrong with the information they deliver. If you like, you can add the bug id as comment here, perhaps someone else will have the same problem.

**Comment by lostpebble** [comment]
Cool, bug opened at Facebook here, for any who might have the same problem: https://developers.facebook.com/bugs/1623129087934838/
