### ISSUE TITLE
Facebook moves to SHA-2

### ISSUE THREAD

**Issue by MayBogus** [restfb/restfb#254]
Hi Norbert,

Regarding recent Facebook announcement that they will stop support apps, which are not using SHA-2 certificates: 
https://developers.facebook.com/blog/post/2015/06/02/SHA-2-Updates-Needed/

There are several topic on SackOverflow, here is one of them:
http://stackoverflow.com/questions/30866583/facebook-how-to-test-sha-2-connections-to-facebook-before-sha-2-certificates-a

As far as I understand, all these “certificate stuff” should be processed somewhere at sun.security.ssl.Handshaker level or close.

Could you please confirm (or deny) that users who are utilizing RestFb Lib don’t have to update their code anyhow to comply with Facebook anouncement.

Thanks a lot

BTW, didn't catch how to mark this "new issue" as a "question". :(

**Comment by nbartels** [comment]
Java should handle the sha-2 stuff and because RestFB only uses pure Java (no libs) to connect to Facebook everything should work. But I agree, I should check this and give some explanation how to connect to a host using ssl with sha-2 (if there is something special).

**Comment by scraly** [comment]
Hi,

a SSL certificate is installed on a web server, in order to test is your
web serer have a sha-2 ssl certificate and not a sha-1, or if a part of
your ssl certificate is sha-1, you can test your certificate:
https://www.sslshopper.com/ssl-checker.html



2015-06-23 10:18 GMT+02:00 Norbert Bartels <notifications@github.com>:

> Java should handle the sha-2 stuff and because RestFB only uses pure Java
> (no libs) to connect to Facebook everything should work. But I agree, I
> should check this and give some explanation how to connect to a host using
> ssl with sha-2 (if there is something special).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restfb/restfb/issues/254#issuecomment-114402631>.
>



-- 
Aurélie
Twitter: http://twitter.com/#!/aurelievache
CV : http://www.scraly.com <http://scraly.free.fr/cv.php>
Scraly's Blog : http://scraly.blogspot.com/

**Comment by nbartels** [comment]
Here's a description how the certificate can be added to the java truststore, if not working out-of-the box:
http://stackoverflow.com/questions/21127896/suncertpathbuilderexception-with-sha-2-signed-certificate

But we should have another look at that and collect the information here.

**Comment by nbartels** [comment]
## Here some information regarding Java
Globalsign has a compatibility list and Java 1.4.2+ supports sha2
https://support.globalsign.com/customer/portal/articles/1499561-sha-256-compatibility

And here's the changelog of Java 1.4.2
https://web.archive.org/web/20111116061638/http://download.oracle.com/javase/1.4.2/docs/guide/security/index.html

**Comment by nbartels** [comment]
I think I can close this issue, because we passed October 1, 2015 and everything seems to be fine. At least the integration tests are still working and we didn't got any issues regarding the sha-2 topic.
