### ISSUE TITLE
Using FeedTargeting wrapper when posting

### ISSUE THREAD

**Issue by Karnifexx** [restfb/restfb#256]
We like to have very low level access to the facebook graph API and use RestFB as a great helper for all of the common tasks.

We currently post as follows:

```
Map<String, Parameter> postParams = new HashMap<>();
postParams.put("message", Parameter.with("message", "this is my message"));
Parameter[] paramArray = postParams.values().toArray(new Parameter[postParams.size()]);
Post newPost = facebookCon.publish("me/feed", Post.class, paramArray);
```

We would like to extend this to be able to also post **feed_targeting** and **targeting** parameters.

The *com.restfb.types.Post.FeedTargeting* class provides an excellent wrapper for storing and manipulating the necessary targeting params such as **age_min** and **age_max**. We would need to convert this to a *Parameter* in order to provide it during the publish step. Currently we are trying to perform this as follows:

```
FeedTargeting target = new FeedTargeting();
target.setAgeMax(20);
target.setAgeMin(18);
String targetStr = new DefaultJsonMapper().toJson(target);
```

which produces:

> {"fan_of":[],"age_min":18,"genders":[],"regions":[],"college_years":[],"countries":[],"college_majors":[],"college_networks":[],"age_max":20,"work_networks":[],"cities":[],"locales":[],"interested_in":[],"education_statuses":[],"relationship_statuses":[]}

using this as follows:

```
postParams.put("feed_targeting", Parameter.with("feed_targeting", targetStr));
```

results in the following API error:

> Received Facebook error response of type OAuthException: (#100) targeting must only contain one or more of relationship_statuses, interested_in, education_statuses, college_years, fan_of, relevant_until, interests, countries, regions, cities, locales, zipcodes, age_min, age_max, genders (code 100, subcode null)

which makes sense as the following *feed_targeting* string is what should be used:
> {"age_min":18,"age_max":20}

My question is how can we serialize the FeedTargeting instance to the desired value:
> {"age_min":18,"age_max":20}

As an alternative if there is a better (read more correct) way to use RestFB to achieve the same goal we would like to know more.

**Comment by nbartels** [comment]
Okay, thanks for your report. This is a bug. But it will be fixed in the next version. Obviously we need some more unittests :smile: 

In the meantime you can create a object like that:
```java
com.restfb.JsonObject sendFeedTargeting = new JsonObject();
sendFeedTargeting.put("age_min", 18);
sendFeedTargeting.put("age_max", 20);
```

and use it in that way:
```java 
Post newPost = facebookCon.publish("me/feed", Post.class, 
          Parameter.with("message", "this is my message", 
          Parameter.with("feed_targeting", sendFeedTargeting);
```

you can simply add several Parameter separated with a comma.
