### ISSUE TITLE
"full_picture" field in Post

### ISSUE THREAD

**Issue by CannyDuck** [restfb/restfb#263]
Please support the field "full_picture" in the Post class

**Comment by nbartels** [comment]
Is this a new field? I cannot find it in the Graph API Reference: https://developers.facebook.com/docs/graph-api/reference/v2.3/post

Perhaps you can provide a JSON?

**Comment by CannyDuck** [comment]
It is not part of the reference documentation, but it is implement in the API.

Example: me/home?fields?id,from,message,full_picture,link

**Comment by nbartels** [comment]
:disappointed: okay. I hope there are not too many "hidden fields"
