### ISSUE TITLE
fetchConnection should allow for adding fields

### ISSUE THREAD

**Issue by jarylchong** [restfb/restfb#269]
First off, thanks for adding support for full_picture.

When I try to fetchConnection(<page_id> + "/tagged", Post.class, Parameter.with("fields", "id, from, full_picture, ...")), I get a syntax error from Facebook that the "fields" parameter is specified more than once. My assumption from this is that RestFB already includes the fields parameter implicitly? It would be great to have a way to add the "full_picture" value to the fields parameter.

If this already exists, or if there is some way I can pull full_pictures from fetchConnection, do let me know.

**Comment by nbartels** [comment]
I just added a integration test and I cannot reproduce your issue. Perhaps you have to remove the spaces between the fields?

**Comment by jarylchong** [comment]
How embarassing. I took a second look at my error message and parameters, and realized I had included the "link" value twice. The error message I was getting back was that the "Field link specified more than once", which I incorrectly took to mean that the Field parameter was defined more than once. So sorry, this is a non-issue. Thanks for your time!
