### ISSUE TITLE
Facebook Ads API 2.4 not supported

### ISSUE THREAD

**Issue by skaluva** [restfb/restfb#272]
Hi,
I was using Facebook Ads/Marketing API version 2.2 till now. Today i received below error:

    Received Facebook error response of type OAuthException: (#2635) You are calling a deprecated  version of the Ads API. Please update to the latest version. (code 2635, subcode null)

I want to migrate to 2.4 version which is latest. In the latest restfb jar, supported version is 2.3. Can you please  support 2.4 version as well. It would be good if its a string instead of enum so that we can pass version whenever new versions got released if we feel its not going to affect our functionality.

**Comment by nbartels** [comment]
We are preparing the next release with Graph API 2.4.

How do you use the ads API. Do you have custom types?

**Comment by skaluva** [comment]
No, we don't have any custom type. I need to fix the production bug which is stopping to access APIs. May i know the timeline for the new version, 1.14.0, release.

**Comment by nbartels** [comment]
We release it this weekend. Just the video likes/comments count issue is open, but almost done.
