### ISSUE TITLE
Places should be CategorizedFacebookType

### ISSUE THREAD

**Issue by lehneres** [restfb/restfb#275]
I dont know who or when it changed, but recently I had difficulties to parse the categories from Places recieved with `facebookClient.fetchObject(/*someid*/, Place.class)` as not all categories remain in the `categories_list`. 
Inspecting the Graph API, it showed that my place has a field `category` which is not reflected in the `Place` Object. I think `Place` should extend CategorizedFacebookType in order to make this field available

**Comment by nbartels** [comment]
okay, no problem to change the parent class, but can you provide some place-ids?

I found only some Places that are Pages, if you look carefully. And btw, the graph api reference don't mention any category. Neither a single, nor a list :smile: 

I'll try to add some unittest later and commit the change, asap

**Comment by lehneres** [comment]
I filled in a bug report at Facebook first, see https://developers.facebook.com/bugs/855986937818811. 
The ID I tested with was 144200068927014. 

Ah, you mean I should rather parse to Pages than Places?

**Comment by nbartels** [comment]
Right, I just checked the id and if you look at the metadata (https://graph.facebook.com/v2.4/144200068927014?metadata=true) you see all the possible fields. In particular, the noteworthy field `is_verified` is present with this explanation:

```
...
{
    "name": "is_verified",
    "description": "Pages with a large number of followers can be manually verified by Facebook as [having an authentic identity](https://www.facebook.com/help/196050490547892). This field indicates whether the page is verified by this process",
    "type": "bool"
},
...
```

So I think the `Place` is `Page` :smile: 

Can you please try your request with a Page and give some feedback. ATM I'm not sure if the `category_list` change is really needed. FYI: The `Page` type is a `CategorizedFacebookType`.

**Comment by nbartels** [comment]
@lehneres what about the `Page` idea. Is it a solution? 

I'd like to close this issue, soon :smile:

**Comment by lehneres** [comment]
give a few more days to check in this.

**Comment by nbartels** [comment]
okay, that's fine with me.

**Comment by lehneres** [comment]
Well okay, its okay to use a Page for that example, but how can we be sure that every Place with categories is a Page?

**Comment by nbartels** [comment]
Hm, interesting question. The `place-tag` explicitly defines a place as page. And I checked the search with type `place` and it seems you get pages there, too.
```
search?q=coffee&type=place&center=37.76,-122.427&distance=1000
```
Do you have an example where a place is not a page? Important is the place id. 

Really interesting is the graph api reference for pages, if you look at the `location`-field there's the short note 'Applicable to all Places'. So it seems a place is a page :smile: 

BTW, you're right. This is more a Graph API problem, so I close the issue.
