### ISSUE TITLE
getLikesCount for post doesnt work

### ISSUE THREAD

**Issue by spunxz** [restfb/restfb#276]
Hi,

In the iteration I can't seem to get the likes per individual post.

        user = fbclient.fetchObject(pageID, User.class);
        page = fbclient.fetchObject(pageID, Page.class);

        Connection<Post> myFeed = fbclient.fetchConnection(pageID + "/feed", Post.class);

        for (List<Post> myFeedConnectionPage : myFeed) {
            for (Post post : myFeedConnectionPage) {

If I do something like I don't get the correct like values per post, no other issues apparent with this lib for me:
 
                    System.out.println("Likes count: " + post.getLikesCount());
                    System.out.println("Likes count: " + post.getLikes().getData().size());
                    System.out.println("Likes count (from Likes): " + post.getLikes().getTotalCount());

**Comment by nbartels** [comment]
Facebook do not provide the likes count on that simple call. You have to force the graph api to send you these information for example:

```java
Connection<Post> myFeed = 
   fbclient.fetchConnection(pageID + "/feed?fields=likes.limit(1).summary(true)", Post.class);
```

**Comment by spunxz** [comment]
Thanks very much!

I tried that, gives below. Also added it to the end of the token. That gives this one: Received Facebook error response of type OAuthException: Bad signature (code 1, subcode null). Next question will be how to add those parameters so it will work :100: %

com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: Syntax error "Expected end of string instead of "?"." at character 28: likes.limit(1).summary(true)?access_token=<token> (code 2500, subcode null)
   at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1238)
   at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1153)
   at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1086)
   at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:997)
   at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:959)
   at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:383)
Received Facebook error response of type OAuthException: Syntax error "Expected end of string instead of "?"." at character 28: likes.limit(1).summary(true)?access_token=<token> (code 2500, subcode null)

**Comment by spunxz** [comment]
Partly resolved it now by adding the parameters, however now lost many other items. Looking into that now.

Connection<Post> myFeed = fbclient.fetchConnection(pageID + "/feed", Post.class,Parameter.with("fields","likes.limit(1).summary(true)"));

**Comment by nbartels** [comment]
You have to add all `fields` you need. With version 2.4 it's the way Facebook works :smile: 

It's a comma-separated list (for example: `id,name,created_time,likes.limit(1).summary(true),message,from` )

**Comment by spunxz** [comment]
:+1: Thanks!

**Comment by saviocamacam** [comment]
I have da same problem with the access_signature:

My query:
Connection<JsonObject> currentPage = facebookClient.fetchConnection(post.getPage().getIdFacebook() + "_"
+ post.getIdFacebook() + "/?fields=reactions.type(" + reaction + ").limit(0).summary(1)&access_token="+"i5XUUvsezTyGcAJe3N6tzpYvfOQ",

Return:
[fb][storeReplies] Received Facebook error response of type OAuthException: Invalid OAuth access token signature. (code 190, subcode null)

**Comment by nbartels** [comment]
try:

```java
FacebookClient facebookClient = new DefaultFacebookClient("<access token>, Version.LATEST);
// building facebook ids in this way is imho a bad idea, however let's do it that way
String postId = post.getPage().getIdFacebook() + "_" + post.getIdFacebook();
String fields = "reactions.type(" + reaction + ").limit(0).summary(1)";
Post post = facebookClient.fetchObject(postId, Post.class, Parameter.with("fields", fields));
```

**Comment by valeripaw** [comment]
I have tha same problem with:

```
me/posts?fields=id,created_time,story,message,caption,from,description,link,name,parent_id,comments.limit(0).summary(true),likes.limit(0).summary(true)
```

I tried this request in Graph API Explorer and gave success result. But when I tried execute that with library I gave:

```
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: Syntax error "Expected "(" instead of "%"." at character 89: id,created_time,story,message,caption,from,description,link,name,parent_id,comments.limit%280%29.summary%28true%29,likes.limit%280%29.summary%28true%29 (code 2500, subcode null)
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerator.java:174) ~[restfb-2.5.0.jar:na]
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookExceptionGenerator.java:59) ~[restfb-2.5.0.jar:na]
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:917) ~[restfb-2.5.0.jar:na]
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:835) ~[restfb-2.5.0.jar:na]
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:797) ~[restfb-2.5.0.jar:na]
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:337) ~[restfb-2.5.0.jar:na]
```
	
My code:

```
private static final String FIELDS_POSTS = "id,created_time,story,message,caption,from,description,link,name," +
            "parent_id,comments.limit(0).summary(true),likes.limit(0).summary(true)";
            
public void findPosts(String token) {
        FacebookClient facebookClient = new DefaultFacebookClient(token, Version.LATEST);
        Parameter[] parameters = {Parameter.with("fields", FIELDS_POSTS)};
    
        Post post = facebookClient.fetchObject("me/posts", Post.class, parameters);
    
		/* another logic */    
}
```

**Comment by nbartels** [comment]
First of all you should open a new issue, because this is an old issue and your problem is different. 
Nevertheless I used your code and it is working.

But you don't need to create the parameters Array and you should use fetchConnection instead of fetchObject.
