### ISSUE TITLE
Improvise Version class to make it useful for runtime values

### ISSUE THREAD

**Issue by skaluva** [restfb/restfb#277]
Hi,
I'm using below code to open fb connection:
```
fbClient = new DefaultFacebookClient(accessToken,fbAppSecret,fbWebProxy,new DefaultJsonMapper(),Version.VERSION_2_4);
```

However, whenever new version gets released, we are getting forced to change the java file, build the jar and deploy changes. So thought of get this version from a properties file and use it here like `Version.valueOf(myVersion)`. But its giving exception as shown below due to the string having dots ie., v2.2, v2.3 etc.

`Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.restfb.Version.v2.4`

It seems java is not treating "v2.4" as single string. I tried escaping dots while passing to `valueOf` method but no luck. Its not working. So it would be good, if you can implement method something like this or use Map for better performance in Version class:

``` 
static Version getEnum(String value) {
        for (Version version : Version.values()) {
            if (version.value.equals(value)) {
                return version;
            }
        }
        return null;
    }
```

For now, i'm implementing this in my own class and using it to evaluate the respective Enum. Hope you understand.

**Comment by nbartels** [comment]
Perhaps you should set `myVersion` to something like "VERSION_2_2".

**Comment by skaluva** [comment]
Thanks for considering my request. I definitely use it :smiley: 
This is what i'm doing for now (a bit optimized code than earlier) in my class:
```
private static final Map<String, Version> VERSION_ENUM_MAP = new HashMap<>();

	static {
		logger.debug("loading version map...");
	    for (Version version : Version.values()) {
	        VERSION_ENUM_MAP.put(version.getUrlElement(), version);
	    }
	}
```
You can implement whatever is feasible for you.

**Comment by revetkn** [comment]
My two cents:

+1 for concept of a magic ```LATEST``` enum value
-1 for adding a map of version strings to enum values...unless I am missing something, @skaluva, this is specific to how you prefer to encode data in your configuration file (in other words, I am not sure this is an issue for others)

**Comment by skaluva** [comment]
Hi,
Ok. Let me explain my usecase. This is what i have in my application. FB Login is configured in js file where we need to specify version of fb api (for ex: v2.4) in FB.init() block of code and further API calls we redirect to controller and from there, we use restfb to make respective calls. Here, restfb also expects version as enum (Version_2_4 etc) while opening facebook client connection (as specified in my question). So now the problem is, whenever new version gets released, we need to make sure in both files use same version, so thought of reading this version from a property file (like FB_API_VERSION=v2.4) which i'm going to read in my java layer and the same i set in model object in my controller and then pass to javascript function while loading the page. So this way, it is enough to change version in one file if a new version gets released rather than finding and modify files everywhere. While doing this, i was facing some issue with enum constants (explained in my question). Hope this explains the need of my request. 

This definitely may not be the issue to others :yum:

**Comment by nbartels** [comment]
We don't need a map, because you can iterate over a enum with the `values()` method. And afterwards you can compare the urlElement with the given String. So we can find to the urlElement the corresponding enum. 

I add the `latest` enum value soon and show you what I mean, so @revetkn can review that change.

**Comment by nbartels** [comment]
And here's the "reverse lookup" idea, this static method would be added to the Version enum.

```java
public static Version lookup(String urlElement) {
      for (Version version: Version.values()) {
	    if (version.getUrlElement().equals(urlElement)) {
	      return version;
	    }
      }
      
      return Version.UNVERSIONED;
  }
```

The fallback can be discussed :smile: BTW if you lookup "v2.4" you should get VERSION_2_4 and not LATEST, if the javadoc is right.

**Comment by skaluva** [comment]
@nbartels No issues. I just need ENUM to be returned if i pass string version as your API expects ENUM. Thats it.  Your method gives Null Pointer Exception as UNVERSIONED ENUM has NULL value. Add null check to  version.getUrlElement() before equals.

But i believe, if we create multiple facebook clients for various reasons, everytime it iterates over the values, instead one time static final map gives better performance. So whenever i request, getEnum("v2.4") or lookup("v2.4"), you can simply return ENUM from the map. Just my suggestion, its upto you.  

This all can be eliminated, if you simply expect string to that API instead of ENUM. Just kidding.. :smile:

**Comment by nbartels** [comment]
Thanks for the review, I shouldn't post untested code at 1am :smile: 

What about this suggestion. Write your own FacebookClient. For example a PropertiesFacebbokClient which extends the DefaultFacebookClient and provides a constructor with your String. You can add your enum map id in that special FacebookClient and everything's fine.

**Comment by skaluva** [comment]
That anyway i can do. Ofcourse, i implemented in my own way for now as i said earlier. But if you provide api, it will be helpful for the people who are having need like me. :yum:

**Comment by nbartels** [comment]
Okay, so I close this issue and all users can use the new `LATEST` version. So, thanks for the input
