### ISSUE TITLE
Make it Osgi bundle

### ISSUE THREAD

**Issue by skaluva** [restfb/restfb#278]
Hi,
I'm with another requirement. Fortunate or unfortunate, my application is Osgi bundle war in which i'm unable to import this jar's packages as this jar is not Osgi compatible. After googling some time, i found some articles to make the jar as osgi bundle using maven bundlor plugin or karaf, but i'm getting lot of errors and so finally i'm unable to make it as Osgi compatible jar :disappointed: 

For now, i solved my problem by putting the jar inside war/WEB-INF/lib which i'm not supposed to do. But i don't have choice. So it would be really helpful if you can make it osgi compatible jar and upload to maven repository.

**Comment by nbartels** [comment]
You can use 3rd party libs like that:
http://stackoverflow.com/a/1342331/1379528

We need a vote option here in our issues, I think...

**Comment by skaluva** [comment]
Hi,
I tried the same link before posting here. But its expecting jar need to be inside my bundle i.e, war/WEB-INF/lib. Then only it is able to add to classpath. Ofcourse, if i put the jar inside my bundle, i don't need to specify all that. It works  as is .. :smile:  which i don't want to do. So it would be good if the jar is Osgi compatible.

**Comment by revetkn** [comment]
Documentation for supporting OSGI is difficult to google for (or maybe it is too complex for me to understand :smile:)

If it is just a matter of adding some metadata to the project, then it seems reasonable to look into it.

If it seems like more work or maintenance complexity or ..., perhaps we should hold off for now, especially if there are workarounds like storing in WEB-INF/lib.  The RestFB project has existed for over 5 and a half years and this is the first OSGI request I can remember!

**Comment by skaluva** [comment]
Ok no issues. I'm ok to make the changes to support the osgi compatibiliy. Can i send you pull request??

**Comment by revetkn** [comment]
If the changes are minimal, then please go ahead and send a pull request - thanks

**Comment by skaluva** [comment]
There will be changes in pom.xml (to build from source if required) and META-INF. As far as i know, there won't be any code changes :smile:

**Comment by revetkn** [comment]
OK, great - that is exactly what I was hoping.  Thanks in advance for the pull request!

**Comment by nbartels** [comment]
As soon as you send the pull request I'll add it to the next version.

**Comment by skaluva** [comment]
Hi,
I made respective changes and made it as osgi bundle. Currently, testing in my application and will raise pull request by EOD if everything is fine.

**Comment by nbartels** [comment]
Great. Looking forward to merge the PR.

BTW please base your pull request on `restfb` / `dev` not `master` :smile:

**Comment by nbartels** [comment]
hey @skaluva,

what about the OSGI bundle?

**Comment by skaluva** [comment]
hi @nbartels ,
I think i'm done with that. I even sent you merge request for that few weeks back.

**Comment by nbartels** [comment]
I squashed your commits into one, and added the issue number to the commit message. So the next version is a osgi bundle :smile: 

Thanks a lot
