### ISSUE TITLE
Friend Count Always Zero (0)

### ISSUE THREAD

**Issue by neutt22** [restfb/restfb#280]
Hi, I'm wondering what could be I'm missing with this code. It works fine if I fetch like name, etc:

    public Main(){
		   String accessToken = new FacebookToken().getAccessToken();
		   facebookClient = new DefaultFacebookClient(accessToken, Version.VERSION_2_4);
		   User user = facebookClient.fetchObject("me", User.class);
		   out.println("User name: " + user.getName());
	}

However, when I'm trying to fetch my total friend count:

    public Main(){
		String accessToken = new FacebookToken().getAccessToken();
		facebookClient = new DefaultFacebookClient(accessToken, Version.VERSION_2_4);
		Connection<User> myFriends = facebookClient.fetchConnection("me/friends", User.class);
		out.println("Count of my friends: " + myFriends.getData().size());
	}

Result: `Count of my friends: 0` but in the Graph API Explorer it's showing `3`

Note: I'm sure the the access token is fine and working because I can publish a feed on my wall.

It's been bugging me for hours.

Thanks guys,
Peace

**Comment by neutt22** [comment]
I've found out that I have no `user_friends` permission. And it's set to `publish_actions`. Is there any way I could put them all in an array of permissions?

**Comment by neutt22** [comment]
Got it `.scope("manage_pages,publish_actions,publish_pages")`

Thanks. Closed.

**Comment by nbartels** [comment]
You can use the `ScopeBuilder`, too. More code to write, but a bit more Java like :smile:
