### ISSUE TITLE
Multiple Photos

### ISSUE THREAD

**Issue by neutt22** [restfb/restfb#283]
Hi, just wanna know how do you guys upload more than one(1) photos per publish. I need it because I don't want my app to look spammy since it's main purpose is to publish photos on timeline.

Thanks!

**Comment by nbartels** [comment]
Hi,

the answer can be found in the Facebook API: https://developers.facebook.com/docs/graph-api/reference/user/photos/

> There is no way to publish more then one photo in the same graph API call.

**Comment by neutt22** [comment]
Thanks. I guess I just have to put all the details in one photo instead of multiple publish =)
