### ISSUE TITLE
the best way to follow a facebookok page

### ISSUE THREAD

**Issue by stanislav80** [restfb/restfb#284]
I am not sure if this is the correct section, but I do not know where to ask.

In my application I would like to follow a facebook page. This means that anytime a post (maybe even comment) is published, modified or deleted I will be notified. For example, when someone publishes a post (comment), it will downloaded, when the post is deleted I will get an id. And so on. I am not very good at facebook, so I do not know all features. Then I can create/delete that post in the database of my application.

The only solution that comes to my mind is to try download all posts from the page with parameter since (I think that unlike for comments for posts it should return only the new posts) every let's say 5 minutes. This should at least partially work and I will get at least new posts, but I would like to know if there some better way to do that by restFb.

**Comment by thiagogcm** [comment]
With this solution you might exceed the maximum API calls easily. 

For this matter read about this feature in the documentation.

https://developers.facebook.com/docs/graph-api/real-time-updates/v2.4

**Comment by nbartels** [comment]
@thiagogcm is right. Additionally you have a time problem, because it's possible that a run takes longer than 5 minutes. So You would have more than one fetch thread and this can cause trouble aggregating the posts and comments.

And if you wait for the last run until you start the new one, it's possible you get new post with a high latency...

BTW an interesting topic...

**Comment by stanislav80** [comment]
Thank you very much for your answer. 
I didn't know that the API has a limit for number of calls. Can you please let me know what the limit is?

@nbartels I know about time problem. We have the same problem with the comment. Facebook API does not support downloading only the new comments (at least I didn't find a way how to do that), so always have to download all comments. We solved this by extending the period how often we check the posts (number of likes, shares, comments) so that after some time without activity we check it only once a day.

I have one more question. I haven't tried the solution yet so I ask. I will create a subscription on a page and when someone creates a post there Facebook will send and HTTP post request that will contain the information that a post was created and maybe its id. I will process it, extract the id and download this post by restfb. Is this the way how it should work?

**Comment by nbartels** [comment]
@stanislav80 yes, you'll get some JSON posted by facebook. But the json is not very well documented. So it's trial and error until you get it working.

**Comment by nbartels** [comment]
Do you need further information or is this question answered. I'd like to close this issue :smile:

**Comment by stanislav80** [comment]
sorry for the late answer.
I did some research and it seams that the the tip you game me is useless for me. The problem is that the real time updates are usable only for cases when pages (I wan to follow) adds my application in to it. And that is completely unacceptable for me.

The reason for that is that I want to follow any page. For example BBC or president Obama's page and be notified about activity on it. I think you will agree that in general I cannot hope that they will accept my application.

So it seams that the only way for now is the way I supposed at start and to repeatably download new posts every hour or so.

But thank you very much for your advises.
