### ISSUE TITLE
BatchRequestBuilder doesn't exist.

### ISSUE THREAD

**Issue by tariqfcb** [restfb/restfb#285]
While trying to use the batch request example, I got the following error:
BatchRequestBuilder cannot be resolved to a type

I checked, the class doesn't exist in the library.

**Comment by nbartels** [comment]
The ```BatchRequestBuilder``` is a inner class of the ```BatchRequest```.
https://github.com/restfb/restfb/blob/master/source/library/com/restfb/batch/BatchRequest.java#L130
