### ISSUE TITLE
Error while trying to pull comment with fields

### ISSUE THREAD

**Issue by bogdanneacsa** [restfb/restfb#286]
Fields I'm pulling for comments: 

FacebookClient facebookClient = new DefaultFacebookClient(access_token, Version.VERSION_2_2);
					Comment comment = facebookClient.fetchObject(commentId, Comment.class, 
							   									 		 Parameter.with("fields", BaseDataProcessor.COMMENTS_FULL_FIELDS));

Here: 

COMMENTS_FULL_FIELDS = "attachment,can_comment,can_hide,can_like,can_remove,comment_count,created_time,from,id,is_hidden,is_private,like_count,message,message_tags,object,parent,user_likes,likes"

Getting error about JSON (even though it looks valid to me).

Reason is Unable to map JSON to Java. Offending JSON is '{"can_comment":false,"can_hide":false,"can_like":false,"can_remove":true,"comment_count":0,"created_time":"2015-09-01T00:17:03+0000","from":{"name":"Tester Page","category":"App Page","id":"474930769339741"},"id":"520586098107541_520590871440397","is_hidden":false,"is_private":false,"like_count":1,"message":"new comment","object":{"updated_time":"2015-08-31T23:57:59+0000","id":"520586098107541"},"user_likes":false,"likes":{"data":[{"id":"474930769339741","name":"Tester Page"}],"paging":{"cursors":{"before":"NDc0OTMwNzY5MzM5NzQx","after":"NDc0OTMwNzY5MzM5NzQx"}}}}

Is this a bug? If so, any quick ways we can deal with it?

Thanks,
Bogdan

**Comment by nbartels** [comment]
I'll write a unittest with your json, perhaps I get a better insight.

At first sight, the json look okay.

**Comment by nbartels** [comment]
@bogdanneacsa The problem is the likes field. Facebook used it earlier as likes count and defined the field as number, nowadays it's a jsonobject. So the fastest solution is to remove the likes field from the request and do another call to fetch the likes.

I will change the Comment class, so this cannot occur, but I cannot give you a release date for the 1.15.0.

Of course I try to release it soon ...

**Comment by bogdanneacsa** [comment]
Thanks for the quick update.

**Comment by nbartels** [comment]
The just released version 1.14.1 contains this fix.
