### ISSUE TITLE
Publishing An Album to a Facebook Page

### ISSUE THREAD

**Issue by chandrasekhar4u** [restfb/restfb#288]
How can we **publish an Album (List of Images)** to Facebook page?

I tried below code but it's publishing one by one, Is there any way to **Publish an Album** by posting **multiple images** together to Facebook page?
```java
List<String> photoList=new LinkedList<String>();
if(CollectionUtils.isNotEmpty(imageList)){
	for(String imageUrl:imageList){
		InputStream is = ImageUtils.readImage(imageUrl);
		FacebookType photo = facebookClient.publish(facebookPageId + "/photos" , 
				FacebookType.class,BinaryAttachment.with("TestImg", is));
		Link photoLink = facebookClient.fetchObject(photo.getId(), Link.class);
		photoList.add(photoLink.getLink());
	}
      //Is there any way to publish/post below photo list to page at same time?
	FacebookType post =  facebookClient.publish(facebookPageId + "/feed", 
		FacebookType.class,Parameter.with("message", "msg"),Parameter.with("type", 
		"photo"),Parameter.with("links", photoList));
}
```

**Comment by nbartels** [comment]
No, and I think that's because you get a JSON as response with the id of the new generated photo.

**Comment by chandrasekhar4u** [comment]
How can I solve this Issue? Please help me on this,

**Comment by nbartels** [comment]
Because Facebook does not provide this feature you can only use your solution or send a bug report to Facebook (https://developers.facebook.com/bugs/).
