### ISSUE TITLE
Improve connection paging documentation on website

### ISSUE THREAD

**Issue by revetkn** [restfb/restfb#289]
See https://groups.google.com/forum/#!topic/restfb/fZC6vNMsTXU

It is not clear from the documentation that connections don't "autopage" - we should have an example of how to fetch additional pages via ```Connection::getNextPageUrl()``` and ```FacebookClient::fetchConnectionPage()```

**Comment by nbartels** [comment]
I moved the issue to the webpage project and close it here.
