### ISSUE TITLE
DefaultFacebookClient not working with Version 2.4

### ISSUE THREAD

**Issue by mossaddequemahmood-dsi** [restfb/restfb#291]
Trying to fetch "me" user object with scope email. When facebook app version is 2.4, its not working, but its working for 2.3 app.

**Comment by nbartels** [comment]
Can you please elaborate what you mean with "not working" ...

**Comment by mmahmoodictbd** [comment]
By not working, I meant - fetched "me" user does not have email, first name, last name, etc.

It returns - 
13:38:40,223 DEBUG FbController:92 - Fetched FB User info -  User[about=null ageRange=null bio=null birthday=null birthdayAsDate=null currency=null devices=[] education=[] email=null favoriteAthletes=[] favoriteTeams=[] firstName=null gender=null hometown=null hometownName=null id=10208110521707899 interestedIn=[] languages=[] lastName=null link=null locale=null location=null meetingFor=[] metadata=null middleName=null name=Mossaddeque Mahmood picture=null political=null quotes=null relationshipStatus=null religion=null significantOther=null sports=[] thirdPartyId=null timezone=null tokenForBusiness=null type=null updatedTime=null username=null verified=null website=null work=[]]

As you see, just 'name'.

But for my old fb app with version 2.3, it shows email and other fields.
FYI - I did not missed to change DefaultFacebookClient Version accordingly.

My code sample here -
```
String code = request.getParameter("code");

if (code == null || code.trim().length() == 0) {
    logger.debug("facebookSignUpLogin expecting 'code' parameter in request. Redirecting to /auth/login");
    return "redirect:/auth/login";
}

String urlEncodedRedirectURI = URLEncoder.encode(
HttpUtil.getFbRedirectUrl(request), "UTF-8");

StringBuilder authURL = new StringBuilder();
authURL.append("https://graph.facebook.com/oauth/access_token?client_id=");
authURL.append(fbAppId);
authURL.append("&redirect_uri=");
authURL.append(urlEncodedRedirectURI);
authURL.append("&client_secret=");
authURL.append(fbAppSecret);
authURL.append("&code=");
authURL.append(code);

WebRequestor wr = new DefaultWebRequestor();
WebRequestor.Response accessTokenResponse = wr.executeGet(authURL.toString());
String MY_ACCESS_TOKEN = DefaultFacebookClient.AccessToken.fromQueryString(accessTokenResponse.getBody()).getAccessToken();

logger.info("FB ACCESS_TOKEN: " + MY_ACCESS_TOKEN);

FacebookClient facebookClient = new DefaultFacebookClient(
MY_ACCESS_TOKEN, fbAppSecret, Version.VERSION_2_3);

User loginUser = facebookClient.fetchObject("me", User.class);
logger.debug("Fetched FB User info -  " + loginUser);
```

**Comment by nbartels** [comment]
Ah okay, I see. That's a change at Facebook. It's done from version 2.3 to 2.4. You need to specify the fields you need. So the request is more like:
```java
User loginUser = facebookClient.fetchObject("me", User.class, Parameter.with("fields","email,last_name,first_name");
```

You can find the explanation here: https://developers.facebook.com/docs/apps/changelog
> **Declarative Fields**
> To try to improve performance on mobile networks, Nodes and Edges in v2.4 requires that you explicitly request the field(s) you need for your GET requests. For example, GET /v2.4/me/feed no longer includes likes and comments by default, but GET /v2.4/me/feed?fields=comments,likes will return the data. For more details see the docs on how to request specific fields.

So you have to check for the endpoints what Facebook returns with version 2.4. The better way is to specify what you need. This should work even in version 2.3 :smile:

**Comment by mmahmoodictbd** [comment]
Thx man, saved hours! love this lib, much simpler than spring social.

**Comment by nbartels** [comment]
thx, we try to keep it as simple as possible

**Comment by Shevelyov** [comment]
Unfortunately even with specified fields everything except names and link is null

**Comment by nbartels** [comment]
Can you please give some more information? What endpoint do you call, which fields do you expect do be filled and which are not filled.
