### ISSUE TITLE
Language support question

### ISSUE THREAD

**Issue by spunxz** [restfb/restfb#292]
Hi,

First of all, I am really happy with restfb and want to thank everyone that contributed. Great work!

One thing that I currently don't understand yet is the topic of language support..

E.g. I have a piece of code that works with Comment.class specifically getMessage(), the issue is that English language is working fine, however if we throw in cyrillic or other languages I see a lot of question marks in the log file and database. Is this a known issue in restfb or am I using a wrong collation?

I don't see any options inside the functions that I am using regarding language options or formats, is it utf-8 that is by default being used? What format is the data transferred in?

Let me know ok, I want to expand based on the great library! :+1:

**Comment by nbartels** [comment]
Glad to hear that you like restfb!

I never heard about that kind of issue and only use english and german post/comments without any issues. 

Can you please provide some ids for posts/comments that are in cyrillic? 

So I can check that and write some unittests :smile:

**Comment by spunxz** [comment]
Latest update. I setup an empty table in mysql with collation utf8_unicode_ci instead of latin1_swedish_ci.

If you look here:
http://graph.facebook.com/698692733519032_870850086303295
You see the following message at the top:

Bizim Nutrilon 3 v\u0259 4 promo qutular\u0131m\u0131zda u\u015faqlar\u0131n\u0131z\u0131n inki\u015faf\u0131na yard\u0131m\u00e7\u0131 olacaq oyuncaqlar \u0259ld\u0259 ed\u0259 bil\u0259rsiniz. Art\u0131q \u0259ld\u0259 etmisinizmi?

However it does not arrive in mysql like that (seems like some kind of utf right?). All unknown characters seem to be converted to ? this counts for commenter name and message/comment.

**Comment by spunxz** [comment]
Another example here:
http://graph.facebook.com/489791117831811_685310131613241

First message (wow!):
\u041d\u0435\u0441\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u043e \u0438\u043b\u0438 \u0442\u0440\u0430\u0434\u0438\u0446\u0438\u043e\u043d\u043d\u043e \u0438\u043c\u0435! \u041a\u0430\u043a\u0432\u043e \u0438\u0437\u0431\u0440\u0430\u0445\u0442\u0435 \u0437\u0430 \u0412\u0430\u0448\u0435\u0442\u043e \u0431\u0435\u0431\u0435?

It should be like below (eventually ASCII):
Нестандартно или традиционно име! Какво избрахте за Вашето бебе?

**Comment by spunxz** [comment]
ISO-Latin-1 makes the utf message into: ???????????? ??? ??????????? ???! ????? ???????? ?? ?????? ????? And that's exactly the problem! I want it to stay UTF so I can handle it later. Provide me an option to set the format. :100:

**Comment by malulmj2** [comment]
HI @spunxz , we also had the same issue, you will need to change the character set in your database to the below. As for you LOG file you will need to use a Log formatter that caters for UTF8 character set.

CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci

**Comment by spunxz** [comment]
Resolved, thanks a lot. Used this guide: 
https://mathiasbynens.be/notes/mysql-utf8mb4
