### ISSUE TITLE
Picture of commenter in Comment.Class

### ISSUE THREAD

**Issue by spunxz** [restfb/restfb#293]
Hi, I want to know how can I retrieve pictures of people that commented? 

        Connection<Comment> allComments = client.fetchConnection(post_id + "/comments", Comment.class);

        for (List<Comment> postcomments : allComments) {
            for (Comment comment : postcomments) {

comment.getPicture() is not there? How to obtain it from this scope?

Is it advisable to use: https://graph.facebook.com/<comment id here>/picture?type=normal

**Comment by nbartels** [comment]
Normally Facebook don't provide this information, if you simply cann `<post_id>/comments`. You have to add some fields to add this information. So you have to call `<post_id>/comments?fields=from{name,id,picture}`. 

With RestFb you have to add the `Parameter.with('fields',from{name,id,picture}')` to the fetchConnection call.

But the `Comment`-type returns a `CategorizedFacebookType` instead of a `User`-type. So you cannot access the picture easily.

I think we have to change this in RestFB, I have to check how we can solve this without breaking the API :smile:

**Comment by nbartels** [comment]
Just a little note. You can solve the "missing User in the Comment-type" with a Custom-Type. Let's call it `CommentWithUser`.

```java
class CommentWithUser extends Comment {

     @Facebook("from")
     private User userFrom;

     public User getUserFrom() {
          return userFrom;
     }

}
```

You should use this class instead of the `Comment` class and you should be able to access the picture field. The `Parameter` is still needed.

**Comment by spunxz** [comment]
Hi,

Compiler bums out on line:
@Facebook("from")
Don't know why. :-1: 

Just had a thought.. :+1: 
Can I use the getFields function to iterate over all items in fields=from{name,id,picture} ?

**Comment by spunxz** [comment]
P.S. I also ran into the following issue: post.getPicture() gives a really small low resolution picture. It's really ugly. :-1: How can I pimp it up so it becomes beautiful again :+1:

**Comment by spunxz** [comment]
I really like restFB, we need to get funding from Facebook for all the good work done. In fact I will write a message to them right now.

**Comment by nbartels** [comment]
Okay, so I try to answer all questions :smile: 

The `Facebook` annotation needs (of course) the restfb-jar and the import `com.restfb.Facebook`. You can check this.

`fields` is a query parameter and I don't see why you should iterate over these.

You can retrieve a big picture calling `<userid>/picture?type=large`. I tried to fetch it with the comments in one call, but couldn't find a solution right now. Perhaps caching the image urls is a good idea. `post.getPicture()` simply returns the picture provided by Facebook without any type parameter.

**Comment by spunxz** [comment]
Latest update, this gets the images of users:

id = comment.getFrom().getId();
userFrom = fbclient.fetchObject(id, User.class, Parameter.with("fields", "name,id,picture.type(square).height(66).width(66)"));

Do note that picture from Post is not customizable for some reason, I end up with a really small picture on that. But my original issue is resolved. :-) Thanks!
