### ISSUE TITLE
list of users I follow

### ISSUE THREAD

**Issue by stanislav80** [restfb/restfb#294]
Does restfb has a function that returns the list of users that I follow? In the facebook GUI they can be found under tab friends / following.

And one (two) more qustions. Is it possible to start (stop) following someone by using restfb? 

Thank you very much.

**Comment by nbartels** [comment]
the `subscribers` and `subscribedto` edges had been removed with graph version 2.0, so I don't think it is possible.

https://developers.facebook.com/docs/apps/changelog#v2_0_graph_api

Perhaps a change request at Facebook is a good idea...

**Comment by stanislav80** [comment]
I made a change request so that they return the edge. 
For how I think that this issue can be closed because even if they return the edge it will not be any time soon.
If I have any more info, I will post it here.

**Comment by nbartels** [comment]
Okay great. Perhaps you can post the link to the CR here.
