### ISSUE TITLE
Picture of Post in Post.Class seems very small

### ISSUE THREAD

**Issue by spunxz** [restfb/restfb#295]
Hi,

I also want the high resolution version of pictures in posts, for users this seems to work. However with the below code I seem to get only small pictures even after hard setting the height and width or the type to e.g. large.

fbclient.fetchConnection(pageID + "/feed", Post.class, Parameter.with("fields", "created_time,story,shares,message,comments.summary(true),link,picture,id,status_type,type,likes.limit(1).summary(true)"));

Oh wait a minute, now I am checking I see there is also a full_picture option :+1:
And so there must be a restFB associated with that one too. Omg, this will save people time. :1234:
:100: 
:100: 
:+1:

**Comment by nbartels** [comment]
`full_picture` is supported by restfb. You have to use the field in your request to force Facebook to deliver it. But this information can be found in the javadoc. 

I think we should add this information to the documentation, so user can find it more easily.
