### ISSUE TITLE
Comments: attachment type picture

### ISSUE THREAD

**Issue by spunxz** [restfb/restfb#296]
So some have a picture or a video attached in their comment. How to get a hold of that url information (mime type also)? Sorry can't find it! I checked the site as well.

**Comment by nbartels** [comment]
Can you please give a sample id for a comment with a picture and one with a video, I have a look at it.

**Comment by spunxz** [comment]
https://www.facebook.com/NutriciaClub.centroamerica/photos/a.422545604574813.1073741829.421139554715418/508603092635730/?type=1
Behold pictures of babies.

**Comment by nbartels** [comment]
:smile: 

So, I checked the attachment field and there is nothing like a mime type. You can check the graph api reference here: https://developers.facebook.com/docs/graph-api/reference/v2.4/story_attachment/

```json
"attachment": {
        "media": {
          "image": {
            "height": 539,
            "src": "https://scontent.xx.fbcdn.net/hphotos-xtf1/v/t1.0-9/11863412_934381206623394_2226598391850721647_n.jpg?oh=039f1e22bdf34a8150296f5fca418e41&oe=56637E0E",
            "width": 525
          }
        },
        "target": {
          "id": "934381206623394",
          "url": "https://www.facebook.com/photo.php?fbid=934381206623394&set=p.934381206623394&type=3"
        },
        "type": "photo",
        "url": "https://www.facebook.com/photo.php?fbid=934381206623394&set=p.934381206623394&type=3"
      }
```
As you can see, you only get the information this is a `photo`. The image url can be found in `attachment->media->image->src`.

Your example contains only photos, do you have one with a video?

**Comment by spunxz** [comment]
Luckily I have no demand for video's so I will close this item. I do recommend to add mime type info (facebook) so that people do not need to interogate the extension. Consider it closed (for now ;-)
