### ISSUE TITLE
OAuthException 1 on search

### ISSUE THREAD

**Issue by speedy78** [restfb/restfb#298]
This is the code that I'm using in order to search post with the word "soccer":

```java
Connection<Post> myFeed =  
          facebook.fetchConnection("search", Post.class, 
               Parameter.with("q", "soccer"), Parameter.with("type", "post"))
```

I don't know why I got the OAuthException code = 1 exception. Why? Can you helm me?

The access token works fine.

Cheers, 
Fabio

**Comment by nbartels** [comment]
That's easy :smile: 

With Graph API Version 2.0 search with type `post` has been deprecated and is no longer available. After version 2.0 you get the error message you got. 

Have a look here (https://developers.facebook.com/docs/graph-api/using-graph-api/v2.0#search) for available search types.

**Comment by nbartels** [comment]
@speedy78 your issue is solved with this answer, so it can be closed?

**Comment by speedy78** [comment]
Yes you can close it.
Many thanks for you support.

Cheers,

Fabio Latini
Founder Wallin.tv
+39 328 9459476
