### ISSUE TITLE
Engagements (likes + comments + shares + postclicks) - the latter postclicks missing?

### ISSUE THREAD

**Issue by spunxz** [restfb/restfb#306]
Hello,

So let's talk engagements. We can access likes, comments and shares, but what about post clicks? I have been looking inside the api docs, can't find anything related to this. I want to capture this information. Is it possible?

Thanks!

**Comment by nbartels** [comment]
you should try `<post-id>/insights`. And have look at the output. The `read_insights` permission is needed. 

the clicks can be found here `<post-id>/insights/post_consumptions_unique/lifetime`. At least I think this is the resource :smile:

**Comment by spunxz** [comment]
Hi nbartels,

I enter this: 698692733519032_866499350071702/insights
don't see anything, also when amending the post_consumptions_unique/lifetime

Any ideas why? And also how to expose it via restfb?

**Comment by nbartels** [comment]
you should use your page access token. You can use the `Insight` type.

**Comment by spunxz** [comment]
Ok got this to work, my account got access to the read_insights permission and I got to say there are a lot of insights :+1: :+1: 

How can I get a hold of all this data via the api? Can you provide an example?

 Connection<Insight> insights = fbclient.fetchConnection(pageID + "/insights", Insight.class);
        for (List<Insight> insightsConnectionPage : insights) {
            for (Insight insight : insightsConnectionPage) {
                // e.g. IF I WANT TO ITERATE OVER ALL VALUES (VALUE) meeting a certain "name"
// Any best practises?
            }
        }

**Comment by nbartels** [comment]
If you want just some insights you can fetch them separated. For example, you want to fetch `post_impressions_viral`. So you simply use the endpoint `<post-id>/insights/post_impressions_viral/lifetime` and you're done.

The object you get is a `Insight` as you already did right in your example.

Btw you can use a different `period` instead of `lifetime`. You should have a look at the [Facebook Reference](https://developers.facebook.com/docs/graph-api/reference/v2.4/insights) to get a better understanding of the `period` part and the possibilities.

And if you want to get the correct endpoint, it is the id field of the insights object.

**Comment by nbartels** [comment]
@spunxz can I close this issue, or do you have some open questions?

**Comment by spunxz** [comment]
for (int i = 0; i < insight.getValues().size(); i++) {
                    System.out.println("++++++++++++++++++" + insight.getValues().get(i));
                }

I am doing this now, checking if it works. Will it work?

Also this seems to work for me:
https://www.rocketmarketinginc.com/blog/get-never-expiring-facebook-page-access-token/

**Comment by nbartels** [comment]
No. It should look like:
```java
for (int i = 0; i < insight.getValues().size(); i++) {
     JsonObject valueObject = insight.getValues().get(i);
     System.out.println("++++++++++++++++++" + valueObject.getInt("value");
}
```

The `Values` are a list of `JsonObject`s.

Ah interesting, so you can convert a Page Access token into a long living token.

**Comment by spunxz** [comment]
OK thanks, btw the insights values are some days behind. I just take the latest value for now. Thanks.

**Comment by nbartels** [comment]
Yes, the App Analytics a 2 days behind, I think they calculate these data and prevent running into timezone problems with the 2 days delay. But just a guess :smile:
