### ISSUE TITLE
Support user-definable logging to avoid slf4j bridge overhead

### ISSUE THREAD

**Issue by revetkn** [restfb/restfb#31]
Per Juan Tula's suggestion -

> Mark,
> 
> I was thinking in a possible solution, and a first non intrusive approach
> may be as follows:
> - Create a com.restfb.logging.LogFactory and com.restfb.logging.Logger
> implementation, and change all the code to use those instead of JUL
> framework
> - Create a com.restfb.logging.api.LogFactory and
> com.restfb.logging.api.Logger interface, and a default JUL implementation
> of them (the idea is to use com.restfb.logging.LogFactory as the factory
> for the concrete implementation, and at runtime use a, for example, system
> parameter to define the concrete impelentation used by the static factory).
> This way, your library is self contained, all that's needed is there.
> - Any user that wants to use other logging framework, just only need to
> implement the com.restfb.logging.api interfaces, and define the system
> property to point to that concrete implementation.
> - because we will be depending on internal interfaces, there's no
> classloader problems that are present with general logging frameworks.
> - you can also provide that other implementations so anyone can use them,
> without the need to rewrite them.
> 
> What do you think?
> 
> Cheers!
> 
> Juan

**Comment by fern** [comment]
So we're saying that this issue is "wont fix", or that it'll be "move restfb to use slf4j directly"?

**Comment by juantula** [comment]
I think it was a wont fix...

**Comment by nbartels** [comment]
Atm, we try to leave the zero dependencies condition untouched. As soon as we add slf4j we have to drop this. So I let the issue open and I make once in a while some thoughts how to solve it.

**Comment by bseib** [comment]
I am a big fan of "zero dependencies".  But logging is such a peculiar beast that I would find this an acceptable dependency to introduce. SLF4J does not have the "chain reaction" of dependency that needs a dependency that needs a dependancy -- it was designed specifically to avoid that issue:

> SLF4J is only a facade, meaning that it does not provide a complete logging solution. Operations such as configuring appenders or setting logging levels cannot be performed with SLF4J. Thus, at some point in time, any non-trivial application will need to directly invoke the underlying logging system. In other words, complete independence from the API underlying logging system is not possible for a stand-alone application. Nevertheless, SLF4J reduces the impact of this dependence to near-painless levels.

And wrapping anything is just contributing to the problem: http://www.slf4j.org/faq.html#optional_dependency

I don't recall all the issues surrounding this topic, but I don't feel that you would be selling out your "zero dependency" principles if you choose slf4j as your logging facade.

**Comment by fern** [comment]
If there were a vote, I would vote going directly to slf4j-api.  But I was just thinking we could close this bug and open a different one specific for that discussion.

Though my vote is for slf4j, I don't have experience with android-slf4j... so that might actually be a valid argument to keep it as it is for now..? probably not..?

**Comment by nbartels** [comment]
Perhaps we can use logging similar to DataNucleus:
https://github.com/datanucleus/datanucleus-core/blob/4.1/src/main/java/org/datanucleus/util/NucleusLogger.java
