### ISSUE TITLE
Event.getPicture() returns a JSON string rather than a link (v 1.14.1)

### ISSUE THREAD

**Issue by OhGhie4iew** [restfb/restfb#312]
Using this code:
```
Event e = facebookClient.fetchObject(id, Event.class,
  Parameter.with("fields", 
    "id,updated_time,owner,name,location,cover,venue,picture"));
String p = e.getPicture();
```
p is the JSON string rather than the picture url:

```
{
    "data":{
        "is_silhouette":false,
        "url":"https://scontent.xx.fbcdn.net/...."
    }
}
```

**Comment by nbartels** [comment]
Can you please provide a sample Event JSON or the event's id, so I can fetch the JSON. The Graph Api Reference does not know about picture on events. So it's a bit hard to check the correct structure.
