### ISSUE TITLE
Cover picture for User

### ISSUE THREAD

**Issue by badoualy** [restfb/restfb#313]
Hi,

thanks for your work,

do you plan to add the cover field in the user class ? Maybe I missed it somewhere, anyway to get it easily currently ?

**Comment by nbartels** [comment]
You can extend the `User` type and create an `ExtendedUser` (for example) with the `cover` field. Additionally you have to add the `CoverPhoto` type. 

I'll add the change soon.

**Comment by badoualy** [comment]
Great, thanks !
