### ISSUE TITLE
User profile picture size - FacebookJsonMappingException

### ISSUE THREAD

**Issue by FunnyDevs** [restfb/restfb#327]
Hi! I have tried this code

facebookClient.fetchObject("me/picture", JsonObject.class, Parameter.with("type", "large"))

but it returns com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON

**Comment by nbartels** [comment]
Can you please provide the returned JSON?

**Comment by FunnyDevs** [comment]
This is the returned JSON with Graph Api Explorer

{
  "data": {
    "is_silhouette": false,
    "url": "https://scontent.xx.fbcdn.net/xxxxxxxx-frc3/v/t1.0-1/p200x200/xxxxxxx_10204952009779090_xxxxxxxxxxxxxxxxxxx_n.jpg?oh=xxxxxxxxx615640xxxxxx5abe0d67xxx&xx=xxxxxxxx"
  },
}

I change some values

**Comment by nbartels** [comment]
I added a test for your json and cannot reproduce your exception. Everything's fine. Even though the json is not valid the parser generates a `JsonObject` with the expected values.

**Comment by FunnyDevs** [comment]
mmmm bad news...have you tried the same call with your facebook test app and your facebook account??? I obtain always same result

**Comment by nbartels** [comment]
This one was a bit tricky. You have to add a special parameter to your request to get the json, otherwise Facebook redirects you automatically to the image binary. The image binary cannot not be parsed as json :smile: 

The call should look like this:
```java 
JsonObject js = 
   fc.fetchObject("/me/picture", JsonObject.class, 
       Parameter.with("type","large"), // the image size
       Parameter.with("redirect","false")); // don't redirect
```

**Comment by FunnyDevs** [comment]
Thanks a lot!!

**Comment by aarushi15** [comment]
Hi ,

I have tried this code :+1: 

FacebookClient client = new DefaultFacebookClient(accessToken);
			        JsonObject picture = 
			        		  client.fetchObject("me/picture", 
			        	      JsonObject.class, 
			        	      Parameter.with("type","large"),
			        	      Parameter.with("redirect","false"));

But I am getting this error:

com.restfb.exception.FacebookJsonMappingException: Don't know how to map JSON to class com.google.gson.JsonObject. Are you sure you're mapping to the right class? Offending JSON is '{"data":{"height":200,"is_silhouette":false,"url":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/c0.0.200.200\/p200x200\/23168039_1865609390119434_2100761744741111111_n.jpg?oh=578b7c28eadead9c62a62b8540a453ad&oe=5A953D05","width":200}}'

I have changed the digits to hide the correct json.
Can you please suggest whats going wrong here?

**Comment by nbartels** [comment]
You imported the wrong JsonObject. `com.google.gson.JsonObject` is not supported, use `com.restfb.json.JsonObject` instead.

**Comment by aarushi15** [comment]
Yes I rectified this just after posting the comment and it worked :) Thanks for the quick response !!Much appreciated.

**Comment by aarushi15** [comment]
Hi, 
I am suddenly facing this exception:

SEVERE: Error is this:Exception - org.springframework.social.**ExpiredAuthorizatio
nException**
Stack -

        at org.springframework.social.facebook.api.impl.FacebookErrorHandler.han
dleFacebookError(FacebookErrorHandler.java:83)
        at org.springframework.social.facebook.api.impl.FacebookErrorHandler.han
dleError(FacebookErrorHandler.java:59)
        at org.springframework.web.client.RestTemplate.handleResponseError(RestT
emplate.java:589)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.ja
va:547)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java
:518)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate
.java:256)
        at org.springframework.social.facebook.api.impl.FacebookTemplate.fetchOb
ject(FacebookTemplate.java:225)

Can you please let me know a solution to this. It was working fine yesterday.

**Comment by nbartels** [comment]
This is a Spring Social exception. You should ask them what's the problem ;) But according to the exception class name it looks like the access token is expired. But only a guess ...
