### ISSUE TITLE
Facebook error code: 6001 subcode: 1363037

### ISSUE THREAD

**Issue by frank72833** [restfb/restfb#328]
Hi,

I am experiencing some issues with resumable uploads using RestFB API. From time to time during the upload_phase transfer I receive an exception 6001:1363037. 

Reading the documentation in the graph API, I found that they return the following error Message for that exception: "There was a problem uploading your video. Please try uploading it again. error_data:{start_offset:0,end_offset:392695}"

However, I cannot access the JSON erro_data with the start offset and end offset in the exception. I can see the error message but there is not such information in the provided FacebookGraphException.

I was wondering how can I have access to this JSON that is sent in the error message?

Graph API Doc link: https://developers.facebook.com/docs/graph-api/video-uploads

Many thanks,
Kind regards.

**Comment by nbartels** [comment]
Can you please provide the complete error json, so we can write a test.

**Comment by frank72833** [comment]
Hi,

How can I get the complete error json you are referring to?

With RestFB, I've just got an exception with the error message: "There was a problem uploading your video. Please try uploading it again." with the code and subcodes.

And the JSON in Facebook Graph API docs is:
error_data:{start_offset:0, end_offset:392695} // This is an example.

Which JSON are you referring to and how can I access it?

Many thanks

**Comment by nbartels** [comment]
Facebook returns a status code (!=200) and a JSON if an error occurs. In that JSON there are some fields filled with the error information and RestFB transform them into a exception. 

The response body should be found in the log file. Try to set the "com.restfb.HTTP" logger to finest. If you need more information, just ask.

**Comment by frank72833** [comment]
Hi,

I have tried to replicate this issue with the logs but it is really inconsistent and I could't replicate it in my test environment to get the logs that you asked.

Is there any process in place to implement this so we can access the JSON from the exception? Do you know any work around to access that info so I can parse the JSON (not logs)?

Many thanks,
Kind regards.

**Comment by nbartels** [comment]
I think we add a `rawError` field with the json and everyone may take the information from that field. This should not interfere with the current implementation.

Anyway, if you have some more information about the returned json, I'd like to get it, because I run only into the best case :smile:

**Comment by nbartels** [comment]
With the next release you may access the error JSON and call `getRawErrorJson` on the exception.

**Comment by EZWrighter** [comment]
Heads up, I ran into this same issue and tracked it down to a bug in the code provided here: http://restfb.com/#publishing-big-video  In the transfer phase, the offsets and length are being calculated incorrectly due to "returnValue" variable being used instead of "filePart".

These lines: 
```Javascript
startOffset = returnValue.getStartOffset();
endOffset = returnValue.getEndOffset();
length = endOffset - startOffset;
```

Should be replace with: 
```Javascript
startOffset = filePart.getStartOffset();
endOffset = filePart.getEndOffset();
length = endOffset - startOffset;
```

So I assume this error code refers to your application sending the wrong data.

Hope that helps.

**Comment by nbartels** [comment]
I see, so this is a issue in the documentation. But nevertheless we provide access to the plain JSON that Facebook returns in case of an error. This can be useful in some other cases, too. 

Thanks for the hint!

**Comment by alexconlin** [comment]
@nbartels: would it be possible to access the http headers in the getRawErrorJson?

**Comment by nbartels** [comment]
No, only the returned json can be found in the `rawErrorJson` object. Why do you need the http headers, perhaps it's a common use case and we should provide some other way to access them?

**Comment by alexconlin** [comment]
We want to access the http headers so we can access the "FBTrace ID". This is returned in the headers for all responses, and it seems to be returned in the json response for errors as well, so maybe it could be added to the exception object?

**Comment by nbartels** [comment]
if it is returned with all responses we should access this value on a different way. I'll create a new issue for this.
