### ISSUE TITLE
.getCommentsCount() and .getLikesCount() return 'null' invariably

### ISSUE THREAD

**Issue by iamgroot42** [restfb/restfb#329]
Calling .getCommentsCount() (or .getLikesCount() ) on a Post object returns null.
However, running .getComments().getData().size() or .getLikes().getData().size() returns the correct value
. What is then the point of having the .getCommentsCount() and .getLikesCount() function?

**Comment by nbartels** [comment]
Please have a look at the documentation, this should help you: http://restfb.com/#fetch-post-total-count

**Comment by iamgroot42** [comment]
I guess the problem is that something like :
Connection<Post> pageFeed = facebookClient.fetchConnection("me/posts",Post.class);
and then iterating through pageFeed.data() does not get the number of likes/comments for a post correctly.I'm now extracting the ID of every post and fetching a new connection for each elements,which seems to work

**Comment by nbartels** [comment]
You should simply use:
```java 
Connection pageFeed = 
     facebookClient.fetchConnection("me/posts",
          Post.class, 
          Parameter.with("fields", "from,to,likes.summary(true),comments.summary(true)"));
```

With this call you get a `Connection` with the `Post` objects correctly prefilled. You should change the `fields` parameter according to your needs.
