### ISSUE TITLE
Add Comments to Album Class

### ISSUE THREAD

**Issue by vido88** [restfb/restfb#333]
Hi guys,
if i make an API call like _page_id/albums?fields=comments.limit(5),description_ i can get a list of comments of the album, without make a call to comments endpoint , 
<pre>
{
    "description": "Alcune delle somiglianze più curiose tra giocatori e personaggi celebri del mondo dello spettacolo e non (Fonte foto: Repubblica.it) Ve ne vengono in mente altre? ;)",
    "id": "817655031603811",
    "comments": {
        "data": [
            {
                "created_time": "2014-11-12T15:14:17+0000",
                "from": {
                    "name": "Calcio Illustrato",
                    "id": "521525131216804"
                },
                "message": "E loro due li riconoscete?",
                "id": "817655031603811_817746908261290"
            }
        ],
        "paging": {
            "cursors": {
                "before": "NjkZD",
                "after": "NjUZD"
            },
            "next": "https://graph.facebook.com/v2.5/817655031603811/comments?access_token=CAACEdEose0cBANLHB0G3SRzKnUALLCFOBzJSZA5xBQ0ddZChBx0AcFlTTsnCI4uZCbhdwtneHSAvS6F8ClKUzBwnPCmNZADP3oZA8lmWqW9sFoTcktZBKDKimYPmLa7M3obgkWeDVYYKRAmRltVl2HP9w5eZAbf6jFlkIlT3HTJbaARVJLQEKP4V0mph8LCBTcNrZATZCtZAHRKQZDZD&pretty=0&limit=5&after=NjUZD"
        }
    }
}
</pre>
but the Album class doesn't contain it, while Post class has it.
Is there a reason, or it could be added to Album class ?
(Something like this ...)
<pre>
   /**
   * The comments for this album.
   *
   * @return The comments for this album.
   */
  @Getter
  @Setter
  @Facebook
  private Comments comments;
</pre>

Thanks in advance,

Paolo

**Comment by nbartels** [comment]
Hi Paolo,

no, there's no particular reason and I'll check the `album` type soon. Perhaps some other fields are missing, too.

**Comment by vido88** [comment]
Thanks man!
