### ISSUE TITLE
Access post likes summary has_liked and can_like values?

### ISSUE THREAD

**Issue by jarylchong** [restfb/restfb#335]
Thanks for all the work you guys put into this library!

When I pull the field `likes.summary(true)` on a Page's posts (I assume this applies for Users as well), I see that the following js object is returned to me as a member of the likes js object.

```javascript
"summary": {
          "total_count": 1,
          "can_like": true,
          "has_liked": true
}
```

Assuming that I have a Java object `restfb.types.Post post`, I know that doing `post.getLikes().getTotalCount()` returns me that `summary.total_count` value. Is there some way I can access the `summary.can_like` and `summary.has_liked` values? My use case is that I need to know if the user can/already has liked a post, and allow/disallow him/her to like/dislike a post as appropriate.

**Comment by nbartels** [comment]
Ah I see, this is a new feature with API 2.4, I don't think it's already supported. I have to write a testcase and add the new feature.

Thanks for the hint!
