### ISSUE TITLE
Photo getComments() return List of Comment instead of Comments

### ISSUE THREAD

**Issue by vido88** [restfb/restfb#337]
Hi,
the method getComments() in Photo class return List\<Comment\>
<pre>@Facebook
private List<Comment> comments = new ArrayList<Comment>();
[...]
public List<Comment> getComments() {
    return unmodifiableList(comments);
  }</pre>
while getComments() in Post return an object of type Comments
<pre>
  @Getter
  @Setter
  @Facebook
  private Comments comments;
</pre>
as well of Album class 
<pre>
  @Getter
  @Setter
  @Facebook
  private Comments comments;
</pre>

I think also getComments() in Photo class should return Comments object, so i could use all the method of this class (e.g. totalCount); the Facebook Graph API documentation link the same object for both Post and Photo (https://developers.facebook.com/docs/graph-api/reference/v2.5/photo - https://developers.facebook.com/docs/graph-api/reference/v2.5/post)

Thanks, Paolo

**Comment by nbartels** [comment]
I moved your request to the new 2.0 branch because it breaks current applications and we don't like to do this in a minor release.
