### ISSUE TITLE
SimpleDateFormat produces wrong date on parsing yyyy-MM-dd inputs

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#340]
The SimpleDateFormat produces a differen output on different machines. This only happens on the special "yyyy-mm-dd" format pattern. Other patterns work correctly...

**Comment by revetkn** [comment]
Can it be solved by providing Locale.US?

**Comment by nbartels** [comment]
No, it's a timezone problem ... the SimpleDateFormat instance need a defined one, otherwise some "default" is used. And the default depends on the machine the code is running on. But this only happens if the format pattern does not contain a timezone information like in "yyyy-MM-dd"
