### ISSUE TITLE
Facebook OAuth Exception While Accessing Facebook "publicMessages" using restfb

### ISSUE THREAD

**Issue by ssakthi** [restfb/restfb#347]
We are using restFB 1.17.0 and I get the following error while trying to access the FB end point searching for messages.

com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: An unknown error has occurred. (code 1, subcode null)
at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1174)
at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1100)
at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1041)
at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:952)
at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:914)
at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:356)

**Comment by mukesh14149** [comment]
May be the access token you are using is expire, you need to regenerate the access token and use it.
Check this link http://developers.facebook.com/docs/facebook-login/access-tokens/#extending

**Comment by mukesh14149** [comment]
I don't think it is restfb issue.
Possible Reason:- The access code you have it does not have righe permission to see public message.
I tried on graph tool explorer to read inbox it showing me "Requires extended permission: read_mailbox"," even i extended permission.So possibly this was not restfb issue.

And you have asked this issue before is that not solvable.
https://github.com/restfb/restfb/issues/76

**Comment by ssakthi** [comment]
Thanks for your prompt reply!!!!

Yes. I didn't solve yet... If it is not restfb issue, then why I am getting the same error in [graph api](https://developers.facebook.com/tools/explorer/517312558337191?method=GET&path=search%3Fq%3Ddog&version=v2.5)

``` {
  "error": {
    "message": "An unknown error has occurred.",
    "type": "OAuthException",
    "code": 1,
    "fbtrace_id": "DGK1yfY63HC"
  }
} 
```
1. If I search public posts, which token should I use "User Access Token" or "App Access Token" or "Page Access Token" ?
2. How long those access-tokens will take to expire?
3. If the token gets expired, how to extend their validity using java code?

Kindly provide your inputs....

**Comment by nbartels** [comment]
1. You cannot search public posts, because facebook does not support this anymore.
2. about 1 hour, but check in the Access Token Debugger on Facebook
3. You may check the validity of a token by using the application access token
