### ISSUE TITLE
Restfb jar:- In restfb jar com.restfb.types.FacebookType.java does not contain getId() method

### ISSUE THREAD

**Issue by Devmassnk** [restfb/restfb#349]
Connection<Photo>photos =facebookClient.fetchConnection("me/photos/uploaded", Photo.class);
out.println(photos.getData().get(0).getLikes().get(0).getId());

This was successfully print id of a user but i am not able to find any getId() method in this class com.restfb.types.FacebookType.java so how it is printing.
Moreover Is there any doc which can specify how  all classes of restfb are arrange.

**Comment by nbartels** [comment]
Have a look at the javadoc: http://restfb.com/javadoc/index.html

FacebookType has a `getId` method. The classes are arranged in the way Facebook built its Json. So you may and should have a look at the Graph Reference.

Example codes can be found on http://restfb.com

**Comment by Devmassnk** [comment]
https://github.com/restfb/restfb/blob/master/source/library/com/restfb/types/FacebookType.java
There is no getID method in this but in java docs classes have, can you explain little more.

**Comment by nbartels** [comment]
The Getter and Setter for the id field is generated. You can see the corresponding annotations. You need to have lombok installed in your ide. https://projectlombok.org/

Netbeans provides support out of the box, intellij provides a plugin and how to use lombok with eclipse can be found in the lombok documentation.

This information can be found on our website.

**Comment by Devmassnk** [comment]
Hey
After installing lombok into my eclipse, I will have the generated methods (getters, setters, ...) in the outline view - but still not in the source code.So what else do i need to do to have these method in my source code so that i can manipulate it.

**Comment by mukesh14149** [comment]
You need to do "delombok"  for getting all method.
You can find all detail about how to delombok here:- https://projectlombok.org/features/delombok.html 

In Summary you need to run following commands
java -jar lombok.jar delombok -p Filename.java

You need to set the correct path for lombok.jar and your file that I assume is named Filename.java. You can also perform that for all files in your src folder 

java -jar lombok.jar delombok src -d src-delomboked
src being the folder with source files that use Lombok annotations and src-delomboked the output folder.

For further detail i think @nbartels  helps you more.

**Comment by nbartels** [comment]
No, because there's no boilerplate code. If you need your own `getId` method you have to add it (and remove the `@Getter` annotation. But perhaps you can tell why you need something different than a simple getter.
