### ISSUE TITLE
A network error occurred while trying to communicate with Facebook: Facebook request failed (HTTP status code null) 

### ISSUE THREAD

**Issue by agkreddy** [restfb/restfb#35]

**Comment by minhphong306** [comment]
@agkreddy Can you explain "This was due to blocking sites"
I've search for nearly a week. 
Please help me.

**Comment by nbartels** [comment]
I think some firewall was blocking requests to the Facebook API endpoints. In that case strange http error codes may occur.

**Comment by minhphong306** [comment]
Let me try to turn off the firewall.
