### ISSUE TITLE
Make HTTP headers accessible

### ISSUE THREAD

**Issue by alexconlin** [restfb/restfb#352]
As per my comment in a previous issue (https://github.com/restfb/restfb/issues/328#issuecomment-163581108), we would like to be able to access the information on requests returned in the HTTP headers via RestFB without having to resort to logging. For example, the FBTrace ID which is included in the JSON of some errors, but not others, and only in the headers for successful requests. Additionally in the future it might be useful to access the other headers such as ETAG so it could make sense to implement a generic way to access HTTP headers.

**Comment by nbartels** [comment]
The solution should include two approaches, first return access to the header and second provide access to some debug header. These headers are defined like this (Copy and Paste from FB documentation):
> If you need to report a bug in the Graph API, we include some additional request headers that you should send with your bug report to help us pinpoint and reproduce your issue. These request headers are X-FB-Debug, x-fb-rev, and X-FB-Trace-ID.

**Comment by nbartels** [comment]
The `FacebookClient` interface provides access to the 3 debugging http header fields and the version header. So you may access these fields via a container. 

For the complete header list, we have a getter in the `DefaultFacebookClient`. I think we should not provide a easy access to these fields, but you may if you cast. So you know what you are doing :smile:
