### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by luli0822** [restfb/restfb#361]
Hi, I've downloaded the latest zip but there came up a lot of compilation errors when I tried to clean the build and run the example. For example, there's no definition for User.getHometown() around line 956 inside getHometownName(). I'm running on Eclipse Luna, JDK 1.6 (also tried v1.7, 1.8 libraries). Can you help me with this? Thanks.

**Comment by nbartels** [comment]
Let me guess: You tried to build your restfb jar?
Install lombok (restfb.com -> working with source code) in your eclipse and please try again. This should solve the problem.

If you problems compiling the example, please show the error here. But I tried compiling the example yesterday myself and it worked.

**Comment by luli0822** [comment]
Thanks Norbert. I followed the instructions from Iombok to install it and then restart Eclipse. It works now.
