### ISSUE TITLE
deprecated permissions?

### ISSUE THREAD

**Issue by lomon** [restfb/restfb#371]
Hey, is it possible that the following permissions are deprecated in API v2.5?
* UserDataPermissions.USER_ACTIVITIES
* UserDataPermissions.USER_GROUPS
* UserDataPermissions.USER_INTERESTS
* ExtendedPermissions.MANAGE_NOTIFICATIONS
* ExtendedPermissions.READ_MAILBOX
* ExtendedPermissions.READ_STREAM

Because I got this error message @ Facebook for Device - test
> Invalid Scopes: user_activities, user_groups, user_interests, manage_notifications, read_mailbox, read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by nbartels** [comment]
Yes this is possible. RestFB provides all permissions that can be used from Graph API 2.0 to 2.5.

**Comment by lomon** [comment]
So it could be helpful to add a deprecated warning, such as this one:
> @deprecated in Graph API 2.3 use READ_CUSTOM_FRIENDLISTS instead. If you use the Graph API before 2.3 ignore the deprecation warning
  @Deprecated READ_FRIENDLISTS("read_friendlists"), //

**Comment by lomon** [comment]
Sorry, it's me again, both are not labeled as deprecated in `1.19.0`:

- UserDataPermissions.USER_ACTIVITIES
- UserDataPermissions.USER_INTERESTS

Still get this error:
> Invalid Scopes: user_activities, user_interests. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Thank you!

**Comment by nbartels** [comment]
Ah, I see. I checked the deprecated permissions on the Facebook permission website. These 2 you mention are not listed there, but are removed with Graph API 2.3

I'll open a new issue and have to check the permissions in detail. Obviously the Facebook reference is not sufficient here. :smile: 

btw, thanks for the hint
