### ISSUE TITLE
Error when FB doesn't return a value

### ISSUE THREAD

**Issue by kriswatson** [restfb/restfb#372]
Getting an error when trying to get Campaign details with "spend_cap" but FB doesn't always return an integer if there is no value "spend_cap" doesn't get returned at all.  The restfb error I am getting is: 

java.lang.IllegalArgumentException: The 'object' parameter cannot be an empty string.
	at com.restfb.BaseFacebookClient.verifyParameterPresence(BaseFacebookClient.java:370)
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:390)

Is there a way to make parameters optional so it doesn't break if FB doesn't return the field?

**Comment by nbartels** [comment]
The error is something different. You seem to use `DefaultFacebookClient#fetchObject` without an resource url. For example like `fetchObject("/me", User.class)`. Please check how you use `fetchObject`.

**Comment by kriswatson** [comment]
Using fetchObject like:
facebookClient.fetchObject(campaignID, Campaign.class, campaignFields);

Whete campaignFields is 
Parameter campaignFields = Parameter.with("fields", "id,name,account_id,effective_status,configured_status,start_time,end_time,updated_time,created_time,lifetime_budget,daily_budget,budget_remaining,campaign_id,targeting,promoted_object,is_autobid,optimization_goal,billing_event,bid_amount,rtb_flag,rf_prediction_id,pacing_type");

**Comment by kriswatson** [comment]
I am also getting the following error:
com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"billing_event":"CLICKS","targeting":{"geo_locations":{"location_types":["home"],"countries":["DK"]},"age_min":35,"relationship_statuses":[2,4,3,8],"page_types":["desktopfeed","mobilefeed","rightcolumn"],"age_max":65},"optimization_goal":"CLICKS","account_id":"118045838312891","configured_status":"ACTIVE","lifetime_budget":"750000","updated_time":"2015-08-10T09:32:37+0200","campaign_id":"6032084744346","rtb_flag":false,"id":"6032084764346","pacing_type":["standard"],"end_time":"2015-08-16T00:00:00+0200","is_autobid":false,"name":"Launch Comp. \"Giveaway\" (Rightside)","daily_budget":"0","start_time":"2015-07-27T13:00:00+0200","effective_status":"CAMPAIGN_PAUSED","created_time":"2015-07-24T15:38:15+0200","bid_amount":400,"budget_remaining":"552921"}'.
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:320)
	at com.restfb.Connection.<init>(Connection.java:155)
	at com.restfb.DefaultFacebookClient.fetchConnectionPage(DefaultFacebookClient.java:382)
	at com.restfb.Connection.fetchNextPage(Connection.java:199)

**Comment by kriswatson** [comment]
Closing this as it turns out it was something to do with mapping Enum status values
