### ISSUE TITLE
like total count is bigger than like data set size

### ISSUE THREAD

**Issue by shmerko** [restfb/restfb#378]
post.getLikes().getTotalCount()     and     post.getLikes().getData().size()    should be the same but
post.getLikes().getTotalCount() > post.getLikes().getData().size()

post.getLikes().getTotalCount() is accurate.

**Comment by nbartels** [comment]
Facebook provides only the first "page" of the comments. With `getData().size()` you get the amount of `Likes` on this first page. `getTotalCount()` returns - as the name says - the total count. Therefore the total count may be bigger than the page count.
