### ISSUE TITLE
Unable to post image to an event page

### ISSUE THREAD

**Issue by rj93** [restfb/restfb#386]
I am trying to post an image to an events page. It works if I supply the url to the image, but if i try to do it using a `byte[]` then it doesn't work. I am using your code from the examples:

    byte[] imageAsBytes = extractBytes("resources/test.png");
    JsonObject obj = facebookClient.publish(EVENT_ID + "/photos", JsonObject.class,
			BinaryAttachment.with("test.png", imageAsBytes, "image/png"),
    Parameter.with("message", "TestImage"));

and my extractBytes function:

	public static byte[] extractBytes (String ImageName) throws IOException {
		 File imgPath = new File(ImageName);
		 BufferedImage bufferedImage = ImageIO.read(imgPath);

		 WritableRaster raster = bufferedImage .getRaster();
		 DataBufferByte data   = (DataBufferByte) raster.getDataBuffer();

		 return data.getData();
	}

However, this produces the following error:

	Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: Invalid parameter (code 100, subcode 1366046)
		at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1174)
		at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1100)
		at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1041)
		at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:952)
		at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:444)
		at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:461)
		at com.rich.pibooth.Test.main(Test.java:35)

**Comment by revetkn** [comment]
Related: https://github.com/restfb/restfb/issues/181

Does this work with the old byte-array version of the API per the comments on ticket 181?  You might have to use an old version of RestFB to test that out.

**Comment by rj93** [comment]
Built v1.18 and using <pageid>/photos without the paramaters works fine. 

My code now looks like:

    JsonObject obj = facebookClient.publish(EVENT_ID + "/photos", JsonObject.class,
			BinaryAttachment.with("test.png", imageAsBytes, "image/png"));

I tried this with v1.19 and it produces the same error as above.

**Comment by rj93** [comment]
I built v1.18, and after me getting confused with it correctly posting (forgot to comment out the url one) it still produces the same error as above for `<pageid>/photos` with the parameters removed.

**Comment by rj93** [comment]
Realised I wasn't using the old byte-array version. This way still works in v1.19:

	InputStream is = new FileInputStream("resources/test.png");
	FacebookType publishPhotoResponse = facebookClient.publish(EVENT_ID + "/photos",FacebookType.class, BinaryAttachment.with("test.png", is));

**Comment by nbartels** [comment]
Can you try posting a photo to the `Event` with a message? Because your latest code is without a message. And it would be interesting to activate the debug log and/or check the `FacebookOAuthException` content. There is the `getRawErrorJson()`-method on the `FacebookOAuthException`.

Perhaps you can post the content.

**Comment by rj93** [comment]
I can post an image with via the old way with both the `message` and `caption` field, and they both include the mesaage/caption in the post on facebook. 

The raw JSON returns:

    {"error":{"error_user_title":"Can't Read Files","code":100,"error_subcode":1366046,"message":"Invalid parameter","type":"OAuthException","is_transient":false,"fbtrace_id":"HK+2o2CtVKW","error_user_msg":"Your photos couldn't be uploaded. Photos should be less than 4 MB and saved as JPG, PNG, GIF or TIFF files."}}

According to windows explorer the file is < 1mb (81,178 bytes), and the file is saved as PNG.

**Comment by nbartels** [comment]
Okay I see. Perhaps you can replace your extract Bytes with my version and try if this is working :smile: 

```java
protected byte[] getBytesFromInputStream(InputStream is) {
    ByteArrayOutputStream os = new ByteArrayOutputStream();
    try {
      byte[] buffer = new byte[65535];
      for (int len; (len = is.read(buffer)) != -1;) {
        os.write(buffer, 0, len);
      }
      os.flush();
      return os.toByteArray();
    } catch (IOException e) {
      return null;
    }
  }
```

I think it is very interesting to know what is going on there.

**Comment by rj93** [comment]
Using your method it works for the the newer, `BinaryAttachment.with("test.png", imageAsBytes, "image/png")`, with both `caption` and `message` as parameters :smile:
