### ISSUE TITLE
wrong type for picture in Page

### ISSUE THREAD

**Issue by QUEnDo** [restfb/restfb#387]
picture is defined as 'String' but in javadoc it's 'ProfilePictureSource'
and thats exactly what facebook sends...an object with url and is_silhouette

**Comment by nbartels** [comment]
I don't get it. I just checked the Graph API Explorer and Facebook sends a `ProfilePictureSource` object. And the `Page` type uses this object for the picture, too. There is no String or do you use a older version of restfb?
