### ISSUE TITLE
Comments misses can_comment field

### ISSUE THREAD

**Issue by anenkov** [restfb/restfb#396]
Comments.class is missing the can_comment field which is similar to the Likes.class and the can_like field

I think this should be enough:
```
/**
   * returns if the user can comment the object
   *
   * @return if the user can comment the object
   */
  @Getter
  @Setter
  private Boolean canComment;
```

**Comment by nbartels** [comment]
This field is already in the `dev-2.0` code and was introduced with #337 . Do you need this function asap or can you wait for RestFB 2.0.0 do be released?

**Comment by anenkov** [comment]
I already extended it in our code. Just wanted to contribute to the project :)

**Comment by nbartels** [comment]
okay, thanks. I think your change may not be sufficient, but I'll check this later and pull your PR or a changed version :smile: into version 1.20.0.
