### ISSUE TITLE
missing parent_id field in Post object

### ISSUE THREAD

**Issue by vido88** [restfb/restfb#398]
Hi, 
according to [this bug](https://developers.facebook.com/bugs/172612423097646/), posts may have **parent_id** field 

> However, you can detect that they are about the same original post by requesting the `parent_id` field on the post.

I haven't found any reference in the documentation, but in fact the field is present in the response
<pre>
{
         "id": "299150370269_1566464073671397",
         "parent_id": "380528198800882_493275620859472",
         "from": {
            "name": "Rosa Maria Pollaci",
            "id": "1396877040630102"
         },
         "to": {
            "data": [
               {
                  "name": "Kiko Milano",
                  "category": "Health/Beauty",
                  "id": "299150370269"
               }
            ]
         },
....
}
</pre>

Thanks, Paolo

**Comment by nbartels** [comment]
yes, it can be found with metadata enabled

```json
{
     "name": "parent_id",
     "description": "ID of the parent post",
     "type": "token with structure: post id"
}
```
