### ISSUE TITLE
Publish to Facebook groups message + image sets the text as description

### ISSUE THREAD

**Issue by kfredy** [restfb/restfb#404]
Hi,
When you post to a Facebook group a new photo, the message is set as description and not as "message" but as "description". Users cannot see the text, only when clicking on the image.
`fbType = fbClient.publish(postTo + "/photos", FacebookType.class,
Parameter.with("message", attachmentMessage)
,Parameter.with("url", picture));
`

Thanks,
   Fredy

**Comment by nbartels** [comment]
This information is for our documentation? Then I'll open a documentation issue ;)

**Comment by nbartels** [comment]
BTW, you can this behavior in the description of the `group/photos` endpoint. 

https://developers.facebook.com/docs/graph-api/reference/v2.5/group/photos

| Name | Description | Type |
| --- | --- | --- |
| source | The photo, encoded as form data. Either this or url field is required, but both should not be used together. | multipart/form-data |
| url | The URL of a photo that is already uploaded to the internet. Either this or source is required, but both should not be used together. | String |
| message | The **description of the photo**, used as the accompanying status message in any feed story. | String |

**Comment by kfredy** [comment]
Thank you for the reply.

Still through the Facebook UI i can publish an image to the group and set
the headline of the image. For example:
[image: Inline image 1]

Does this mean i cannot set it through the API. (i was able to make a
workaround by publish the photo with Parameter.with("published", "false").
then retrieve the image and post it back to the "feed". the only downside
is FB adds "xxx shared a photo" near the user name)

BTW, restFB works great when the publish is for a page (we can see the text
and the image)

Thanks again,
   Fredy

**Comment by nbartels** [comment]
Hi Fredy,

I just used to Graph API Explorer to push a image to `groupid/photos` including a message.
The image was fetched from an url and so I used the `url` and the `message` parameter.

In Facebook this looks like this:
<img width="507" alt="testimagegroup" src="https://cloud.githubusercontent.com/assets/1113969/13893670/db62b4d2-ed60-11e5-902c-409879c5b7a7.png">

I think this is just what you need. I'll try this with restfb this weekend and it should just work the same.
A integration test will be added afterwards.

**Comment by nbartels** [comment]
I added the integration test and the publishing of a photo with message works on RestFB just like in the Graph API Explorer. Please have a short look at the integration test. Perhaps you see a difference ...

**Comment by kfredy** [comment]
Thanks a lot, Now i see my message in the stream itself :-)
