### ISSUE TITLE
Missing getVideoData() on com.restfb.types.Message.Attachment

### ISSUE THREAD

**Issue by lalitg14** [restfb/restfb#415]
Hello, 
I am using restfb 1.21.1 version and missing the getVideoData() method to get the details of Video on Private Messages to Faceook Page.
Below is a data given from FB Explorere.

Query: me/conversations?fields=updated_time,message_count,snippet,messages{created_time,from,id,message,subject,to,attachments,shares,tags}&since=2016-03-31
Result:

```json
"attachments": {
              "data": [
                {
                  "id": "222088404818734",
                  "mime_type": "video/mp4",
                  "name": "video-1459938992.mp4",
                  "size": 233101,
                  "image_data": {
                    "width": 256,
                    "height": 240
                  },
                  "video_data": {
                    "width": 256,
                    "height": 240,
                    "length": 6,
                    "video_type": 1,
                    "url": "https://video.xx.fbcdn.net/hvideo-xat1/v/t42.3356-2/12048213_10205243564634244_247050400_n.mp4/video-1459938992.mp4?vabr=305351&oh=2a70242c0d0fd37e56e890575bcf914e&oe=5706592F&dl=1",
                    "preview_url": "https://scontent.xx.fbcdn.net/hvthumb-xat1/v/t15.3394-10/12365321_1137155502996003_1377746299_n.jpg?oh=08de41615bdd78a357b3912087032d35&oe=5773F36D",
                    "rotation": 0
                  }
                }
              ]

```
Could you please let me know if you need further info?

Kind Regards
Lalit

**Comment by nbartels** [comment]
Okay, this is a very interesting. Thank you for the json example. We check this as soon as possible ...

**Comment by lalitg14** [comment]
Thanks. When will get the 1.22 jar file?

**Comment by nbartels** [comment]
On Tuesday (12 April, 2016), there is the F8 (Facebook developer conference). Quite likely Facebook will introduce a new Graph API version at that date and we have to change the `Version` enum to allow developers to use that version. 

So I'd like to wait until Tuesday/Wednesday and release the 1.22 than. Because we don't have to release 2 versions in 3-4 days. 

Do you need the new version earlier?

**Comment by lalitg14** [comment]
Hi Norbert,

Thanks for the update. I can surely wait till next week.

Thanks again.

Kind Regards
Lalit

**Comment by nbartels** [comment]
The new version is released ;)
