### ISSUE TITLE
What Happened to Post Fields?

### ISSUE THREAD

**Issue by brentjwt** [restfb/restfb#421]
I upgraded to the latest version and generated my tokens using v2.5 of the FB API and now all I get back is the body content....no thumbnails, images, links, etc.

**Comment by nbartels** [comment]
Obviously you moved from a version before 2.4 to 2.5. So please check these links and you'll understand what happened to these fields:

* http://restfb.com/documentation/#fetching
* https://developers.facebook.com/blog/post/2015/07/08/graph-api-v2.4/ (Fewer default fields for better performance)

**Comment by brentjwt** [comment]
Ah...yep you are right.  Totally read right past that in the docs!  Thank you!
