### ISSUE TITLE
restfb corrupts Parameter names by converting them to lowercase

### ISSUE THREAD

**Issue by rheylen** [restfb/restfb#444]
I have a request that needs an aggregateBy parameter which was failing. The request was submitted to facebook with the parameter name changed to "aggregateby" which failed.
At first glance, this seems to be the fault of line 72 of https://github.com/restfb/restfb/blob/master/source/library/com/restfb/Parameter.java

   this.name = trimToEmpty(name).toLowerCase();

**Comment by nbartels** [comment]
Wow, you have found a bug we have in the code since the initial commit in 2010 :smiley:

I have to write some more unit test to have the different possibilities covered and this will be fixed in the next version.

**Comment by revetkn** [comment]
My (very old) bug - great find!  I don't recall why I forced lowercase in the first place...
