### ISSUE TITLE
Successful login redirect contains "expires_in" instead of "expires"

### ISSUE THREAD

**Issue by Mobe91** [restfb/restfb#451]
Currently, you expect the query part of the redirect to contain `expires` in [FacebookClient#fromQueryString](https://github.com/restfb/restfb/blob/master/source/library/com/restfb/FacebookClient.java#L678). However, the actual query parameter that is returned is `expires_in`.

This might be related to https://github.com/restfb/restfb/issues/223.

**Comment by nbartels** [comment]
I checked this and cannot find the information on the Facebook Graph Reference. `expires_in` is (afaik) used in the returned json and the access token object can handle that. 

Can you please give some more information.

**Comment by Mobe91** [comment]
I am using the following login URL
```
https://www.facebook.com/dialog/oauth?client_id=<app-id>&redirect_uri=https%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html&scope=public_profile%2Cuser_photos&response_type=token&display=popup
```
and I finally get redirected to this URL after successful login
```
https://www.facebook.com/connect/login_success.html#access_token=<access-token>&expires_in=5184000
```
As you can see, the redirect URL contains `expires_in` and not `expires`. Parsing the query part of the redirect URL with the `fromQueryString` method gives me an AccessToken object with `expires` set to `null`.

Moreover, the `fromQueryString` method expects `?` as a separator for the query part instead of a `#` which is why I have to split the redirect URL manually before passing the query part to `fromQueryString`.

I could not find any details about this in the Facebook docs either but I found this [article](http://hayageek.com/facebook-dialog-oauth/) where they describe the format of the redirect URL - with `expires_in`.
