### ISSUE TITLE
Getting "Unable to map JSON to Java" when making call to pages because JSONObject["likes"] is not a long

### ISSUE THREAD

**Issue by vido88** [restfb/restfb#453]
Hi Guys,
I need to make this request :
>  https://graph.facebook.com/v2.6/search?q=xxx&type=page&fields=id,name,likes,link

so I write this code:
<code>public static final String INFO_FIELDS = "id,name,link,fan_count";
client.fetchConnection("search", type, Parameter.with("q", "xxx"), Parameter.with("type", "page"),Parameter.with("fields", INFO_FIELDS))
</code>

but i get an exception, because with the new version of the Facebook API, the likes field contains a list of user who has liked the page.

> com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"name":"Paolo Nutini","link":"https://www.facebook.com/PaoloNutini/","id":"6513804564","likes":{"data":[{"name":"Damien Rice","id":"10582587785"},{"name":"Arctic Monkeys","id":"9520450966"},{"name":"Snow Patrol","id":"6191917071"},{"name":"James Morrison","id":"6134209286"},{"name":"Atlantic Records UK","id":"166380523407983"}],"paging":{"cursors":{"before":"MTA1ODI1ODc3ODUZD","after":"MTY2MzgwNTIzNDA3OTgz"}}}}'.
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:320)
	at com.restfb.Connection.<init>(Connection.java:155)
	at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:356)
...
Caused by: com.restfb.json.JsonException: JSONObject["likes"] is not a long.
	at com.restfb.json.JsonObject.getLong(JsonObject.java:588)
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:687)
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300)
	... 12 more

Response from facebook is :

```json{
    "data": [
        {
            "id": "1672755836271884",
            "link": "https://www.facebook.com/PaoloBonolisOfficial/",
            "name": "Paolo Bonolis"
        },
        {
            "id": "427389037347980",
            "link": "https://www.facebook.com/Patisserie.Libreville/",
            "likes": {
                "data": [
                    {
                        "name": "Location Eventi Milano",
                        "id": "1655189674715496"
                    },
                    {
                        "name": "Alexandre Paisant",
                        "id": "258245294331976"
                    },
                    {
                        "name": "INBP · Institut National de la Boulangerie Pâtisserie",
                        "id": "293781934007125"
                    },
                    {
                        "name": "Deco&Style",
                        "id": "658217487548277"
                    }
                ],
                "paging": {
                    "cursors": {
                        "before": "MTY1NTE4OTY3NDcxNTQ5NgZDZD",
                        "after": "NjU4MjE3NDg3NTQ4Mjc3"
                    }
                }
            },
            "name": "Paolo Pâtisserie"
        },
        ...
```

 Am i doing something wrong ?

Thanks in advcance,
Paolo

**Comment by PsiLupan** [comment]
Add "likes.limit(0).summary(true)" to your fields, and it should map properly.

**Comment by nbartels** [comment]
You can skip the `likes` field in your fields and add `fan_count` instead. 

If you need the likes list, we have to change something ...

**Comment by nbartels** [comment]
How did you manage to get the likes? I cannot get the list if I request the likes field in the Graph API explorer. Would be interesting to know ...

**Comment by vido88** [comment]
> How did you manage to get the likes? I cannot get the list if I request the likes field in the Graph API explorer. Would be interesting to know ... 

The request i've made is this https://graph.facebook.com/v2.6/search?q=paolo&type=page&fields=id,name,likes,link.
The json i've pasted was taken from the Graph API explorer. This is the link of the saved session https://developers.facebook.com/tools/explorer/145634995501895/?session_id=793636820771167, if you want to make some tests (not all the pages have the list).

> Add summary(true) to a "likes" field, and it should map properly as a workaround.

I think this doesn't work when calling the search endpoint. I will try.

By the way, I found a workaround to solve my problem, using the fetchObject method, with JsonObject.class as type:
`final JsonObject fetchObject = client.fetchObject("/search", JsonObject.class, Parameter.with("q", "paolo"), Parameter.with("type", "page"),
                Parameter.with("fields", "id,name,link,likes"));`

If you need some other informations just ask, otherwise feel free to close this issue.

Thank you very much for the support,
Paolo

**Comment by nbartels** [comment]
Thanks for the query string! This is really interesting, and we have to fix this. The same bug can be seen fetching a page with likes. So it has nothing to do with the search. Therefore some more people can run into trouble switching from 2.5 to 2.6 ...
