### ISSUE TITLE
getLoginDialogUrl does not support reauthentication

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#457]
Hello,

AFAIK getLoginDialogUrl doesn't seem to support reauthentication:
https://developers.facebook.com/docs/facebook-login/reauthentication

Am I right?

**Comment by nbartels** [comment]
yes, you're right. Reauthentication requires the url to contain some additional (and some optional) parameter. Perhaps it would be useful if the user can add optional some `Parameter` objects like in `fetchObject`. So both possibilities can be handled with one method and the optional parameters are no problem...

**Comment by hkroger** [comment]
Yes, I think that would be a good way to handle it. Any chance anyone of you who are working it could add it there? :)
