### ISSUE TITLE
FundingSourceDetails causes an exception when trying to load it.

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#458]
Hi,

I see that FundingSourceDetails.java has missing implementation which breaks when you do an actual query. 

When you query adaccounts with field "funding_source_details" you get json like this back:

    "funding_source_details": {
        "id": "12345679",
        "display_string": "American Express *1234",
        "type": 1
    }

I hope this helps. "type" is an enum but I don't know all the options. I think 1 is credit card and pay pal was something like 13 and so on. Better keep it an integer before it's know what all options are...

See: https://github.com/restfb/restfb/blob/02e799eacc0331a6a8c3960cd3e1c5b1f7c7f70e/source/library/com/restfb/types/ads/FundingSourceDetails.java

**Comment by nbartels** [comment]
Wow, great. At the time the type was implemented, these information were not present in the facebook reference. So we can change this and with your example json it's possible to test the changed class.

> ID = ID of the payment method
COUPON = Details of the Facebook Ads Coupon from the payment method
AMOUNT = Amount of Facebook Ads Coupon
CURRENCY = Currency of the Facebook Ads Coupon
DISPLAY_AMOUNT = How the amount of Facebook Ads Coupon is displayed
EXPIRATION = When the coupon will expire
DISPLAY_STRING = How the payment method is shown
TYPE = Type of the funding source
