### ISSUE TITLE
Issue with TOS fields in Ad Account

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#460]
Hi,

When trying to load AdAccount with parameter `fields=name,offsite_pixels_tos_accepted,tos_accepted,funding_source,funding_source_details,owner_busines` I get

    com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"custom_audience_tos":1,"web_custom_audience_tos":1}'.

The issue seems to be with `tos_accepted` which is a `Map<String, Int>` on java side. In theory it should work though.

**Comment by nbartels** [comment]
Can you please provide the complete JSON Facebook sends to your request. I can write a unit test and fix this issue much faster ;) please obfuscate any private data

**Comment by hkroger** [comment]
Hi,

Here's the query and response. Indentation I added for readability. 

URL: `https://graph.facebook.com/v2.6/123123123123/adaccounts?limit=25&offset=0&access_token=abcdef&fields=name,offsite_pixels_tos_accepted,tos_accepted,funding_source,funding_source_details,owner_business,account_id`

Response:

        {
                "data": [
                {
                        "name": "Test Company (AMEX)",
                        "offsite_pixels_tos_accepted": true,
                        "tos_accepted": {
                                "web_custom_audience_tos": 1,
                                "custom_audience_tos": 1
                        },
                        "funding_source": "12345678",
                        "funding_source_details": {
                                "id": "123123123",
                                "display_string": "American Express *1002",
                                "type": 1
                        },
                        "owner_business": {
                                "id": "123123123123",
                                "name": "Test Company"
                        },
                        "account_id": "123123123123",
                        "id": "act_123123123123"
                },
                {
                        "name": "Test Company (VISA)",
                        "offsite_pixels_tos_accepted": true,
                        "tos_accepted": {
                                "web_custom_audience_tos": 1,
                                "custom_audience_tos": 1
                        },
                        "owner_business": {
                                "id": "123123123",
                                "name": "Test Company"
                        },
                        "account_id": "123123123",
                        "id": "act_123123123123"
                },
                {
                        "name": "John Doe",
                        "offsite_pixels_tos_accepted": false,
                        "account_id": "234234234234",
                        "id": "act_234234234234"
                }
                ],
                "paging": {
                        "cursors": {
                                "before": "AFKBATEJHKAETJH",
                                "after": "KAJGKAJTHKATH"
                        }
                }
        }
