### ISSUE TITLE
Page is missing owner_business and perms

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#461]
Hi,

Class Page is missing perms and owner_business attributes:

`https://graph.facebook.com/v2.6/me/accounts?limit=25&offset=0&access_token=abc&fields=name,owner_business,perms`

        {
                "data": [
                {
                        "name": "Test Company Page",
                        "owner_business": {
                                "id": "123123123123",
                                "name": "Test Company"
                        },
                        "id": "123123123123",
                        "perms": [
                                "ADMINISTER",
                                "EDIT_PROFILE",
                                "CREATE_CONTENT",
                                "MODERATE_CONTENT",
                                "CREATE_ADS",
                                "BASIC_ADMIN"
                        ]
                }
                ],
                "paging": {
                        "cursors": {
                                "before": "ABCDABBA",
                                "after": "ABCDABBA"
                        }
                }
        }

See: https://developers.facebook.com/docs/pages/access-tokens

**Comment by nbartels** [comment]
You should use the `Account` type for the accounts list. So you get at least the `perms` field. The `owner_business` is still missing, but I think this can be solved ;)

Imho the accounts are only pages enriched with the perms field. I have to  check this further ...
