### ISSUE TITLE
Retrieving business userpermissions maybe not supported atm.?

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#462]
Sorry that I'm bombarding you with all these questions and reports but it seems that there something more missing. Or at least I didn't find it where it is.

This API endpoint `https://graph.facebook.com/v2.6/<business id>/userpermissions?limit=25&offset=0&access_token=abcdf1234` returns:

        {
                "data": [
                {
                        "business_persona": {
                                "name": "Peter Smith",
                                "id": "123123123123"
                        },
                        "role": "ADMIN",
                        "status": "ACTIVE",
                        "email": "milkman@test.com",
                        "user": {
                                "name": "Peter Smith",
                                "id": "234234234234"
                        }
                },
                {
                        "business_persona": {
                                "name": "Jane Doe",
                                "id": "1231231231234"
                        },
                        "role": "EMPLOYEE",
                        "status": "ACTIVE",
                        "email": "bono@u2.com",
                        "user": {
                                "name": "Jane Doe",
                                "id": "2342342342342344"
                        }
                },
                {
                        "business_persona": {
                                "name": "John Doe",
                                "id": "456456456456456456"
                        },
                        "role": "ADMIN",
                        "status": "ACTIVE",
                        "user": {
                                "name": "John Doe",
                                "id": "567567567567567567"
                        }
                }
                ],
                "paging": {
                        "next": "https://...."
                }
        }

**Comment by nbartels** [comment]
okay thanks, that's no problem. It seems the marketing api is not used that much via restfb so we really appreciate your help and your bug reports.

**Comment by nbartels** [comment]
can you please call the request and add the fields `created_time` and `updated_time`. According to the Facebook Marketing API reference this field may be present and I'd like to know what kind of "date string" is used here.

**Comment by hkroger** [comment]
They look like this:

    "created_time": "2016-01-21T15:33:50+0000",
    "updated_time": "2016-01-21T15:33:50+0000",

**Comment by nbartels** [comment]
Thanks ...
