### ISSUE TITLE
Custom / Lookalike Audience management is missing

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#464]
If you check here there are APIs to handle custom audiences:
https://developers.facebook.com/docs/marketing-api/lookalike-audience-targeting#conversion-data

I don't see audience management objects in RestFB. Maybe those could be added?

**Comment by nbartels** [comment]
Sorry for the delay, but as soon I had a deeper look inside the lookalike audience targeting topic, I discovered some more missing types and had to add them to.

It's a big (in the sense of LOCs) change and I hope I get it done until this weekend ...
