### ISSUE TITLE
Examples for Facebook Messenger Bot

### ISSUE THREAD

**Issue by chandrasekhar4u** [restfb/restfb#465]
Please update examples for facebook messenger Bot,
How to communicate to messenger and webhook, vice versa.
If documentation with examples(restfb) is already available please let me know the details.

**Comment by nbartels** [comment]
You should simply at the [webhooks documentation](http://restfb.com/documentation/#using-webhooks) and the [messenger documentation](http://restfb.com/documentation/#messenger-overview). Further information can be found at the [Facebook Messenger docs](https://developers.facebook.com/docs/messenger-platform).

If you need more information write a comment.

**Comment by chandrasekhar4u** [comment]
Hi @nbartels ,
Thank you for the update,
Let me go through the documentation shared by you,

**Comment by chandrasekhar4u** [comment]
Hi @nbartels ,

I used code like below and facing an issue while publishing message,

```
FacebookClient facebookClient = new DefaultFacebookClient(
				"pageAccessToken",
				"myAppSecret",
				Version.VERSION_2_6);
		final IdMessageRecipient recipient = new IdMessageRecipient("recipientUserID");

		final Message simpleTextMessage = new Message("First Message");
		facebookClient.publish("/me/messages", Message.class,
				Parameter.with("recipient", recipient),
				Parameter.with("message", simpleTextMessage));
```

When I ran this code getting error like below:
`Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#100) No matching user found (code 100, subcode null)`

could you please help me to solve this issue,
If you have any example implementation which is done by using restfb could you pleas share...

**Comment by nbartels** [comment]
Where do you get the `recipientUserID`?

**Comment by chandrasekhar4u** [comment]
Ya I need that information too, as per the fb docs, User ID used in FB is different from User ID used in messenger, I am not sure how to get it, could you please help me to solve this issue?

For the time being I fallowed below tutorial, And I am able to create bot using node.js,
I am planning to do the same with restfb, if restfb is not supporting then I should go for node.js only.
If same kind of tutorial or documentation is available it helps us very much.

Could you please guide me to solve this issue.

**Comment by nbartels** [comment]
You have to subscribe your webhook at your messenger as you subscribe every other webhook, too. Therefore you have to write for example a servlet to handle the webhook requests. Parsing of these requests can be done with restfb.

https://developers.facebook.com/docs/messenger-platform/implementation#setup_webhook

In the webhook response object you'll find the recipient id and with this id you can send answers to the user with the code you wrote above.

We can add some documentation how to handle these webhook types, but it is the same as the webhook , you can already found in the restfb documentation.

In general: A user has to write your bot a message before she can get an answer. Spamming users is not possible 😄

**Comment by chandrasekhar4u** [comment]
How can I use restfb code to do the same thing what I am doing in below code,
I am not able to debug to verify the response/content sending by facebook,
could you please help me to convert below js code to restfb java code.

```
app.post('/webhook', function (req, res) {
    var events = req.body.entry[0].messaging;
    for (i = 0; i < events.length; i++) {
        var event = events[i];
        if (event.message && event.message.text) {
                sendMessage(event.sender.id, {text: "Echo: " + event.message.text});
        } else if (event.postback) {
            console.log("Postback received: " + JSON.stringify(event.postback));
        }
    }
    res.sendStatus(200);
});
```

I created  a servlet as below, but not sure how to get events from the request object.

```
@WebServlet(name = "/webhook", urlPatterns = { "/webhook" })
public class EndPoint extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	@Override
	protected void doGet(final HttpServletRequest request, final HttpServletResponse response)
			throws ServletException, IOException {
		System.out.println("inside doGet() method");
		if (request.getParameter("hub.verify_token") == "testbot_verify_token") {
			response.getWriter().append(request.getParameter("hub.challenge"));
		} else {
			response.getWriter().append("Served at: ").append(request.getContextPath());
		}
	}

	@Override
	protected void doPost(final HttpServletRequest request, final HttpServletResponse response)
			throws ServletException, IOException {
		System.out.println("inside doPost() method");
		doGet(request, response);
	}

	@Override
	public void init(final ServletConfig config) throws ServletException {
		System.out.println("inside init() method");
	}
}
```

**Comment by nbartels** [comment]
okay, so you have to change the `doPost` method like this:

```java
@Override
  protected void doPost(final HttpServletRequest request, final HttpServletResponse response)
      throws ServletException, IOException {

    // retrieve POST Body
    String body = request.getReader().lines().reduce("", (accumulator, actual) -> accumulator + actual);

    // map body json to WebhookObject
    DefaultJsonMapper mapper = new DefaultJsonMapper();
    WebhookObject webhookObject = mapper.toJavaObject(body, WebhookObject.class);

    for (WebhookEntry entry : webhookObject.getEntryList()) {
      if (!entry.getMessaging().isEmpty()) {
        for (MessagingItem item : entry.getMessaging()) {
          String senderId = item.getSender().getId();

          // create recipient
          IdMessageRecipient recipient = new IdMessageRecipient(senderId);

          // check message
          if (item.getMessage() != null && item.getMessage().getText() != null) {
            // create simple text message
            Message simpleTextMessage = new Message("Echo: " + item.getMessage().getText());

            // build send client and send message
            FacebookClient sendClient = new DefaultFacebookClient(AccessToken.TOKEN, Version.VERSION_2_6);
            sendClient.publish("me/messages", GraphResponse.class, Parameter.with("recipient", recipient),
              Parameter.with("message", simpleTextMessage));
          }

          if (item.getPostback() != null) {
            LOG.debug("run postback");
          }
        }
      }
    }
  }
```

The code is untested ... and some parts can be optimized.

**Comment by chandrasekhar4u** [comment]
@nbartels thank you for the update, I'll try with the given code.

**Comment by chandrasekhar4u** [comment]
@nbartels  one more thing how can I get below attributes from servlet request object?

I tried by using request.getParameter(), request.getAttribute() but no luck,
```
req.query['hub.verify_token']
req.query['hub.challenge']
```

**Comment by nbartels** [comment]
You have to implement a servlet and [override the `doGet` method](https://docs.oracle.com/cd/E17802_01/products/products/servlet/2.3/javadoc/javax/servlet/http/HttpServlet.html#doGet(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)).

Than you can take the `hub.verify_token` from the request by using [the `getParamter`-method](https://docs.oracle.com/cd/E17802_01/products/products/servlet/2.3/javadoc/javax/servlet/ServletRequest.html#getParameter(java.lang.String)).

That's all.

**Comment by chandrasekhar4u** [comment]
Hi @nbartels 

I tried below code, but parameters are not getting(it's returning null).
could you please let me know if there are any changes need to done.

```
@Override
	protected void doGet(final HttpServletRequest request, final HttpServletResponse response)
			throws ServletException, IOException {
		System.out.println("inside doGet() method");

		if (request.getParameter("hub.verify_token") == "testbot_verify_token") {
			response.getWriter().append(request.getParameter("hub.challenge"));
		} else {
			response.getWriter().append("Served at: ").append(request.getContextPath());
		}
	}
```

**Comment by revetkn** [comment]
@chandrasekhar4u Can you print out all the query parameter name-value pairs Facebook sends in the GET request?

**Comment by nbartels** [comment]
@chandrasekhar4u don't use `==` to compare strings. You have to use the `equals` method.

And simply check the request with a debugger ...

**Comment by chandrasekhar4u** [comment]
Hey @nbartels,

**Thank you for correcting me**(due to some copy paste I missed it), I am able to use the api.
Able to see echo messages from messenger.. :+1: 
Shall I help you to document overall the flow/usage?

**Comment by nbartels** [comment]
@chandrasekhar4u yes, you may send a pull request to https://github.com/restfb/restfb.github.io.

**Comment by chandrasekhar4u** [comment]
Sure @nbartels , by end of this week I'll do the needful.

**Comment by nbartels** [comment]
Issue added to RestFB website repository, close this issue here

**Comment by dhruv7491** [comment]
i am getting the following error  code 
{"error":{"message":"(#100) No matching user found","type":"OAuthException","code":100,"fbtrace_id":"H7XCSldIzYb"}}
i am able to send normal text message but when it send the generic template i get this error

**Comment by nbartels** [comment]
you should check your recipient id. The error says that the id is not correct. And if this is still an issue please open another issue here, so we can track the progress

**Comment by dhruv7491** [comment]
The recipient id is correct the whole issue started when i added the item
url to the generic template of the facebook messenger bot. Before that it
was working fine

**Comment by aillon** [comment]
I too am getting the same error.  It seems that this line requires a user access token and not a app_access token?
FacebookClient sendClient = new DefaultFacebookClient(AccessToken.TOKEN, Version.VERSION_2_6);

If I fetch the appAccess token, it still doesn't work.

						AccessToken appAccessToken = new DefaultFacebookClient(Version.VERSION_2_6).obtainAppAccessToken(app_Id, app_secret);
						String token=appAccessToken.getAccessToken();

						FacebookClient sendClient = new DefaultFacebookClient(token, Version.VERSION_2_6);

Any thoughts?  Thank you!!!

**Comment by nbartels** [comment]
@aillon the page access token is required as you can see in your Facebook App Dashboard.

@dhruv7491 can you please provide an example source code similar to what you use?

**Comment by aillon** [comment]
@nbartels Sorry to bother you about this, but I'm still getting an Oauth error when I call.

FacebookClient sendClient = new DefaultFacebookClient(MY_PAGE_TOKEN, Version.VERSION_2_6);
 I'm using the page token from the setting tab under Messenger from the Dashboard.  Do I need to set the permissions for this token or something?  thanks for your help

**Comment by dhruv7491** [comment]
i want to send  a message to a user after a fixed interval like cnn does.
how can i implement that functionality.

**Comment by nbartels** [comment]
@aillon switch the logger to a finer log level and provide the request and response that you work with. You code is used in my demo bot and works flawlessly. So there is something strange going on. The scopes my access token contains are: `manage_pages, business_management, pages_messaging, pages_messaging_phone_number, public_profile`

@dhruv7491 I would let the user register in the bot and save the recipient id. With a cron job or a similar construction, I would send a message to the saved id. But, this not a RestFB topic...

**Comment by aillon** [comment]
@nbartels it was a scope issue.  I only had the "pages_messaging" added on the "App Review For Messenger" section.  I added the other two choices and it works.  I suspect it was the "pages_messaging_subscriptions" section that enabled the right permission scope.  Thank you for your help!!!

**Comment by nbartels** [comment]
okay great ...
