### ISSUE TITLE
How to do a POST with data payload?

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#466]
I have a class that contains CustomAudience and I would just like to issue a POST with the class to an endpoint.

If I look here https://developers.facebook.com/docs/marketing-api/reference/custom-audience I need to create a POST To `/{ad_account_id}/customaudiences`. But how to do it properly using RESTFB?

**Comment by hkroger** [comment]
Ok, there is something I understood wrong here.

**Comment by nemccarthy** [comment]
@hkroger do you have a code sample you could share?

**Comment by hkroger** [comment]
Well, for ads at least it is something like this:

    Response response = facebookClient.publish("act_123234345/campaigns", Response.class, Parameter.with("name", "My Campaign"), Parameter.with("status","ACTIVE"));

Basically you just give all data using the parameters. `Response` class is probably not any real class, so don't get confused about that.
