### ISSUE TITLE
setting welcome message for messenger bot

### ISSUE THREAD

**Issue by bqcuong2212** [restfb/restfb#472]
I think restfb should have the api to set or delete welcome message for messenger bot.
It's very useful when the server used for bot is down to maintain or etc, bot's owner can notify to users this important message. Thanks!
https://developers.facebook.com/docs/messenger-platform/send-api-reference#welcome_message_configuration

**Comment by nbartels** [comment]
This should already be possible and therefore it's a documentation issue ...

**Comment by bqcuong2212** [comment]
oh! hope to see this documentation soon :D

**Comment by nbartels** [comment]
Okay, I'll add a integration test and a small convenience method and a special documentation chapter. It should be clear how to use everything ...
