### ISSUE TITLE
Release with changes in Ads apis

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#473]
Hi,

I have seen that there are a lot of updates in the Ads Management APIs that you have pushed already. Could make a release with those so that we can test them and take them into use?

**Comment by nbartels** [comment]
yes, I have to commit 1 change and afterwards I'll publish the new version. I hope I can manage to release the version today ...

**Comment by nbartels** [comment]
done!

**Comment by hkroger** [comment]
Cool, have you pushed that to maven repository somewhere?

**Comment by nbartels** [comment]
it should be available in maven central.
