### ISSUE TITLE
Error while reading AdGroup

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#478]
I'm using FB API v2.6 and I get this while reading AdGroup (which is these days called `Ad`, right?)

    com.restfb.exception.FacebookJsonMappingException: JSON is an array but is being mapped as an object - you should map it as a List instead. Offending JSON is '[{"action.type":["page_engagement"],"page":["123456789"]}]'.

This is related to `tracking_specs` field.

**Comment by hkroger** [comment]
Also related to `conversion_specs` field.

**Comment by nbartels** [comment]
Can you please provide a complete "Ad" Json. I'm working on that issue and a additional unit test would be very useful.

**Comment by hkroger** [comment]
With a request like this:
`https://graph.facebook.com/v2.6/123412341234/ads?fields=account_id%2Cadset%2Ccampaign%2Cadset_id%2Cbid_amount%2Cbid_type%2Cconfigured_status%2Ccreated_time%2Ccreative%2Ceffective_status%2Clast_updated_by_app_id%2Ccampaign_id%2Cupdated_time%2Cad_review_feedback%2Ctracking_specs%2Cconversion_specs&access_token=ACDCABBA&format=json`

I got:

        {  
           "data":[  
              {  
                 "account_id":"123123",
                 "adset":{  
                    "id":"123123"
                 },
                 "campaign":{  
                    "id":"123123"
                 },
                 "adset_id":"123123",
                 "bid_type":"ABSOLUTE_OCPM",
                 "configured_status":"ACTIVE",
                 "created_time":"2016-06-08T12:55:57+0300",
                 "creative":{  
                    "id":"123123"
                 },
                 "effective_status":"ACTIVE",
                 "last_updated_by_app_id":"123123",
                 "campaign_id":"123123",
                 "updated_time":"2016-06-08T12:56:02+0300",
                 "tracking_specs":[  
                    {  
                       "action.type":[  
                          "page_engagement"
                       ],
                       "page":[  
                          "123123"
                       ]
                    }
                 ],
                 "conversion_specs":[  
                    {  
                       "action.type":[  
                          "like"
                       ],
                       "page":[  
                          "123123"
                       ]
                    }
                 ],
                 "id":"123123"
              },
              {  
                 "account_id":"1018684694864335",
                 "adset":{  
                    "id":"123123"
                 },
                 "campaign":{  
                    "id":"123123"
                 },
                 "adset_id":"123123",
                 "bid_type":"ABSOLUTE_OCPM",
                 "configured_status":"ACTIVE",
                 "created_time":"2016-06-08T12:55:57+0300",
                 "creative":{  
                    "id":"123123"
                 },
                 "effective_status":"ACTIVE",
                 "last_updated_by_app_id":"123123",
                 "campaign_id":"123123",
                 "updated_time":"2016-06-08T12:56:02+0300",
                 "tracking_specs":[  
                    {  
                       "action.type":[  
                          "page_engagement"
                       ],
                       "page":[  
                          "123123"
                       ]
                    }
                 ],
                 "conversion_specs":[  
                    {  
                       "action.type":[  
                          "like"
                       ],
                       "page":[  
                          "123123"
                       ]
                    }
                 ],
                 "id":"123123"
              }
           ],
           "paging":{  
              "cursors":{  
                 "before":"123123123",
                 "after":"123123"
              }
           }
        }

**Comment by mhchen124** [comment]
Where can I get 1.26.0?
Thanks.

Michael

**Comment by nbartels** [comment]
1.26.0 is still under development ... you have to be patient 😄
