### ISSUE TITLE
Url class OGObject is missing "image"

### ISSUE THREAD

**Issue by Enalmada** [restfb/restfb#481]
The opengraph object for om.restfb.types.Url class is missing "image".
    https://developers.facebook.com/docs/sharing/opengraph/using-objects

Would there happen to be an alternate way to get at that?

**Comment by nbartels** [comment]
Okay thanks, we add this in the next release. 

*In the meantime:*
You may write your own class, extend the Url class and simply add the missing image with the `Facebook` annotation. You can find here some information: http://restfb.com/documentation/#json-mapping-rules
