### ISSUE TITLE
Wrong data type for TargetingProductAudienceSubSpec.retetionSeconds

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#484]
If you check this:
https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-audiences/v2.5

TargetingProductAudienceSubSpec.retetionSeconds should be a number, not a string.

**Comment by hkroger** [comment]
Also, the `rule` should be some more complex structure. 

Check Audience Rules in
https://developers.facebook.com/docs/marketing-api/custom-audience-website/v2.5

**Comment by nbartels** [comment]
`retention_seconds` should be a `Long` and for `rule` a factory is needed :)
