### ISSUE TITLE
Video, Audio, and Template Attachment Support?

### ISSUE THREAD

**Issue by alexdlaird** [restfb/restfb#493]
Looks like Video and Audio attachment types are not implemented?

Template support is implemented, but not correctly. The TemplateAttachment does not properly extend a MessageAttachment, so when the WebhookObject is deserialized it fails to parse these attributes and leaves them as null.

I need this ASAP, so I'll try to fix these two issues tomorrow and get a PR for you.

**Comment by nbartels** [comment]
Hm I don't see a video or audio attachment in the reference ... but perhaps you have some more insights like in #491 :)

So I'll wait for the PR.

**Comment by alexdlaird** [comment]
I logged out to verify these docs aren't whitelisted, but I'm pretty sure they just updated them this week (if not yesterday, they look different than when I was looking at them when I commented last).

According to this link: https://developers.facebook.com/docs/messenger-platform/webhook-reference

The attachment type can be "image", "audio", "video", "file", or "location" (those last two are new to me). No examples yet of what "file" and "location" would look like, but the first three are identical; all they require is a "url" in the payload. Would it make more sense to simply have a MediaAttachment object with an enum for that type that you set when initializing?

**Comment by alexdlaird** [comment]
Okay, further clarification: I just tested all the supported types by pushing them through my webhook, and the MessagingAttachment object does actually support all "media" types. So on the receiving end, those are good. In the "send" package, however, is what I'm referring to. I propose ImageAttachment becomes MediaAttachment with the "type" being an enum with valid types.

The second issue is TemplateAttachments. These look to be supported on the "send" package, but they are not supported in the WebhookObject, so they're dropped when received. Also, per the updated documentation, there's a new type of "receipt" template's as well that need to be supported (blarg, this list is just going to keep growing, methinks): https://developers.facebook.com/docs/messenger-platform/send-api-reference#guidelines

**Comment by nbartels** [comment]
I added the #495 PR, so I close this issue.

Thanks a lot for it!
