### ISSUE TITLE
TargetingProductAudienceSubSpec serialization

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#496]
Hi,

if you serialize TargetingProductAudienceSubSpec, does it properly populate "rule" field. Based on what I saw there is code only for deserialization. However, the targetingSpec needs to be sometimes also serialized in GET parameters when you query for reach or create advertisements.

**Comment by nbartels** [comment]
Hm, okay ... puh. The recursive structure makes it hard to use the current mapping implementation. I have to think about this and find a more generic solution for such cases.
