### ISSUE TITLE
When creating catalog, you need undocumented password field

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#497]
Hi,

When you create new product feed with schedule, you need also undocumented "password" field in the object if the API requires authentication.

I have something like this at the moment:

    static class ProductFeedSchedule {
        @Facebook
        String interval;

        @Facebook
        String url;

        @Facebook
        String username;

        @Facebook
        String password;

        @Facebook
        Integer hour;

        @Facebook
        Integer minute;
    }

How should this be handled?

**Comment by hkroger** [comment]
I'm not in a hurry. I can live with my current solution until a fix is available.

**Comment by nbartels** [comment]
Okay, so I add the change to the 1.27.0
