### ISSUE TITLE
Lookalike spec has extra field origin

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#499]
Lookalike spec class has extra field origin that does not appear in FB docs:
https://developers.facebook.com/docs/marketing-api/lookalike-audience-targeting/v2.6

Maybe that was moved or something? If it is an undocumented field, that could be mentioned in the code.

**Comment by nbartels** [comment]
The field can be found in the reference: 
https://developers.facebook.com/docs/marketing-api/lookalike-audience-targeting/v2.6#read

So I think this is okay so far ...
