### ISSUE TITLE
Long Post.getLikesCount() returns null

### ISSUE THREAD

**Issue by ryancmlee** [restfb/restfb#50]
In the Docs, it says says that getLikes() could return null so you should check getLikesCount().   getLikesCount() returns null.   looking at the code, im not sure how likesCount gets set.  Maybe set the default value to 0? or change likesCount from Long to long

**Comment by bogdanlupashko** [comment]
Hello,
think this should be reopened because of :
{code}
public Long getLikesCount() {
    if (getLikes() != null) {
      return getLikes().getTotalCount();
    }

    return likesCount; 
  }

  public Long getSharesCount() {
    if (shares != null) {
      return shares.getCount();
    }
    return 0L;
  }
{code}
likesCount isn't initialized so it could return null value

**Comment by nbartels** [comment]
And you expect the value to be `0` instead?

**Comment by bogdanlupashko** [comment]
why not? 
Shares and reations already return 0 in such case
