### ISSUE TITLE
EVEN MORE Attachment Improvements (Plus Some Message Attributes)

### ISSUE THREAD

**Issue by alexdlaird** [restfb/restfb#500]
I'm only creating this ticket so you know I'll get you a PR with the new Location attachment type (improvements) and the Airline templates that were just released in the documentation yesterday. I should have the PR by Tuesday at the latest.

**Comment by alexdlaird** [comment]
Here's the new Location attachment type spec: https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-received#location_payload

Here's the airline documentation: https://developers.facebook.com/docs/messenger-platform/send-api-reference/airline-checkin-template

**Comment by alexdlaird** [comment]
Also will be adding the app_id and metadata fields to echoed messages (this is necessary for mapping between the legacy LiveChat SDK and the new Send / Receive API): https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-echo

**Comment by alexdlaird** [comment]
PR here: https://github.com/restfb/restfb/pull/503

**Comment by nbartels** [comment]
Many thanks, obviously there's a lot going on in the messenger api :smiley:
