### ISSUE TITLE
Error when sending fb smiley characters in Messenger API

### ISSUE THREAD

**Issue by bqcuong2212** [restfb/restfb#501]
When I tried to send a smiley like this grin smiley 😃 (as  _\uD83D\uDE03_) by method **FacebookClient.publish("me/messages",....)**, Facebook responded an error which notified that the content of message was empty. I tried sending an POST method manually with RestTemplate of Spring, and it worked. I think this was caused by your library. Please fix it! :D
Look forwarding to seeing your update,
Thank!

**Comment by nbartels** [comment]
Can you please provide the exact call you are using ...

**Comment by bqcuong2212** [comment]
```
		Message textMessage = new Message("\uD83D\uDE03");		
		pageClient.publish("me/messages",
				FacebookType.class,
				Parameter.with("recipient", idRecipient),
				Parameter.with("message", textMessage));
```
With the above code, I got error ```OAuthException: (#100) Invalid data (code 100, subcode null)``` from Facebook

**Comment by nbartels** [comment]
I checked this with a Post and there it is working, with the Messenger API it is not working as you already know. And I tried the smiley with the Graph API Explorer and there it depends on how I add the unicode :smile: 

Copy and paste is not working, write the unicode via keyboard is working. 

So I assume there's a general problem sending a java String with "interesting" unicodes to Facebook. It seems the signs are not converted into the unicode as expected. I have to dig deeper.

Thanks for the interesting hint.

**Comment by alexdlaird** [comment]
What's the status of this? Is it a blocker to 1.27 being released? :D

**Comment by nbartels** [comment]
Not necessarily, but it would be great to get this done. I think you need the 1.27 changes soon, so I can move the bug to the next release and deploy the 1.27 to maven soon ...

**Comment by alexdlaird** [comment]
Yah, I'm using a local build currently, but this will need to be switched a proper Maven dependency with 1.27 issues resolved before release, which we'd like to do soon. So that's why I asked.
