### ISSUE TITLE
Fallback Attachment Fails Parsing (String, Not Object)

### ISSUE THREAD

**Issue by alexdlaird** [restfb/restfb#502]
Unlike every other template payload (which is a JSON object with attributes), according to the documentation, "fallback" templates (i.e. templates that contain legacy data from deprecated APIs like LiveChat, etc.) are simply a string. I believe this is because it's not guaranteed that all legacy data will actually be in a JSON format, thus they just dump the payload of a legacy attachment into this payload.

When this is the case, JSON parsing will fail, as it's looking for an object but instead finds a string. Documentation here: https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-echo#fallback

I have verified with my Facebook contact that this documentation is correct. Not ideal, but it's what we have to work with, so the code will need to be updated so we properly parse these templates.

**Comment by nbartels** [comment]
This is part of the #503 PR, if I see it correctly. So I can close this issue with the merge of the PR?

**Comment by alexdlaird** [comment]
I don't yet have a fix for this. Just wrapping up some things currently, then it's on my plate for this afternoon or tomorrow to look into this and hopefully get a different PR. Probably we can just use the custom JSON annotations the JsonMapper uses (similar to how we parse timestamps), but ... I don't think it's going to be pretty, is the problem.

**Comment by nbartels** [comment]
I see, so I solve some of the other open issues first and have a look at this tomorrow. The `JsonMappingCompleted` annotation may help. Is used frequently... You know that there's the possibility to add a field in the json more than one time as `Facebook` annotation and let the mapper (and the user) decide what she likes to work with. The `Place` type is an example for this.

**Comment by alexdlaird** [comment]
I'm not seeing an example of this with Place.

If that is possible, that sounds like it's the best solution. The MessagingAttachment's "payload" field should resolve to either a MessagingPayload or a String. Is this possible with what you're describing?

**Comment by nbartels** [comment]
Yes. Let me write a short example:

```java 
class ObjWithFallbackParsing {

   @Facebook("complex_field")
   public String complexObjectAsString;

   @Facebook("complex_field")
   public ComplexObject complexObjectAsObj;

}
```

As you can see the Json field `complex_field` is used two times in the java object. And the DefaultJsonMapper tries to fill the `complexObjectAsString` and `complexObjectAsObj` java class fields. If one (normally the one with the ComplexObject type) cannot be mapped it would throw an exception. But if there are more than one possible mappings the mapper tries the next one. In this case it is a String and this should work. 

I think this secret is missing in the documentation or at least not clear enough explained.

**Comment by alexdlaird** [comment]
Getting closer then ... but if I put a string payload in the legacy JSON for the unit testing and change the code to this:

```
  @Getter
  @Setter
  @Facebook("payload")
  private MessagingPayload payload;

  @Getter
  @Setter
  @Facebook("payload")
  private String fallbackPayload;
```

I still get a null payload. This is because the getters and setters, I think, aren't follow the same rules.

**Comment by nbartels** [comment]
You have to use `getFallbackPayload` instead of `getPayload`. Let me try something different ...

**Comment by alexdlaird** [comment]
K, in that case, it does work. Just not super pretty :). I'll make the PR.

**Comment by nbartels** [comment]
Okay, just checked your PR and thought a bit about it. What do you think about this:

```java
public class MessagingAttachment {
...
@Facebook("payload")
  private String fallbackPayload;

  @Getter
  @Setter
  @Facebook
  private MessagingPayload payload;

  @JsonMapper.JsonMappingCompleted
  private void selectPayload() {
    if (payload == null) {
      payload = new MessagingPayload();
      payload.setFallback(fallbackPayload);
    }
  }
```

The `MessagingPayload` needs a new field fallback of type String. So you get a `MessagingPayload` and just have to fetch the fallback String from the payload. We can add a `isFallback` method to have a pretty way to decide what field should be fetched.

**Comment by alexdlaird** [comment]
Yes, I like this better. Adds more clarify, methinks.
