### ISSUE TITLE
"MessagingItem" timestamp field is always null

### ISSUE THREAD

**Issue by alexdlaird** [restfb/restfb#505]
This is also the case when running restfb tests. Looks like there's no assertion on this field to ensure this doesn't happen.

**Comment by alexdlaird** [comment]
This is part of the problem: https://github.com/restfb/restfb/blob/master/source/library/com/restfb/types/webhook/messaging/MessagingItem.java#L44

The proper serialization name "timestamp" is not given here. However, putting that there still doesn't resolve the issue. Debugged and tried stepping through it, but rawTimestamp is still always null by the time you get to the convertDate() function in MessagingItem.

**Comment by nbartels** [comment]
oh man, yes you're right and there are some more changes:

The `rawTimestamp` should be of type String and the converter method may use `DateUtils.toDateFromLongFormat`.

**Comment by alexdlaird** [comment]
It's not a long date format though, it is an epoch time. So I think a Long is a fine variable type for it.

But even if you do change it to a String, it still serializes to null. So I think there's another underlying problem.

**Comment by nbartels** [comment]
Okay, the timestamp provided in the example and in the messenger webhook reference is already the correct one and we don't need to calculate. With my change I commit in a minute, the unittest is working and the timestamp is filled correctly. 

Please check if this is working for you, too ...
