### ISSUE TITLE
AdCreative creative_id field

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#508]
Hi,

I don't find creative_id for AdCreative field in the FB docs. Is it unused field?

**Comment by nbartels** [comment]
I found the field in the Facebook lib. But perhaps it was a bug in the Facebook generator ... :)

**Comment by hkroger** [comment]
When I try to include it, the API gives an error. So maybe it's a bug?

**Comment by nbartels** [comment]
Yes, okay. So I remove it ...
