### ISSUE TITLE
Implement debugToken()

### ISSUE THREAD

**Issue by bseib** [restfb/restfb#52]
Expose the debug_token endpoint for the GraphAPI:
  https://developers.facebook.com/docs/howtos/login/debugging-access-tokens/

This function helps determine if user's tokens are expired or not, and lets you do it using your AppAccessToken, which doesn't (normally) expire.

**Comment by nbartels** [comment]
So! It's a bit late, but I implemented a new ```ScopeBuilder``` class. And enums for the different permissions. Almost all permissions are documented (at least with the information from Facebook) and I think you'll like it. 

In my opinion the *Scope* is the whole concatenated string and the *Permission* is only a single part. So a *Scope* consists of multiple *Permissions*. 

It works like that:

```java
ScopeBuilder sb = new ScopeBuilder();
sb.addPermission(UserDataPermissions.USER_ABOUT_ME);
sb.addPermission(ExtendedPermissions.READ_FRIENDLISTS);
System.out.println(sb.toString());
```
