### ISSUE TITLE
please support add and remove videos in ChangeValueFactory

### ISSUE THREAD

**Issue by LukeEchobox** [restfb/restfb#520]
Hi all, 
I love restfb, it is a really useful tool. However, I have the need to detect when my users add or remove video from their feeds. 
This behaviour results in an error : 

> Jul 18, 2016 5:16:20 PM com.restfb.types.webhook.ChangeValueFactory buildWithMapper
> WARNING: undefined change value detected
> Jul 18, 2016 5:16:20 PM com.restfb.types.webhook.ChangeValueFactory buildWithMapper
> WARNING: please provide this information to the restfb team: 
> {"verb":"add","sender_id":141048972123456,"item":"video","recipient_id":141048972123456,"post_id":"141048972123456_962581297123456","created_time":1454177675} 

am I missing something? Maybe a equivalent to ChangeValueEnumeration.FEED_PHOTO_REMOVE **but for videos**? 

any help , advice or update would be fantastic.

Many thanks 
luke (echobox.com)

**Comment by nbartels** [comment]
Issue #513 may solve your problem. I'll check this asap.

**Comment by LukeEchobox** [comment]
thanks nbartels, this is exactly what I needed. 
Any ETA on the merge?

**Comment by nbartels** [comment]
Yes, the PR is merged a second ago 😄

**Comment by nbartels** [comment]
Can you please provide the json that is sent on video remove? So I can this to the values, too. ATM only add is supported.

**Comment by nbartels** [comment]
Okay, because I'd like to publish the release today, I move your Issue to the next one. So the Graph API 2.7 support is available for all and half of your issue is solved, too.

As soon as you send me the json I can add the "Remove".

**Comment by LukeEchobox** [comment]
Hi , sorry for the late reply. 
Here you go: 
feed-video-remove.json
```
{
  "entry": [
    {
      "changes": [
        {
          "field": "feed",
          "value": {
            "recipient_id": 141041234567891,
            "post_id": "141041234567891_1072871234567891",
            "sender_id": 141041234567891,
            "item": "post",
            "verb": "remove",
            "created_time": 1468860467
          }
        }
      ],
      "id": "14101234567891",
      "time": 1468860471
    }
  ],
  "object": "page"
}

```
if you need anything more please don't hesitate to ask. :)

**Comment by LukeEchobox** [comment]
Hi , sorry for the late reply. 
Here you go: 
feed-video-remove.json
```
{
  "entry": [
    {
      "changes": [
        {
          "field": "feed",
          "value": {
            "post_id": "141041234567891_1072871234567891",
            "sender_name": "senderTest",
            "video_id": 1072871234567891,
            "sender_id": 141041234567891,
            "item": "video",
            "verb": "remove",
            "link": "https://video.test.net/v/test.mp4"
          }
        }
      ],
      "id": "141041234567891",
      "time": 1468859757
    }
  ],
  "object": "page"
}

```
if you need anything more please don't hesitate to ask. :)

**Comment by LukeEchobox** [comment]
sorry, Json provided  above is incorrect . 
The actual Json which is returned when a video is removed from a users feed is.
```
{
  "entry": [
    {
      "changes": [
        {
          "field": "feed",
          "value": {
            "recipient_id": 141041234567891,
            "post_id": "141041234567891_107331234567891",
            "sender_id": 141041234567891,
            "item": "post",
            "verb": "remove",
            "created_time": 1468922715
          }
        }
      ],
      "id": "141041234567891",
      "time": 1468922716
    }
  ],
  "object": "page"
}
```
or deleted from "videos" is 

```
{
  "entry": [
    {
      "changes": [
        {
          "field": "feed",
          "value": {
            "recipient_id": 141041234567891,
            "post_id": "141041234567891_1073311234567891",
            "sender_id": 141041234567891,
            "item": "post",
            "verb": "remove",
            "created_time": 1468922919
          }
        }
      ],
      "id": "141041234567891",
      "time": 1468922920
    }
  ],
  "object": "page"
}

```
I believe this is already supported though, so maybe there is no need for a feed_remove_video. 
my apologies again 
thanks
Luke

**Comment by nbartels** [comment]
Ah I see. It's a feed post remove. So this is already supported and I can close this issue. Adding a video is supported with 1.28.0.

**Comment by LukeEchobox** [comment]
Yep, thanks for everything. 
Amazing that there was already a PR for my issue. 
All the best
Luke
