### ISSUE TITLE
jsonObject.keys() as Iterator<String>

### ISSUE THREAD

**Issue by leandroutn** [restfb/restfb#526]
Hello,

Since `jsonObject.keys()` returns `Iterator<?>`, we need to add logic to check the key type. Can you make it return `Iterator<String>`? or there's some implication that I'm not aware of?

Thanks

**Comment by nbartels** [comment]
I think this is a modification of an older Json.org implementation and I just checked the newest and it has already the typed Iterator. 

I'll try to change this and let the unittests check if there's a problem. I think the json keys should be a String anyway ...
