### ISSUE TITLE
com.restfb.types.Payment contains an unknown field "product"

### ISSUE THREAD

**Issue by fmachado** [restfb/restfb#527]
As you can see in this bug report https://developers.facebook.com/bugs/595368380634100/, the field "product" does not exists.

I would like to submit a PR but I'm not sure how restfb team would deal with this API change: remove the attribute from the Payment class as it never worked properly or take a more safe approach and just "@deprecate" it.

**Comment by nbartels** [comment]
Thanks for the PR. Normally we set methods and fields to deprecated, but the marketing API is still new and in the flow. So it's okay to remove buggy things directly.
