### ISSUE TITLE
getCoverPhoto() of Album returns JSON object instead of ID

### ISSUE THREAD

**Issue by torbenw** [restfb/restfb#543]
The JSON response for a photo album changed after Graph API version 2.3. 

2.3:
https://graph.facebook.com/v2.3/.../albums?limit=100&access_token=...&format=json
=>
`"cover_photo": "1234567890123456"`

2.4+:
https://graph.facebook.com/v2.7/.../albums?limit=100&fields=cover_photo&access_token=...&format=json
=>
```
"cover_photo": {
  "created_time": "2016-07-06T14:33:46+0000",
  "name": "A name!",
  "id": "1234567890123456"
}
```

The doc of the method getCoverPhoto() is:
```
  /**
   * The album cover photo ID.
   * 
   * @return The album cover photo ID
   */
```

This is incorrect when using a Graph API version newer than 2.3.

**Comment by nbartels** [comment]
okay, I see. So we have to implement a switch ...
