### ISSUE TITLE
Add toString() method to webhook classes

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#544]
For debugging it would be nice to add proper `toString()` methods to the webhook classes like:

- `com.restfb.types.webhook.WebhookEntry`
- `com.restfb.types.webhook.WebhookObject`
- `com.restfb.types.webhook.messaging.MessagingItem`
- `com.restfb.types.webhook.messaging.MessageItem`
- `..`

Maybe these classes can just extend `AbstractFacebookType` like `SendResponse` does or otherwise directly use `ReflectionUtils.toString(this)` instead.

**Comment by nbartels** [comment]
Yes, okay. We will add a super type with a toString method. I'm unsure about the `AbstractFacebookType,` but we'll find a good solution soon :)

**Comment by nbartels** [comment]
The Project Lombok lib provides a `ToString` annotation and I suggest to add it to the webhook classes. Not that much overhead in the code, no additional super class. And the feature is already and waits to be used :smile:
