### ISSUE TITLE
Webhook does not yet support Account Linking

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#546]
See https://developers.facebook.com/docs/messenger-platform/webhook-reference/account-linking

**Comment by marceloverdijk** [comment]
@nbartels is this change published in a snapshot release accessable via Maven/Gradle?

**Comment by nbartels** [comment]
No, we don't provide Snapshot releases. The next version will be published soon and in the meantime, you have to build a custom version.

**Comment by marceloverdijk** [comment]
Ok no problem. I will build a custom version.

**Comment by nbartels** [comment]
Or take the just release 1.30.0 😄

**Comment by marceloverdijk** [comment]
👍 great will do 😀
