### ISSUE TITLE
Provide page-level rate limiting header

### ISSUE THREAD

**Issue by kukido** [restfb/restfb#548]
Looks like although RestFB provides app-level rate limiting header, it is missing page-level rate limiting header. Would be great to have one available.

https://developers.facebook.com/docs/graph-api/advanced/rate-limiting

**Comment by kukido** [comment]
Added a PR. Please review.

**Comment by matthewbogner** [comment]
+1

**Comment by kukido** [comment]
Hi @nbartels, thank you for super-quick turnaround! Do you have an estimate when 1.30 will be released and pushed to Maven central?

**Comment by nbartels** [comment]
I pushed it just now, so it will in maven central soon.

**Comment by wiliamsilva** [comment]
Hi. Is it possible to get "x-app-usage" when I am logged in as an user (via user access token)? I tried to do that, but it does not work. My restfb release is "restfb-1.30.0.jar" and my code:
`		Connection<JsonObject> dataList = fbClient.fetchConnection("me/permissions", JsonObject.class);

		WebRequestor wr = fbClient.getWebRequestor();
		
		DebugHeaderInfo dhi =  wr.getDebugHeaderInfo();
		
		System.out.println(dhi.getAppUsage());`

The result of print: []

**Comment by kukido** [comment]
@wiliamsilva your code is correct. And per Facebook documentation: "There is no header if the Page's utilization is effectively 0%."
I just tried it, and with low utilization pages we get no header back, and for some we get one.

**Comment by wiliamsilva** [comment]
Thank @kukido. Even then my app is desktop to publish on public groups that I am member. My app made less than 200 calls per hour and wait 30 seconds before a new call. Then Facebook launchs:

```
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: It looks like you were misusing this feature by going too fast. You’ve been blocked from using it.

Learn more about blocks in the Help Center. (code 368, subcode 1390008)
```
Facebook recommends to catch the error code 4 and that code warns if you hit these limits in "Application-Level Rate Limiting": https://developers.facebook.com/docs/graph-api/advanced/rate-limiting

... but the error code 4 does not occur.

Now I'm trying to solve the error code 368 by header attribute X-App-Usage.

**Comment by nbartels** [comment]
It seems that the error code 368 has nothing to do with the rate limiting but with publishing too much or content Facebook don't like:

Check this here: http://stackoverflow.com/questions/11372890/oauthexception-368-the-action-attempted-has-been-deemed-abusive-or-is-otherwi

**Comment by wiliamsilva** [comment]
@nbartels  You are in right. Error 368 refers to links in my publication are out of domain configured in my FB application. Facebook requires post links have the same domain of application.

After change all links to the correct domain, it is working fine!

Thanks @nbartels and @kukido!
