### ISSUE TITLE
When fetch user by id the property gender is null

### ISSUE THREAD

**Issue by faelperetta** [restfb/restfb#551]
When I try to fetch user in this way:

`User facebookUser = facebookClient.fetchObject(String.valueOf(userId), User.class, Parameter.with("fields", "name,gender,picture"));`

**facebookUser.getGender()** is returning null

But, when I try this:
`User facebookUser = facebookClient.fetchObject("me", User.class, Parameter.with("fields", "name,gender,picture"));`

**facebookUser.getGender()** returns the expected value

**Comment by nbartels** [comment]
Is `userId` and `me` pointing to the same user?

**Comment by faelperetta** [comment]
Yep, I'm pointing to the same user

**Comment by nbartels** [comment]
You can validate the request in the Graph API Explorer. If it also happens there, you should open a bug report on Facebook.

**Comment by faelperetta** [comment]
I checked it and it's not happening there

**Comment by revetkn** [comment]
So what you are observing is that you get identical JSON from Graph API Explorer for `me` and `userId`, but when you query using RestFB you receive different JSON?  If so, can you enable logging to see the raw requests RestFB is making?  Also, I am curious if your access token is the same for Graph Explorer as it is when using RestFB.

**Comment by faelperetta** [comment]
I was using the same access token, but  I tested again in facebook graph explorer and I have the same problem there. I will open a bug report on Facebook.

**Comment by nbartels** [comment]
Okay, great. So I close this issue here...
