### ISSUE TITLE
Missing send types for Sender Actions

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#553]
I'm missing send types in `com.restfb.types.send` for the Sender Actions: https://developers.facebook.com/docs/messenger-platform/send-api-reference/sender-actions

**Comment by nbartels** [comment]
Not really :)

just do:
```java
IdMessageRecipient recipient = new IdMessageRecipient("<userID>");
FacebookClient pageClient = new DefaultFacebookClient(pageAccessToken, Version.VERSION_2_6);

SendResponse resp = pageclient.publish("me/messages", SendResponse.class,
     Parameter.with("recipient", recipient), // the id recipient
	 Parameter.with("sender_action", "typing_on")); // typing on (e.g.)
```

**Comment by marceloverdijk** [comment]
Yes, that's what I did, but maybe it's useful to have an `Enum` for that? Just like the `notification_type`.. But I can understand to choose not. Pls close issue if you think it's not worth it.

**Comment by nbartels** [comment]
hm, okay. Let's think about this :smile:

**Comment by marceloverdijk** [comment]
I will be off on holiday shortly but the project is shaping up nicely though.

Implementing a message webhook and sending a response would look like:

```
public class EchoHandler {

    @OnMessage
    public void echo(Chatbot chatbot, MessagingParticipant sender, MessageItem message) {
        IdMessageRecipient recipient = new IdMessageRecipient(sender.getId());
        chatbot.send().markSeen(recipient);
        chatbot.send().typingOn(recipient);
        chatbot.send().textMessage(recipient, "Echo: " + message.getText());
        chatbot.send().typingOff(recipient);
    }
}
```

**Comment by nbartels** [comment]
@marceloverdijk I added the enum type and checked how the `Parameter` is working with enums. I think this is okay so far and we have to add the information to our documentation ...

**Comment by marceloverdijk** [comment]
Thanks!

**Comment by marceloverdijk** [comment]
Hi @nbartels to check locally I think it's best to checkout the `dev` branch right?
Is there a reason the version in `master` and `dev` is pointing to `1.30.0` instead of `1.31.0-SNAPSHOT`?

**Comment by nbartels** [comment]
@marceloverdijk yes your right, in the `dev` branch you'll find the latest changes. `master` is the latest published version. 

We ignored the snapshot for now, because we use a mix of ant and maven. It was not a major topic to generalise the build system. But I think we should invest some time.

**Comment by marceloverdijk** [comment]
The problem with 1.30.0 in the pom is that when I build it locally it will overwrite the real 1.30.0... which could give some serious problems with projects depending on the real 1.30.0... hence the snapshot.
I thinks it's wise to change the development version after a new release.
