### ISSUE TITLE
[Proposal] Retrieving X-App-Usage HTTP header

### ISSUE THREAD

**Issue by huymluu** [restfb/restfb#554]
Should we add some mechanism to get info about API call rate, to prevent rate limiting?

Reference: [https://developers.facebook.com/docs/graph-api/advanced/rate-limiting](https://developers.facebook.com/docs/graph-api/advanced/rate-limiting)
(section "Rate limiting header")

**Comment by nbartels** [comment]
If you have a FacebookClient client you call this:

```java
DebugHeaderInfo dhi = client.getWebRequestor().getDebugHeaderInfo();
System.out.println("App usage: " + dhi.getAppUsage());
System.out.println("Page usage: " + dhi.getPageUsage());
```

The issue here is the missing documentation on the restfb page.
