### ISSUE TITLE
FacebookPermissions package privacy issues

### ISSUE THREAD

**Issue by rhino88** [restfb/restfb#555]
A couple of inconveniences to bring to your attention regarding the package access restriction on [FacebookPermissions](https://github.com/restfb/restfb/blob/master/source/library/com/restfb/scope/FacebookPermissions.java).

I'm currently unable to use [UserDataPermissions](https://github.com/restfb/restfb/blob/master/source/library/com/restfb/scope/UserDataPermissions.java)/[ExtendedPermissions](https://github.com/restfb/restfb/blob/master/source/library/com/restfb/scope/ExtendedPermissions.java) in stream operations. For example, this throws a Runtime Exception:

```
public void foo() {
   final ScopeBuilder scopeBuilder = new ScopeBuilder();

   Set<UserDataPermissions> scopes = getScopes();
   scopes.stream().forEach(scopeBuilder::addPermission)
}
```

It is also inconvenient when using an ORM which stores `enum` values as Strings, because you will unnecessarily have to have two fields in your Java model, instead of one if I need both Extended and UserData Permissions.

Would you consider making `FacebookPermissions` a public interface?

**Comment by nbartels** [comment]
Ah, I see. 

You can change the `forEach` to this:
```java
```
