### ISSUE TITLE
Facebook partnerdata API

### ISSUE THREAD

**Issue by nemccarthy** [restfb/restfb#562]
Hi guys,

This SDK is really handy however its missing one big feature, if we want to upload data to the `/act_<AD_ACCOUNT_ID>/partnerdata` endpoint its not supported. Are there plans to add this one in?

Thanks!

**Comment by nbartels** [comment]
Thanks!

Can you send us a link to the endpoint reference?

**Comment by nemccarthy** [comment]
Here; https://developers.facebook.com/docs/marketing-api/data-partners-api

The API docs are locked down so only certain partners can see them.

**Comment by nbartels** [comment]
That's a problem, because it's hard to implement features that are not available to me. I can only create new types if I can see the structure or at least the documentation...

**Comment by nbartels** [comment]
@nemccarthy do you think you can provide the API description as (for example) PDF files. You may send us the files privately if you don't like to post the information here.

If this is not possible I have to close this issue, because I cannot access the private information ... :worried:

**Comment by nbartels** [comment]
I'll close this now, because it is unlikely we get access to the API documentation. If someone can provide it. He/she may mail it or add it here. I'll open the bug then ...
