### ISSUE TITLE
Update QuickReply after Facebook Messenger changes Sep 12

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#566]
In the latest Facebook Messenger update of Sep 12 quick replies have been changed.

https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies

Not only images are supported now (via new `image_url` attribute) also a `location` content type is possible.

Note that the `com.restfb.types.send.QuickReply` does not yet support the `image_url` and also there is only a `QuickReply(String contentType, String title, String payload)` constructor.
E.g. in case of the location quick reply, no title or payload is needed.

Example:
```
curl -X POST -H "Content-Type: application/json" -d '{
  "recipient":{
    "id":"USER_ID"
  },
  "message":{
    "text":"Please share your location:",
    "quick_replies":[
      {
        "content_type":"location",
      }
    ]
  }
}' "https://graph.facebook.com/v2.6/me/messages?access_token=PAGE_ACCESS_TOKEN"
```

Maybe there also other changes as well as part of the Sep 12 update..

**Comment by nbartels** [comment]
Oh great, thanks. I'll have to check the changes ...

**Comment by marceloverdijk** [comment]
OK, let me if I can help.
I'm also particularly interested in https://github.com/restfb/restfb/issues/544

**Comment by nbartels** [comment]
For now you can simply use `new QuickReply("location", null, null)`.

With the next RestFB version this is still possible but marked as deprecated. The new version provides two constructors: `new QuickReply()` and `new QuickReply("title","payload")`.

This should be sufficient. You're right, the issue #544 is still open.

Is there way to get informed about new versions?

**Comment by marceloverdijk** [comment]
I'm on the Facebook Messenger group on Facebook which is the best way to get 'notified' I think...

Thx for the change, looking forward to next release!
