### ISSUE TITLE
Inconsistent paging results fetching invitable_friends

### ISSUE THREAD

**Issue by davehrdng** [restfb/restfb#572]
Hi,

I am using RestFB and I am not sure if what I am seeing is a problem with Facbook's API, how I am using it, or restFB. 

All I am doing is trying to fetch all the names of Invitable Friends for a particular user. I am iterating through the collection. I have written a simple test class to prove what I see.

I get inconsistent results, with pages sometimes being 'missed out', and sometimes being duplicated. If I run the example below on an AccessKey generated for myself, I should get 266 invitable_friends. If I run it looped 10 times, I get varying results of 340, 266, 266, 216, 373, 216, 266, 216, 216, 329.

Any help in understanding what is going on appreciated.

Test code: [Need to replace the AccessKey with a valid one obvs.]

``` java
/**
 * 
 */
package restFB_Paging_Bug;

import java.util.List;
import com.restfb.Connection;
import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.Version;
import com.restfb.exception.FacebookOAuthException;

/**
 * @author dave
 *
 */
public class RestFBPagingBug {

    private String accessToken;

    /**
     * 
     */
    public RestFBPagingBug(String accessToken) {
        this.accessToken = accessToken;
    }

    public void test(){

        Connection<com.restfb.types.User> myInvitableFriends = null;        
        FacebookClient fbClient = new DefaultFacebookClient(accessToken, Version.VERSION_2_7);
        String fbfriendName;

        try{
            myInvitableFriends = fbClient.fetchConnection("me/invitable_friends", com.restfb.types.User.class);
        }catch(FacebookOAuthException fe){
            System.out.println("Failed to connect to Facebook");
        }

        if(myInvitableFriends != null){

            int numInvitableFriends=0;

            for(List<com.restfb.types.User> userList : myInvitableFriends){
                for(com.restfb.types.User fbfriend : userList){

                    fbfriendName = fbfriend.getName();

                    ++numInvitableFriends;
                    // System.out.println("Invitable Friend found: "+fbfriendName+" number: "+numInvitableFriends);

                }
            }

            System.out.println("Invitable Friends found: "+numInvitableFriends);

        }else{
            System.out.println("Something went wrong connecting to Facebook");
        }


    }



    /**
     * @param args
     */
    public static void main(String[] args) {

        String at = "**********";
        RestFBPagingBug obj = new RestFBPagingBug(at);
        for(int i=0; i<10; i++){
            obj.test();
        }
    }

}
```

**Comment by nbartels** [comment]
Okay. Perhaps you can try something different to calculate the size of the `invitable_friends`. Create a HashSet and put the fbfriend.getId() in this set. So you should remove duplicates automatically. 

Print the numInvitableFriends and the HashSet size. So you can see if there is a difference. A difference means in that case that a friend is present on 2 or more pages.

In general, we only work with the information Facebook provides via the API. If you see such a fluctuation, it is highly possible you discovered a Graph API Bug ;)

**Comment by nbartels** [comment]
No further feedback received, perhaps this is solved. In case of ... we will open it again.
