### ISSUE TITLE
Consider adding Messenger Thread Settings types

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#574]
Please consider adding types for the Messenger Thread Settings:
https://developers.facebook.com/docs/messenger-platform/thread-settings
E.g. to set a persistent menu with MenuItem's etc.

I also wonder which Response can be used for e.g. the result from https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

```
{
  "result": "Successfully added new_thread's CTAs"
}
```

For the Send Api I'm using the restfb SendResponse return type.

**Comment by nbartels** [comment]
Do you know what's returned if the thread settings are not "successfully" added?

**Comment by marceloverdijk** [comment]
Hi @nbartels 

See below what I'm getting for setting e.g. the greeting.

Request:
```
curl -X POST -H "Content-Type: application/json" -d '{
  "setting_type":"greeting",
  "greeting":{
    "text":"Hi {{user_first_name}}, welcome to the bot!"
  }
}' "https://graph.facebook.com/v2.6/me/thread_settings?access_token=<MY_ACCESS_TOKEN>"
```

Response: 

```
{"result":"Successfully updated greeting"}
```

When I make a request with `"test":null` I get back a `400` response with:

```
{"error":{"message":"(#100) A greeting message is missing.","type":"OAuthException","code":100,"fbtrace_id":"Dh2y4A3wGrL"}}
```

**Comment by nbartels** [comment]
So we get a "normal" error. Then it should be possible to improve the `SendResponse`
