### ISSUE TITLE
Problem when converting location using toJson

### ISSUE THREAD

**Issue by vido88** [restfb/restfb#583]
Hi guys,

I have a problem when I convert a Post object that has a location, using toJson method in DefaultJsonMapper class.  

The response from facebook is :

```json
{
"place": {
    "name": "Milano Cafe",
    "location": {
      "city": "Milan",
      "country": "Italy",
      "latitude": 45.4831009,
      "longitude": 9.1700497,
      "street": "Via Procaccini 37",
      "zip": "20100"
    },
    "id": "315222948535906"
  }
```
while the method returns
```json
"place": {
		"location": "{\"zip\":\"20100\",\"country\":\"Italy\",\"city\":\"Milan\",\"street\":\"Via Procaccini 37\",\"latitude\":45.4831009,\"longitude\":9.1700497}",
		"name": "Milano Cafe",
		"id": "315222948535906"
	}
```
treating the value of the location like a single string, instead of a json.

Could you please fix this ?

I hope I was clear, thanks in advance,
Paolo

**Comment by nbartels** [comment]
Do you use `getPlace().getLocation()` or `getPlace().getLocationAsString()` ?

**Comment by vido88** [comment]
No, I do something like this :
```java 
final List<Post> posts = feedConnection.getData();
for (Post post : posts) {                     String xxx = jsonMapper.toJson(post, true);
}`

**Comment by vido88** [comment]
No, I do something like this
```java
[...]
final JsonMapper jsonMapper = new DefaultJsonMapper();
final List<Post> posts = feedConnection.getData();
for (Post post : posts) {
      String postAsJson = jsonMapper.toJson(post, true);
      log.info("post as json is :: " + postAsJson );
[...]
}
```
and I expect 

```json
...
{
"place": {
    "name": "Milano Cafe",
    "location": {
      "city": "Milan",
      "country": "Italy",
      "latitude": 45.4831009,
      "longitude": 9.1700497,
      "street": "Via Procaccini 37",
      "zip": "20100"
    },
    "id": "315222948535906"
  }
...
```

but I get 

```json
...
"place": {
        "location": "{\"zip\":\"20100\",\"country\":\"Italy\",\"city\":\"Milan\",\"street\":\"Via Procaccini 37\",\"latitude\":45.4831009,\"longitude\":9.1700497}",
        "name": "Milano Cafe",
        "id": "315222948535906"
    }
...
```

Like I said, it seems that the value of field location is not treated as a nested json object (like place), but as a single string.

Paolo

**Comment by nbartels** [comment]
Ah, okay. So you convert an JSON to object and back to JSON. The Post object is not intended to be used like that. Can you explain why you need this? Just for logging/debugging?

**Comment by vido88** [comment]
My code uses Post object to filter on some fields (e.g. date or postId or messageTags), without parsing the Json, and then converts the Post object back to Json, and passes it to another software that needs the original format. I know it may sound strange, but we don't want to add logic to the other software.

Let me know if it's possibile to convert location in the right way, or if I need to implement my own Mapper.

Thanks in advance,
Paolo

**Comment by nbartels** [comment]
okay, I see. So what about this idea:

```java
FacebookClient client = new DefaultFacebookClient(token, Version.LATEST);
Connection<String> stringConnection  = client.fetchConnection("me/feed", String.class);
List<String> stringList = stringConnection.getData();
JsonMapper mapper = new DefaultJsonMapper();
for (String stringItem : stringList) {
    Post post = mapper.toJavaObject(stringItem, Post.class);
    // do something with Post object ...
            
    // print json
    System.out.println(stringItem);
}
```

The posts are fetched as `String` and mapped in the for-loop to a `Post` object. You can filter work with this object and use the original JSON from Facebook and send it to the next system. 

Can you please give some feedback if this is sufficient ...

**Comment by vido88** [comment]
Ok, that looks fine; I didn't notice that even with Connection<String> i could get the list of post.

Thanks for your support, 
Paolo
