### ISSUE TITLE
Wrong appsecret_proof created by EncodingUtils

### ISSUE THREAD

**Issue by mchmielarz** [restfb/restfb#586]
Call on `com.restfb.util.EncodingUtils.encodeAppSecretProof` creates wrong appsecret_proof. It is caused by providing a charset in this line:
`byte[] raw = mac.doFinal(accessToken.getBytes(Charset.forName("UTF-8")));`
Without charset provided the appsecret_proof is correct.

I have found it duplicates the same logic from `DefaultFacebookClient.obtainAppSecretProof`, so it should be deleted maybe.

**Comment by nbartels** [comment]
I just added this test case locally and it works.

```java
@Test
  public void encodeAppSecretProof() {
    String message = "Just a short Test message";
    String secret = "342314a43e";
    String expected = "322db18096e205ee3b3fef0a540e5566ac41f7631d5b84add759081814583897";

    try {
      String actualChecksum = EncodingUtils.encodeAppSecretProof(secret, message);
      assertEquals(expected, actualChecksum);
    } catch (Exception e) {
      fail("Something went wrong");
    }
  }
```

The checksum was calculated here: http://www.freeformatter.com/hmac-generator.html

So I think it cannot be the UTF-8 in general. Perhaps this depends on the input. Can you please check this and provide your obfuscated input.

Thanks for the duplication hint, as soon as we solved the wrong checksum issue I'll use the `EncodingUtils` method in the `DefaultFacebookClient`

**Comment by mchmielarz** [comment]
Ok, it can be correct, but when I used checksum generated by `EncodingUtils`, call to Facebook ended with an error. On the other hand, with checksum provided by `DefaultFacebookClient` everything worked as expected.

**Comment by mchmielarz** [comment]
This is the message I got from FB after making a call with `appsecret_proof` created by `EncodingUtils`: `Invalid appsecret_proof provided in the API argument`

**Comment by nbartels** [comment]
Okay. I'll check why we added the method in the utilities. And perhaps this will solve the problem. :smile:
