### ISSUE TITLE
MultiBubble issue in Messenger API 

### ISSUE THREAD

**Issue by vraffy** [restfb/restfb#593]
As I originally reported in https://github.com/restfb/restfb/issues/592, I am experiencing issues in sending a "generic message" using the Messenger API.

Here you can find a code example:

```java
@Test
public void testSendGenericMessage() {
  
    final String accessToken = "<my access token>";
    final FacebookClient facebookClient = new DefaultFacebookClient(accessToken, Version.VERSION_2_6);
    final IdMessageRecipient recipient = new IdMessageRecipient(<recipient id>);

    final GenericTemplatePayload payload = new GenericTemplatePayload();

    // create a bubble with a web button
    final Bubble firstBubble = new Bubble("Organization info");
    final WebButton webButton = new WebButton("ACME", "http://www.acme.org");
    firstBubble.addButton(webButton);
    payload.addBubble(firstBubble);

    // create a bubble with a postback button
    final Bubble secondBubble = new Bubble("Links");
    final PostbackButton postbackButton = new PostbackButton("contact us", "contact request");
    secondBubble.addButton(postbackButton);
    payload.addBubble(secondBubble);

    final TemplateAttachment templateAttachment = new TemplateAttachment(payload);
    final Message templateMessage = new Message(templateAttachment);

    final SendResponse resp = facebookClient.publish("me/messages", SendResponse.class,
            Parameter.with("recipient", recipient),
            Parameter.with("message", templateMessage));

    System.out.println(resp);
}
```

When I send this message, in the recipient chat I can only see the first bubble (web button).
If I comment out the `payload.addBubble(firstBubble);` line, I can see the second bubble in the chat.
It looks like only one of the two bubbles is really sent.
Or am I doing something wrong?

I am using restfb version 1.31.0 (from Maven repository) with Facebook API version 2.6.

**Comment by nbartels** [comment]
Okay, I took the code above and add it to my test chatbot. 

I received the bubbles and both are there, but only on mouse over I can switch between them. On the first look it seems that only one bubble is there.

You can see the "Li" on the right corner:
![bubble1](https://cloud.githubusercontent.com/assets/1113969/19205862/3f1d08e6-8ce5-11e6-8594-d6a1f489955a.jpeg)

In the second bubble, there is only a part of the title line in the left corner.
![bubble2](https://cloud.githubusercontent.com/assets/1113969/19205863/40e45bf2-8ce5-11e6-8eb0-9bf27034a5df.jpeg)

**Comment by vraffy** [comment]
Yes, you are right!
Now that you have made me notice it, I can see a little right arrow when I put my mouse over the first bubble. If I click on it I can see the second bubble with a little left arrow pointing back to the first one.

In effect, by reading better the Facebook API documentation I have found this line:
> Use the Generic Template with the Send API to send a **horizontal scrollable carousel** of items

Hence, it is not a bug, it is a feature :)

Thank you very much for your support.

**Comment by nbartels** [comment]
ok, great. Hopefully the users notice this... 😉

**Comment by vraffy** [comment]
> ok, great. Hopefully the users notice this...
Perhaps it could be useful to mention that line from the Facebook API documentation inside your "Generic Message" documentation example, so that inattentive users (like me) would avoid reporting it as a bug ;)
