### ISSUE TITLE
Getting UserID and not just UserNames from Likes

### ISSUE THREAD

**Issue by brandon-tingley** [restfb/restfb#595]
Unless I'm doing this all wrong -- which is entirely possible -- it doesn't seem possible to get a user Id from a "like" on a post, only a user name -- which don't have to be unique. I ran into the same issue with facebook4j as well. Judging from facebook itself, it would seem like this information should be available somewhere...

**Comment by nbartels** [comment]
Can you provide the snippet you are using and in which Graph API version the problem occurs?

**Comment by brandon-tingley** [comment]
Yes, it was a Graph API version issue. I'm new at this :) Thanks...
