### ISSUE TITLE
Post video with "file_url"

### ISSUE THREAD

**Issue by Hao-Wu** [restfb/restfb#606]
According to [the video-uploads API](https://developers.facebook.com/docs/graph-api/video-uploads) description:

![image](https://cloud.githubusercontent.com/assets/860738/19514785/7c9efb20-9627-11e6-9431-9fc1663f3bee.png)

does restfb support post video in this way of 
POST `/{user-id}/videos` with file_url = http://www.some_video_storage_cloud.com/video_url
or 
POST `/me/videos` with file_url = http://www.some_video_storage_cloud.com/video_url

With the file_url, server doesn't need to make file stream and upload to facebook server. Video data is retrieved by facebook from some other video storage server.

**Comment by Hao-Wu** [comment]
Just tried it and it works!

A quick example here:

```java
String publishVideo() {
    out.println("***Start to upload video***");

    FacebookType publishVideoReponse = facebookClient.publish(
            "me/videos",
            FacebookType.class,
            Parameter.with("file_url","http://example.com/12345.mp4"),
            Parameter.with("title", "Title of testing video"),
            Parameter.with("description", "Description of  testing video")
    );

    out.println("***End of upload video***");
    out.println(format("***Facebook Video ID returned: %s ***",  publishVideoReponse.getId()));
    return publishVideoReponse.getId();
}
```

**Comment by nbartels** [comment]
Yes, I'll add this (or a similar) example to the documentation ...
