### ISSUE TITLE
Consider a Recipient interface

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#612]
It would be useful that both `PhoneMessageRecipient` and `IdMessageRecipient` implement a generalized `Recipient` interface.

**Comment by nbartels** [comment]
But that's only a marker interface, they don't have a method in common. They even don't have a method ;)

**Comment by marceloverdijk** [comment]
Correct!

But it allows method signatures like:

```
public void sendMessage(Recipient recipient, String text) { .. }
```

Now I have basically have to use 2 methods, one with a `PhoneMessageRecipient` and one with a `IdMessageRecipient `.

**Comment by marceloverdijk** [comment]
Thanks a lot! Now I can simplify my method signatures drastically.
Are you planning 1.34.0 soon?

**Comment by nbartels** [comment]
I'd like to collect some more improvements before releasing the new version. In about two weeks this should be possible.

**Comment by marceloverdijk** [comment]
Ok 👍  fair enough, will work on local 1.34.0-SNAPSHOT for now
