### ISSUE TITLE
deleteObject only checking on "true" string

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#618]
I'm trying to use the `#deleteOject` method to remove the Messenger Platform greeting like:

```
facebookClient.deleteObject(
                "me/thread_settings",
                Parameter.with("setting_type", SettingTypeEnum.greeting));
```

This seems to work and I get the following json response back from Facebook:
`{"result":"Successfully deleted greeting"}`

(I checked this by debugging https://github.com/restfb/restfb/blob/master/source/library/com/restfb/DefaultFacebookClient.java#L340) 

The `#deleteObject` explicitly checks on a `success` field (which is not there; only a `result` field when removing the thread settings) and that the `success` field's value equals `true`.

So currently I cannot use the `#deleteObject` for the thread settings; at least not in a way to let it return success is `true`..

The response Facebook is sending for removing the thread settings (just sending a json with a `result` message) deviates from the other responses.

Maybe the `#deleteObject` can check for the `result` field when the `success` field is not available. But still the actual result message is different per thread setting. Note the message 'Successfully deleted **greeting**'.

**Comment by marceloverdijk** [comment]
@nbartels if this `#deleteObject` fails, e.g. a 400 with an error does it throw e.g. a `FacebookOAuthException`
In that case I can ignore the `boolean` result from the `#deleteObject` method in case the greeting removal only returns `Successfully deleted greeting` (which I need to verify)

**Comment by nbartels** [comment]
Yes I think so, at least this is how it works on "normal" Graph API calls. Would be nice to catch the exception and return `false`, but which exception is thrown and what are possible reasons for not deleting an object is not 100% clear. So this is the safe way ;)

**Comment by marceloverdijk** [comment]
Let's see if we get some info on the FB group :-)
If they only return a `200` with the `result` json if the call was successful, then I can abstract the boolean away for the thread settings.
I'm now returning the boolean but it feels bad, as it can return `false` or throw a `FacebookException`.
