### ISSUE TITLE
Messenger Platform: List Template

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#620]
https://developers.facebook.com/docs/messenger-platform/send-api-reference/list-template

**Comment by marceloverdijk** [comment]
Please don't forget the `template_type` and `top_element_style` enum types ;-)

**Comment by nbartels** [comment]
`template_type` is not necessary because it is set only internally by using the right payload object, but the `top_element_style` enum is already there 😄

**Comment by marceloverdijk** [comment]
Good :-)
