### ISSUE TITLE
Messenger Platform: Checkbox plugin

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#622]
https://developers.facebook.com/docs/messenger-platform/plugin-reference/checkbox-plugin

It seems the Optin callback now also includes a `user_ref ` param.
But also note that in that case the `sender` and `sender.id` are not included.

This `user_ref` can then be used to send a message, so probably a new `UserRefMessageRecipient` is needed? They also mention that in that case the response includes the `recipient_id `.

**Comment by nbartels** [comment]
okay thx, I'll have a look at that.
