### ISSUE TITLE
Messenger Platform: messaging_referral event

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#623]
Besides the new `referral` as part of the already existing `postback` event, also a complete new `messaging_referral` event was added in the latest messenger platform update.

See https://developers.facebook.com/docs/messenger-platform/referral-params 2. Existing User Scenario

**Comment by nbartels** [comment]
okay, so we have to support jsons like this

```javascript
{
  "sender":{
    "id":"USER_ID"
  },
  "recipient":{
    "id":"PAGE_ID"
  },
  "timestamp":1458692752478,
  "referral": {
    "ref": ref_data_in_m_dot_me_param,
    "source": "SHORTLINK",
    "type": "OPEN_THREAD",
  }
}
```
