### ISSUE TITLE
Messenger Platform:Send API - List Template 

### ISSUE THREAD

**Issue by Abdelrahman-Hasan** [restfb/restfb#624]
https://developers.facebook.com/docs/messenger-platform/send-api-reference/list-template

Facebook now offers a New Template in Messenger Platform

The List Template is a template that allows you to present a set of items vertically. It can be rendered in two different ways.

The first way renders the first item with a cover image with text overlaid. This is good to making the first item appear prominently above the other items.

default_action object

The default_action behaves like a URL Button and contains the same fields except that the title field is not needed.

**Comment by nbartels** [comment]
The implementation is already done: https://github.com/restfb/restfb/issues/620
You may try the snapshot ...
