### ISSUE TITLE
Update from 1.31 to 1.33 broke logging

### ISSUE THREAD

**Issue by torbenw** [restfb/restfb#625]
Somehow requests aren't logged anymore since updating from restfb 1.31 to 1.33. 

MyClass.java
```
SLF4JBridgeHandler.removeHandlersForRootLogger();
SLF4JBridgeHandler.install();
```

logback.xml
```
  <logger name="com.restfb" level="debug" additivity="false">
    <appender-ref ref="RESTFB" />
  </logger>
```

Do I have to change something because of issue #603?

(The link to the logging examples with SLF4J is broken: http://restfb.com/documentation/examples/RestFB%20Log4j%20Example.zip)

**Comment by nbartels** [comment]
I just checked this with the slf4j simple logger and this is working, so the log messages are coming to slf4j, in theory 😄 

It's a bit late now so, I have to check this with logback and the example configuration tomorrow. But I think, perhaps the logger name is the problem, because the simple logger seems to use `unknown.jul.logger`.

**Comment by nbartels** [comment]
Please try this snapshot, it contains all changes for the 1.34.0 so far plus a fi for your problem.
[restfb-1.34.0-SNAPSHOT.jar.zip](https://github.com/restfb/restfb/files/587249/restfb-1.34.0-SNAPSHOT.jar.zip)

**Comment by torbenw** [comment]
Thanks, it works again now!

I noticed the class name and method name are not logged anymore. It's not very important for me, though.

Old
`2016-11-10 14:59:47.975 [ DefaultWebRequestor  | llHeaderAndDebugInfo | Poll ] DEBUG : Facebook used the API v2.7 to answer your request`

New
`2016-11-14 10:00:17.139 [ JulLogger            | log                  | Poll ] DEBUG : Facebook used the API v2.8 to answer your request`

**Comment by nbartels** [comment]
Okay great. It seems the method where the logging is done is used. I'll check this, too.

Thanks for your log message, this is really helpful.
