### ISSUE TITLE
Add Builders for send types?

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#627]
For instantiating send types it might be interesting to have Builders available.
As the project is already using Lombok this might be easy to add: https://projectlombok.org/features/Builder.html

What do you think?

**Comment by nbartels** [comment]
Okay, but why do you need a builder? As I can see the Lombok builder is only to use a fluent interface on a object, that does not provide such an interface. This is nice but not necessary.

Can you explain the use case a bit?

**Comment by marceloverdijk** [comment]
Hi @nbartels this is indeed the point: to use a fluent interface to build the objects.
I agree this is not necessary, but gives a nice sugar syntax; and with Lombok you almost get this for free :-)

So instead of:

```
Message message = new Message("some text");
List<QuickReply> quickReplies = new ArrayList<>();
quickReplies.add(new QuickReply("title 1", "payload 1"));
quickReplies.add(new QuickReply("title 2", "payload 2"));
message.addQuickReplies(quickReplies);
```

someone could do:

```
Message message = Message.builder()
    .text("some text")
    .quickReply(QuickReply.builder()
        .title("title 1")
        .payload("payload 1")
        .build())
    .quickReply(QuickReply.builder()
        .title("title 2")
        .payload("payload 2")
        .build())
    .build();
```

I always like builders so imo it would be a nice addition.

**Comment by nbartels** [comment]
Okay, I see. I'll think about this ... but not for the 1.34.0 release :smile:

**Comment by marceloverdijk** [comment]
OK let me know when finished thinking about it ;-)

**Comment by nbartels** [comment]
So, I added the annotation. But the builder is not using methods like `addQuickReply`, so the precondition checks are ignored and we need some special constructor.

**Comment by marceloverdijk** [comment]
@nbartels I agree; in that case we should forget about it.
