### ISSUE TITLE
Default logger calling stacktrace for every log message

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#631]
We are seeing that JulLogger.java is calling stacktrace for every log message and since stacktrace call is expensive that is causing some load in our production systems.

This could be solved in two ways:
1) Remove stacktrace
OR
2) Provide a way to enable alternative logger implementation for RestFBLogger and try to figure out how achieve same or similar functionality without stacktrace.

What do you think?

**Comment by nbartels** [comment]
Perhaps it makes sense to active/deactivate the option. It is not everyone necessary to have the calling method and class in the log message.

**Comment by hkroger** [comment]
We are currently using log4j.

**Comment by nbartels** [comment]
This fix should solve the problem for the moment. Perhaps you can verify this. I'll publish the next release soon. Hopefully this week ...

**Comment by hkroger** [comment]
If it's ok, we will test this when it's released.
