### ISSUE TITLE
Issue in sending Get Started button request 

### ISSUE THREAD

**Issue by haresh208** [restfb/restfb#637]
Hi

I have integrated restfb library in my java project and trying to call api for "Get Started" buttons and setting messages in call_to_action but it gives "#400 Bad Request" error because call_to_action is accepting payload not message for "Get Started" button call.

Can you help to solve this error?

Thanks

**Comment by nbartels** [comment]
Okay ... there was a breaking change in a Messenger Platform Send API update. We missed this: https://developers.facebook.com/docs/messenger-platform/changelog#20160630

As a workaround you can build the Json with a `JsonObject`. It is not that complicated.

```java
JsonObject callToActionButton = new JsonObject();
callToActionButton.put("payload","USER_DEFINED_PAYLOAD");
```

**Comment by haresh208** [comment]
Thanks for your quick reply.

Yes this is workaround and it works but it was just reminder as i have seen last update of library at 25th November and i didn't see this feature update in library so updating your team to provide solutions in your next release version.

Thanks a lot.
