### ISSUE TITLE
Feed post with image seems not work

### ISSUE THREAD

**Issue by luisbontempo** [restfb/restfb#641]
Hi I've been trying to add a image to a feed post both to me/feed or a pageId/feed and only the text is seen and the image seems to be ignored.

The code is here:

```
		JsonObject obj = client.publish("me/feed", JsonObject.class,
			BinaryAttachment.with("test.png", imageAsBytes, "image/png"), 
			Parameter.with("message", "TestImage"),
			Parameter.with("privacy", "{'value': 'SELF'}")
				);
```

Can you please help me on this? I am banging with my head already ;)

Many thanks!

Luis

**Comment by nbartels** [comment]
You need to use the `me/photos` endpoint instead of `me/feed`. 

I'll have to adapt the integration tests and our documentation.

**Comment by luisbontempo** [comment]
Thank you so much Norbert! I have made the changes and now creating the photo, fetching its link after and then using it to publish.

```
response = client.publish("me/photos", FacebookType.class,
					BinaryAttachment.with("Demo.jpg", imageBytes, "image/jpeg"),
					Parameter.with("no_story", "1")
					);
Photo photoLink = client.fetchObject(response.getId(), Photo.class, Parameter.with("fields", "id,link"));
		response =  client.publish("me/feed", FacebookType.class,
                Parameter.with("link", photoLink.getLink()),
                Parameter.with("message", "text"),
                Parameter.with("status_type", "wall_post"),
                Parameter.with("type", "status"),
                Parameter.with("privacy", "{'value': 'SELF'}"));

```

However I still got one major issue that I couldn't resolve, the post displays always as "shared his photo" instead of just a normal status post, like when we do it with just text. 

I've tried with status_type = wall_post, type=status, read dozens of things out there but couldn't yet got the answer for this..

Do you know what is the work around for this, we really need it!

Many thanks!

Luis

**Comment by nbartels** [comment]
You can simply publish the image to me/photos and add the message. The post in the feed is generated automatically. 

```java
byte[] imageAsBytes = fetchBytesFromImage();
JsonObject privacy = new JsonObject();
privacy.add("value", "SELF");
DefaultFacebookClient client =
        new DefaultFacebookClient(getTestSettings().getUserAccessToken(), Version.VERSION_2_7);
JsonObject obj = client.publish("me/photos", JsonObject.class,
      BinaryAttachment.with("test.png", imageAsBytes, "image/png"), 
      Parameter.with("privacy", privacy));
```

**Comment by luisbontempo** [comment]
Now it says "added new photo", any other ideas?

**Comment by nbartels** [comment]
Publish a photo with `no_story` and check the `id` in the returned JSON. Afterwards publish a new Post and use this id in `object_attachment` field.

Not tested but according to the API this should work.

**Comment by dahbasit** [comment]
Here is how to post photo with message without creating link or any thing. It is simplest;

`fbClient.publish(pageID + "/photos", FacebookType.class,
                                BinaryAttachment.with("jpg", imageinByte),
                                Parameter.with("message", summary + "\n" + hashTags));`

Please note that my image is in binary format(simple byte array)
