### ISSUE TITLE
Simplify accessing user access token

### ISSUE THREAD

**Issue by vashchenkov** [restfb/restfb#645]
Now to get user access token and post message after that I should have to use "bad" code like this:

			DefaultFacebookClient facebookClient = new DefaultFacebookClient(Version.VERSION_2_8);

			FacebookClient.AccessToken accessToken = facebookClient.obtainUserAccessToken(APP_ID, SECRET, "http://localhost:8080/auth", AUTH_CODE);

			facebookClient = new DefaultFacebookClient(accessToken.getAccessToken(), Version.VERSION_2_8);

			FacebookType publishMessageResponse = ...

It would be better if client would be initialized inside method obtainUserAccessToken. Or userAccessToken obtained in other class or in static method.

**Comment by nbartels** [comment]
You can extend the `DefaultFacebookClient` and build your own FacebookClient with such a function ;)

**Comment by vashchenkov** [comment]
@nbartels Of course it's possible. But it would be nice to  have this functionality in library

**Comment by sridhar4sd** [comment]
@nbartels pls hlp me with the restFB login option
