### ISSUE TITLE
post_id on photo publish

### ISSUE THREAD

**Issue by maheshneogi** [restfb/restfb#646]
when I publish a photo  using
`newPostResponse = fbClient.publish("me/photos", FacebookType.class, BinaryAttachment.with(FileName, imageBytes), Parameter.with("message", Message));`

`newPostResponse.getId();`  gives me an id  something like "12320222222222",  but what I want is a post_id, something like "10556478222214_123202222222" which is what I get on posting a plain text or a link.
how to get a post_id as shown in the image (img src = https://developers.facebook.com/docs/graph-api/photo-uploads)
![11891372_1639824522972953_857268423_n](https://cloud.githubusercontent.com/assets/13569068/21383321/223656e8-c78b-11e6-8218-2efac46e87b9.png)

**Comment by nbartels** [comment]
You can use the `GraphResponse` as response type. It contains the `post_id` field.

We have to add this information to the documentation ...

**Comment by maheshneogi** [comment]
that worked.
thanks a lot man
