### ISSUE TITLE
Error when trying to get the accounts of a user 

### ISSUE THREAD

**Issue by digitalxxl** [restfb/restfb#648]
when I hit the endpoint:

**v2.8/{userId}?fields=accounts**

the json data array can not be extracted, Exception hits the floor and nothing is returned.

the returned JSON from Facebook looks like this
```
{
  "accounts": {
    "data": [
      {
        "access_token": ,
        "category": "Camera\/Photo",
        "name": ,
        "id": ,
        "perms": [
          "ADMINISTER",
          "EDIT_PROFILE",
          "CREATE_CONTENT",
          "MODERATE_CONTENT",
          "CREATE_ADS",
          "BASIC_ADMIN"
        ]
      },
      {
        "access_token":,
        "category": "Community",
        "name":,
        "id":,
        "perms": [
          "ADMINISTER",
          "EDIT_PROFILE",
          "CREATE_CONTENT",
          "MODERATE_CONTENT",
          "CREATE_ADS",
          "BASIC_ADMIN"
        ]
      }
    ],
    "paging": {
      "cursors": {
        "before": "MTQ4NTg1NjkyMTcyMjY5NgZDZD",
        "after": "NDA1NTUyODM5NTkwMDc2"
      }
    }
  },
  "id": "user_id"
}
```

Problem occures inside Connection.java line 154
```
// Pull out data
JsonArray jsonData = jsonObject.getJsonArray("data");
```
this call results in a 
```
com.restfb.json.JsonException: JsonObject["data"] not found.
```

To have it working;
```
jsonObject.getJsonObject("accounts").getJsonArray("data");
```
I am using the latest version 1.35.0

Wishing you all a merry merry christmas !!!

Cheers, bye bye

  Stephan

**Comment by nbartels** [comment]
Hm, okay, interesting. I didn't know there is the way to access the accounts via the field in the user object. No hint in the Facebook docs ;)

Normally you should access the accounts by calling the `userid/accounts` endpoint and expect a `Connection<Account>`.
