### ISSUE TITLE
Deleting a connection

### ISSUE THREAD

**Issue by eipark** [restfb/restfb#653]
Is there a way to `DELETE` a connection? There seems to be no `deleteConnection` method, only `deleteObject`. For instance, I want to be able to make a `DELETE` to `/{page_id}/subscribed_apps` as outlined [in the docs here](https://developers.facebook.com/docs/graph-api/reference/page/subscribed_apps/).

**Comment by nbartels** [comment]
This should work like this:

```java
DefaultFacebookClient client = new DefaultFacebookClient("<pageAccessToken>", Version.VERSION_2_8);
boolean success = client.deleteObject("me/subscribed_apps");
```

**Comment by eipark** [comment]
Ah, thanks!
