### ISSUE TITLE
Add equals methods to types

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#657]
It would be very useful to add `equals` methods to the type classes.

E.g.

```
IdMessageRecipient recipient1 = new IdMessageRecipient("123");
IdMessageRecipient recipient2 = new IdMessageRecipient("123");

System.out.println(recipient.equals(recipient2));

>> false
```

**Comment by marceloverdijk** [comment]
Hi Nico, thanks for adding this.

The `IdMessageRecipient` was just an example.
E.g the types in `com.restfb.types.send.*` like `QuickReply` (and probably other packages also) don't have the equals method.

Especially when writing unit tests it and verifying that specific methods are called with this is very useful. I now have to write custom ArgumentMatchers.

**Comment by nbartels** [comment]
I see. I'll try to add some unit test to check for the presence of the `equals` method.

**Comment by marceloverdijk** [comment]
@nbartels thanks for opening this one again.
I think all type classes should have a equals and hashcode method.
Maybe you could use Lombok's `@EqualsAndHashCode`? (https://projectlombok.org/features/EqualsAndHashCode.html)
