### ISSUE TITLE
LeadGen Webhook not supported

### ISSUE THREAD

**Issue by pibernardi** [restfb/restfb#660]
Hi,
thanks for your work!

Actually the LEADGEN Webhook is not supported,
this is the log message:

undefined change value detected: LEADGEN

please provide this information to the restfb team: 
`{
 "created_time":1485964825,
   "page_id":12345,
   "ad_id":0,
   "adgroup_id":0,
   "leadgen_id":12345,
   "form_id":12345
}
`
I've read the source code of the ChangeValue class but 
I'm not sure which is the cleanest way to implement a custom 
ChangeValue object

Bye,
Paolo

**Comment by nbartels** [comment]
Okay thanks, if you like you can provide the complete json. We will add it to the next version.

**Comment by pibernardi** [comment]
Thanks for the fast reply! ;)

this is a comple json webhook for the Leadgen event

`"{"entry":[{"changes":[{"field":"leadgen","value":{"ad_id":0,"form_id":12345,"leadgen_id":1636129430026801,"created_time":1485964825,"page_id":12345,"adgroup_id":0}}],"id":"246022332166618","time":1485964826}],"object":"page"}"`
