### ISSUE TITLE
Connection<T> not setting new pagination cursors if iterator fetches next page

### ISSUE THREAD

**Issue by DerKeil** [restfb/restfb#672]
Assume you have a Connection-object and want to paginate over all posts of a page or all comments of a page until you reach someCondition, then it might look like this.

```java
Connection<T> connectionCreatedBeforeIteration = ...;
String afterCursor;
for (List<T> list : connectionCreatedBeforeIteration) {
    ...
    if (someCondition) {
       afterCursor =  connectionCreatedBeforeIteration.getAfterCursor(); //<- will be the same in every iteration as it will not be updated
       break;
    }
}
```

After this loop I want to resume the pagination at the page I have been before by using the afterCursor. The problem I have is that the afterCursor of the connection-object is not updated when a new page is fetched. It would be nice if one could fix this.

The reason is that the next()-method of the `ConnectionIterator` creates a new Connection-object and replaces the current connection-object, thus the connectionCreatedBeforeTheIteration will still point to the old one, but internally we use a new one.

I would be fine with either of the following solutions:

1. Make a Getter for the Connection in the ConnectionIterator.
2. Make a Getter for afterCursor, beforeCursor, getNextPageUrl etc. in the ConnectionIterator, which then accesses the underlying Connection.
3. Instead of 
`connection = connection.fetchNextPage();`
in `ConnectionIterator.next()`, one could do something like
`Connection<T> nextPageConnection = connection.fetchNextPage();
connection.copyValues(nextPageConnection);`

Thanks
Stefan

**Comment by nbartels** [comment]
So, if I get you right, you try to break the loop due to a condition and resume it later on?

**Comment by DerKeil** [comment]
This is exactly what I want to do. Thus, I am interested in the 'afterCursor' of the actual iteration.

**Comment by nbartels** [comment]
Can you please explain what you try to achieve, because you can simply call a method during the loop and it resumes afterward automatically. Or do you try to do some asynchronous?

```java
Connection<T> connectionCreatedBeforeIteration = ...;
for (List<T> list : connectionCreatedBeforeIteration) {
    ...
    if (someCondition) {
       doSomeGreatStuff(list);
    }
}
```

**Comment by DerKeil** [comment]
Yes its about asynchronous tasks. I want to complete the call on my backend, return some data, and then start another task on my backend with the current 'afterCursor'.

**Comment by nbartels** [comment]
Okay, so I had some time to think about your problem and the proposed solutions. First I asked myself why you don't work with the iterator as it is atm. But soon I realised that you cannot access the current page, only the next page is accessible. 

Therefore (and you suggested this already) I'd like to change the iterator and provide a not only a `hasNext` and `next` but also a `current` method. It returns the list elements in the current page. 

The signature will look like `public List<T> current()`. Because the current iterator interface does not provide such a method, I'd like to add a new interface that extends the iterator. So the implementation can stays almost as it is and should not disturb other users and their application.

Does this look like a solution that solves your problem?

**Comment by DerKeil** [comment]
Hey Norbert,

thanks for your suggestion. But I don't see how this solves my problem. Maybe I oversee something.

What I want to do is to start a new `connection`(not merely a new ìterator`).

Image I want to gather the last 20 posts of a page with all its comments and replies. So I start a routine doing so. But assume that there are many, many comments and replies. As I want to limit the amount of memory and time one of my servers is busy doing so, I count the number of fetched objects. After some amount X is fetched I want to terminate this process on the server and start a new one (on maybe another server, decided by the loadbalancer). So I want to tell the new server what was already done so far, i.e. the current post I was at plus the page of the comments-connection I was at. So I need the current cursor of the `connection` to resume the iteration.

(When you create a `connection`-object you can ask for the current and next cursor, BUT when the ìterator`of the `connection`goes to the next page, these two cursors of the `connection`are not updated, and neither you cannot ask the `iterator`about the new cursors. Either of the two possibilities would be a solution for me.)

**Comment by nbartels** [comment]
Ah, I see. I thought it would be possible to work with the iterator after the breaking condition. But transferring information to other servers sounds a bit more complicated. So I think returning the current connection from the iterator is the best way. I think I'll use the name @revetkn already proposed internally :)

So there should be a `public Connection<T> snapshot()` method. I think you suggested this already :smile: but it's hard to understand a issue without seeing the use case.

**Comment by DerKeil** [comment]
Yes a snapshot-method would be great :)
