### ISSUE TITLE
AdStudy entity missing

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#673]
This entity seems to be missing:
https://developers.facebook.com/docs/marketing-api/reference/ad-study

**Comment by hkroger** [comment]
Also missing related:
https://developers.facebook.com/docs/marketing-api/reference/ad-study/cells/
https://developers.facebook.com/docs/marketing-api/reference/ad-study/userpermissions/
https://developers.facebook.com/docs/marketing-api/reference/ad-study/objectives/

**Comment by nbartels** [comment]
There is no documentation for the `AdStudyAdsAssetUserPermissions` type. Maybe the `UserPermission` class is sufficient. Otherwise an example JSON is needed.

**Comment by hkroger** [comment]
This should contain the permission documentation:
https://developers.facebook.com/docs/marketing-api/reference/ad-study/userpermissions/

ads/UserPermission.java seems to have a bit different set of fields.

**Comment by nbartels** [comment]
No, it doesn't. In the "Reading" section you only get the information that you get a list of `AdStudyAdsAssetUserPermissions` nodes. But it is not specified how a node looks like. Only for creating new objects the parameters are described, but the may differ from the "Reading" objects. I used the feedback button to let Facebook know, that there is something missing.

**Comment by hkroger** [comment]
Ah, true that. I can also try to whip up some example data. But of course that would contain only subset of all possible fields.

**Comment by nbartels** [comment]
Yes, would be great ...
