### ISSUE TITLE
fetchObjects

### ISSUE THREAD

**Issue by UbaldoF** [restfb/restfb#698]
Hi, 
in DefaultFacebookClient class the method fetchObject contains:
`for (int i = 0; i < ids.size(); i++) {
String id = ids.get(i).trim().toLowerCase();`
but message ids are case sensitive.

For example if I try to get a Message by fetchObject "m_mid.$cAABa3TfYONthItWMjla8ZBEQ-vGW" works and "m_mid.$caaba3tfyonthitwmjla8zbeq-vgw" doesn't.

I will extend DefaultFacebookClient to solve, but it would be nice to fix it because if you need to get many messages you have to make a lot of calls.

Cheers

**Comment by nbartels** [comment]
Okay, I'll check this. It seems Facebook changed the message ids.

Regarding many calls. If you have the ThreadId you can simply fetch the Connection with the `<thread-id>/messages` endpoint. So you have one call per Thread and page, because it is paged.

**Comment by UbaldoF** [comment]
Ok, but I have a lot of threadId too :-)

Thanks a lot

Il 21 mar 2017 5:40 PM, "Norbert Bartels" <notifications@github.com> ha
scritto:

**Comment by nbartels** [comment]
I think you're right and I don't a good reason why `toLowerCase` is needed. It's a very old part of the code, perhaps in ancient times it was needed ;)

@revetkn can you remember it? 😄

**Comment by revetkn** [comment]
@nbartels TBH I don't recall why I did that and agree we should get rid of it!
