### ISSUE TITLE
Update comment describing possible LookalikeSpec.Origin types

### ISSUE THREAD

**Issue by pkoivisto** [restfb/restfb#700]
According to the documentation, field `type` of `com.restfb.types.ads.LookalikeSpec.Origin` can have the value of `custom_audience`, `conversion_pixel`, `page` or `app`. 

It seems however that the behaviour of FB API has changed recently in that the value `multi_custom_audience` is now returned for cases where `custom_audience` was returned earlier. The documentation should be updated to take this into account.

**Comment by nbartels** [comment]
Can you provide a link to this information? 

The reference does not have this information:
https://developers.facebook.com/docs/marketing-api/reference/lookalike-spec/

And I checked the `facebook-ads-php-sdk`. There is only an `object` referenced, this is a bit too general 😄 

If you have some JSON, it would be very great!

**Comment by pkoivisto** [comment]
Yeah, the reference isn't exactly overly verbose on this topic.

I thought I had some JSON for this, but looks like the change I described above was quite short-lived - the objects returned from the API no longer demonstrate the issue.

As I can't reproduce the problem anymore, I'll just close this issue for now.
