### ISSUE TITLE
Total count for likes and comments not available

### ISSUE THREAD

**Issue by frangarcia** [restfb/restfb#707]
When requesting the images of an album, Facebook provides a way of getting the total number of likes and comments like this:

10154409230764305/photos?fields=id,created_time,from,height,images,link,picture,source,width,likes.limit(0).summary(true),comments.limit(0).summary(true)

but then this values are available in the object.

**Comment by nbartels** [comment]
Please check the 2.0.0 RC2. Because this breaking our API we already added this to the next release.

**Comment by frangarcia** [comment]
Great! Thanks Norbert. I will check it.

**Comment by nbartels** [comment]
@frangarcia is your issue solved with the RC?

**Comment by frangarcia** [comment]
Yes sorry, it worked. Thanks @nbartels
