### ISSUE TITLE
Page/Group members?

### ISSUE THREAD

**Issue by saveSession** [restfb/restfb#708]
I saw there is a way to get raw string of page members but none to get group members, and I think there is no technique in order to get the avaliable 5k members http://stackoverflow.com/questions/20261708/facebook-api-not-giving-me-complete-list-of-members-of-facebook-groups

**Comment by nbartels** [comment]
The FQL way is dead. But what about the graph api suggestion, you already tried to fetch the members? `fetchConnection` is the way to go. Because the blog post is 3 years old and maybe this changed. 

But attention, the user can disable the Platform access and the user is not listed in that case.

**Comment by nbartels** [comment]
I just checked this and wrote an integration test. 

I checked two groups, one with 1778 on Facebook and received 1750 users. And one with 10.038 and received 9687 users. So I think you can get more than 5k users. There are two explanations for the difference. 1. some users have disabled the Facebook Platform. 2. Facebook returns only a subset. 

To analyse the difference further one could let the test run several times and compare the result sets. Feel free to do so and if you investigated it, you can open a bug on Facebook. RestFB can only show the information Facebook provides. 😄

**Comment by saveSession** [comment]
Nice!
