### ISSUE TITLE
image_aspect_ratio not working on webview?

### ISSUE THREAD

**Issue by midofit** [restfb/restfb#710]
Hi, for the generic template message, the image_aspect_ratio seems to work only on the messenger app when I set it to 'square'. On the webpages like messenger or the facebook chat box, the image is still rendered as default (horizontal). Can this possibly a bug? 
Edit: This seems like the wrong place for this issue, you can close this if you want

**Comment by nbartels** [comment]
Yes, you're right. 

Here is the link to this bug at Facebook: https://developers.facebook.com/bugs/651186948339236/

**Comment by midofit** [comment]
This bug was submitted by me actually 😄 . Anyway, thanks for the response.
