### ISSUE TITLE
No wrapper for AdsPixel response

### ISSUE THREAD

**Issue by eipark** [restfb/restfb#711]
I'm not sure if this is a conscious omission, but there doesn't appear to be a data type for the response object for `GET /[ad_account_id]/adspixels`. There is an `AdsPixel` object but the response for this endpoint comes in an array, even though I believe an ad account can only have one pixel (I'm guessing this is likely a relic of some backwards compatibility as pixels have changed). 

Sample call:

![image](https://cloud.githubusercontent.com/assets/723778/24915955/a7b0eec4-1ea6-11e7-9597-fb818ec8f92b.png)

**Comment by nbartels** [comment]
You should try to use `fetchConnection` instead of `fetchObject`. If an array of items is possible the `Connection` provides access to the iterator. See here: http://restfb.com/documentation/#fetching-connections

**Comment by nbartels** [comment]
@eipark Is the problem solved?

**Comment by eipark** [comment]
Sorry for the slow response, that should work.
