### ISSUE TITLE
DefaultJsonMapper incorrectly attempts to map string to an array

### ISSUE THREAD

**Issue by pkoivisto** [restfb/restfb#719]
It appears that the implementation in `DefaultJsonMapper.toJavaObject(..)` is a bit too eager in trying to deduce object types based on JSON field values. Could this possibly be fixed?
Please see below for an example where things go wrong:

Searching for interests with the query `dunkelbunt` (essentially a GET to `https://graph.facebook.com/v2.8/search?type=adinterest&q=dunkelbunt&access_token={{access_token}}`) yields the following JSON in response:

```javascript
{
  "data": [
    {
      "id": "6003280521210",
      "name": "[dunkelbunt]",
      "audience_size": 21110,
      "path": [
        "Interests",
        "Additional Interests",
        "[dunkelbunt]"
      ],
      "description": null,
      "disambiguation_category": "Musician/Band"
    }
  ]
}
```

When this response is parsed by RestFB, an exception with the following message is thrown:
`JSON is an array but is being mapped as an object - you should map it as a List instead. Offending JSON is '[dunkelbunt]'.`

**Comment by nbartels** [comment]
This is a nasty one...
