### ISSUE TITLE
user.getLink()

### ISSUE THREAD

**Issue by github4chris** [restfb/restfb#720]
Hi,

in the Graph API Explorer i get the correct value for "me?fields=link", but with the RestFB i get only null:

```
User user = fbClient.fetchObject("me", User.class);
System.out.println("name:" + user.getLink());
```

Any clues?

THX
Chris

PS: @nbartels & Co: Many thanks for your big work! :)

**Comment by nbartels** [comment]
please try:

```java
User user = fbClient.fetchObject("me", User.class, Parameter.with("fields","link"));
System.out.println("name:" + user.getLink());
```

**Comment by github4chris** [comment]
Hi Norbert,

thanks for the try, but there is a problem with your call...

I need the mapped userName from the Link to the user profile i.e. 

A try with `153080620724/?fields=link ` over the Graph API Explorer gives me:

`"link": "https://www.facebook.com/DonaldTrump/",`

Your call gives me a link too, but to the _app_scoped_user_id_ only:

`https://www.facebook.com/app_scoped_user_id/119598358506131/`

is this a bug, or a feature (i use the 1.39.0)?

many thanks! :)
chris

**Comment by github4chris** [comment]
Hi Norbert,

ooooops, my bad... sorry, i have to use the "Parameter.with"-call. It works now, many thanks!!! :)

chris
