### ISSUE TITLE
AdReportRunFields

### ISSUE THREAD

**Issue by eipark** [restfb/restfb#723]
I don't see support for `FacebookAds\Object\Fields\AdReportRunFields` at the moment in the docs. See the `Filtering Leads` section [here](https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving/v2.8). 

As a side note - I don't really see much documentation for this type of filtering pattern or object within FB either. I don't think it's possible via the FB debug tool but I could be wrong.

**Comment by eipark** [comment]
Hi @nbartels - `AdReportRun` seems like its different from `AdReportRunFields`. https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving/v2.8 shows `AdReportRunFields::FILTERING` with  an object with a field of `time_created` and an `operator` key. I think these are different concepts/objects?

**Comment by nbartels** [comment]
Hm, okay. I'll have to check this. But I think this is some JSON that is used to filter the result on Facebook side. If I'm right, we don't have objects for this case in RestFB. Until now something like that is only used on publishing to Facebook and I think in this case the JsonObject is used.

**Comment by nbartels** [comment]
I suggest you do this:

```java
class AdReportRunFieldFilteringItem {

     @Facebook
     public String field;

     @Facebook
     public String operator;

     @Facebook
     public Long value;

}

List<AdReportRunFieldFilteringItem> filteringList = new ArrayList<>();
// add some filtering items here...

fcClient.fetchConnection("<AD_ID>/leads", Lead.class ,Parameter.with("filtering", filteringList));
```

If there are more requests like this we have to provide a solution, but atm I think this is sufficient.

**Comment by eipark** [comment]
Yeah, that seems reasonable for now. Thanks for taking a look.
