### ISSUE TITLE
Retrying when fetch connection page error occurs (question)

### ISSUE THREAD

**Issue by ivanviragine** [restfb/restfb#724]
Hi!

I wonder which is the best approach to retry fetching a page from connection when error occurs.

When on a paging loop through RestFB's iterator:

```
for (List<T> page : connection) {
    if (numberOfPages > 1 && page != null && page.size() > 0) {
        log.info("Paging connection: " + numberOfPages);
    }

    for (T entity : page) {
        entities.add(entity);
    }

    if (++numberOfPages > maxPages) {
        break;
    }
}
```

If an exception occurs, like:

`com.restfb.exception.FacebookGraphException: Received Facebook error response of type : An unknown error occurred (code 1, subcode 99)`

How can I retry that specific page?
I don't want to restart paging through the connection, so I wonder which is the best approach in the case.

**Comment by nbartels** [comment]
You can use the iterator of the `Connection` object. In case of an error you can take the "snapshot" from the iterator and you get the current connection object. After handling the error some how (wait a second or whatever depending of the exception type) you can take from the "snapshoted" connection a new iterator and run over the object again. 

But depending on the exception you need a more sophisticated solution ;)
