### ISSUE TITLE
TargetingSentenceLine missing

### ISSUE THREAD

**Issue by eipark** [restfb/restfb#728]
[TargetingSentenceLine doc in FB](https://developers.facebook.com/docs/marketing-api/reference/targeting-sentence-line/)

[`targetingsentencelines` edge on ad](https://developers.facebook.com/docs/marketing-api/reference/adgroup)

I'd like to be able fetch these via an ad similar to how theres already `AdSet`/`AdCreative` as edges of the `Ad` object, so I can just do `ad.getTargetingSentenceLines()`

![image](https://cloud.githubusercontent.com/assets/723778/26161208/40128748-3af1-11e7-8a62-2dadf9f3c480.png)

Thanks

**Comment by eipark** [comment]
Thanks for the responsiveness @nbartels - will this get added to `Ad` also?

**Comment by nbartels** [comment]
Oh sorry, I missed that part. I'll add it, too. asap 😄

**Comment by eipark** [comment]
Sadly discovered that this documentation was out of date and doesn't actually reflect what the API is returning. 

Looks more like this:
```
eg: GET "act_xxxxx/ads?fields=targetingsentencelines" returns:

    [{
      "targetingsentencelines": {
        "id": "/targetingsentencelines",
        "targetingsentencelines": [
          {
            "content": "Location:",
            "children": [
              "United States"
            ]
          },
          {
            "content": "Age:",
            "children": [
              "18 - 65+"
            ]
          },
          {
            "content": "Placements:",
            "children": [
              "News Feed on desktop computers, Instagram Feed or News Feed on mobile devices"
            ]
          }
        ]
      },
      "id": "23842588419050715"
    },
{... }]
```

I filed a direct-support ticket w/ FB but if they update their docs I'll link to them here.

**Comment by nbartels** [comment]
Okay, I see. Imho the `TargetingSentenceLine` object returns the `targetingsentencelines` as String at the moment and according to your example this should be a object containing  a `String` `content` and a `list of Strings` `children`. This should be possible even with a backwards compatibility. So I change this and use your example as "blueprint".
