### ISSUE TITLE
getBirthdayAsDate appears to be off by one day

### ISSUE THREAD

**Issue by blinder** [restfb/restfb#731]
After successfully fetching a User object, then calling:

```
FacebookClient facebookClient = new DefaultFacebookClient(fbAccessToken, Version.VERSION_2_9);
 User user = facebookClient.fetchObject("me", 
          com.restfb.types.User.class,
         Parameter.with("fields","email,last_name,first_name,birthday,hometown,gender,work,likes,movies,music,groups,picture,about"));
long bdayTimestamp = user.getBirthdayAsDate().getTime()
```
 the resulting timestamp results in a date on our front-end that is 1 day early. So if a birthday is on 5/24 it shows up as 5/23

Our front-end code (JavaScript) is just doing a straight up `new Date(timestamp)` so no transformation is happening at any time. 

This behavior is very consistent and very easy to reproduce. I simply did this to find the inconsistency:

```
String strBirthday = user.getBirthday();
Date dtBirthday = user.getBirthdayAsDate();
```
In my test case, using my fb account,  `strBirthday` was: 06/11/1973 (correct)

dtBirthday (toString'd): is: `Sun Jun 10 20:00:00 EDT 1973` (incorrect)

So clearly there's a problem with how the string birthday gets translated into a date object. 

I'm currently using restfb v: `1.40.1` from maven central

In the meantime to workaround this, we'll be using the string form of the birthday and parse it into a date object.

**Comment by revetkn** [comment]
When RestFB was created, there was no concept of [LocalDate](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html) (that is, a timezone-less date representation) as part of core Java.  So we are just returning a raw "epoch" date to you.

To be clear, epoch dates (for which java.util.Date is just a wrapper) are understood to be in UTC timezone (no offset).

What you are doing on the frontend is "breaking" the date at string formatting time by applying your current timezone - appears to be US/Eastern - to what is in fact a UTC date.  This subtracts 4 hours from the actual time and puts you a day before the actual date represented.

So - solution - format the birthday for display using UTC as the timezone (whatever library you use - moment.js? should support this).

**Comment by revetkn** [comment]
@blinder - please let me know if you think this is still an issue.  If not, I will close it out.  Thanks!

**Comment by blinder** [comment]
closed this by using momentjs on the front-end
