### ISSUE TITLE
can't persist User.class to mongo DB

### ISSUE THREAD

**Issue by bogdanlupashko** [restfb/restfb#733]
Hi, 
while I tried to code saving com.restfb.types.User.class related with myUser to mongo there was an error on startup the server:

> Caused by: org.springframework.data.mapping.model.MappingException: Attempt to add id property private java.lang.String com.restfb.types.FacebookType.id but already have an property private java.lang.String com.restfb.types.StoryAttachment$Target.id registered as id. Check your mapping 
> configuration!

I'm a new one with restfb, provide me an answer please
I should wait for a fix 
or 
I should save an user in other way.

Thanks

**Comment by nbartels** [comment]
I'm not a Spring guy, but I think there is something wrong how Spring internally stores the mapping. The error message complains about `com.restfb.types.FacebookType.id`, because it cannot be mapped to `id`. `com.restfb.types.StoryAttachment$Target.id` is already mapped to `id`. These ids are completly different and the StoryAttachment is not used in the user object.

So I think you should check how the spring mapping to mongodb is implemented.

**Comment by bogdanlupashko** [comment]
Thanks a lot for a quick answer :)
I'll check spring mapping out

**Comment by bogdanlupashko** [comment]
I' ll checked the config and found that probably I could not save to mongo any of com.restfb.types.* classes
The issue:
com.restfb.types.FacebookType has an id property

**Comment by bogdanlupashko** [comment]
I' ll checked the config and found that probably I could not save to mongo any of com.restfb.types.* classes
The issue:
com.restfb.types.FacebookType has an id property
+
com.restfb.types.StoryAttachment$Target. class extends FacebookType
and has id property too.

Yes your answer was that these ids are completly different. 
But mongo document can't contains two ids. 

I use automated mapping with spring data like
public interface UserRepository extends MongoRepository<com.restfb.types.User, String> {}

Please take a look at
http://i.prntscr.com/fb99e9e697b54c999d95af693ac4c085.png

there are usages of Target.id field and as you can see it conflicts with FacebookType.id

**Could you do something with this, please?
(Maybe renaming Target.id should help?)**

P.S. same issue related to 2 ids 
https://stackoverflow.com/questions/38803532/entity-inheritance-attempt-to-add-id-property-private-but-already-have-prope

**Comment by bogdanlupashko** [comment]
The solution for me was adding mongo custom write convertors for fields:
- exclude from mapping com.restfb.types.StoryAttachment.Target.id
- exclude from mapping com.restfb.types.CategorizedFacebookType.category

http://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mapping-configuration

Ps maybe it could be halpful for someone.

Pss maybe this should be rewrited to support automated config for case like I has.

Thanks guys for awesome library and support :+1: 
Have a nice day!

**Comment by nbartels** [comment]
Okay, thanks for your information. So the additional `id` in the `StoryAttachment$Target` should be removed and it is already in RestFB 2.0.0. 
And the Page type has an additional `category` field that is already in the `CategorizedFacebookType`.
So I think you should Page.category.
