### ISSUE TITLE
Can not get X-Page-Usage by getWebRequestor().getDebugHeaderInfo()

### ISSUE THREAD

**Issue by nmhoang310** [restfb/restfb#734]
I want to check the data of X-Page-Usage in the header, so i wrote the for loop to continually call the end point "messages" and show the info by the code below:
```
DebugHeaderInfo headerInfos = fbClient.getWebRequestor().getDebugHeaderInfo();
System.out.println("App usage: " + headerInfos.getAppUsage());
System.out.println("Page usage: " + headerInfos.getPageUsage());
```
But the above values are always empty, even when i got the Page limited reached error.

> Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#32) Page request limited reached (code 32, subcode null)
> 	at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1199)
> 	at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1116)
> 	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1057)
> 	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:979)
> 	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:941)
> 	at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:365)

How can i get the value of X-Page-Usage?
Thanks.

**Comment by nbartels** [comment]
Can you please change to log level of `com.restfb.HTTP` to debug and replay your test. You should see all HTTP headers as they are transferred from Facebook. What about the other Debug information, do you get any?

BTW the usage information is available as soon as the first limit (yellow line in the Facebook app dashboard) is reached. Facebook don't send the information on every request.

**Comment by nmhoang310** [comment]
Thanks for your quick reply. I change the log level to DEBUG. I just got the data of PageUsage 1 time, after that, i could not get that info again...

```
Debug: WAQCGsjEThWwo+gso2ge/3t/P2jrBWEaWwrvJWPa6+ICGcmsDf3BW/1R12ebMVOvmSY8cAPRLWWVlwf25snUrQ==
App usage: 
Page usage: {"call_count":2,"total_cputime":1,"total_time":1}
Rev: 3057073
Trace ID: GMFTkTI7UHg
```

**Comment by nmhoang310** [comment]
After i reached the Page limit, i got the below info:
```
Debug: QeodrDSB0AN6qqY1eWNkPlsB93xSMEWg80qsyfUAMqzlB0AOvmMR6mypF0HHkoSiGP8k54AHwDrn5aQfMLvZrg==
App usage: 
Page usage: {"call_count":144,"total_cputime":73,"total_time":44}
Rev: 3057133
Trace ID: HiH1euz4Umo
```
Look like it's just got data after reach the limit...

**Comment by nmhoang310** [comment]
I think it's a problem at response from Facebook, sometime it does not response the header X-Page-Usage (test by explorer tool of Facebook)

**Comment by nbartels** [comment]
Just found this in the [Facebook rate limiting documentation](https://developers.facebook.com/docs/graph-api/advanced/rate-limiting)
> If enough calls are being made on behalf of a page to be considered for rate limiting by our system, we return an X-Page-Usage HTTP header

They returned the usage percentage before and changed it to the JSON you see at some time. So we have to adapt this change. Although RestFB can not force Facebook to send the header information, we have to deal with this JSON. 

Therefore I'll create a new issue to solve the JSON problem and link it here.
