### ISSUE TITLE
Add ChangeValue type for webhook page mentions?

### ISSUE THREAD

**Issue by torbenw** [restfb/restfb#735]
When you subscribe to mentions of your page with webhooks, Facebook will send JSON like this:

`{
  "field": "mention",
  "value": {
    "post_id": "44444444_444444444",
    "sender_name": "Example Name",
    "item": "post",
    "sender_id": "44444444",
    "verb": "add"
  }
}`

Currently this will be interpreted as a "FallBackChangeValue" by restfb 1.41. Do you plan to support this as a type like "MentionChangeValue" in the future?

**Comment by nbartels** [comment]
Sure thing. The webhooks and the JSON sent by Facebook are not that well documented, so we are rely on issues like this to complete the implementation.

**Comment by torbenw** [comment]
Thanks!

Facebook now makes it possible to test webhook updates if you registered a callback URL. Maybe that can help you with other responses? You can see the JSON data without having to send it.

https://developers.facebook.com/docs/graph-api/webhooks?locale=en_US

**Comment by nbartels** [comment]
The available example is only a post, we have to investigate this further and check how the JSON look like in case of a comment, photo. And how does removing or editing a object with a mention is transferred.

**Comment by torbenw** [comment]
I tried to get some example mention updates for you, but for some reason I can't get Facebook to send any webhook updates when I mention my test page.

**Comment by nbartels** [comment]
That's the same behavior I'm observing. I added the subscription to a test app at work and hopefully get better results. But I'm overall unsure if the mentioned posts/comments etc are sent as soon as the feed subscription is activated. Afaik they are part of that. But perhaps there is a Facebook Bug or there are some special preconditions we don't fulfill.

**Comment by nbartels** [comment]
I think I found the answer:
"This is currently only available for Workplace apps." - So normal Facebook apps don't get the mentions, only Facebook Workplace (https://www.facebook.com/workplace).

**Comment by torbenw** [comment]
Ah, thanks again. I didn't know that.

**Comment by nbartels** [comment]
It was mentioned 😄 in the webhook docu. So, I close this issue and hopefully some developer who is using Facebook Workplace add some JSON sometime.

I think you can get the mention posts with the feed subscription, but you have to check some conditions. At least this is a way we used some time ago.
