### ISSUE TITLE
Upload resumable error

### ISSUE THREAD

**Issue by david84tong** [restfb/restfb#737]
Hi You guys,

I'm having the error while uploading video based on chunk in Facebook. Each uploading i got the error

body =     {
        error =         {
            code = 6001;
            "error_data" =             {
                "end_offset" = 2048576;
                "start_offset" = 1048576;
            };
            "error_subcode" = 1363037;
            "error_user_msg" = "There was a problem uploading your video. Please try uploading it again.";
            "error_user_title" = "Error Uploading Video";
            "fbtrace_id" = "AUpRzpz+eJH";
            "is_transient" = 0;
            message = "There was a problem uploading your video. Please try again.";
            type = OAuthException;
        };
    };
    code = 400;
}, com.facebook.sdk:FBSDKGraphRequestErrorCategoryKey=0}
["body": {
    error =     {
        code = 6001;
        "error_data" =         {
            "end_offset" = 2048576;
            "start_offset" = 1048576;
        };
        "error_subcode" = 1363037;
        "error_user_msg" = "There was a problem uploading your video. Please try uploading it again.";
        "error_user_title" = "Error Uploading Video";
        "fbtrace_id" = "AUpRzpz+eJH";
        "is_transient" = 0;
        message = "There was a problem uploading your video. Please try again.";
        type = OAuthException;
    };
}, "code": 400]

**Comment by nbartels** [comment]
Can you please show your Java Source, so we can get an better insight in what you are doing there?

**Comment by nbartels** [comment]
I got no response for one month now, so I close it. You can reopen this issue if this is still a problem.
