### ISSUE TITLE
How to know one Reaction from webhook is of post or comment

### ISSUE THREAD

**Issue by thienit5** [restfb/restfb#741]
I receive FeedReactionValue object from Webhok, but have no field in object can hint this reaction is of post or comment?
Can you add field comment_id if reaction is of comment and fields: commentReaction, postReaction like in FeedLikeValue?

WebhookObject(object=page, entryList=[WebhookEntry(uid=null, id=436913053309741, time=Tue Jun 13 10:57:08 ICT 2017, rawTime=1497326228, changedFields=[], changes=[Change(field=feed, value=FeedReactionValue[createdTime=Tue Jun 13 10:57:08 ICT 2017 item=reaction parentId=446163252384721_447172818950431 postId=436913053309741_446163252384721 reactionType=love senderId=10206635083634304 senderName=Tran Duc Thien verb=ADD verbAsString=add], rawValue={"created_time":1497326228,"item":"reaction","post_id":"436913053309741_446163252384721","reaction_type":"love","parent_id":"446163252384721_447172818950431","verb":"add","sender_name":"Tran Duc Thien","comment_id":"446163252384721_447508348916878","sender_id":10206635083634304})], messaging=[])])

**Comment by nbartels** [comment]
Okay, now I understand the problem :smile: 
The `commentId` field in the json is not mapped to a field in the `FeedReactionValue`. So we have to add it there and provide some convenience methods to check if the reaction was made to a post, comment or Reply.
