### ISSUE TITLE
How to Obtain User Access Token from Login Dialog?

### ISSUE THREAD

**Issue by MJMann** [restfb/restfb#743]
I'm creating an app that requires a user access token (as do most). I understand how to generate a Login Dialog URL, and I understand hot to use the obtainUserAccessToken() method. However, it requires the verification code in the Graph API callback to the redirect URI, which is included in the login dialog url.

My question is, how do I get this verification code? How do I have my program communicate with the browser to actually get this code and store it. I can't find this answer anywhere.

Thank you!

**Comment by nbartels** [comment]
It depends on your application and how you like to implement the whole thing.

For web applications you should have a servlet that gets the needed information and can forward these to the RestFB lib for converting the Strings to useful objects.

If the application has a native java ui you can work with the device access token or you can show a some web view or html viewer ("embedded browser").

**Comment by MJMann** [comment]
Okay, I'll elaborate because my wording was a bit ambiguous:

The goal of my program:

When the program is run, it first calls this **logIn** method. The method returns a User Access Token so the program can make calls to the Graph API on the user's behalf. The calls are covered by the permissions I wrote in the code below.

The problem:

In order to get the User Access Token, I need a verification code. To get the verification code, I need to open the Login Dialog URL, and the code will be appended to the redirect url. In order to get this code, I need to somehow access and read this redirect url.

So my question is, how do I effectively open the Login Dialog URL, keep track of its redirects, and parse the final URL for the verification code? 

My implementation is below

`	public static AccessToken logIn(String redirectURI, 
			String appID, String appSecret, FacebookClient f) {
		
		ScopeBuilder scopeBuilder = new ScopeBuilder();
		scopeBuilder.addPermission(UserDataPermissions.USER_BIRTHDAY);
		scopeBuilder.addPermission(UserDataPermissions.USER_FRIENDS);
		scopeBuilder.addPermission(UserDataPermissions.USER_HOMETOWN);
		scopeBuilder.addPermission(UserDataPermissions.USER_LIKES);
		
		String loginDialogURLString = f.getLoginDialogUrl(appID,
				redirectURI, scopeBuilder);
		
		AccessToken at = f.obtainUserAccessToken(appID, appSecret, redirectURI, <verification-code>);
		return at;
    }`

Perhaps I'm misunderstanding how to get a User Access Token, or maybe I don't even need one and I'm confused. Some elaboration would be of great help. Thank you

**Comment by nbartels** [comment]
Perhaps this video tutorial is useful. Perhaps we can provide later on an example code for the login flow.

https://youtu.be/0GzyBPT2QpA?list=PLYPFxrXyK0BwiXNe09hTPjFqYbsWv8gxb

**Comment by MJMann** [comment]
The video is great, but I understand everything in there. The problem is, he manually gets an access token using the Graph API Explorer, and then does the rest from his program. So there's no login flow. 

My question is, how do I get the initial User Access Token using my app itself. I have tried opening a browser window that goes to the login dialog URL, but after a user approves, the URL redirects and I have no way to access, from my program, the redirected URL that contains the access token or verification code. I really can't progress with my project until I figure this out, and I am unable to find anything online to answer this question.

Facebook says 

> When using a desktop app and logging in, Facebook redirects people to the redirect_uri mentioned above and places an access token along with some other metadata (such as token expiry time) in the URI fragment:
> 
>```
 https://www.facebook.com/connect/login_success.html#
>     access_token=ACCESS_TOKEN...
```
> _Your app needs to detect this redirect and then read the access token out of the URI using the mechanisms provided by the OS and development framework you are using. You can then skip straight to the Inspecting access tokens step._

How do I do that last step?

Thank you

**Comment by nbartels** [comment]
Okay, so you have a native java application and not a web application. I think in this case I'll provide an example... 

Normally you can read body and url from the webview and work with that. That is what the comment tries to explain.

**Comment by MJMann** [comment]
Thank you so much! Would you be able to link the example once you've done it?

**Comment by nbartels** [comment]
I finished the example code. But I have to clean the code a bit, add some documentation how the app needs to be configured and then add the link here. So thank you for your patience ...

**Comment by nbartels** [comment]
You can the example here: https://github.com/restfb/restfb-examples/issues/4

**Comment by shakram02** [comment]
Can obtaining the token be done using a console app or some other way that doesn't depend on a GUI in my application ? (for example, the console opens up a -chrome, maybe?- browser window and get the token)
