### ISSUE TITLE
Posts from "app_scoped_user_id" impossible?

### ISSUE THREAD

**Issue by github4chris** [restfb/restfb#747]
Hi,

i wonder, how to get posts for FB-User-ID, which have the status "app_scoped_user_id" (i.e. random 100012646301909).

```
[...]
private Connection<Post> posts;
[...]
fbUserID="100012646301909";
userObject = restfb.getUserObject(fbUserID);
[...]
posts = fbClient.fetchConnection(fbUserID + "/posts", Post.class);
[...]
if (userObject.getLink().contains("app_scoped_user_id")) {
  System.out.println("no posts!");
} else {
  for (List<Post> page : posts) {
   for (Post post : page) {
    System.out.println(post.getId());
   }
  }
}
```
Any idea?

TIA! :)
chris

**Comment by nbartels** [comment]
Hm, I just tried it and the posts endpoint returns an empty array. But I'm not sure if the user posted something public.

**Comment by github4chris** [comment]
Hi Norbert! :)

in the example user posted many non public posts => all users, they user name is written in arabic script are mapped to "app_scoped_user_id" ( i.e. 100012646301909,  100004974540659, etc), so this may be a global issue, or....maybe the posts must be here requested in a different way/method (like the user link from User.class, where we must use a Parameter.with("fields", "link"), or so )?

Danke schön! :)
chris

**Comment by nbartels** [comment]
hm, so we should check if it possible to fetch the user posts with the "normal" user id. But perhaps it is simply not allowed/possible to request this endpoint. Or it is a bug... Let's see.

**Comment by nbartels** [comment]
I opened this as bug at Facebook and hope to get a statement:
https://developers.facebook.com/bugs/239723139868631/

**Comment by nbartels** [comment]
According to Facebook this is by design. Only apps that have granted the user_posts permission can fetch the user posts. The posts of other users are not accessible.
