### ISSUE TITLE
Get rate limiting

### ISSUE THREAD

**Issue by minhphong306** [restfb/restfb#751]
I get null object when I do that:
`FacebookClient appClient = new DefaultFacebookClient(Constants.APP_TOKEN, Version.LATEST);
 DebugHeaderInfo headerInfos = appClient.getWebRequestor().getDebugHeaderInfo();`

**Comment by nbartels** [comment]
You made a request between these lines (`fetchConnection`, `fetchObject` ...)?

**Comment by minhphong306** [comment]
No, I wasn't. Is this use only in catch clause?

**Comment by nbartels** [comment]
The debug header are part of the response send from Facebook. Therefore you need to send a request first.

**Comment by minhphong306** [comment]
Thanks you. I'll try it.

**Comment by nbartels** [comment]
I think this should work now, otherwise write a short note 😄

**Comment by minhphong306** [comment]
Sorry, I've not use my computer for a few day.
I've tried but may be I don't deep understand about restFB.
I wil read more and when it work, I write a short note :)

**Comment by nbartels** [comment]
We answer questions in google groups, stackoverflow and on Facebook (send PM to the RestFB page), too :smile:
