### ISSUE TITLE
Upload closed captions error

### ISSUE THREAD

**Issue by frank72833** [restfb/restfb#753]
Hi guys,

We are trying to upload closed captions to a video using RestFB but we are getting the same error all the time.

We have tried using CURL in the terminal and it works with the same file. I am guessing the issue resides in how we are sending the SRT file to Facebook. I am using a BinaryAttachment (which is used for video and image) but I cannot find any other type of attachment in you documentation for files such as SRT.

We are setting the SRT file as follows:
`final BinaryAttachment captionsBinary = BinaryAttachment.with("captions_file", IOUtils.toByteArray(captionsInputStream), "application/octet-stream");`

but the error from Facebook is the following:

`com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#385) Sorry, the captions file you selected is in a format that we don't support. (code 385, subcode null)
`
In the documentation Facebook expects a File object as captions_file:

https://developers.facebook.com/docs/graph-api/reference/video/captions/

Am I doing something wrong? Is there any known issues uploading file object (non image or video) to the Facebook API?

Many thanks,
Kind regards.

**Comment by nbartels** [comment]
Can you please try this `BinaryAttachment`:

```java
final BinaryAttachment captionsBinary = BinaryAttachment.with("test.de_DE.srt", IOUtils.toByteArray(captionsInputStream), "application/octet-stream")
```

change the locale (in this case `de_DE`) to the locale you need.

**Comment by frank72833** [comment]
Hi,

Thanks for your response.

Now the API to Facebook seems to work but the video does not contain the closed captions. However, it I use curl commands in the terminal to replicate the process or the FB UI with the same files the video does contains closed captions.

If I replace the parameter key "captions_file" with "test.en_US.srt", how does the API know that it is a closed captions file?

I have also tried to add any random string to that parameter key and the API works but the closed captions are not present in the video. I guess the means that FB cannot find the file even if it replies without any exception.

Many thanks for the help.
Kind regards.

**Comment by nbartels** [comment]
hm, okay I see. Can you provide the curl call so we can investigate where's the difference.
Adding captions should work with RestFB, too ...

**Comment by frank72833** [comment]
Hi,

I send you the curl executed. Please replace {videoId} with the video Id provided when you upload btn.mp4 to Facebook (You can use the Facebook page publishing tools UI).

Then execute this curl with the CC file btn.en_US.srt file.

`curl -X POST   'https://graph.facebook.com/v2.9/{videoId}/captions?access_token={access_token}' -F captions_file=@btn.en_US.srt -F default_locale=en_US`

Video: https://s3-eu-west-1.amazonaws.com/grabyo-prod/test/btn.mp4
CC: https://s3-eu-west-1.amazonaws.com/grabyo-prod/test/btn-cc.srt (rename it to be filename.en_US.srt)

**Comment by nbartels** [comment]
Here's the raw content transferred by curl. I have an idea what's going wrong and will this check later:

```
POST https://graph.facebook.com/v2.9/<video-id>/captions?access_token=<access-token> HTTP/1.1
Host: graph.facebook.com
User-Agent: curl/7.53.0
Accept: */*
Content-Length: 8086
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------1910dd497402c848

--------------------------1910dd497402c848
Content-Disposition: form-data; name="captions_file"; filename="btn-cc.de_DE.srt"
Content-Type: application/octet-stream

<<< file_content, remove because it is not necassary >>>

--------------------------1910dd497402c848--
```

**Comment by nbartels** [comment]
Okay, I'm able to send the caption file, but have to change some files first. So I think this is some kind of "missing feature" or bug 😄 

With the next version it will work.

**Comment by nbartels** [comment]
So, with RestFB 1.44 you'll get the solution for this problem. The `BinaryAttachment` has no a optional `fieldName`. That is the name of the form field that Facebook expects the binary content to be connected with. Until now, we calculated the name ourself and with this new feature the developer can override it. Additionally the content type is changed. We try to detect it in different ways and if it is not working the fallback is `application/octet-stream`. Facebook expect us to send this content type with the caption file. 

You can create a snapshot or wait for the new version to be released.
