### ISSUE TITLE
Read-After-Write

### ISSUE THREAD

**Issue by thienit5** [restfb/restfb#764]
How can i use function Read after write from restfb api.
This link guide me
https://developers.facebook.com/docs/graph-api/using-graph-api#read-after-write

**Comment by nbartels** [comment]
You simply can publish a element as you done before the read-after-write was introduced. But now you add another `Parameter` with the fields you like to get and as return type you provide instead of `GraphResponse` the type of the new generated object, a `Post` for example. This object will be filled after publishing and you can work with that afterwards. If you need more information, you can provide the example you try to get running ...

**Comment by thienit5** [comment]
Thanks for your support!
I give you example like this, i replace JsonObject.class return by Parameter.with("fields", "id, from, to"), but it not correct.
How can i add Parameter return type?
FacebookClient client = new DefaultFacebookClient("<token>");
          client.publish("465764050424641_485798388421207/private_replies",
                Parameter.with("fields", "id, from, to"),
                Parameter.with("message", "private reply"));

**Comment by nbartels** [comment]
Hm, without check this actually in code, I think will look like:

```java
// specify the version you like to use, or latest for the latest supported version (in restfb 1.43: 2.9)
FacebookClient client = new DefaultFacebookClient("<token>", Version.Version.LATEST);
Message newMessage = client.publish("465764050424641_485798388421207/private_replies",
                 Message.class, // the type of the Facebook response
                 Parameter.with("message", "private reply"),
                 Parameter.with("fields", "id,from,to,message,created_time"));
```

**Comment by thienit5** [comment]
I try with comment, private_replies, it is ok
But with message it returns only id

Message message = client.publish("t_mid.$cAAayfWUcmARj08i0b1dooNnd8O7g/messages", Message.class,               
                Parameter.with("message", "Hi Tran duc thien"),
                Parameter.with("fields", "id, from, to, message, created_time, attachments"));

Response:
Message[attachments=[] createdTime=null from=null id=m_mid.$cAAayfWUcmARj144YQVdpkjPfcFKM message=null metadata=null shares=[] subject=null tags=[] to=[] type=null unread=null unseen=null updatedTime=null]

**Comment by nbartels** [comment]
ah yes, I think I read about this last day or the day before. But I'm not sure where, Stackoverflow or in the Facebook bugtracker ... as soon as I find this issue again, I'll update this.
