### ISSUE TITLE
Messenger Platform 2.1: support NLP on messages

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#765]
Messages can contain NLP information, we have to provide a way to convert it into a usable java object.

**Comment by RedEagle** [comment]
The entities parameter that is being sent by Messenger Platform is an object but "convertedEntities" global variable is a List<BaseNlpEntity>.

**Comment by nbartels** [comment]
There is no problem with convertedEntities because the rawEntities contains the object and this is converted into a list. But obviously we have to provide a more flexibel class that extends the BaseNlpEntity. ATM I made the wrong assumption it would be intend (with the d). But this was only a custom name in my wit.ai configuration. So we have a stupid and bad bug ;) Thanks for your hint!

**Comment by nbartels** [comment]
Moved the latest problem to https://github.com/restfb/restfb/issues/782
