### ISSUE TITLE
Resumable Upload

### ISSUE THREAD

**Issue by KyleBrownUbnt** [restfb/restfb#767]
I am having two separate issues with your Resumable Upload implementation. First, on the finish method, I am getting the following error.....

"Don't know how to map JSON to class com.facebook.GraphResponse. Are you sure you're mapping to the right class? Offending JSON is '{"success":true}'."

Second, as you can see above, I am receiving a success=true response from the Facebook Server, however the video never uploads to facebook. Do you have any idea as to why these issues may be occurring? My code directly matches the code you have on restFB's website. I can still post it if youd like to see it though

**Comment by nbartels** [comment]
can you please provide some more information about the code you are using. Does it depend on an integration test or example in our docs? Can you provide snippet?

**Comment by KyleBrownUbnt** [comment]
Absolutely! Here's the entirety of the code I use to post. I monitor the output and the video makes it through the Transfer phase successfully but does not post for some reason

`File videoFile = new File(paths.get(0));
        long filesizeInBytes = videoFile.length();
        // We need the file size in bytes to make the start request
        FacebookClient fbc = new DefaultFacebookClient(Constants.FACEBOOK_TOKEN,  Version.LATEST);
        ResumableUploadStartResponse returnValue = fbc.publish(Constants.FACEBOOK_ID+"/videos",
                ResumableUploadStartResponse.class, // The return value
                Parameter.with("upload_phase", "start"), // The upload phase
                Parameter.with("file_size", filesizeInBytes)); // The file size

        long startOffset = returnValue.getStartOffset();
        long endOffset = returnValue.getEndOffset();
        String vidId = returnValue.getVideoId();
        int length = (int) (endOffset - startOffset);

        // The upload session ID is very important, because Facebook needs
        // this ID to identify all the uploads that belong together
        String uploadSessionId = returnValue.getUploadSessionId();
        while (length > 0) {
            // First copy bytes in byte array
            byte fileBytes[] = new byte[length];
            in.read(fileBytes);

            // Make the request to Facebook
            ResumableUploadTransferResponse filePart = fbc.publish(Constants.FACEBOOK_ID+"/videos",
                    // The returned object
                    ResumableUploadTransferResponse.class,
                    // The file chunk that should be uploaded now
                    BinaryAttachment.with("video_file_chunk", fileBytes),
                    // Tell Facebook that we are in the transfer phase now
                    Parameter.with("upload_phase", "transfer"),
                    // The offset the file chunk starts
                    Parameter.with("start_offset", startOffset),
                    // The important session ID of this file transfer
                    Parameter.with("upload_session_id", uploadSessionId));

            // After uploading the chunk we recalculate the offsets according to the
            // information provided by Facebook
            startOffset = filePart.getStartOffset();
            endOffset = filePart.getEndOffset();
            length = (int) (endOffset - startOffset);
        }
        GraphResponse finishResponse = fbc.publish(Constants.FACEBOOK_ID+"/videos",
                GraphResponse.class,
                Parameter.with("upload_phase", "finish"), // Tell Facebook to finish the upload
                Parameter.with("upload_session_id", uploadSessionId));
        Log.d("The_end", String.valueOf(finishResponse.getRequest()));`

**Comment by KyleBrownUbnt** [comment]
To answer your first question it depends on examples in your docs. I gravitated towards your code because attaching a chunked binary file has proved difficult over the regular Graph API or HTTPPost methods

**Comment by KyleBrownUbnt** [comment]
Update, when the facebook SDK is included while using restFB the default GraphResponse is facebook SDK version. Must use com.restfb.types.GraphResponse. However, video is still not posting to facebook.

**Comment by nbartels** [comment]
Okay, this explains why RestFB was not able to map the json to the GraphResponse object. Regarding the Upload I'm already checking it ... stay tuned ;)

**Comment by KyleBrownUbnt** [comment]
Thank you!

**Comment by nbartels** [comment]
Okay, so I tried this myself and the video was uploaded as expected, but I had to add a small change to your code. Here is your code with the modification and I think you can simply replace yours with it.

```java
File videoFile = new File(paths.get(0));
long filesizeInBytes = videoFile.length();
// +++ NB: we need a input stream, without this the uploading will not work
FileInputStream in = new FileInputStream(videoFile);
// +++ NB
// We need the file size in bytes to make the start request
FacebookClient fbc = new DefaultFacebookClient(Constants.FACEBOOK_TOKEN,  Version.LATEST);

ResumableUploadStartResponse returnValue = fbc.publish(Constants.FACEBOOK_ID+"/videos",
                ResumableUploadStartResponse.class, // The return value
                Parameter.with("upload_phase", "start"), // The upload phase
                Parameter.with("file_size", filesizeInBytes)); // The file size

long startOffset = returnValue.getStartOffset();
long endOffset = returnValue.getEndOffset();
String vidId = returnValue.getVideoId();
int length = (int) (endOffset - startOffset);

// The upload session ID is very important, because Facebook needs
// this ID to identify all the uploads that belong together
String uploadSessionId = returnValue.getUploadSessionId();
while (length > 0) {
      // First copy bytes in byte array
      byte fileBytes[] = new byte[length];
      in.read(fileBytes);

      // Make the request to Facebook
      ResumableUploadTransferResponse filePart = fbc.publish(Constants.FACEBOOK_ID+"/videos",
      // The returned object
      ResumableUploadTransferResponse.class,
      // The file chunk that should be uploaded now
      BinaryAttachment.with("video_file_chunk", fileBytes),
      // Tell Facebook that we are in the transfer phase now
      Parameter.with("upload_phase", "transfer"),
      // The offset the file chunk starts
      Parameter.with("start_offset", startOffset),
      // The important session ID of this file transfer
      Parameter.with("upload_session_id", uploadSessionId));

      // After uploading the chunk we recalculate the offsets according to the
      // information provided by Facebook
      startOffset = filePart.getStartOffset();
      endOffset = filePart.getEndOffset();
      length = (int) (endOffset - startOffset);
      // +++ NB: added current uploaded percentage to the log - can be removed 
      Log.d("uploading_finished", String.valueOf(startOffset * 100.0 / filesizeInBytes));
      // +++ NB:
}

GraphResponse finishResponse = fbc.publish(Constants.FACEBOOK_ID+"/videos",
                GraphResponse.class,
                Parameter.with("upload_phase", "finish"), // Tell Facebook to finish the upload
                Parameter.with("upload_session_id", uploadSessionId));
Log.d("The_end", String.valueOf(finishResponse.getRequest()));
```

**Comment by KyleBrownUbnt** [comment]
Thank you sir! I am a somewhat novice programmer so I missed the necessity of the input stream. Hope your day goes well! Also, thank you for designing such a simple and intuitive API. It helped me out a lot

**Comment by nbartels** [comment]
I'll add the missing line to the documentation soon. Thanks for pointing to the problem.
