### ISSUE TITLE
message_tags not retrieved for type = "user"

### ISSUE THREAD

**Issue by rberga** [restfb/restfb#768]
I'm using RestFB to get the data for Facebook comments, in particular the message_tags. It seems to work fine when the type of the message_tag is a "page", but I get an empty list when the type = "user". Here is the FB comment id where this happens: **10156566664184478_10156576298439478**
I'm using the following call to get the message_tag list:

`List msgtaglist = comment.getMessageTags();`

to get the list of MessageTag's. But it returns an empty list for the comment above, although the FB Graph Explorer shows there is a message tag. 
I've tried RestFB versions 1.42 and 2.0.0.

Reinaldo

**Comment by nbartels** [comment]
Okay, so I used the id and built a unit test. But I cannot reproduce the problem.

Can you please write down the call you are using to fetch the comment?

**Comment by rberga** [comment]
Hi,
I was able to reproduce the problem with the following piece of code:

```
public static void main()
{
	final String FBTOKEN = "please-add-your-own-token";	   // not page/post owner

	// get FacebookClient
	FacebookClient facebookClient = new DefaultFacebookClient(FBTOKEN, Version.LATEST);
		
	// get messages associated with this post
	String postId = "162523134477_10156566664184478";
	Connection<Comment> postComments = facebookClient.fetchConnection(postId+"/comments", Comment.class, Parameter.with("fields", "id, permalink_url, from, created_time, message, message_tags, attachment"));
		
	for (List<Comment> commts: postComments) {
		for (Comment comm : commts) {
			System.out.println("Comment date: " + comm.getCreatedTime());
			System.out.println("          id: " + comm.getId());
			System.out.println("         msg: " + comm.getMessage());
			System.out.println("        user: " + comm.getFrom().getName());

                        // The two "if"s below are 2 examples of comment ids that work and not work. You can
                        // put breakpoints in them to stop executing only at the interesting comments.
			if (comm.getId().equals("10156566664184478_10156576809999478")) {
				System.out.println("This one works - the message_tags list has 1 element with MessageTags.type = page\n");
			}
			if (comm.getId().equals("10156566664184478_10156576298439478")) {
				System.out.println("This one does not works - the message_tags list is empty altough the FB explorer indicats 1 element with MessageTags.type = user\n");
			}
				
			// get mentions from field message_tags if present.
			List<MessageTag> msgtaglist = comm.getMessageTags();
			if ((msgtaglist!=null) && (!msgtaglist.isEmpty())) {
				for(MessageTag mt: msgtaglist) {
					System.out.printf("msgtag.name = %s, msgtag.type = %s\n", mt.getName(), mt.getType());
				}
			}							
		}	
	}
}

```
Please find enclosed the screen shot from the FB Graph explorer showing that the comment in question does have message_tags.
Thanks!

Reinaldo

![fbgraphapiexplorer_msgtag](https://user-images.githubusercontent.com/30734559/28995855-42dd4fd6-79ca-11e7-9736-8a576c477647.png)

**Comment by nbartels** [comment]
I changed your code a bit to get only the two interesting ids in the `System.out` and still cannot reproduce this.

The output is this. First we have the `Comment` that is working:
```
This one works - the message_tags list has 1 element with MessageTags.type = page

Comment date: Mon Jul 31 17:16:11 CEST 2017
          id: 10156566664184478_10156576809999478
         msg: Faltou fazer o evento em Brasília, capital do Rock, e reduto de grandes guitarristas também, como Marcelo Barbosa Official! Mas parabéns e que seja um ótimo evento!
        user: Alexander Marinho
msgtaglist.size() = 1
msgtag.name = Marcelo Barbosa Official, msgtag.type = page
```
I write the msgtaglist size to std out, too. As expected everything is fine.

Now we check the non-working example, but this looks almost the same and is working, too.
```
This one does not works - the message_tags list is empty altough the FB explorer indicats 1 element with MessageTags.type = user

Comment date: Mon Jul 31 15:17:29 CEST 2017
          id: 10156566664184478_10156576298439478
         msg: Pedro Padilha
        user: Laércio Paixão
msgtaglist.size() = 1
msgtag.name = Pedro Padilha, msgtag.type = user
```

The only reason for this - in my opinion - it is a policy setting. Can you try it with another users access token?

**Comment by nbartels** [comment]
*Just another idea:* You wrote that you can fetch the data in the Graph API Explorer, but not with your app. So can you please switch the application in the Graph API Explorer to the one you would normally use. Perhaps this brings some new insights.

**Comment by rberga** [comment]
I'm sorry for taking so long to get back. But I have confirmed your suspicions about the policy setting on the access token. The problems does NOT happen when I user a "user access token". However it does happen when I use a "app access token". 
Even in the FB Graph explorer, if I use an "app acess token" I cannot see the message_tags that list users.
In summary, the "app access token" allows one to see the message-tags that refer to other pages, but NOT to individual users (even if that user's page is public.
I don't understand why FB would make such distinction if the user pages are public.
In any case, thanks for your quick feedback and suggestions.

**Comment by nbartels** [comment]
No problem. This is good to know and maybe interesting for other user. Your investigation of the access token differences are really interesting.
