### ISSUE TITLE
DefaultFacebookClient.obtainUserAccessToken() not returning an expiration date

### ISSUE THREAD

**Issue by tcourdy** [restfb/restfb#770]
Hello - 

Using the following code:
`FacebookClient client = new DefaultFacebookClient(Version.LATEST);`
`AccessToken userToken = client.obtainUserAccessToken(clientID, clientSecret, redirectOnSuccessURI, code);`

`userToken.getExpires()` is always null.

Is this a bug or is this expected behavior?

Thank you for your time.

**Comment by nbartels** [comment]
I just tried the login flow and the returned JSON does not contain an `expires_in` field. Therefore the `getExpires` method returns null. Perhaps it is provided in an other login flow configuration. 

So the answer to your question is: it depends and it might be null.

**Comment by tcourdy** [comment]
Thank you for the quick response.

Is it possible to update the documentation for future users?

https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#exchangecode

I will look for another way to get the expires_in field.  Do you have 
any recommendations?

Thank you for your time.

-Tarik

**Comment by nbartels** [comment]
I cannot update the Facebook documentation :) But I think I have to investigate this further and maybe this is a bug on Facebook or I'll find the correct configuration to get the expires_in field.

**Comment by tcourdy** [comment]
Thank you very much for investigating this further.

**Comment by tcourdy** [comment]
What was the result of this?

**Comment by nbartels** [comment]
In the https://github.com/restfb/restfb-examples/tree/dev project, there is a an example JavaFX browser that is used to fetch a user access token and logs the token and the expires date. This is working as expected. 

<img width="953" alt="oauth setting with expires_in" src="https://user-images.githubusercontent.com/1113969/50737363-842a3200-11c8-11e9-9d28-b177b2e4dc5e.png">
