### ISSUE TITLE
Received Facebook error response of type OAuthException: (#100) Parameter since: Must be a unixtime or a date/time representation parseable by strtotime() (code 100, subcode null)

### ISSUE THREAD

**Issue by tcourdy** [restfb/restfb#771]
When running this code:

``Connection<Insight> conn = facebookClient.fetchConnection(testQuery, Insight.class, Parameter.with("since", new DateTime(queryInfo.getStart())), Parameter.with("until", new DateTime(queryInfo.getEnd())), Parameter.with("period", providerField.getMetricPeriod()));``

I get the error that is the title of this issue.

I am using Joda's DateTime()

the testQuery is of the format {pageid}/insights/{metric name}  (the metric name I am using in this case is page_fan_adds)

Both queryInfo.getStart() and queryInfo.getEnd() are long values that represent milliseconds since epoch.

When running php's strtotime on both the values output using ``new DateTime(queryInfo.getStart())`` or ``new DateTime(queryInfo.getEndTime())``, the appropriate dates are returned.

Is there something I'm missing that is preventing facebook from handling my request correctly or is their a bug in the restfb implementation?

I am using restfb v1.43.0

Thank you for your time

**Comment by tcourdy** [comment]
**Update**

Using just the ``queryInfo.getStart() / 1000`` is working.

**Comment by nbartels** [comment]
The JodaTime `DateTime` is a problem because the `Parameter` uses the JsonMapper to convert the object to a String. We have a special handling for the `java.util.Date`, therefore you can use it in the `Parameter` object.

I suggest you simply use the long value as you already discovered.
