### ISSUE TITLE
restfb not supporting FB API v2.10

### ISSUE THREAD

**Issue by jcdavidconde** [restfb/restfb#773]
Hi

I'm having some trouble using your library with the recent Facebook API Graph version (v2.10).
I had to fork your repository in order to modify the Version enum adding a new item for 2.10 version.
Could you take this in consideration for your next release?

Thanks

**Comment by nbartels** [comment]
The Graph API 2.10 enum is already in our dev branch and is part of the 1.44 release. 

You can build a snapshot, or have to wait until the next release and we hope to manage this soon.
