### ISSUE TITLE
Reply Message 

### ISSUE THREAD

**Issue by thienit5** [restfb/restfb#776]
i have a problem.
I want to send a message use conversation_id, not use recipient_id
Example:
String url = "http://content.pages.fm/2016/11/8/fc0660e6afd35add5644edc696e658251c12d177.jpg";
MediaAttachment attachment = new MediaAttachment(MediaAttachment.Type.IMAGE, url);
com.restfb.types.send.Message message = new com.restfb.types.send.Message(attachment);
        Message result = client.publish("t_mid.$cAAayfWUcmARj08i0b1dooNnd8O7g/messages",  Message.class, 
Parameter.with("message", message));

But, it sent to facebook:  {"attachment": {"payload": {"url": <path of image above>, {"type": image}}, not attach file.
How can i publish a attachment message by conversation_id?
Thanks

**Comment by nbartels** [comment]
There is a difference between sending with Send API and with Graph API. The first one is used with the messenger platform and there you can add files to the message (or the template) you send. 

The Graph API does not support sending messages with attachments. 

Your endpoint looks like you try to send a Send API object to a Graph API endpoint and this will not really work. 

https://developers.facebook.com/docs/messenger-platform/send-api-reference/image-attachment
vs 
https://developers.facebook.com/docs/graph-api/reference/v2.9/conversation/messages/
