### ISSUE TITLE
Null email for just one user

### ISSUE THREAD

**Issue by suzgjacobs** [restfb/restfb#777]
For most of my users, things are working very well.  But, for one user, the email is coming back null.

Facebook's access token debugger says my access token is valid, and Scopes are email, public_profile.  And I get first name, last name, and id fine.

In facebook's About/Contact and Basic Info, the user's Email is set to "Friends" and "Hidden from Timeline".  Same as other users who have no problem.  Is there some other setting I should look at, or do I have a problem in my code?

```
Facebook Client fc = new DefaultFacebookClient(ckAccessToken, Version.VERSION_2_9);
User u = fc.fetchObject("me", User.class, Parameter.with("fields", "id, first_name, last_name, email"));

```

**Comment by nbartels** [comment]
you can try the access token and your request in the Graph API Explorer, but I think it is a Facebook Problem. According to the information you already gave to us, there is at least an email. Because some users don't have an email and a phone number only.

**Comment by suzgjacobs** [comment]
Tx, you were right.  Graph API Explorer did the same thing - no email returned from that user.

So I added a 2nd email to that user.  Then deleted that 2nd email.  Now everything works fine!   :)   Mysterious.
