### ISSUE TITLE
Increasing number of FacebookNetworkExceptions

### ISSUE THREAD

**Issue by amanduggal** [restfb/restfb#778]
Hi ,

For the past few days, we have been seeing an increasing number of FacebookNetworkExceptions. In the last 24 hours, we saw 475 of these errors. Specifically,

```
com.restfb.exception.FacebookNetworkException: A network error occurred while trying to communicate with Facebook: Facebook request failed (HTTP status code null)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1038)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:977)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:939)
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:399)
```

I filed a Facebook bug (https://developers.facebook.com/bugs/1180812125356821/) to see if they had any insights but got a generic response saying that its a restfb issue. From looking at the code, it seems FacebookNetworkException can be thrown mainly for network errors. We have seen this error while trying to fetch objects and attempting to post to FB. 

Does anyone have any ideas on what I can look at outside of Facebook for this? We have a Java app that is making API calls.

**Comment by nbartels** [comment]
You should try setting the log level of `com.restfb.HTTP` to `FINE` or `DEBUG` depending on your logging framework. Then you can see what you send to Facebook and what you receive from Facebook in return. Perhaps this information is helpful ...

**Comment by nbartels** [comment]
@amanduggal what about the network error. Is it still there and do you have some insights after changing the log level?
