### ISSUE TITLE
Posting Picture Link not using all parameters

### ISSUE THREAD

**Issue by cal-holman** [restfb/restfb#783]
I have been using restfb for a few years to post messages on my facebook page based on loading a picture on my personal site.  While there was little (no) doc on how the various fields were displayed i experimented and achieved a look.  The last time i posted successfully was 6 June.  Since 20 Aug the same code resulted in an odd post with many of the parameters not showing up in facebook.  I upgraded to the latest restfb and same results.  I have tried to figure out what i am doing incorrectly and can see no issue.   I have not tried the API without restfb.  No error being returned by facebook.  The "description", "name", and "caption" are not appearing in the posting. My code is below. I am also including the before and after facebook postings for refrence.  Thanks.

publishMessageResponse =
                facebookClient.publish(CAL_HOLMAN + "/feed", GraphResponse.class,
                                       Parameter.with("message", thePicture.getTitle() + " is on our website in larger size, click on photo"),
                                       Parameter.with("link", "http://www.calandva.com/holmansite/do/scrapbook/ScrapbookDisplayPicture?SelectedPicture=" + thePicture.getPictureKey()),
                                       Parameter.with("picture", "http://www.calandva.com/holmansite/ServeImage?pictureSquare=155&file="  + thePicture.getBlobKey()),
                                       Parameter.with("name", thePicture.getTitle()),
                                       Parameter.with("caption", theReturnDate),
                                       Parameter.with("description", thePicture.getDescription() + " Taken on " + theReturnDate));
        }
![capture2](https://user-images.githubusercontent.com/8411590/30181444-e3335a48-93d8-11e7-8c4f-1ee8ae9443e4.JPG)
![capture1](https://user-images.githubusercontent.com/8411590/30181443-e32e9576-93d8-11e7-9c69-55980370b858.JPG)

**Comment by nbartels** [comment]
I think this is the explanation:
https://developers.facebook.com/blog/post/2017/06/27/API-Change-Log-Modifying-Link-Previews/

Facebook changed the way additional information can be added to a link. You have to provide picture, caption and things like that as open graph metadata. 

Please check the possibility, because you won't get any error but the link looks different.

**Comment by cal-holman** [comment]
Thanks for the quick reply.  Did not think Fake News would impact me.  I have coded a work around.  Again thanks for the great project.
