### ISSUE TITLE
WebhookObject parsing exception (2.0-rc.3)

### ISSUE THREAD

**Issue by jflebeau** [restfb/restfb#786]
`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'getStarted': was expecting ('true', 'false' or 'null')`

doing : 
`WebhookObject` wo = fbJsonMapper.toJavaObject(body, WebhookObject.class);`

**Comment by nbartels** [comment]
Hm, we don't use Jackson, so the exception should have another source. Can you please provide the whole stacktrace (obfuscate internal classes if needed).

**Comment by jflebeau** [comment]
My bad.

**Comment by nbartels** [comment]
no problem
