### ISSUE TITLE
Searching people by city

### ISSUE THREAD

**Issue by damluar** [restfb/restfb#789]
Hello Norbert,

thanks for your great work! Could you tell me if there is a way to find all people from (or living in) a particular city? Facebook web page allows it by typing in `People who live in Rome, Italy`. This request leads to https://www.facebook.com/search/115353315143936/residents/present. Facebook also has a filter on the left side allowing to choose a city. I tried to use `fetchConnection` method with `q` set to `People who live in Rome, Italy`, but it returns nothing.

Vielen Dank im Voraus :)

Regards,
Konstantin.

**Comment by nbartels** [comment]
Hi Konstantin,

according to the API this is not possible. Searching for user objects allows only the `q` parameter to be the name (or part of the name). https://developers.facebook.com/docs/graph-api/using-graph-api#search
