### ISSUE TITLE
Debug information

### ISSUE THREAD

**Issue by tonci** [restfb/restfb#790]
It will be very convenient to have a method to retrieve the post/get request made to facebook in order for easier debugging.

The best scenario would be to return curl structured command (string).

Also the response in json format would be very helpful, as fb support is always asking for more information (request/response).

**Comment by nbartels** [comment]
So we checked this issue again and we will not add this feature to the library.

* Logging provides the desired information and a developer should only have to work with these URLs in exceptional cases. In such a case she may look at the log files. During normal workflows the URLs are not needed.
* The `DefaultWebRequestor` implements the `WebRequestor` interface and therefore the developer can extend the `DefaultWebRequestor` or write a new `WebRequestor` that provides the desired information.  This should be possible with only some lines of code.
