### ISSUE TITLE
Add object for Pass/Take Thread Control API

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#806]
The [Pass Thread Control API](https://developers.facebook.com/docs/messenger-platform/reference/handover-protocol/pass-thread-control) and [Take Thread Control API](https://developers.facebook.com/docs/messenger-platform/reference/handover-protocol/take-thread-control) provide API's to pass and take the thread control.

E.g.:
```
curl -X POST -H "Content-Type: application/json" -d '{
  "recipient":{"id":"<PSID>"},
  "target_app_id":123456789,
  "metadata":"String to pass to secondary receiver app" 
}' "https://graph.facebook.com/v2.6/me/pass_thread_control?access_token=<PAGE_ACCESS_TOKEN>"
```

Would it be useful to create objects for these?
Note the `recipient` field is a nested object. Can we already do something like this without an explicit object?

**Comment by nbartels** [comment]
I suggest this call:

```java
GraphResponse result = 
   facebookClient.publish("me/pass_thread_control", 
   GraphResponse.class, // result type
   Parameter.with("recipient", new IdMessageRecipient("<PSID>")),  // recipient
   Parameter.with("target_app_id", 123456789), // app
   Parameter.with("metadata", "String to pass to ...")); // metadata
```

So I think is is more a documentation issue.

Sending a JSON in the body without using `Parameter.with` is not possible with the current implementation. That will be solved in a later version (2.x or 3).

**Comment by marceloverdijk** [comment]
OK thx, that is sufficient.
I wasn't aware the `Parameter.with` would take care of the nested `recipient` field.

**Comment by nbartels** [comment]
`Parameter.with` uses our mapper to convert objects into JSON. This direction works the same way as the other direction without some kind of post processing method (`JsonMappingCompleted`) . The `Facebook` annotated fields are added to the JSON and normally null fields are not transferred.

I let this one open until it is added to the documentation.
