### ISSUE TITLE
Async API extension

### ISSUE THREAD

**Issue by johnou** [restfb/restfb#812]
Currently restfb provides a blocking API implementation which might cause problems eg. thread starvation if there is a network interruption between Facebook and the service running restfb.

I propose to extend the restfb API to include non-blocking / async methods [1] which will allow developers to easily plugin a http client which supports async requests / responses.

[1]
```java
<T> CompletionStage<T> fetchObject(String object, 
         Class<T> objectType, Parameter... parameters)
```

Thoughts? I will try and reserve a bit of time to create a prototype with async-http-client.

**Comment by nbartels** [comment]
Sounds interesting, but I think most users put the restfb client in a thread to solve the problem. However, I'd like to see your prototype.

**Comment by johnou** [comment]
Sure, offloading restfb work to a threadpool will help to an extent but one thread per connection simply does not scale.

**Comment by johnou** [comment]
@nbartels I created a mini project which hopefully shows what I described above. You can check out the source here https://github.com/johnou/async-restfb

**Comment by johnou** [comment]
I'll close this for now, the prototype extension is good enough for our use case.

**Comment by nbartels** [comment]
OK, I had a look at the code and it looks really exciting. But atm I cannot merge this into RestFB and I think we have to discuss this internally first. However, these changes cannot be made that soon.

Thanks for your effort.
