### ISSUE TITLE
Send private message to friend error: com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#100) No matching user found (code 100, subcode 2018001)

### ISSUE THREAD

**Issue by apovn** [restfb/restfb#814]
Hi 

I get this error when I send a private msg to my friend: 
`Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#100) No matching user found (code 100, subcode 2018001)
	at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1278)
	at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1195)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1136)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:1058)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:493)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:518)
	at Main.main(Main.java:23)`

My source code look like:
`        FacebookClient facebookClient = new DefaultFacebookClient(MY_ACCESS_TOKEN, Version.LATEST);

        IdMessageRecipient recipient = new IdMessageRecipient("10202989806958658");

        Message simpleTextMessage = new Message("Just a simple text");

        facebookClient.publish("me/messages", GraphResponse.class,
                Parameter.with("recipient", recipient),
                Parameter.with("message", simpleTextMessage));`

My FB app version is v2.10, I'm using restfb-1.46.0.jar library, Java 8.
Do you know about this error ?
Could you help me to fix it ?

Thank you

**Comment by nbartels** [comment]
According to your snippet you use the Messenger Platform Send API to send a message to your friend. So you implemented a chatbot? Because the recipient id used in your request is send to you via the chatbot webhook. The id is a page scoped user id, so if you try to use the API without a valid id you see the message above.

**Comment by apovn** [comment]
Hi, thank you for your answer.
I don't implement chatbot. Is this valid if I have a page and I directly send private message to some friends without chatbot. Or I must implement chatbot ?
Thank you

**Comment by nbartels** [comment]
In general it is not possible to send messages to someone without he/she contacts your page first. 

You can check the `me/conversations` endpoint. There you'll find the conversations between your page and the users. You can fetch snippets of the conversations and the participants. Every conversation or thread has it's own id. With this id you can then fetch the messages (`<thread-id>/messages`). And you can post new messages, but only test messages re possible.
