### ISSUE TITLE
Sending file as BinaryAttachment

### ISSUE THREAD

**Issue by zvyagintsev** [restfb/restfb#815]
I need to send a message with a file as a BinaryAttachment to an user. I have valid token and valid user Id (I can send a simple text message). I try this code:
```
final IdMessageRecipient recipient = new IdMessageRecipient(userId);
FacebookClient fbClient = new DefaultFacebookClient(accessToken, Version.LATEST);
fbClient.publish(
    "/me/messages",
    GraphResponse.class, 
    Parameter.with("recipient", recipient),
    Parameter.with("attachment", attachment)
);
```
As a result, I get: 
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#100) Must send either message or state (code 100, subcode 2018015)

Could you tell me, where an error in my code?

**Comment by nbartels** [comment]
Sending an attachment via the Send API is atm not possible with RestFB. I'll add an issue for that problem. But in the meantime you can work with reusable attachments or use URLs. 

For reusable attachments you upload an asset to a special endpoint and get an id, this id can be used in your message. (see https://developers.facebook.com/docs/messenger-platform/send-messages/saving-assets/#attachment_upload_api)

Working with urls requires the asset to be publicly available. You can check the examples here: http://restfb.com/documentation/#messenger-imagemessage

**Comment by zvyagintsev** [comment]
Thank you for the answer!
I usually send attachments via MediaAttachment (as in your sample), but in some cases file names contain spaces (for example `some file.docx`), so it's necessary to encode the URL. But after sending the files, Messenger does not decode the names of the attachments. 
Could you suggest a solution to this problem?

**Comment by nbartels** [comment]
How do you encode the files? And are the accessible in the Messenger with bad looking names or are they ignored completely?

**Comment by zvyagintsev** [comment]
I encode an URL using 
```
URLEncoder.encode(fileUrl, StandardCharsets.UTF_8.name());
```
After receiving a message with bad looking name is accessible in the Messenger.

**Comment by nbartels** [comment]
So the problem is on Facebook side? It looks like they don't decode the filename correctly. So I suggest open a bug here: https://developers.facebook.com/bugs/
