### ISSUE TITLE
Graph API 2.11: add new version to version enum

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#816]

**Comment by torbenw** [comment]
Is there already a release date for this new RestFB version?

**Comment by nbartels** [comment]
No, not atm. But I have to add the messenger platform 2.2 changes first, so we provide a new version that provides changes and fixes for both: Messenger Platform AND Graph API. 

I think we will manage to release the new version next week.

**Comment by nbartels** [comment]
@torbenw 1.48.0 is released!

**Comment by torbenw** [comment]
Thank you!
