### ISSUE TITLE
Incompatible types: java.util.List<com.restfb.types.Insight> cannot be converted to com.restfb.types.Insight

### ISSUE THREAD

**Issue by aaronbenjaminhm** [restfb/restfb#822]
Hi, I am attempting to fetch Facebook Insight data from a band page and getting an Incompatible Type error during 'mvn compile'.

**CODE SNIPPET....**

	  Connection<Insight> insights = 
				facebookClientLatest.fetchConnection("DemuirBeats/insights", 
				      Insight.class, // the insight type
				      Parameter.with("metric", "page_fan_adds_unique,page_fan_adds")); 

	  for (Insight insight : insights) {
		  out.println(insight.getValues());
	  	}

**COMPILE ERROR.......**
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building RestFB examples 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ restfb-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ restfb-example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /Users/abenjamin/git/restfb-examples/target/classes
^[[A[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /Users/abenjamin/git/restfb-examples/src/main/java/com/restfb/example/LegacyExample.java: Some input files use or override a deprecated API.
[WARNING] /Users/abenjamin/git/restfb-examples/src/main/java/com/restfb/example/LegacyExample.java: Recompile with -Xlint:deprecation for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/abenjamin/git/restfb-examples/src/main/java/com/restfb/example/GraphReaderExample.java:[114,34] incompatible types: java.util.List<com.restfb.types.Insight> cannot be converted to com.restfb.types.Insight

**Comment by nbartels** [comment]
The for loop is simply wrong. A `Connection` object contains a list of Insights, so change the code to this:

```java
for (List<Insight> insightList : insights) {
    for (Insight insight : insightList) {
       out.println(insight.getValues());
    }
}
```

**Comment by aaronbenjaminhm** [comment]
It's working now thank you! I grabbed the original code from http://restfb.com/documentation/

**Comment by nbartels** [comment]
Many thanks for the hint. I'll add an documentation issue.

**Comment by aaronbenjaminhm** [comment]
Hi Norbert,

I may have spotted another code example typo in the documentation:

Under GETTING ANY KIND OF DATA AS A JSON OBJECT http://restfb.com/documentation/#creating-json-objects:
When using JsonObject in a Connection…

Example snippet: JsonObject photosConnection = facebookClient.fetchConnection("me/photos", JsonObject.class);
should be…
Connection<JsonObject> photosConnection = facebookClient.fetchConnection("me/photos", JsonObject.class);

**Comment by nbartels** [comment]
Good catch, I'll add another issue in our website project.
