### ISSUE TITLE
Search for groups doesn't work

### ISSUE THREAD

**Issue by finalspy** [restfb/restfb#823]
I'm used to search for pages containing a keyword using : 

`Connection<Page> targetedSearch = appFBclient.fetchConnection("search", Page.class,
        Parameter.with("q", keyword),
        Parameter.with("type", "page"),
        Parameter.with("fields", "id,description")
);`

It also works the same way for places : 

`Connection<Place> targetedSearch = appFBclient.fetchConnection("search", Place.class,
        Parameter.with("q", keyword),
        Parameter.with("type", "place")
);`

I tried to do the same for groups search : 
`Connection<Group> targetedSearch = appFBclient.fetchConnection("search", Group.class,
        Parameter.with("q", keyword),
        Parameter.with("type", "group"),
        Parameter.with("fields", "id")
);`

It reports the following error, on the fetchConnection line : 

> com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#200) Must have a valid access_token to access this endpoint (code 200, subcode null)
> 
> 	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerator.java:174)
> 	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookExceptionGenerator.java:59)
> 	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:945)
> 	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:867)
> 	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:829)
> 	at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:372)

Am i doing something wrong ? 
Do I need some specific permission to list groups ? 
Am i so blind that I can't see the mistake in my code?
Or is there a bug in the rest API?

(note: the requests is OK in the facebook graph explorer)

**Comment by nbartels** [comment]
Do you use a access token to generate the appFBclient? Did you check that access token in the access token debugger?

**Comment by finalspy** [comment]
Thanks for the quick tip Norbert ! It saved me time.

After checking my code, i noticed that I only used the client with the app token: 
`appFBclient = new DefaultFacebookClient(appToken, VERSION);`

So I tried with the client with a user access token and it worked : 
`userFBclient = new DefaultFacebookClient(userAccessToken, appSecret, VERSION);`

So basically the answer is that searching PAGES and PLACES works with an APP_TOKEN client
while searching for **GROUPS** needs a **USER_ACCESS_TOKEN** client.

I didn't notice anything about that in the Facebook documentation, but may be I'm too blind for that :/
