### ISSUE TITLE
Should the OpenGraphTemplatePayload have elements instead of buttons?

### ISSUE THREAD

**Issue by marceloverdijk** [restfb/restfb#826]
https://developers.facebook.com/docs/messenger-platform/send-messages/template/open-graph

```
"payload": {
  "template_type":"open_graph",
  "elements":[
     {
      "url":"<OPEN_GRAPH_URL>",
      "buttons":[<BUTTON_OBJECT>]             
    }
  ]
}
```

https://github.com/restfb/restfb/blob/f07dae117efede6e0b5e5861bfff7c2754b8aa3f/source/test/java/com/restfb/types/SendApiTest.java#L276

```
  @Test
  public void messageOpenGraphTemplateWithButton() throws JSONException {
    WebButton button = new WebButton("Check this", "http://www.google.com");
    OpenGraphTemplatePayload payload = new OpenGraphTemplatePayload("some url");
    payload.addButton(button);
    TemplateAttachment attachment = new TemplateAttachment(payload);
    Message recipient = new Message(attachment);

    DefaultJsonMapper mapper = new DefaultJsonMapper();
    String recipientJsonString = mapper.toJson(recipient, true);

    JSONAssert.assertEquals(
      "{\"attachment\":{\"payload\":{\"url\":\"some url\",\"template_type\":\"open_graph\",\"buttons\":[{\"type\":\"web_url\",\"title\":\"Check this\",\"url\":\"http://www.google.com\"}]},\"type\":\"template\"}}",
      recipientJsonString, false);
  }
```

I'm missing the `elements` array on the same level as `template_type` = `open_graph`.
Related to http://restfb.com/javadoc/com/restfb/types/send/OpenGraphTemplatePayload.html.

**Comment by nbartels** [comment]
It looks like the `url` and `buttons` should be added to a new JSONObject. This object is part of the `elements` JSONArray. 

Perhaps this was changed or bug that no one discovered yet :)

I'll change this according to the current JSON description
