### ISSUE TITLE
How to  get 3 second video views

### ISSUE THREAD

**Issue by manssa01** [restfb/restfb#829]
Hello,
I don't know how to use restfb to get 3 second video views on ads level regarding a campaign.

Could you please help?

Best regards,

**Comment by nbartels** [comment]
Do you have a link to the documentation, where I can find this.

**Comment by manssa01** [comment]
https://developers.facebook.com/docs/graph-api/reference/video/video_insights/

**Comment by manssa01** [comment]
My code is like that:

Ad.APIRequestGetInsightsAsync insightsAsync = new  Ad(adId, context).getInsightsAsync();
//                     AdReportRun report = insightsAsync
//				.requestField("account_name")
//		                .requestField("impressions")
//                                .requestField("spend")
//                                .requestField("reach")
//                                .requestField("total_actions")
//		                .requestField("clicks")
////		                .requestField("total_video_views")
////		                .requestField("cpc")
////		                .requestField("cost_per_action_type")
////		                .requestField("cost_per_unique_click")
////		                .requestField("cpm")
//                                .requestField("video_10_sec_watched_actions")
//                                .requestField("video_30_sec_watched_actions")
//                                .requestField("video_p100_watched_actions")
//                                .requestField("video_p95_watched_actions")
//                                .requestField("video_p75_watched_actions")
//                                .requestField("video_p50_watched_actions")
//                                .requestField("video_p25_watched_actions")
//		                .execute()
//		                .head();
//                                while (report.fetch().getFieldAsyncPercentCompletion() != 100) {
//			        try {
//						Thread.sleep(6000);
//					} catch (InterruptedException e) {
//						
//					}

**Comment by nbartels** [comment]
The link you mentioned will result in RestFB in something like this:


```java
Connection<Insight> insightsConnection = 
	facebookClient.fetchConnection("POST_ID/insights", 
	      Insight.class, // the insight type
	      Parameter.with("metric", "total_video_views_autoplayed,total_video_views_clicked_to_play"));

for (List<Insight> insights: insightsConnection) {
  for (Insight insight : insights) {
    out.println(insight.getName());
  }
}

```

I added only the `total_video_views_autoplayed` and the `total_video_views_clicked_to_play` metric, but you can add more separated with comma.

**Comment by manssa01** [comment]
Sorry,
https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group/insights/

But I could not find the fields.

Best regards,

**Comment by manssa01** [comment]
ould you please advise how to integrate that in my code?

**Comment by manssa01** [comment]
Hello,
I am trying to use RestFB to get somemetrics, I got the majority but the 3 second thing is missing, here is my code:

import com.facebook.ads.sdk.APIContext;
import com.facebook.ads.sdk.APIException;
import com.facebook.ads.sdk.APINodeList;
import com.facebook.ads.sdk.APIRequest;
import com.facebook.ads.sdk.Ad;
import com.facebook.ads.sdk.AdAccount;
import com.facebook.ads.sdk.AdSet;
import com.facebook.ads.sdk.AdsActionStats;
import com.facebook.ads.sdk.AdsInsights;
import com.facebook.ads.sdk.Campaign;
import com.restfb.Connection;
import com.restfb.json.JsonObject;
import com.restfb.types.Insight;
import java.util.Iterator;
import java.util.List;

/**
*

@author manssa01
*/

public static void main(String[] args) throws APIException {
APIContext("********************************************************************************************");
try {
APIRequest request = new APIRequest<>(context, "me", "/adaccounts", "GET", AdAccount.getParser());
APINodeList accounts = (APINodeList)(request.execute());
for (AdAccount account : accounts) {
APINodeList campaigns = new AdAccount( account.getId(), context).getCampaigns().requestAllFields()
.execute();
for (Campaign campaign : campaigns) {
APINodeList adSets = new Campaign( campaign.getId(), context).getAdSets().requestAllFields()
.execute();
for (AdSet adset : adSets) {

          APINodeList<Ad> ads = new AdSet( adset.getId(), context).getAds().requestAllFields()
 .execute();
          
          for (Ad ad:ads) {
               APINodeList<AdsInsights> adInsights = new Ad(ad.getId(), context).getInsights().requestField("what to write here")
 .execute();
                for (AdsInsights adInsight : adInsights) {
                    System.out.println(adInsight);
                    
                }
                }
               
          }
        }  
        }
} catch (Exception e) {
e.printStackTrace();
}
}

}

**Comment by nbartels** [comment]
Your example is not a RestFB code. It uses the Facebook Ads SDK I think, so I ported the calls to RestFB. Then I took your desired fields and added them to the last request, assuming you need that information.

Please check this.

Attention: I did not run the code, but used an IDE to write it. So there may be non-obvious errors in it ;)

```java
import com.restfb.Connection;
import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.Parameter;
import com.restfb.Version;
import com.restfb.json.JsonObject;
import com.restfb.types.ads.Ad;
import com.restfb.types.ads.AdAccount;
import com.restfb.types.ads.AdSet;
import com.restfb.types.ads.Campaign;
import java.util.ArrayList;
import java.util.List;

public class Example {
    
    public static void main(String[] args) {
        
        // fetch AdAccounts
        List<AdAccount> adAccounts = new ArrayList<>();
        FacebookClient fbClient = new DefaultFacebookClient("access token", Version.LATEST);
        Connection<AdAccount> connAdAccount = fbClient.fetchConnection("me/adaccounts", AdAccount.class);
        for (List<AdAccount> adAccountList : connAdAccount) {
            adAccounts.addAll(adAccountList);
        }

        // fetch campaigns
        List<Campaign> campaigns = new ArrayList<>();
        for (AdAccount adAccount : adAccounts) {
            Connection<Campaign> connAdCampaigns = fbClient.fetchConnection(adAccount.getId() + "/campaigns", Campaign.class);
            for (List<Campaign> adCampaingList : connAdCampaigns) {
                campaigns.addAll(adCampaingList);
            }
        }
        
        // fetch AdSets
        List<AdSet> adSets = new ArrayList<>();
        for (Campaign campaign : campaigns) {
            Connection<AdSet> connAdSets = fbClient.fetchConnection(campaign.getId() + "/adsets ", AdSet.class);
            for (List<AdSet> adSetList : connAdSets) {
                adSets.addAll(adSetList);
            }
        }

        // fetch Ads
        List<Ad> ads = new ArrayList<>();
        for (AdSet adSet : adSets) {
            Connection<Ad> connAds = fbClient.fetchConnection(adSet.getId() + "/ads ", Ad.class);
            for (List<Ad> adList : connAds) {
                ads.addAll(adList);
            }
        }
        
        // fetch Insights and print to Sysout
        for (Ad ad : ads) {
            String reqFiels = "account_name"
                    + ",impressions"
                    + ",spend"
                    + ",reach"
                    + ",total_actions"
                    + ",clicks"
                    + ",total_video_views"
                    + ",cpc"
                    + ",cost_per_action_type"
                    + ",cost_per_unique_click"
                    + ",cpm"
                    + ",video_10_sec_watched_actions"
                    + ",video_30_sec_watched_actions"
                    + ",video_p100_watched_actions"
                    + ",video_p95_watched_actions"
                    + ",video_p75_watched_actions"
                    + ",video_p50_watched_actions"
                    + ",video_p25_watched_actions";
            
            
            Connection<JsonObject> insightsConnection
                    = fbClient.fetchConnection(ad.getId() + "/insights",
                            JsonObject.class, // the insight type
                            Parameter.with("fields", reqFiels));

            for (List<JsonObject> insights : insightsConnection) {
                for (JsonObject insight : insights) {
                    System.out.println(insight);
                }
            }
        }
    }        
}
```

**Comment by manssa01** [comment]
Many thanks,
but how to get the field  3 second video views   with this code?

**Comment by nbartels** [comment]
According to the Marketing Ad reference there is no such metric on Ad. The 10 secs metric is the lowest you get. Perhaps the developer group on Facebook knows more ...

**Comment by manssa01** [comment]
There is on Video level, but how to get it from ad, no idea..
