### ISSUE TITLE
Unable to extract `unit` from `wit/amount_of_money` entity

### ISSUE THREAD

**Issue by RedEagle** [restfb/restfb#833]
If an entity of type `wit/amount_of_money` is extracted from a phrase, a `NlpCustomWitAi` class is  instantiated.

Unfortunately that class doesn't have a `unit` global value. 

```
{
  "entities": {
    "amount_of_money": [
      {
        "confidence": 0.936795,
        "value": 1000,
        "type": "value",
        "unit": "EUR"
      }
    ]
  }
}
```

**Comment by nbartels** [comment]
Many thanks for the JSON, Facebook has some more/new builtin types and you discovered one of them. I have to check them and add the new types. So please stay tuned. 😄

**Comment by RedEagle** [comment]
Thanks @nbartels 

Already have this issue in my bookmark bar ;)

**Comment by RedEagle** [comment]
Thanks @nbartels Looking forward for the release
