### ISSUE TITLE
Scheduled Feed Post OAuth Error

### ISSUE THREAD

**Issue by cal-holman** [restfb/restfb#835]
I am trying the code below and getting an OAuth error: OAuthException: An unknown error has occurred. (code 1, subcode null)

I used the code in the restfb doc - which uses a Date object and the parameter needs a Unix number - so i modified.  The code works without the "published" and "scheduled" parameters.  I tried removing the "link" parameter and just a message but received the same error.    I am trying to post a picture to my own feed.  I tried the other example in the doc in posting a picture to the feed but the picture did not display.  

`
        Date in15 = new Date(currentTimeMillis() + 1000L * 60L * 15L);
        long unixTime = in15.getTime() / 1000L;

            publishMessageResponse =
                facebookClient.publish(CAL_HOLMAN + "/feed", GraphResponse.class,
                        Parameter.with("message", thePicture.getDescription()),
                        Parameter.with("link", "http://www.calandva.com/holmansite/do/scrapbook/ScrapbookDisplayPicture?SelectedPicture=" + thePicture.getPictureKey()),
                        Parameter.with("published", false),
                        Parameter.with("scheduled_publish_time", unixTime));`

**Comment by nbartels** [comment]
Ever tried to use a page access token instead a user access token. In the Facebook documentation the possible parameters are different between [user](https://developers.facebook.com/docs/graph-api/reference/v2.11/user/feed) and [page](https://developers.facebook.com/docs/graph-api/reference/v2.11/page/feed).

**Comment by cal-holman** [comment]
Nope - i can't find an example in your doc - can i get the page access_token using restfb?

**Comment by cal-holman** [comment]
I see how to create a client with the page access token - is there a way to get my page id based on my user id)?

**Comment by nbartels** [comment]
With the page access token you post as a page not as a normal user. Afaik the Facebook GUI allows scheduling only for pages, so this should make no difference. 

You need a user access token with manage_pages and publish_pages permission. Then you can access me/accounts and take the page access token from the list of pages.

**Comment by cal-holman** [comment]
Thanks - i find navigating the facebook objects and permissions very confusing.  Sorry for all the basic questions.
