### ISSUE TITLE
DefaultFacebookClient.fetchObjects() uses comma separated list for ids

### ISSUE THREAD

**Issue by grumseren** [restfb/restfb#838]
When using fetchObjects to fetch objects identified by urls, the urls themselves can contain commas which in turn will fail the request on facebooks side, since they will split the string of ids on comma.

Facebook recommends using a JSON array instead of a comma separated list, so instead of sending
```
id_one,id_two
```
it should be
```
["id_one","id_two"]
```
I encountered this problem and got a response from facebook on this bug report: https://developers.facebook.com/bugs/1980759305580242/

**Comment by nbartels** [comment]
Thanks for the hint!
