### ISSUE TITLE
Reactions by type for a single post

### ISSUE THREAD

**Issue by joelforessottile** [restfb/restfb#840]
How can I get all reactions by type for a single post? I know that I can get the amount of reactions for every post, but I'd like to get them by type, just like in the graph api, for example:
`like_count: 10
sad_count: 13
love_count: 20`
and so on, But I can't get it, I tried by using `reaction.summary(1)` in the `Parameter.with` parameters, but that only allowed me to get the reactions count (`fbPost.getReactionsCount()`). So I also tried by saving `fbPost.getReactions()` in another variable and then iterate trough it, but I get nothing. 
```
Reactions r = tPost.getReactions();
List<ReactionItem> rr = r.getData();
					
for(int i = 0; i< rr.size(); i++) {
System.out.println(i+": "+rr.get(i));
}

```
And I checked if `rr `is empty and it certainly is.

**Comment by nbartels** [comment]
Yes, you can get the reactions by type. You have to extend the `Post` and the `Comment` type and use a custom implementation, because this is a custom requirement. Nevertheless I'll provide you an example, soon ;)

**Comment by joelforessottile** [comment]
@nbartels That would be very helpful. I  tried by doing the custom implementation, like in the Graph API Explorer, where I did get the reactions by type just like I wanted. I tried this same thing in the JavaScript SDK some time ago and It worked, but I can't make it work here, so I'd be very thankful If you could make some example. Thanks!

**Comment by nbartels** [comment]
You need two things. First you have to extend the `Post` or/and `Comment` type, depending on your use case. Here is the example for the `Post`:

```java
public class PostWithDetailedReactions extends Post {

  @Facebook("reactions_like")
  private Reactions reactionsLikes;

  @Facebook("reactions_love")
  private Reactions reactionsLove;

  @Facebook("reactions_wow")
  private Reactions reactionsWow;

  @Facebook("reactions_haha")
  private Reactions reactionsHaha;

  @Facebook("reactions_sad")
  private Reactions reactionsSad;

  @Facebook("reactions_angry")
  private Reactions reactionsAngry;

  @Facebook("reactions_thankful")
  private Reactions reactionsThankful;

  public Reactions getReactionsLikes() {
    return reactionsLikes;
  }

  public Reactions getReactionsLove() {
    return reactionsLove;
  }

  public Reactions getReactionsWow() {
    return reactionsWow;
  }

  public Reactions getReactionsHaha() {
    return reactionsHaha;
  }

  public Reactions getReactionsSad() {
    return reactionsSad;
  }

  public Reactions getReactionsAngry() {
    return reactionsAngry;
  }

  public Reactions getReactionsThankful() {
    return reactionsThankful;
  }
}
```

Then you can use that type in your `fetchObject` call and don't forget to modify the `fields`. You have to add this section to them:

```java
String fields = "id,message"; // the 'normal' fields
fields += ",reactions.limit(0).summary(1)" // reactions overview
        + ",reactions.type(LIKE).limit(0).summary(1).as(reactions_like)" // like reactions
        + ",reactions.type(LOVE).limit(0).summary(1).as(reactions_love)" // love reactions
        + ",reactions.type(WOW).limit(0).summary(1).as(reactions_wow)" // wow reactions
        + ",reactions.type(HAHA).limit(0).summary(1).as(reactions_haha)" // haha reactions
        + ",reactions.type(SAD).limit(0).summary(1).as(reactions_sad)" // sad reactions
        + ",reactions.type(ANGRY).limit(0).summary(1).as(reactions_angry)" // angry reactions
        + ",reactions.type(THANKFUL).limit(0).summary(1).as(reactions_thankful)"; // thankful reactions
```
Now you can use that `String` in the fetch call like this:

```java
PostWithDetailedReactions post = 
    fbClient.fetchObject(postId, PostWithDetailedReactions.class, Parameter.with("fields", fields));
```

Now you can work with the detailed reactions.

**Comment by joelforessottile** [comment]
@nbartels It worked perfectly! Thanks a lot for your help man.
