### ISSUE TITLE
Search for pages using fetchConnection("search",..  not returning all results

### ISSUE THREAD

**Issue by rberga** [restfb/restfb#841]
I'm searching for FB pages using the following code:

`	   FacebookClient fbClient = new DefaultFacebookClient(MY_TOKEN, Version.LATEST);
	   
	    try {
	    	Connection<Page> allPages = fbClient.fetchConnection("search", Page.class,
	    			Parameter.with("q", name),
	    			Parameter.with("type", "page"),
	    			Parameter.with("limit", limit),
	    			Parameter.with("fields", "fan_count,name,username,picture,url,link"));

			Iterator<List<Page>> it = allPages.iterator();
			boolean hasnext = it.hasNext();
			int n = 0;
			while (hasnext)  {
				List<Page> pageList = it.next();

				// up to limit results per pagination. Get only the first 'limit'
				// for (List<Page> pages: allPages) {
				for (int i = 0; i < pageList.size(); i++) {
					Page p = allPages.getData().get(i);
		    		if (p == null) {
						hasnext = it.hasNext();
		    			continue;
		    		}
		    		
		    		String pageName = p.getName();
		    		String pageId   = p.getId();
		    		String pageImg  = p.getPicture().getUrl();
		    		String pageUserName = p.getUsername();
		    		String pageUrl  = p.getLink();
		    		Long   pageFans = p.getFanCount();
		    		++n;
		    		System.out.printf("Found page %d: %s / %s / %d\n", n, pageName, pageUserName, pageFans);
		    	}
				
				// check for another element (another results page)
				hasnext = it.hasNext();
			}
	    }
	    catch (Exception e) {
	    	System.err.printf("Error in searchFacebookPages (msg = %s)", e.getMessage());
	    }
`
This code was working fine, until I tried to search for "volkswagen"
It does NOT return page @volkswagendobrasil . I got 374 results, of different volkswagen pages but NOT "volkswagendobrasil"

When I run the same query in the FB API Explorer:
search?type=page&q=volkswagen&fields=name,username,fan_count
I get "volkswagendobrasil" as the first result

data": [
    {
      "name": "Volkswagen",
      "username": "volkswagendobrasil",
      "fan_count": 32288857,
      "id": "195799454437"
    },
......

I'm using RestFB 2.0.0-rc3
Thanks

**Comment by nbartels** [comment]
Before we dig deep into the returned JSONs, I have two questions. First, do you use the same access token for both search requests?
Is the application located on a US server? I just tested the fanpage and cannot see it from Germany, so perhaps there is a limitation regarding the country the visitor is located in.

**Comment by nbartels** [comment]
With the new breaking changes (4 April, 2018) the `page` search type is no longer supported. I close this issue...
