### ISSUE TITLE
Screennames

### ISSUE THREAD

**Issue by joelforessottile** [restfb/restfb#847]
Is there anyway to get the scrennames detailed in a page information section?
For example, this politician in my country has some info about his other social networks, so if I look for them in the Graph API by `thispolitician?fields=screennames` I get

```
"screennames": {
    "data": [
      {
        "service_name": "Twitter",
        "value": "@sebastianpinera"
      },
      {
        "service_name": "Instagram",
        "value": "sebastianpinerae"
      }
    ]}
```

**Comment by nbartels** [comment]
This field is missing. For our own records, here is the link to the graph api reference: https://developers.facebook.com/docs/graph-api/reference/page/screennames/
