### ISSUE TITLE
compilation error in eclipse

### ISSUE THREAD

**Issue by ofir27** [restfb/restfb#848]
I imported the project to eclipse, and got the following error:
"Project 'restfb' is missing required source folder: 'source\example' ".

Do you know how to solve this?

**Comment by nbartels** [comment]
There are serveral possibilities:
Go to Project > Build Path > Configure Buildpath and change the paths to the correct source paths<br>
_or_<br>
Remove the RestFB project from eclipse, delete the `.project` and `.classpath` files. Remove the `.settings` directory and import the maven project again.
