### ISSUE TITLE
User.class missing the ids_for_apps

### ISSUE THREAD

**Issue by JB4GH** [restfb/restfb#849]
It seems that the User class is missing the "ids_for_apps" field, which is supported by the /me request.

Is it possible to add that field to the User class or is there another way to access that information within the same /me request?

Thanks

**Comment by nbartels** [comment]
This field is missing:
https://developers.facebook.com/docs/graph-api/reference/user/ids_for_apps/

You can wait for the next release, or extend the User class and add the missing field to your custom implementation.

**Comment by JB4GH** [comment]
Ok, thanks for the fast answer.
