### ISSUE TITLE
Instagram WebHooks is down?

### ISSUE THREAD

**Issue by tam04101993** [restfb/restfb#867]
I try to subscript instagram object of facebook webhook but server return 

`{
    "error": {
        "message": "(#200) Permissions error",
        "type": "OAuthException",
        "code": 200,
        "fbtrace_id": "Bdv278VKt0t"
    }
}`
and Instagram object is not showed in my app dashboard from last week.
Is any one face the same issue?

**Comment by nbartels** [comment]
Can you check the permissions of the used access token in the access token debugger? Do you have the instagram permission added to it?

**Comment by tam04101993** [comment]
Access token I used is app access_token.
My app has been approved for items below:
* instagram_basic
* instagram_manage_comments
* instagram_manage_insights
* manage_pages
My problem is I still able to subscript for orther object in this link:
[](https://developers.facebook.com/docs/graph-api/webhooks/reference) 
accept: instagram and page object. Is that Facebook not support webhook for instagram anymore?

**Comment by nbartels** [comment]
Please open a bug on Facebook (https://developers.facebook.com/bugs), it looks like bug on their platform...
