### ISSUE TITLE
Using restfb in a gradle project

### ISSUE THREAD

**Issue by ivanreyess** [restfb/restfb#869]
Hello,

Is there a way to use restfb in a gradle project?
I have been searching but I only found it as a maven depedency. 

Thank you for your time.

**Comment by nbartels** [comment]
According to maven central you have to add this line for the version 2.3.0:

```
compile 'com.restfb:restfb:2.3.0'
```

Or do you need to know how you can add a 3rd party library to your gradle project without using dependency management?

**Comment by ivanreyess** [comment]
I wanted to know how to add it as a dependency.

Thank you for your answer it work perfectly.
