### ISSUE TITLE
Unable to upload caption to a video

### ISSUE THREAD

**Issue by TamaraM88** [restfb/restfb#871]
Hi guys,

I'm having issue with uploading caption to a video. GraphResponse is successful, but caption is not published.

I'm adding file as:
`BinaryAttachment.with("captions_file", fileName, bytes, MediaType.APPLICATION_OCTET_STREAM_TYPE.toString());`

If I try CURL from command line (direct call to graph api) caption is published.

Can you please help?

Note: I'm using version 1.44.0, switching to a 2.3.0 doesn't solves the issue.

Thanks!

**Comment by TamaraM88** [comment]
Hi,

fileName is 'Test.en_US.srt'

curl is:
> curl -X POST 'https://graph.facebook.com/v2.10/{videoId}/captions?access_token={token}&default_locale=en_US' -F captions_file=@Test.en_US.srt

Thanks!

**Comment by nbartels** [comment]
Hi,

I just wrote a small integration test and tried to add a subtitle to an video.

My code looks like the 

```java
InputStream is = getClass().getResourceAsStream("/binary/jellies.srt");
byte[] imageAsBytes = getBytesFromInputStream(is);

GraphResponse result = client.publish("<video_id>/captions", GraphResponse.class,
      BinaryAttachment.with("captions_file","jellies.en_US.srt",imageAsBytes));
```

This worked without a problem. The only change between your code and mine is the content type. I did not provide one. 

Can you please check your `bytes` variable (is the data correct) and try without the content type.

**Comment by TamaraM88** [comment]
The same is without the content type... I also checked bytes and the data is correct.

Not sure what to do next since I tried different combinations of data... I even tried with delay between video upload and caption upload...

Thanks!

**Comment by nbartels** [comment]
Okay. I used an page access token with only two permissions `manage_pages` and `publish_pages`.

**Comment by TamaraM88** [comment]
I'm using app with more permissions, but that shouldn't be a problem....
