### ISSUE TITLE
Get event picture

### ISSUE THREAD

**Issue by raigol** [restfb/restfb#875]
I am having issue with getting picture of event.

FacebookClient fbClient = new DefaultFacebookClient(accessToken.getAccessToken(), Version.LATEST);

JsonObject picture = 
		  fbClient.fetchObject(eventId + "/picture", 
			  JsonObject.class, Parameter.with("redirect","false"), Parameter.with("type","large"));

the error message is 
Unsupported get request. Object with ID 'eventId' does not exist, cannot be loaded due to missing permissions, or does not support this operation. (code 100, subcode 33). 

the event id does exist, I have double checked this. how to get picture of event?

**Comment by nbartels** [comment]
You already checked the breaking changes (https://developers.facebook.com/docs/graph-api/changelog/breaking-changes/#events-4-4)?

According to that page you have to let Facebook review your app again to access the events.
