### ISSUE TITLE
Some OpenGraphRating fields mapped with extra quotation marks

### ISSUE THREAD

**Issue by CrWEE** [restfb/restfb#878]
Since upgrading from 1.49 to 2.4.0 I've noticed the following issue:
I've the following payload: 
```
{
    "open_graph_story": {
        "message": "AAAAA",
        "start_time": "2016-10-11T08:46:36+0000",
        "type": "places.rates",
        "data": {
            "rating": {
                "value": 5,
                "scale": 5
            },
            "review_text": "AAAAA",
            "language": "hu",
            "generic_place": {
                "id": "256080221451513",
                "title": "Zzzs teszt oldal",
                "type": "restaurant.restaurant",
                "url": "https://www.facebook.com/Zzzs-teszt-oldal-1769597826637807/"
            }
        },
        "comments": {
            "data": [
            ],
            "can_comment": true,
            "comment_order": "chronological",
            "count": 1
        },
        "id": "10211119444292023"
    },
    "created_time": "2016-10-11T08:46:36+0000"
}
```
Using this the review_text fields get mapped as String but with extra quotation marks like this: ""AAAAA""
I guess the json mapper has an issue with the OpenGraphRating -> PageRating -> data field where the raw data String field has the correct values but once it is mapped to a JsonObject is doesn't anymore.
I couldn't figure out whats wrong with it until now :) .

Thanks

**Comment by nbartels** [comment]
@CrWEE it is the `PageRating#fillAdditionalValues()` method. I made a mistake in the post mapping method. Thanks for finding this!
