### ISSUE TITLE
Facebook added a new field to instagram comments/replies

### ISSUE THREAD

**Issue by amanduggal** [restfb/restfb#882]
As part of the ongoing breaking changes facebook added a new field 'username' to IgComment and IgMedia. Refer:  https://developers.facebook.com/docs/graph-api/changelog/breaking-changes/#ig-gapi-4-24

I have the necessary change (fairly small and straightforward) done to restfb on a branch off dev. I am happy to open a PR but need access for it. 

Thanks.

**Comment by nbartels** [comment]
you simply need to fork the repository, put your changes in your repository and send the PR. I suggest creating a new branch for your changes.
