### ISSUE TITLE
How to detect if there is a new line character in a message collected from Facebook Graph API

### ISSUE THREAD

**Issue by mraliagha** [restfb/restfb#884]
I am trying to check if a message collected from Facebook Graph API comes with a new line character or not. Hence, I have created a sample post and tried to verify it. However, it looks like Facebook doesn't show the \n character in the message. Is there any way I can get a message/post content in the raw format?

```
Connection<Post> postIterations = fbClient.fetchConnection(pageId + "/posts", Post.class,
                Parameter.with("fields", "message"));

        for (List<Post> posts : postIterations) {
            for (Post post : posts) {
                if (post.getMessage().endsWith("\n")) {
                    // do something
                }
            }
        }
```

**Comment by nbartels** [comment]
Please check in the Graph API Explorer if there is a new line symbol at the end of the message. If there is no message, then Facebook don't provides one and so we can't.

**Comment by mraliagha** [comment]
@nbartels I thought maybe there is a way that we can get it from facebook by passing a special field. For example something like details or debug use case. However, I couldn't find any even inside the message (ignoring at the end use case).

**Comment by nbartels** [comment]
So the use case is to ignore a newline that was added at the end of a message? But according to my test a trailing newline (or two newlines) are removed during posting to Facebook. So removing a trailing newline is no necessary. Facebook seems to trim the message already.

**Comment by mraliagha** [comment]
@nbartels Thanks.
