### ISSUE TITLE
Async insights support

### ISSUE THREAD

**Issue by kevinwenzhang** [restfb/restfb#895]
Hi, I'm wondering if asynchronous insights calls are supported using restfb. 

Here's the relevant facebook documentation:
https://developers.facebook.com/docs/marketing-api/insights/best-practices/#asynchronous

The async call to facebook creates an `AdReportRun`, which tells me job completion status.

I've tried this using the official facebook Java SDK. As an example, the following code accomplishes what I want:
```
AdAccount.APIRequestGetInsightsAsync insightsAsyncRequest = adAccount.getInsightsAsync();
insightsAsyncRequest.setTimeRange("{\"since\":\"2017-08-07\",\"until\":\"2018-08-14\"}");
insightsAsyncRequest.requestAllFields();
AdReportRun adReportRun = insightsAsyncRequest.execute();

while (!adReportRun.fetch().getFieldAsyncStatus().equals("Job Completed")) {
    // do stuff ...
}

APINodeList<AdsInsights> insights = adReportRun.getInsights().execute();
// do stuff with insights data
```
I haven't been able to find examples of this using restfb. Is this supported at all?

Thanks.

**Comment by nbartels** [comment]
So, RestFB provides the `AdReportRun` Type, too.

I did not try this code and so it is more an idea how it works, but perhaps this good enough as starting point:

```java
FacebookClient client; // defined somewhere else

JsonObject result = client.publish("<CAMPAIGN_ID>/insights", JsonObject.class, Parameter.with("level","campaign"));
String reportRunId = result.getString("report_run_id","");

AdReportRun adReportRun;
do {
  adReportRun = client.fetchObject(reportRunId, AdReportRun.class);
  // some additional stuff
} while (!"Job Completed".equals(adReportRun.getAsyncStatus()));

Connection<Insight> insights = facebookClient.fetchConnection(reportRunId + "/insights", Insight.class);
// do stuff with insights
```

**Comment by kevinwenzhang** [comment]
@nbartels, your code snippet was very helpful. I'll close this issue now. Thanks for your help!
