### ISSUE TITLE
[info] As of July, 13th 2018 some virus scanners are blocking the restfb jar-file.

### ISSUE THREAD

**Issue by DennisBayer** [restfb/restfb#896]
As of July, 13th 2018 some virus scanners are blocking the jar-File. The maven repo urls of the jars were used to start the online scan process.

At the moment I suspect that this might be due to a broken heuristic update - at least I hope so. :) But if the problem should remain, you might have a look what went wrong.

Best regards

**local log of bitdefender**
``` 
.m2\repository\com\restfb\restfb\2.7.0\restfb-2.7.0.jar
  =>com/restfb/DefaultFacebookEndpoints.class
Java.Trojan.GenericGB.26315
```

**online results**
2.7.0: https://www.virustotal.com/de/file/ddc46ebf4d4e90dc370571ad2a8d32180b7a0d843c909f861d9e7b342258c64b/analysis/1531468693/
2.6.0: https://www.virustotal.com/de/file/62a0c0a2ab92ce6cab30c22022ae0f732db614ed3c1de446b7f99c3c8da5b9ac/analysis/1531468852/

```
Antivirus | Ergebnis | Aktualisierung
BitDefender | Java.Trojan.GenericGB.26315 | 20180713
Emsisoft | Java.Trojan.GenericGB.26315 (B) | 20180713
F-Secure | Java.Trojan.GenericGB.26315 | 20180713
GData | Java.Trojan.GenericGB.26315 | 20180713
MAX | malware (ai score=82) | 20180713
eScan | Java.Trojan.GenericGB.26315 | 20180713

others engines are fine
```

**Comment by nbartels** [comment]
Many thanks for the information. 
This is really weird and I think this is, as you said, a heuristic problem. The mentioned class does not contain anything interesting. I can decompile it to check if something was compromised, but I don't think so.

**Comment by DennisBayer** [comment]
Update July, 16th:
Local Bitdefender does not complain anymore and VirusTotal report is also looking a little bit friendlier:

2.7.0
https://www.virustotal.com/#/file/ddc46ebf4d4e90dc370571ad2a8d32180b7a0d843c909f861d9e7b342258c64b/detection

2.6.0
https://www.virustotal.com/#/file/62a0c0a2ab92ce6cab30c22022ae0f732db614ed3c1de446b7f99c3c8da5b9ac/detection

```
AegisLab | Java.Troj.Genericgb!c
Ikarus | Trojan.Java.GenericGB
TrendMicro-HouseCall | Suspicious_GEN.F47V0713
```

Regards

**Comment by nbartels** [comment]
Great, so it helped to report the file as false positive. I check the remaining anti-virus software and try to report the jar their, too.

Thanks for the information.

**Comment by nbartels** [comment]
*Update July, 18th:*

Now, only "TrendMicro-HouseCall" is complaining on VirusTotal. But I'm already working on this on so, the jar should be completely okay soon.

**Comment by nbartels** [comment]
No more complains about any trojans in version 2.7.0. So I close this here and hope that future versions work without problem, too. :smile:
