### ISSUE TITLE
Provide an example for Graph API batch request for engagement

### ISSUE THREAD

**Issue by sonerx** [restfb/restfb#898]
I am trying to make a call for the following request by using

curl -i -X GET \
 "https://graph.facebook.com/v3.0/?fields=engagement&ids=http://cnn.com,http://abc.com&access_token=XXYY"

but couldn't figure it out how to do it. Can you please provide an example of the request?

**Comment by nbartels** [comment]
This is not a batch request. Id is a request with multiple ids and you can find an example in our documentation: https://restfb.com/documentation/#fetching-multiple-objects

if you need more information, please send a short note.

**Comment by jedlikar** [comment]
Dne pá 27. 7. 2018 0:32 uživatel sonerx <notifications@github.com> napsal:

**Comment by nbartels** [comment]
I added an integration test as example. BTW don't forget: you spend 2 calls even though you use 1 call in the Graph API. Sometimes it is more easy to work with a loop. 😄
