### ISSUE TITLE
Graph API 3.1 - basic version

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#899]
https://developers.facebook.com/docs/graph-api/changelog/version3.1/

**Comment by torbenw** [comment]
Hey, I just wanted to ask if there is a release date for RestFB 2.8.0. I'm currently using an older version of RestFB with Marketing API v2.11, but Marketing API v2.11 and v2.12 will be deactivated on 07.08.2018, so I have to update to a newer version of RestFB. I'd like to upgrade to API v3.1 for that.

**Comment by nbartels** [comment]
Okay I see, I have to check the Marketing API changes and I think I manage to release the next version this weekend.

**Comment by torbenw** [comment]
Thanks a lot! :)

**Comment by torbenw** [comment]
Thanks again!
