### ISSUE TITLE
Connection should construct next & prev page URLs from cursors as a fallback

### ISSUE THREAD

**Issue by mrhota** [restfb/restfb#909]
Facebook decided that the Instagram `/user/tags` endpoint should support pagination but that it should be a special snowflake and shouldn't include `next` and `previous` fields in the response.

https://developers.facebook.com/docs/instagram-api/reference/user/tags

Is it possible to construct a `Connection`'s `previousPageUrl` and `nextPageUrl` from `beforeCursor` and `afterCursor` if `previousPageUrl` and `nextPageUrl` are `null`?

**Comment by nbartels** [comment]
Okay, I see. We have to add the modified url into the connection in the case you are describing above. Too bad, facebook made the decision to drop the fields in that special endpoint 😁

**Comment by nbartels** [comment]
@mrhota I made some changes and hopefully this is working for you. At least the unittest are working ...
