### ISSUE TITLE
quick reply title not display completely

### ISSUE THREAD

**Issue by SaraYassen** [restfb/restfb#913]
hey,
when I send quick replies to user, there are replies not display completely 
it display with 3 dots ... like "abcdefghijklmnopqrst..."  not "abcdefghijklmnopqrstuvwxyz"
I use:
QuickReply quickReply = new QuickReply("abcdefghijklmnopqrstuvwxyz" , "abcdefghijklmnopqrstuvwxyz");

thanks in advance

**Comment by nbartels** [comment]
According to the QuickReply reference on Facebook the title is limited to 20 characters.
https://developers.facebook.com/docs/messenger-platform/reference/send-api/quick-replies/

![quickreply_reference_title](https://user-images.githubusercontent.com/1113969/45826588-0e6f8880-bcf5-11e8-8133-c7c9e64409a0.jpg)
