### ISSUE TITLE
Place.class improvement with new fields

### ISSUE THREAD

**Issue by egemenozkan** [restfb/restfb#915]
Hello,
 restfb/src/main/lombok/com/restfb/types/Place.java  does not supply all fields in v3.1.   Are you planning to add new fields into class ?

Thank you.

**Comment by nbartels** [comment]
I just checked the Facebook reference and I don't see any fields that are missing:
https://developers.facebook.com/docs/graph-api/reference/place/

Can you provide an example json, so I can check the new fields you are talking about...

**Comment by egemenozkan** [comment]
Dear Norbert,
You are right according to reference which you shared. However, I am trying to use Places Search API.
Please, check following reference url sout to understand what I mean.
https://developers.facebook.com/docs/places/fields, https://developers.facebook.com/docs/places/web/search/

May be restfb has a method which meets a need, however, i am using below method. 

```
Connection<Place> publicSearch = facebookClient.fetchConnection("search", Place.class,
					    Parameter.with("q", "Crystal W"), Parameter.with("type", "place"),
					    Parameter.with("center", "38.734802,35.467987"),
					    Parameter.with("distance", 400000),
					    Parameter.with("fields", "about, name, category_list, checkins, rating_count, overall_star_rating, location, is_verified"));`
			List<Place> places=  publicSearch.getData();
```
