### ISSUE TITLE
Infinite loop while fetching next page

### ISSUE THREAD

**Issue by CrWEE** [restfb/restfb#916]
Hey!

We encountered and "interesting" facebook bug (link:  [https://developers.facebook.com/support/bugs/482984005516645/?disable_redirect=0](url) ) where we receive an empty response but with a next page link available so our logic simply fell into an infinite loop. 
I wonder if it would be a good idea to include an extra condition in the com.restfb.Connection#hasNext method to also check if the actual page has any data?

**Comment by CrWEE** [comment]
Example response that we got: 
```
{
  "data": [],
  "paging": {
    "cursors": {
      "after": "aftercursos...."
    },
    "next": "https://graph.facebook.com/v2.10/1438201462....<restofnextlink>"
  }
}
```

**Comment by nbartels** [comment]
What about the first page, is it possible that there is no data, but the next url?

**Comment by CrWEE** [comment]
We encountered 3 scenarios:
- No data and no next url
- No data but with next url (but the next page has no next url)
- Page with data (less than the limit) but with next url and also the next page has a next url (and so on... this is how we ended up with the infinite loop).
