### ISSUE TITLE
Graph API 3.2: add version to enum

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb#924]
https://developers.facebook.com/docs/graph-api/changelog/version3.2

**Comment by pcornelissen** [comment]
https://github.com/restfb/restfb/pull/925

**Comment by nbartels** [comment]
Many thanks for the PR @pcornelissen, but I made some changes in the `dev` branch that leads to merge conflicts.

**Comment by pcornelissen** [comment]
feel free to remove the PR, it was just to save you a little bit of typing :-D
