### ISSUE TITLE
Please provide JsonMapper#toJavaObject which operates on JsonNode

### ISSUE THREAD

**Issue by eximius313** [restfb/restfb#932]
Most frameworks can already parse incomming request to Json, therefore it would be beneficial to provide `toJavaObject` method which operates on `com.fasterxml.jackson.databind.JsonNode`

**Comment by nbartels** [comment]
Can you explain your use case. Normally you use the `FacebookClient` to fetch data from Facebook and so you don't need to access the `JsonMapper` directly...

**Comment by eximius313** [comment]
The question is: what was the reasoning behind using own Custom Mapper instead of, de facto standards, like Jackson (or even GSON)?
Jackson allows for registering custom modules so you could achieve both: hava custim behavior and use standard API.

**Comment by revetkn** [comment]
@eximius313 the reasoning is pretty much what Norbert said above...many projects use many different JSON libraries (there is no standard), and each library might have many versions, some of which are incompatible.

My question is - why can't the framework you are using provide a `String` instead of a `JsonNode`?  Or, if that's impossible, just do it yourself like below?  The performance impact (a few milliseconds?) is negligible.

```
// OK, we can hand JSON to RestFB now
String json = objectMapper.writeValueAsString(myJsonNode);
```

**Comment by eximius313** [comment]
@revetkn,
> My question is - why can't the framework you are using provide a String instead of a JsonNode?

The framework I'm using can of course convert JSON to string (so, you will then convert it back to JSON). I just find it tedious and unnecessary.

> many projects use many different JSON libraries

that is exactly why I pointed out, that creating another library instead of using "the most popular (and already existing ) one" may be a room for improvement ;)

**Comment by eximius313** [comment]
Ok, I understand...
Hopefully this will be a standard one day (Just like Hibernate -> JPA or `Reactive Streams` -> FlowAPI)

**Comment by revetkn** [comment]
Yes - I agree 😃 Someday...

**Comment by nbartels** [comment]
Just to leave my 2 cents ;)

The complete issues depends on the perspective. RestFB's main purpose is to work with the Graph API. We have the types implemented and a flexible `FacebookClient` that is used to call a Facebook endpoint, convert the returned JSON into out types. For the user no JSON library is involved and only internally used. It's almost completely transparent what we use under the hood. 

As soon as we come to webhooks, things are changing and only a small part of RestFB is used. The mapper and the special webhook types. We like to provide our users an easy access to the information Facebook sends to their callback servlet. It is supported and tested, but not the main purpose. 

BTW you can simply take the request body as text and let RestFB do everything. So you don't need to let the PlayFramework convert the text to JSON objects, then back to a String and then with the RestFB Mapper to a RestFB type.

Use the Text `BodyParser` and use `request().body().asText()`.
https://www.playframework.com/documentation/2.6.x/JavaBodyParsers#choosing-an-explicit-body-parser

As soon as there is a standard interface for handling JSON in Java we will supported or at least provide access to it, as we do with `slf4j` ;)

Anyway, thanks for your input and it is good if someone brings in ideas and questions reasons.

**Comment by eximius313** [comment]
Of course I've tried `request().body().asText()`, but for JSON it returns null and with `@BodyParser.Of(BodyParser.Text.class)` it returns `415 Unsupported Media Type`
I have to investigate if it's a bug or feature ;)

**Comment by nbartels** [comment]
:smile: 

Try `BodyParser.TolerantText.class` 
According to the PlayFramwork docs:
> Like `Text`, but does not validate that the Content-Type is text/plain.

**Comment by eximius313** [comment]
Damn.... I didn't try that... thanks ;)
