### ISSUE TITLE
Improve "Creating a Recipient" section

### ISSUE THREAD

**Issue by eximius313** [restfb/restfb#934]
In this section: https://restfb.com/documentation/#messenger-recipient
1)  `new PhoneMessageRecipient("<userID>");` uses `<userID>` while it should be `<userPhone>`.
2) It's worth noting, that so called "Customer Matching" is now restricted to US only (https://developers.facebook.com/docs/messenger-platform/identity/customer-matching/#availability)
3) There are three types of identifiers that are supported by the `Send API.` The is 3rd is `user_ref` in https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin

**Comment by nbartels** [comment]
changes added and resolved in the website repository, close this issue now
