### ISSUE TITLE
 „(#200) Requires either publish_to_groups.

### ISSUE THREAD

**Issue by weltenbranddesign** [restfb/restfb#937]
Hello I use the restfb jar in one of my Projects but if i want to send a Picture to facebook via restfb i cant upload it every time i get the error #200 GRAPH API. I can get data from Facebook but i cant Post any Data on my Facebook page

**Comment by nbartels** [comment]
Which access token do you use? Is your app already reviewed?

**Comment by weltenbranddesign** [comment]
Hi do i need to review my application to post on facebook?
With the token is everthing ok, i can read data from facebook like my userdata or the Pagedata but i cant post anything

**Comment by nbartels** [comment]
You cannot publish data as user, so you cannot post anything to you user timeline. Is a restriction Facebook added some months ago.
As a page it is possible. Can you please show the permissions your access token has? You can check this in the access token debugger for example.

**Comment by weltenbranddesign** [comment]
EAAH4KSdlYkoBAAUn89QjDHmdwvC6jWweDPeUeH47oCexPS4gft59ohmPMb0tfixvKM1XIdWCHZAUXvZARe90D85ZAKaWT1itebDMgbp84XlPTf93hkzXBJ8GikZCxth7biijyflypsliNZAyBwV1ZAuljZADUfxznqrWZAyxdqLrR84QoHX1OZBUkCM5tciB64XEZD

App-ID | 554330615013962 : MarioJava
-- | --
Typ | User
App-spezifische Nutzer-IDLearn More | 116600882673179 : Mario GuidoneNutzer hat diese App zuletzt via API N/A installiert
Ausgestellt | 1543220393 (vor 6 Sekunden)
Ablaufdatum | 1548404393 (in ungefähr 2 Monaten)
Datenzugriff läuft ab | Niemals
Gültig | Wahr
Herkunft | Unknown
Umfang | user_birthday, user_hometown, user_location, user_likes, user_events, user_photos, user_videos, user_friends, user_status, user_tagged_places, user_posts, user_gender, user_link, user_age_range, email, read_insights, read_audience_network_insights, publish_video, manage_pages, pages_manage_cta, pages_manage_instant_articles, pages_show_list, publish_pages, read_page_mailboxes, ads_management, ads_read, business_management, pages_messaging, pages_messaging_phone_number, pages_messaging_subscriptions, instagram_basic, instagram_manage_comments, instagram_manage_insights, publish_to_groups, groups_access_member_info, leads_retrieval, public_profile

this is my access token. How can i post on a page with restfb?

**Comment by weltenbranddesign** [comment]
can you show me a code example?

**Comment by nbartels** [comment]
Already tried the examples from our docs? https://restfb.com/documentation/#publishing-message-event

**Comment by weltenbranddesign** [comment]
yes gut how can i post it to a specific page?

**Comment by weltenbranddesign** [comment]
i tried it now with the page id i get the same error Code :(

**Comment by weltenbranddesign** [comment]
I wrote this into the GRAPH API Explorer
POST /PageID/feed
message "Test"

And then i get the same error message!

**Comment by nbartels** [comment]
please try posting to /me/feed with your page access token. Is this working for you?

**Comment by weltenbranddesign** [comment]
it works !!! 💃
