### ISSUE TITLE
Support for IgUser getBusinessDiscovery for a 3rd-party instagram page

### ISSUE THREAD

**Issue by rberga** [restfb/restfb#942]
Currenly IgUser.getBusinessDiscovery() does not take a username. However according to FB's documentation
https://developers.facebook.com/docs/instagram-api/business-discovery

it is possible to get some public data for a 3rd-party page using the business-discovery field, as follows

```bash
GET graph.facebook.com/<my-own-instagram-page-id>?fields=business_discovery.username(bluebottle){followers_count,media_count}
```

Does restFB support this at the moment, or will it in the future?
thanks

**Comment by nbartels** [comment]
According to the documentation page you mentioned, the response the request looks like:

```javascript
{
  "business_discovery": {
    "followers_count": 267793,
    "media_count": 1205,
    "id": "17841401441775531"
  },
  "id": "17841405309211844"
}
```

If the JSON response is wrong, please provide us a correct JSON and we add the missing fields in the next version. 

To fetch this information you can use `Parameter.with("fields", "business_discovery.username(bluebottle){followers_count,media_count}")`, but I think this was not the topic of your question 😃

**Comment by rberga** [comment]
Norbert,
thanks a lot. This is exactly what I was looking for.
With your hint I was able to use restFB to get information about a public, business IG page and all its posts, as well as info on each post on the page. The equivalent of the Graph API would be:

`business_discovery.username(instagram-page-name){name,username,ig_id,id,follows_count,followers_count,media_count,profile_picture_url,media{permalink,timestamp,media_url,media_type,caption,comments_count,like_count}}`

I do have one more question along these lines:
Is it possible to get the actual public comments on an instagram post (without being the owner of the page)? (this is possible on Facebook posts)
Thanks!

**Comment by nbartels** [comment]
I have not tried this, but perhaps you like to. With the call you mentioned you should be able to get the user id of the other user.

Then make a request to `<ig_user_id>/media` to get the media and then you can fetch the comments. At least this is almost the way that works with the page owned `IgUserId`. Maybe this is working for other users, too. 

Would be great if you leave some feedback if this is working ...

**Comment by rberga** [comment]
Norbert,

summarizing the issues raised above, I wrote down the steps to retrieve relevant data from the Graph AP Explorer. It should be relatively simple for anyone else to translate them to calls to the RestFB API.

The purpose here is to show how to get data from an Instagram business page, its posts, and (in some cases) the comments associated with each post.

In the Graph API Explorer:

1) Access the Facebook page name, for which the token was generated (i.e., you have permissions for). The instagram business account must have been linked to the Facebook account.

`GET /v3.2/<facebook-page-name>?fields=instagram_business_account`

this returns

```
{
  "instagram_business_account": {
    "id": "178414xxxxxxxxxxx"                <<<< Instagram business pg id
  },
  "id": "121xxxxxxxxxxxx"                    <<<< Facebook page id
}

```
2) Use the Instagram business pg id to get the list of posts

`GET /v3.2/178414xxxxxxxxxxx/media
`
this returns

{```

  "data": [
    {
      "id": "17992160nnnnnnnnn"          <<<< Instagram post id (there is only one in this pg)
    }
  ]
}
```

3) user the Instagram post id, to get its data and list of comments

`GET /v3.2/17992160nnnnnnnnn?fields=caption,like_count,media_type,media_url,permalink,comments_count,comments
`
this returns

```
{
  "caption": "This was the text in the post",
  "like_count": 1,
  "media_type": "IMAGE",
  "media_url": "https://scontent.xx.fbcdn.net/v/t51.2885-15/474ppppp_2255zzzzzzzzzzzz_597kkkkkkkkkkkkkkkk_n.jpg?_nc_cat=101&_nc_ht=scontent.xx&oh=cf48b53444832b8f62kdijmfms434f31&oe=6A99B5C6",
  "permalink": "https://www.instagram.com/p/BrFFxxxxx_X/",
  "comments_count": 1,
  "comments": {
    "data": [
      {
        "timestamp": "2018-12-07T11:03:39+0000",
        "text": "test",
        "id": "1789001vvvvvvvvvv"
      }
    ]
  },
  "id": "17992160nnnnnnnnn"
}
```

CAVEATS:
You can get all this data if you are the owner of the Instagram page.
If you are NOT the owner, you can still get most of it - EXCEPT for the "comments". If you are not the owner, you can get the number of comments per post, but not the individual comments.

**Comment by yoneticic8482** [comment]
Norbert Bartels, how are you?
I'm curious about facebook ig_user_id using https://developers.facebook.com/docs/instagram-api/ can read any instagram's media information.
https://deskgram.net/the_elementofdesign Do you think this web page data is getting new apk on facebook?

**Comment by nbartels** [comment]
Sorry, I don't get it. What a about the APK? Can you elaborate this a bit more. BTW is this somehow connected to the posts above?
