### ISSUE TITLE
Retrieve more than 25 Instagram posts

### ISSUE THREAD

**Issue by rberga** [restfb/restfb#947]
Whenever retrieving posts from an Instagram page using business_discovery, only 25 posts are returned by default. 
How can I get "more" posts?  
This is what I'm doing:
Suppose I want to get the posts from the "motorolaus" Instagram page. I'm not the owner, so I'm using the business_discovery parameter to get the media list associated with the "motorolaus" page.

```java
IgUser iguser = facebookClient.fetchObject(my-instagram-id, IgUser.class, 
          Parameter.with("fields", "business_discovery.username(motorolaus){name,followers_count, media{like_count}}"));

IgUser motoPage = iguser.getBusinessDiscovery();
List<IgMedia> postsList = page.getMedia();
```

This returns 25 posts. How can I get more posts?
Is there a parameter I can pass to get paged media?
Thanks

**Comment by nbartels** [comment]
Please try the following approach:

```java
IgUser iguser = facebookClient.fetchObject(my-instagram-id, IgUser.class, 
          Parameter.with("fields", "business_discovery.username(motorolaus){name,followers_count, media.limit(50){like_count}}"));
```

I added the `limit` to the media according to the Graph API Reference:
https://developers.facebook.com/docs/graph-api/advanced/

If it is working, please send a short feedback or close the issue :smiley:

**Comment by rberga** [comment]
Norbert,
that worked, thanks!
If I may ask a follow up question: is there a way to get the list of posts paged (with limit on the number of posts per page)? or by dates?
Using media.limit I can clearly get a list of posts and then filter by date. But if there is way to limit the number of posts by pages or dates directly in the fetch, that would be more efficient.
thanks.

**Comment by nbartels** [comment]
Perhaps you can use another call:

```java
Connection<IgMedia> mediaConn = facebookClient.fetchConnection(my-instagram-id + "/media", IgMedia.class, Parameter.with("fields", "like_count"), Parameter.with("limit", 50));
for (List<IgMedia> mediaPage : mediaConn) {
  for(IgMedia media: mediaPage) {
     // do something
  }
}
```

**Comment by nbartels** [comment]
Okay this is interesting and somehow looks like a bug on FB side. It makes no sense to me to let the user fetch media information via field but not via endpoint.
Nevertheless there is no official way to page through the field list atm. We have an issue for this already, but many other tasks to do. So you have to be patient or implement a custom solution :smiley:
