### ISSUE TITLE
UrlPayload crash for building image attachment

### ISSUE THREAD

**Issue by nitrag** [restfb/restfb#957]
I'm trying to send an image via Messaging API (in Kotlin). It is crashing on the `UrlPayload` class.

```kotlin
val string = "https://picsum.photos/200/300/?random"
val attachment = MediaAttachment(MediaAttachment.Type.IMAGE, imageUrl)
```

```kotlin
public MediaAttachment(Type type, String imageUrl) { 
  ...
  payload = new UrlPayload(imageUrl);
```
`Method threw 'java.lang.IllegalStateException' exception. Cannot evaluate com.restfb.types.send.MediaAttachment$UrlPayload.toString()`

![image](https://user-images.githubusercontent.com/197010/51641494-47826880-1f34-11e9-9818-4fcb12d5bd9a.png)

**Comment by nbartels** [comment]
Hm, this is really interesting ... I have to try this in kotlin, too. 
In plain Java I cannot reproduce this atm.

**Comment by nbartels** [comment]
@nitrag I fixed the problem, but I'm interested why the `toString` method is called.

**Comment by nitrag** [comment]
Thanks you fixed that, I have no idea about the `toString` that's way over my head.

However I'm getting something else....Is this a different but related issue?

```kotlin
val attachment = MediaAttachment(MediaAttachment.Type.IMAGE, imageUrl) .   **still good here!**
val message = Message(attachment)    **Exception**
publish(recipient, message)


java.lang.IllegalAccessError: tried to access class com.restfb.types.send.MessageAttachment from class com.criticalmix.facebook.FBClient
```

**Comment by nbartels** [comment]
`MessageAttachment` is package private atm, so if `com.criticalmix.facebook.FBClient` is your own implementation of the `FacebookClient` interface this may occur and I have to check this.

**Comment by nbartels** [comment]
@nitrag Kotlin is interesting. I used these examples.

First the Java Version:
```java
package test;

import com.restfb.types.send.MediaAttachment;
import com.restfb.types.send.Message;

public class Example {

    public static void main(String[] args) {
        String imageUrl = "blub";
        MediaAttachment media = new MediaAttachment(MediaAttachment.Type.IMAGE, imageUrl);
        Message message = new Message(media);
    }
}
```

And the same in Kotlin:
```kotlin
package test

import com.restfb.types.send.MediaAttachment
import com.restfb.types.send.Message

fun main(args: Array<String>) {
    val imageUrl = "blub"
    val attachment = MediaAttachment(MediaAttachment.Type.IMAGE, imageUrl)
    val message = Message(attachment)
}
```

The Java version is working and the Kotlin results in the exception you wrote.
I change the `MessageAttachment` to fixed this, too.

But overall it is really confusing. Thanks for this hint 😃

**Comment by nitrag** [comment]
So it requires the `public` attribute... Interesting. Should that be reported as a bug to Kotlin to throw a compiler warning?

It is working now! Thanks so much for you help and attention on this!

**Comment by nitrag** [comment]
Would you mind publishing a minor release? Thanks

**Comment by nbartels** [comment]
> So it requires the `public` attribute... Interesting. Should that be reported as a bug to Kotlin to throw a compiler warning?

I have only a basic knowledge of Kotlin, so maybe it has a different interpretation of the class visibilities. 

Yes, the new version will be published soon.
