### ISSUE TITLE
@mrhota I made some changes and hopefully this is working for you. At least the unittest are working ...

### ISSUE THREAD

**Issue by amanduggal** [restfb/restfb#966]
@mrhota I made some changes and hopefully this is working for you. At least the unittest are working ...

_Originally posted by @nbartels in https://github.com/restfb/restfb/issues/909#issuecomment-421457198_

I believe this fix is causing the Iterator to fail for other Connection types. 
For instance, running `/me/adaccounts` in API explorer returns 

```
{
  "data": [
    {
      "account_id": "260608571309741",
      "id": "act_260608571309741"
    }
  ],
  "paging": {
    "cursors": {
      "before": "MjM4NDI5OTEyNDQ4MjA0NzYZD",
      "after": "MjM4NDI5OTEyNDQ4MjA0NzYZD"
    }
  }
}
```
Before this fix the next page URL would be `null` for this and `Iterator.hasNext` would return false after first iteration. Now `hasNext()` always returns `true` and calling `next()` throws NPE.

Not sure if that is something others are experiencing but this has limited me from upgrading to latest restfb version without significant code changes.

**Comment by nbartels** [comment]
Okay, I see. It looks like bpth cursor values are the same, so maybe we can fix the problem by using this information ;)

**Comment by nbartels** [comment]
@amanduggal can you please show me, how you iterate over the connection ... atm I cannot reproduce the problem with unittests and your example json.

**Comment by amanduggal** [comment]
Code flow is like this 
```
Iterator<List<JsonObject>> adAccountsIts = facebookClient.fetchConnection("me/adaccounts", JsonObject.class, Constants.ADACCOUNTS_WITH_ADS).iterator();
            while (adAccountsItr.hasNext()) {
                       adAccountsItr.next(); // do something with it
            }
```

After pulling in the latest code `adAccountsItr.hasNext()` is always `true`

**Comment by nbartels** [comment]
@amanduggal I'll check this, but maybe you can try this code in the meanwhile:

```java
Connection<JsonObject> adAccountsCon = facebookClient.fetchConnection("me/adaccounts", JsonObject.class, Constants.ADACCOUNTS_WITH_ADS);
for (List<JsonObject> adAccountList: adAccountsCon) {
   // do something with the list 
}
```

**Comment by amanduggal** [comment]
@nbartels that would not be an ideal solution for us since we have the iterator pattern all over our code.

**Comment by nbartels** [comment]
@amanduggal Okay I understand. I think this can be solved in the next version, stay tuned.
