### ISSUE TITLE
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#200) Must have a valid access_token to access this endpoint

### ISSUE THREAD

**Issue by sarragdroura** [restfb/restfb#969]
public static void main(String[] args) throws FileNotFoundException {
        
         String access="EAAjlVbZAAdOMBALy3IoX1wt0LjdmU53G0TmZBirfhKjZCvZCOUd41lwwSoYtCcTIitGCfWBUWL896sywiaY37g7p7fLInJZAPuZAtFbbRUBZCEuxmDrYd0OVPhv1oEk28z0lKT1Pts56OwocyhSsZA1z1pGB7nLSYjIw5XnDqMM7vHpGQZBe7hCGMie1SdD4gnZBUZD";
        FacebookClient fbClient= new DefaultFacebookClient(access) ;
        FileInputStream fis= new FileInputStream(new File("C:\\Users\\sarra\\Desktop\\2.jpg"));
        FacebookType response =fbClient.publish("me/photos", FacebookType.class
                , BinaryAttachment.with("Event_Plaza_and_Rain_Garden.jpg", fis)
                ,Parameter.with("message", "RadixCode Logo"));
        System.out.println("fb.com/"+response.getId());
        
        
        
    }

**Comment by nbartels** [comment]
Can you please check the validity of your access token with the access token debugger:
https://developers.facebook.com/tools/debug/accesstoken/

**Comment by sarragdroura** [comment]
i did and it didn't work for me 
still the same exception

**Comment by nbartels** [comment]
What kind of access token are you using? Page access or user access token? What permissions are used in the access token?

**Comment by sarragdroura** [comment]
user access token

**Comment by nbartels** [comment]
This will not work, because with April 28 (2018) Facebook removed the publish_actions permission and this permission is need to publish a photo as user.

See here: https://developers.facebook.com/docs/graph-api/photo-uploads/#permissions
And check the red box.

**Comment by sarragdroura** [comment]
ahh ok tkx
