### ISSUE TITLE
Cannot upload pdf attachment

### ISSUE THREAD

**Issue by karishmak88** [restfb/restfb#977]
Hi

**I am using below code to upload my pdf file with my post:**

String accessToken = "<PLEASE USE YOUR ACCESS TOKEN";
			FacebookClient fbClient = new DefaultFacebookClient(accessToken, Version.LATEST);
			// to upload pdf file
			
			// Actual: DOES NOT show attachment on the post
			// Expected: should show attachment on the post
			byte[] fileInBytes = IOUtils.toByteArray(new FileInputStream(new File("PATH_TO_DOC_WHICH NEEDS UPLOADING")));
			Post obj2 = fbClient.publish("PAGE_ID/feed", Post.class,
					BinaryAttachment.with("NAME_OF_FILE", fileInBytes), Parameter.with("message", "TestWithPdf"));

**But when i check it only posts "TestWithPdf" and no pdf file is attached.**

**Comment by karishmak88** [comment]
Please could somebody help me in identifying what is wrong. I tried uploading an image or creating a doc and that seems to work as expected.

**Comment by nbartels** [comment]
In the Facebook examples I only see images and videos as binary upload. So can you please write here the exception you get. I assume, that it is simply not possible to post a PDF file.

You post a link that points to the PDF instead.

**Comment by karishmak88** [comment]
I do not get any exception. It gives me back an object. Just the pdf is not posted with the message.

**Comment by nbartels** [comment]
Okay I see, I'll try this later myself. But I think PDFs are simply not supported...

**Comment by karishmak88** [comment]
Ok thank you so much. Will await your findings!

**Comment by nbartels** [comment]
I checked this and you can upload an image using the /me/photos endpoint with an page access token. Videos can be uploaded to me/videos and me/feed only accepts text or links.

PDF files uploading is not possible via the Graph API. In a short it is even not possible to add a PDF file to a page post. So you can only link to the pdf.
