### ISSUE TITLE
Trying to post in bold typeface, but comes up as normal

### ISSUE THREAD

**Issue by karishmak88** [restfb/restfb#978]
Hi

I am trying to post a message in bold. On facebook a message of the format: **This is a bold line** would come up in bold typeface but when doing it through the app using restfb, instead of bold it displays it in normal typeface as - **This ia a bold line**

Here is the code snippet:

                        String accessToken = "<PLEASE USE YOUR ACCESS TOKEN>";
			FacebookClient fbClient = new DefaultFacebookClient(accessToken, Version.LATEST);
			
			//to test  bold message
			
			// Actual: shows in regular text post on page as **bold text**
			// Expected: should show in bold the post as bold text
			Post obj = fbClient.publish("PAGE_ID/feed", Post.class,
					Parameter.with("message", "**bold text**"));
			System.out.println("object is : "+obj);

**Comment by karishmak88** [comment]
The comments made it bold. What i meant is:
Expected result post is: **This is a bold line**
Actual result post seen is: "** This is a bold line **"

**Comment by nbartels** [comment]
Yes, the Facebook graph api does not support this feature.
