### ISSUE TITLE
AdCreativeLinkDataChildAttachment.place_data should be an Object

### ISSUE THREAD

**Issue by AdrianMF** [restfb/restfb#979]
I was trying to create a "Map Card" for a Store Traffic objective ad and it seems to require an object for the "place_data" field of AdCreativeLinkDataChildAttachment.
Example:
`"place_data": {
            "type": "DYNAMIC"
          }`
When looking at the Facebook java sdk, they have it mapped out, however in restfb its just a string field.

https://github.com/facebook/facebook-java-business-sdk/blob/master/src/main/java/com/facebook/ads/sdk/AdCreativePlaceData.java

**Comment by nbartels** [comment]
Many thanks for the hint!
