### ISSUE TITLE
Facebook Marketing API rate limitation (Ad Account Level Limits)

### ISSUE THREAD

**Issue by mikron** [restfb/restfb#983]
Feature Request. We are using restfb client for integration with facebook marketing api. The Marketing api has it is own rate limiting logic and is excluded from all the graph api rate limitations. Facebook marketing api [best practices](https://developers.facebook.com/docs/marketing-api/best-practices/) suggests the use of `x-ad-account-usage` - this shows you how close your ad account is to its limit.
Is it possible to add the `x-ad-account-usage` to `DebugHeaderInfo`?

**Comment by nbartels** [comment]
Absolutely, we will add this header asap to restfb. Many thanks for this hint.

**Comment by nbartels** [comment]
@mikron can you verify that `acc_id_util_pct` is the only field in the JSON provided in the `x-ad-account-usage` field. You can get all headers with the `DefaultWebRequestor#getCurrentHeaders()` method.

**Comment by mikron** [comment]
Thanks for the quick reply. As for the verification, I can confirm for version 3.2 of the Facebook marketing api the only field in the json is

**Comment by nbartels** [comment]
okay, great!
