### ISSUE TITLE
New field on MessagingItem - priorMessage

### ISSUE THREAD

**Issue by chaas** [restfb/restfb#988]
The MessagingItem class (/src/main/lombok/com/restfb/types/webhook/messaging/MessagingItem.java) should have an additional member "priorMessage".
The new PriorMessage class should have String fields "source" and "identifier".

See the FB documentation here https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin#implementation, step #7 under "Implementation" section.
Sample request json:
```
"prior_message": {
    "source":"checkbox_plugin",        
    "identifier":"<USER_REF>"
  }
```
The prior message identifier can be used to connect an inbound message to an outbound one.

Would this addition make sense?

**Comment by nbartels** [comment]
We added a `getPriorMessage` and `hasPriorMessage` method so you can simply check for the field and fetch the object if necessary.

**Comment by chaas** [comment]
Thank you! Appreciate the really quick turnaround
