### ISSUE TITLE
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (# 12) singular statuses API is deprecated for versions v2.4 and higher (code 12, subcode null) 'null - null'

### ISSUE THREAD

**Issue by seyfer** [restfb/restfb#997]
Hello!

Great library, we are using it.
Recently started to get an error
```
com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#12) singular statuses API is deprecated for versions v2.4 and higher (code 12, subcode null) 'null - null'
```

For the code
```
pageClient.fetchConnection(
      "/" + commentId.get + "/comments",
      classOf[JsonObject],
      Parameter.`with`("fields", "created_time,message,from"),
      Parameter.`with`(limitFieldName, itemLimit)
    )
```

Any help on how to fix it back? Thanks!

> Version: 2.17.0

**Comment by seyfer** [comment]
I did an update to the latest version 2.21.0 and the error still present.

**Comment by nbartels** [comment]
Can you please check your `commentId.get`. It seems there is no underscore in the id and at least one is needed ;)

**Comment by seyfer** [comment]
Yes, ID looks like this one now `2282081225188002`

We get it from the rating collection. It is fetched as
```
pageClient.fetchConnection(
      pageId.get + "/ratings",
      classOf[JsonObject],
      Parameter.`with`("fields", "open_graph_story"),
      Parameter.`with`(limitFieldName, itemLimit)
    )
```

then we iterate it, every entry contains something like
```
{
  "open_graph_story": {
    "id": "2282081225188002",
    "message": "Gutes Essen Gutes Personal",
    "start_time": "2019-04-06T17:15:53+0000",
    "type": "sellers.rates",
    "data": {
      "recommendation_type": "positive",
      "review_text": "Gutes Essen Gutes Personal",
      "is_hidden": false,
      "language": "de",
      "seller": {
        "id": "2128207593886460",
        "title": "Hopfen & Salz",
        "type": "place",
        "url": "https://www.facebook.com/hopfenundsalz/"
      },
      "has_review_update": false
    }
  }
}
```

so we get this ID
`Some(openGraphStory.get("id").asString())`

and trying to get comments by it
```
pageClient.fetchConnection(
      "/" + itemId.get + "/comments",
      classOf[JsonObject],
      Parameter.`with`(limitFieldName, itemLimit)
    )
```

it worked before, and now it stopped. :)

shall we glue something with an underscore to this ID?
what is the format? SELLERID_ITEMID?

I can see here an example with such ID
https://restfb.com/documentation/#advanced-usage-selecting-fields

but how this ID `74133697733_10152424266332734` was created I cannot find in docs.

**Comment by seyfer** [comment]
So I have tried to use `2128207593886460_2282081225188002` and opposite - doesn't find an object.

**Comment by nbartels** [comment]
Hm, I just did almost the same but used `/me/ratings` instead of the page id, and I got the ids, fetching the comments from the rating ids worked - at least I got not error message as you mentioned in the first post. 

So, can you please try `me/ratings`, too and check the page access token ...

**Comment by seyfer** [comment]
> with the Graph API Explorer, too.
yes, the same behavior, exactly the same

the page access token is 100% correct

we will check if we can switch our flow to `/me/ratings`, thank you for the tip.

**Comment by nbartels** [comment]
You have a page access tokens for the pages? Or do you have the "Page Public Content Access" feature activated?

**Comment by seyfer** [comment]
For each page customers provide their page access tokens for us.
Everything worked before this deprecation error started to appear.

**Comment by nbartels** [comment]
I suggest to open up an issue at Facebook. They seem to have changed something on their backend and this leads to this bug.

https://developers.facebook.com/support/bugs/

A short search leads to this, but obviously the creator did not provide enough information. Maybe you can and so Facebook is able to solve it.
https://developers.facebook.com/support/bugs/422998221816459/

**Comment by seyfer** [comment]
@nbartels that's exactly our case. Thanks a lot.
